import type { MetadataRoute } from 'next';

const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'https://cv-prime.in';

const publicPaths = [
  '/',
  '/templates',
  '/pricing',
  '/about',
  '/contact',
  '/ethics',
  '/statistics',
  '/llm.txt',
  '/resume-tools',
  '/tools',
  '/embed',
  // Resume builder tools
  '/resume-builder',
  '/free-resume-builder',
  '/ai-resume-builder',
  '/resume-maker',
  '/resume-generator',
  '/resume-optimizer',
  '/resume-checker',
  '/resume-format',
  '/cover-letter-generator',
  '/resume-vs-cv',
  '/fresher-resume',
  '/biodata-format',
  '/one-page-resume',
  '/software-engineer-resume',
  // City-specific resume builder pages
  '/resume-builder-bangalore',
  '/resume-builder-mumbai',
  '/resume-builder-delhi',
  '/resume-builder-hyderabad',
  '/resume-builder-chennai',
  '/resume-builder-pune',
  '/resume-builder-kolkata',
  '/resume-builder-ahmedabad',
  // Industry & career content pages
  '/it-resume-builder',
  '/career-change-resume',
  '/campus-placement-resume',
  '/mba-resume',
  '/internship-resume',
  // CV tools
  '/online-cv-maker',
  '/ai-cv-builder',
  '/cv-builder-india',
  '/resume-builder-india',
  // ATS tools
  '/ats-checker',
  '/ats-friendly-cv',
  '/ats-resume-builder',
  '/resume-writing-service',
  '/linkedin-profile-optimizer',
  '/ats-report-2026',
  '/ats-score-checker',
  '/resume-job-match-score',
  // AI tailoring & rewriting
  '/tailor-resume-to-job-description',
  '/ai-resume-rewriter',
  // Pricing & brand
  '/lifetime-resume-builder-india',
  '/resume-builder-no-subscription',
  '/cv-prime-review',
  '/best-ai-resume-builder-india-2026',
  // ATS & format/template guides
  '/how-to-pass-ats-screening',
  '/ats-resume-format-2026',
  '/ats-resume-template',
  '/professional-cv-template-india',
  '/modern-resume-template-india',
  '/minimal-ats-resume-template',
  '/resume-template-for-engineers',
  '/no-watermark-resume-download',
  '/pdf-resume-builder-india',
  '/resume-format-for-indian-companies',
  '/mnc-resume-format-india',
  '/engineering-fresher-resume',
  '/resume-summary-vs-objective',
  '/job-application-tracker',
  '/best-resume-builders-india',
  '/government-job-resume',
  '/naukri-resume-tips',
  '/resume-builder-for-experienced',
  '/resume-enhancer',
  '/resume-scanner',
  // Comparison & alternatives
  '/naukri-resume-builder-alternative',
  '/free-ats-checker-vs-paid',
  '/cv-prime-vs-resumelab',
  '/cv-prime-vs-visualcv',
  // Content cluster hubs (dynamic sub-pages covered by wildcard Allow below)
  '/cv-examples',
  '/resume-examples',
  '/cover-letter-examples',
  '/interview-questions',
  '/linkedin-headline',
  '/salary',
  '/ats-guide',
  '/resume-tips',
  '/resume-tips/how-to-write-a-resume',
  '/resume-tips/cover-letter-tips',
  '/resume-tips/resume-summary',
  '/resume-tips/action-verbs',
  '/resume-tips/skills-section',
  '/resume-tips/resume-bullet-points',
  '/resume-tips/quantifying-achievements',
  '/resume-tips/ats-keywords',
  '/resume-tips/resume-objective',
  '/resume-tips/work-experience',
  '/resume-tips/resume-length',
  '/resume-tips/gap-in-resume',
  '/resume-tips/resume-certifications',
  '/resume-tips/references-on-resume',
  '/resume-tips/resume-headline',
  '/resume-tips/education-section',
  '/create-with-ai',
  // Research & reference
  '/career-glossary',
  '/glossary',
  '/in-demand-skills-india-2026',
  '/blog',
  // Competitor comparisons
  '/cv-prime-vs-zety',
  '/cv-prime-vs-resume-io',
  '/cv-prime-vs-novoresume',
  '/cv-prime-vs-teal',
  '/cv-prime-vs-enhancv',
  '/cv-prime-vs-kickresume',
  '/cv-prime-vs-rezi',
  '/cv-prime-vs-jobscan',
  '/cv-prime-vs-resume-genius',
  '/cv-prime-vs-myperfectresume',
  '/cv-prime-vs-canva',
  '/cv-prime-vs-google-docs',
  '/cv-prime-vs-linkedin-resume',
  '/cv-prime-vs-overleaf',
  '/cv-prime-vs-flowcv',
  '/cv-prime-vs-resume-worded',
  // Legal
  '/terms',
  '/privacy',
  '/refund',
  '/cookies',
];

const dynamicPatterns = [
  '/cv-examples/',
  '/resume-examples/',
  '/interview-questions/',
  '/linkedin-headline/',
  '/salary/',
  '/ats-guide/',
  '/cover-letter-examples/',
  '/resume-builder/',
  '/blog/',
  '/tools/',
];

const disallowPaths = [
  '/api/',
  '/dashboard/',
  '/editor/',
  '/job-tracker/',
  '/settings/',
  '/print/',
  '/debug-status/',
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [...publicPaths, ...dynamicPatterns],
        disallow: disallowPaths,
      },
      {
        userAgent: [
          'GPTBot', 'ChatGPT-User', 'Google-Extended', 'PerplexityBot',
          'ClaudeBot', 'anthropic-ai', 'Omgilibot', 'FacebookBot',
          'Applebot-Extended', 'Bytespider', 'CCBot', 'DataForSeoBot',
          'Amazonbot', 'Gemini', 'Bingbot',
        ],
        allow: [...publicPaths, ...dynamicPatterns],
        disallow: disallowPaths,
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
  };
}
