import type { AtsGuideData } from '@/lib/atsGuideData';

const SINGLE_COLUMN =
  'Use a single-column layout — table-based or two-column CVs are read out of order by most ATS parsers';
const SECTION_LABELS =
  'Use plain section labels ("Work Experience", "Education", "Skills") — ATS maps headings to fields by exact label';
const FILE_FORMAT =
  'Submit a text-based PDF or .docx (never a scanned image) — follow the JD if it names a format';
const NO_ICONS = 'Avoid icons, skill-bars, and graphics for ratings — ATS cannot read images and drops them';

export const atsGuideDataExtra: Record<string, AtsGuideData> = {
  'business-development-manager': {
    atsKeywords: ['Business Development Manager', 'BDM', 'B2B Sales', 'Lead Generation', 'Pipeline Management', 'Client Acquisition', 'Account Management', 'Revenue Growth', 'Salesforce', 'HubSpot', 'LinkedIn Sales Navigator', 'Negotiation', 'Proposal Writing', 'Strategic Partnerships', 'Sales Forecasting', 'CRM', 'SaaS Sales', 'Quota Attainment', 'Stakeholder Management', 'Market Expansion'],
    mustHaveSections: ['Professional Summary', 'Work Experience', 'Key Skills', 'Education', 'Certifications (if any)'],
    formattingRules: [
      SINGLE_COLUMN,
      SECTION_LABELS,
      'Keep the exact title "Business Development Manager" in your headline or current role — recruiters search the literal title, and "BDM" alone may not match',
      'Write revenue, quota and pipeline figures as plain text inside bullets so ATS indexes them with the role',
      'List CRM and sales tools (Salesforce, HubSpot, Zoho CRM) in a dedicated Skills section',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Using only "BDM" or "BD" without the full title — literal keyword search misses the abbreviation',
      'Hiding CRM and sales-tool names inside long paragraphs instead of a Skills section',
      'Describing "relationship management" without the words ATS screens for: lead generation, pipeline, quota, client acquisition',
      'Showing sales achievement as a chart or infographic — ATS cannot read it',
      'Omitting the industry vertical (SaaS, BFSI, IT services) that many JDs filter on',
      'Contact details in a Word header or footer, which many parsers skip',
    ],
    keywordTips: [
      'Mirror the JD wording: if it says "enterprise sales" or "channel partnerships", use that phrase rather than a synonym',
      'Pair each tool with its use: "Salesforce (pipeline tracking and forecasting)"',
      'Include both the spelled-out and abbreviated forms: "Business Development Manager (BDM)", "Customer Relationship Management (CRM)"',
      'Name the buyer type you sold to (CXO, procurement, SMB owners) — JDs often screen on it',
      'Put your target-attainment results in bullets that also contain the core keywords, so match and proof sit together',
    ],
    faqs: [
      { q: 'Which keywords matter most on a business development manager CV?', a: 'Match the job description first. Across most BDM listings the recurring terms are lead generation, pipeline management, B2B sales, client acquisition, account management, negotiation, and the CRM named in the JD. Place them in both your Skills section and your experience bullets.' },
      { q: 'Should I write BDM or Business Development Manager?', a: 'Write "Business Development Manager (BDM)" at least once. ATS keyword search is literal, and recruiters type either form, so having both strings on the page covers both searches.' },
      { q: 'Can ATS read sales numbers on my CV?', a: 'ATS stores the text, so figures written in plain text (for example "achieved 120% of annual quota") are indexed and visible to recruiters. Figures shown only inside charts, images or text boxes are lost.' },
    ],
  },
  'chartered-accountant': {
    atsKeywords: ['Chartered Accountant', 'CA', 'ICAI', 'Statutory Audit', 'Internal Audit', 'Tax Audit', 'Direct Tax', 'Indirect Tax', 'GST', 'Ind AS', 'IFRS', 'Financial Reporting', 'Transfer Pricing', 'Internal Controls', 'SAP FICO', 'Tally', 'MIS Reporting', 'Statutory Compliance', 'Budgeting', 'Due Diligence', 'Articleship'],
    mustHaveSections: ['Professional Summary', 'Work Experience', 'Articleship', 'Education & ICAI Qualification', 'Skills'],
    formattingRules: [
      SINGLE_COLUMN,
      SECTION_LABELS,
      'State "Chartered Accountant" and "ICAI" in text, with membership year, near the top — many finance JDs filter on the qualification',
      'Spell out acronyms once alongside the short form: "Indian Accounting Standards (Ind AS)", "Goods and Services Tax (GST)"',
      'Keep articleship as its own labelled section with firm, period and audit areas',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Writing "CA" only — it can be misread, so also write "Chartered Accountant" and "ICAI"',
      'Putting the qualification in an image or a decorative badge rather than text',
      'Listing Ind AS, IFRS and GST only inside paragraphs, with no Skills section for ATS to index',
      'Using tables to lay out audit engagements, which scrambles reading order',
      'Omitting ERP and tool names (SAP, Tally, Oracle) that JDs screen on',
      'Contact information stored in a Word header or footer',
    ],
    keywordTips: [
      'Use both audit type and standard: "statutory audit under Ind AS" matches more search strings than either alone',
      'Name the ERP systems you have worked on in a Skills section: SAP FICO, Tally Prime, Oracle',
      'Include the spelled-out and short forms of every standard and tax: "Goods and Services Tax (GST)", "Tax Deducted at Source (TDS)"',
      'If the role is in a Big 4 or a listed company, mention listed-entity, group audit or consolidation experience in plain words',
      'Add the JD’s function words ("month-end close", "reconciliation", "compliance") where they truthfully apply',
    ],
    faqs: [
      { q: 'What ATS keywords should a chartered accountant include?', a: 'Use the ones in the target JD, which commonly include statutory audit, internal audit, taxation, GST, Ind AS, IFRS, financial reporting, internal controls, and the ERP named in the listing. State "Chartered Accountant" and "ICAI" in plain text.' },
      { q: 'Does ATS read the CA qualification correctly?', a: 'It does when written as text. Write "Chartered Accountant (ICAI)" with membership year in your header area or Education section. Do not rely on a logo, badge or image.' },
      { q: 'Should articleship be on a CA CV for ATS?', a: 'Yes, especially for freshers and junior roles. Give it its own labelled section with the firm, duration and audit areas, so the keywords it contains are indexed.' },
    ],
  },
  'embedded-systems-engineer': {
    atsKeywords: ['Embedded Systems Engineer', 'Embedded C', 'C++', 'RTOS', 'FreeRTOS', 'ARM Cortex-M', 'STM32', 'Microcontroller', 'Firmware', 'Device Drivers', 'CAN', 'SPI', 'I2C', 'UART', 'Embedded Linux', 'Yocto', 'JTAG', 'Bootloader', 'AUTOSAR', 'IoT', 'Debugging', 'Unit Testing'],
    mustHaveSections: ['Technical Skills', 'Work Experience', 'Projects', 'Education', 'Certifications (if any)'],
    formattingRules: [
      SINGLE_COLUMN,
      SECTION_LABELS,
      'Group technical skills by category (languages, MCUs/SoCs, RTOS/OS, protocols, tools) in plain comma-separated lines, not a table',
      'Name the exact MCU or SoC family and protocol per project, in text',
      'Write both forms for abbreviations: "Real-Time Operating System (RTOS)", "Controller Area Network (CAN)"',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Listing "embedded systems" with no MCU family, RTOS or protocol — the terms ATS actually screens for',
      'Showing skill levels as bars or stars, which ATS cannot parse',
      'Putting the tech stack in a side column of a two-column template',
      'Writing "C/C++" only — some searches look for "C" and "C++" separately, so write "C, C++" as well',
      'Not naming tools such as JTAG, oscilloscope or logic analyzer that appear in hardware-facing JDs',
      NO_ICONS,
    ],
    keywordTips: [
      'Attach the platform to the skill: "FreeRTOS on STM32F4" gives two matchable keywords in one line',
      'Name standards and domains where true: AUTOSAR, ISO 26262, MISRA C for automotive; IoT stacks for connected devices',
      'List build and debug tools explicitly: Keil, IAR, GCC, GDB, OpenOCD, JTAG',
      'Write the protocol set in full: CAN, SPI, I2C, UART, Ethernet, BLE',
      'Use "firmware" and "embedded software" as the JD does; both phrasings are common',
    ],
    faqs: [
      { q: 'Which keywords matter on an embedded systems engineer CV?', a: 'Embedded C/C++, the MCU or SoC family, the RTOS, communication protocols (CAN, SPI, I2C, UART), debugging tools, and the domain standard if one applies. Copy the exact terms from the JD.' },
      { q: 'How should I show hardware skills so ATS reads them?', a: 'As plain text in a Skills section and in project bullets, such as "bare-metal drivers for SPI and I2C sensors on an ARM Cortex-M4". Avoid diagrams and skill bars.' },
      { q: 'Should I list C and C++ separately?', a: 'Write "C, C++" instead of "C/C++" alone. Literal-match searches treat the slash form inconsistently, and listing both is accurate and clearer.' },
    ],
  },
  'full-stack-developer': {
    atsKeywords: ['Full Stack Developer', 'JavaScript', 'TypeScript', 'React', 'Node.js', 'Express', 'Next.js', 'REST API', 'GraphQL', 'PostgreSQL', 'MongoDB', 'MySQL', 'Redis', 'Docker', 'AWS', 'Git', 'CI/CD', 'HTML', 'CSS', 'Microservices', 'Unit Testing', 'Agile'],
    mustHaveSections: ['Technical Skills', 'Work Experience', 'Projects', 'Education', 'Certifications (if any)'],
    formattingRules: [
      SINGLE_COLUMN,
      SECTION_LABELS,
      'Split Technical Skills into Frontend, Backend, Databases and DevOps/Cloud lines so each keyword is indexed',
      'Keep the exact title "Full Stack Developer" (or "Full Stack Engineer" if the JD uses it) in your headline',
      'Write framework names as the JD does: "Node.js" not "NodeJS" when the JD says Node.js',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Showing the stack as logos or an icon grid, which ATS reads as nothing',
      'Listing only "MERN stack" without naming MongoDB, Express, React and Node.js individually',
      'Embedding technologies only in bullets with no Skills section',
      'Omitting the backend or database that the JD names, so the CV reads as frontend-only',
      'Using "ReactJS" when the JD says "React" — literal matching can treat them as different strings',
      'Two-column developer templates that interleave the sidebar with the main text',
    ],
    keywordTips: [
      'Expand stack acronyms: "MERN (MongoDB, Express.js, React, Node.js)"',
      'Cover both ends: at least one frontend framework, one backend framework, one database and one deployment tool',
      'Use JD spelling variants where the JD offers them, such as "React.js" and "React"',
      'Add testing and delivery terms the JD mentions: Jest, Cypress, CI/CD, GitHub Actions',
      'Include a link to GitHub or a live project as plain text so recruiters can open it from the parsed profile',
    ],
    faqs: [
      { q: 'What keywords should a full stack developer CV include?', a: 'A frontend framework, a backend runtime or framework, a database, API style (REST/GraphQL), cloud and deployment tools, and testing. Pick the exact names in the JD and list each individually.' },
      { q: 'Is it enough to write MERN stack?', a: 'No. Write MERN and also name MongoDB, Express.js, React and Node.js. ATS matches keywords literally, so the abbreviation alone may not satisfy a search for "MongoDB".' },
      { q: 'Do project links help with ATS?', a: 'Plain-text URLs are preserved by most parsers, so recruiters can click through. They do not raise keyword scores directly, but they add proof for the skills you list.' },
    ],
  },
  'interior-designer': {
    atsKeywords: ['Interior Designer', 'Space Planning', 'AutoCAD', 'SketchUp', '3ds Max', 'Revit', 'V-Ray', 'Lumion', 'Adobe Photoshop', 'Mood Boards', 'Material Selection', 'BOQ', 'Site Supervision', 'Furniture Layout', 'Lighting Design', 'Client Presentation', 'Vendor Coordination', 'Residential Design', 'Commercial Interiors', 'Working Drawings', 'Project Management'],
    mustHaveSections: ['Professional Summary', 'Software Skills', 'Work Experience', 'Selected Projects', 'Education', 'Portfolio Link'],
    formattingRules: [
      SINGLE_COLUMN,
      SECTION_LABELS,
      'Keep the CV text-based and put visuals in your portfolio — put the portfolio URL as plain text in the header',
      'List design software in a dedicated Software Skills line, not as logos',
      'Describe each project in text: type, area, your role, tools used',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Designing the CV as a visual layout with text in images or text boxes, which ATS skips',
      'Showing software proficiency as logos or rating bars',
      'Linking to a portfolio only through an image or button',
      'Describing projects with creative titles but no project type (residential, retail, hospitality)',
      'Omitting technical deliverables (working drawings, BOQ) that JDs screen on',
      'Contact details placed in a decorative header',
    ],
    keywordTips: [
      'Use the JD’s project vocabulary: "turnkey", "residential", "commercial", "hospitality"',
      'Name each software in full once: "Autodesk AutoCAD", "SketchUp Pro", "Chaos V-Ray"',
      'Include both design and delivery terms: space planning plus BOQ, site coordination, vendor management',
      'State project scale in plain text (area, number of units) rather than in an image caption',
      'Keep a visually designed portfolio separate and link it, so the CV stays parseable',
    ],
    faqs: [
      { q: 'How do I make an interior designer CV ATS-friendly without losing style?', a: 'Keep the CV itself plain and text-based, with a clean single-column layout, and put visual work in your portfolio. Add the portfolio URL as text near your contact details.' },
      { q: 'Which keywords matter for interior designer roles?', a: 'Space planning, AutoCAD, SketchUp, 3ds Max or Revit, rendering tools, material specification, BOQ, site coordination and the project types in the JD.' },
      { q: 'Can I use a creative template?', a: 'Only if the text remains selectable and in a single reading order. Many creative templates use columns, text boxes and images, which ATS parses badly. Test by copying the text from your PDF and checking the order.' },
    ],
  },
  'investment-banker': {
    atsKeywords: ['Investment Banking', 'Investment Banker', 'M&A', 'Mergers and Acquisitions', 'Financial Modelling', 'DCF', 'LBO', 'Valuation', 'Comparable Company Analysis', 'Precedent Transactions', 'Pitch Books', 'Due Diligence', 'ECM', 'DCM', 'IPO', 'Capital Raising', 'Excel', 'PowerPoint', 'Bloomberg', 'Capital IQ', 'Information Memorandum'],
    mustHaveSections: ['Professional Summary', 'Work Experience (with deal experience)', 'Education', 'Skills & Tools', 'Certifications (CFA, FRM, if any)'],
    formattingRules: [
      SINGLE_COLUMN,
      SECTION_LABELS,
      'List each transaction as plain text: deal type, sector, size and your role',
      'Write modelling skills by type (DCF, LBO, merger model) rather than "financial modelling" only',
      'Keep to one page for early-career roles and use text only, with no graphics',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Writing "M&A" only, when the JD may search "Mergers and Acquisitions"',
      'Describing deals in tables or tombstone images, which ATS cannot read',
      'Listing "financial modelling" with no DCF, LBO or valuation terms',
      'Omitting data tools (Bloomberg, Capital IQ, FactSet) that JDs name',
      'Leaving out the sector coverage (healthcare, technology, industrials) used to match mandates',
      'Using a fancy multi-column layout instead of the plain format banks expect',
    ],
    keywordTips: [
      'Use both the short and long forms: "M&A (Mergers and Acquisitions)", "ECM (Equity Capital Markets)"',
      'Write the transaction type in each bullet so it carries its own keywords: "sell-side M&A", "IPO", "debt syndication"',
      'Name valuation methods individually: DCF, comparable companies, precedent transactions, LBO',
      'List data and presentation tools: Capital IQ, Bloomberg, Excel, PowerPoint',
      'Mention only deals you are permitted to disclose, in generic form where needed ("a listed mid-cap pharma company")',
    ],
    faqs: [
      { q: 'Which ATS keywords matter on an investment banking CV?', a: 'M&A, valuation, financial modelling (DCF, LBO), pitch books, due diligence, capital raising, ECM/DCM, plus the tools and sector named in the JD.' },
      { q: 'How should deals be listed so ATS reads them?', a: 'As text bullets under the relevant role, stating deal type, sector, size where disclosable, and your contribution. Avoid tables or tombstone images.' },
      { q: 'Should I add CFA or MBA in a certain place?', a: 'Put them in the Education or Certifications section as plain text, spelled out once, for example "Chartered Financial Analyst (CFA) Level II".' },
    ],
  },
  'ios-developer': {
    atsKeywords: ['iOS Developer', 'Swift', 'SwiftUI', 'UIKit', 'Objective-C', 'Xcode', 'Combine', 'Core Data', 'Core Animation', 'REST API', 'MVVM', 'Clean Architecture', 'Unit Testing', 'XCTest', 'Git', 'CI/CD', 'Fastlane', 'TestFlight', 'App Store', 'Push Notifications', 'Firebase', 'Dependency Injection'],
    mustHaveSections: ['Technical Skills', 'Work Experience', 'Apps / Projects', 'Education', 'Certifications (if any)'],
    formattingRules: [
      SINGLE_COLUMN,
      SECTION_LABELS,
      'Put App Store links as plain text under each app so recruiters can open them',
      'Separate Languages, Frameworks, Architecture and Tools in the Skills section',
      'Name the minimum iOS version and Swift version you worked with where true',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Listing only "iOS" without Swift, SwiftUI or UIKit',
      'Skipping architecture terms (MVVM, Clean Architecture) that JDs screen on',
      'Showing app screenshots in the CV in place of text descriptions',
      'Omitting testing and delivery keywords: XCTest, Fastlane, TestFlight, CI/CD',
      'Putting the skills in a sidebar column',
      NO_ICONS,
    ],
    keywordTips: [
      'Name both UI frameworks if you know both: "SwiftUI" and "UIKit"',
      'Add concurrency terms the JD uses: async/await, GCD, Combine',
      'Cite apps by name with their role: "feature owner for checkout in a shopping app"',
      'List persistence and networking: Core Data, Realm, URLSession, Alamofire',
      'Include release tooling: App Store Connect, TestFlight, Fastlane',
    ],
    faqs: [
      { q: 'What keywords should an iOS developer CV include?', a: 'Swift, SwiftUI, UIKit, Xcode, the architecture pattern (MVVM), networking and persistence tools, testing (XCTest), and release tools like TestFlight. Copy the JD’s exact terms.' },
      { q: 'Do I need Objective-C on my CV?', a: 'Only if you have used it. Many legacy codebases still ask for it, so list it if true, and place it in your Skills section so ATS can find it.' },
      { q: 'How do I show apps I shipped?', a: 'Write each as a text bullet with its name, your role and the technologies used, and add the App Store URL as plain text.' },
    ],
  },
  'logistics-manager': {
    atsKeywords: ['Logistics Manager', 'Supply Chain', 'Warehouse Management', 'Inventory Control', 'Transportation Management', 'Fleet Management', 'Last Mile Delivery', '3PL', 'Freight Forwarding', 'Procurement', 'Vendor Management', 'WMS', 'TMS', 'SAP', 'Route Optimisation', 'Cost Reduction', 'KPI Reporting', 'Compliance', 'Import Export', 'Demand Planning', 'Team Management'],
    mustHaveSections: ['Professional Summary', 'Work Experience', 'Key Skills', 'Education', 'Certifications (if any)'],
    formattingRules: [
      SINGLE_COLUMN,
      SECTION_LABELS,
      'Keep the exact title "Logistics Manager" (or the JD’s variant) in your headline',
      'List systems separately: WMS, TMS, SAP, Oracle, route-planning tools',
      'Write operational KPIs in plain text inside bullets: on-time delivery, cost per shipment, inventory accuracy',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Writing "managed logistics" without terms like warehouse management, transportation, 3PL or last mile',
      'Leaving out WMS/TMS or ERP names that JDs screen on',
      'Showing KPIs in charts or dashboards pasted as images',
      'Omitting the logistics segment (e-commerce, FMCG, cold chain, freight) the JD targets',
      'Dropping "supply chain" when the JD uses it',
      'Contact information stored in a header or footer',
    ],
    keywordTips: [
      'Match the JD’s segment: "e-commerce fulfilment", "cold chain", "freight forwarding", "last mile"',
      'Spell acronyms once: "Third-Party Logistics (3PL)", "Warehouse Management System (WMS)"',
      'Name licences or compliance areas where relevant: customs, import-export documentation, transport regulations',
      'List the scale of operations in text: warehouses, fleet size, daily shipments',
      'Include both strategy and operations words: network design, route optimisation, vendor management',
    ],
    faqs: [
      { q: 'Which keywords matter for a logistics manager CV?', a: 'Supply chain, warehouse management, transportation management, fleet, last mile, 3PL, inventory control, vendor management, the WMS/TMS or ERP system, and compliance terms in the JD.' },
      { q: 'Should I list systems such as SAP or WMS?', a: 'Yes. Put them in a Skills section and in the bullets where you used them. JDs often screen on these exact names.' },
      { q: 'How do I show KPIs so ATS reads them?', a: 'Write them as plain text in bullets, for example "improved on-time delivery from 91% to 96%" — only with your real figures.' },
    ],
  },
  'machine-learning-engineer': {
    atsKeywords: ['Machine Learning Engineer', 'Python', 'PyTorch', 'TensorFlow', 'scikit-learn', 'Deep Learning', 'NLP', 'Computer Vision', 'MLOps', 'Model Deployment', 'Feature Engineering', 'SQL', 'Docker', 'Kubernetes', 'AWS SageMaker', 'MLflow', 'Spark', 'Model Monitoring', 'A/B Testing', 'REST API', 'Git', 'Transformers'],
    mustHaveSections: ['Technical Skills', 'Work Experience', 'Projects', 'Education', 'Publications / Certifications (if any)'],
    formattingRules: [
      SINGLE_COLUMN,
      SECTION_LABELS,
      'Group skills as Languages, ML Frameworks, MLOps/Infra and Data tools, in plain text lines',
      'Keep "Machine Learning Engineer" in your headline when you target MLE roles — it is distinct from "Data Scientist"',
      'State the model family and the problem for each project in text',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Writing "AI/ML" without naming frameworks, models or tasks',
      'Showing only research or notebooks with no deployment keywords (Docker, MLOps, serving)',
      'Omitting "Python" and "SQL" because they feel obvious',
      'Showing results in images of charts instead of text',
      'Mixing data scientist and ML engineer terms without matching the JD’s title',
      'Listing publications as a table or an image',
    ],
    keywordTips: [
      'Name the task and model: "NLP text classification using BERT (PyTorch)"',
      'Add production terms the JD uses: model serving, monitoring, retraining, feature store',
      'List cloud ML services if used: SageMaker, Vertex AI, Azure ML',
      'Write metrics in text: "improved F1 score from X to Y" using your real numbers',
      'Use the spelled-out and short form once: "Natural Language Processing (NLP)"',
    ],
    faqs: [
      { q: 'What keywords should a machine learning engineer CV include?', a: 'Python, PyTorch or TensorFlow, the model types and tasks (NLP, computer vision), MLOps and deployment tools (Docker, Kubernetes, MLflow), cloud ML services, and SQL. Use the JD’s exact terms.' },
      { q: 'How is an MLE CV different from a data scientist CV for ATS?', a: 'An MLE CV emphasises deployment and production terms (serving, pipelines, monitoring), while a data scientist CV emphasises analysis, statistics and experimentation. Match the one in the JD.' },
      { q: 'Should I list Kaggle or research papers?', a: 'Yes, as text with titles and links in a Projects or Publications section. They add context but should not replace production or applied experience.' },
    ],
  },
  'network-engineer': {
    atsKeywords: ['Network Engineer', 'CCNA', 'CCNP', 'Routing and Switching', 'BGP', 'OSPF', 'VLAN', 'MPLS', 'SD-WAN', 'Firewall', 'Palo Alto', 'Fortinet', 'Cisco', 'Juniper', 'VPN', 'LAN/WAN', 'Network Security', 'Network Monitoring', 'Wireshark', 'Troubleshooting', 'ITIL', 'Load Balancer', 'Wi-Fi'],
    mustHaveSections: ['Technical Skills', 'Certifications', 'Work Experience', 'Education', 'Projects (if any)'],
    formattingRules: [
      SINGLE_COLUMN,
      SECTION_LABELS,
      'Give Certifications their own section with exact names and levels, such as "Cisco Certified Network Associate (CCNA)"',
      'Group skills by Routing, Switching, Security, Cloud and Monitoring',
      'Name vendors and device families you configured',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Burying CCNA/CCNP inside a paragraph instead of a Certifications section',
      'Writing "networking" without protocols such as BGP, OSPF or VLAN',
      'Omitting vendor names that JDs list (Cisco, Juniper, Fortinet, Palo Alto)',
      'Showing network diagrams in place of text descriptions',
      'Leaving out ITIL or incident-management terms for support-oriented roles',
      'Expiry or level not stated for certifications',
    ],
    keywordTips: [
      'Write each certification in full and short form once',
      'List protocols individually, as JDs search for them one by one',
      'State environment scale in text: sites, devices managed, users supported',
      'Add monitoring and automation tools used: SolarWinds, Nagios, Python, Ansible',
      'Match the JD’s vendor stack exactly',
    ],
    faqs: [
      { q: 'What keywords matter on a network engineer CV?', a: 'Certifications (CCNA, CCNP), protocols (BGP, OSPF, VLAN, MPLS), vendors (Cisco, Juniper, Palo Alto), security and firewall terms, monitoring tools, and ITIL where relevant.' },
      { q: 'Where should I put certifications for ATS?', a: 'In a labelled Certifications section near the top, as text with the full name and short form.' },
      { q: 'Is it fine to add network diagrams?', a: 'Keep them for your portfolio. Inside a CV they are invisible to ATS and take space from keyword-rich text.' },
    ],
  },
  pharmacist: {
    atsKeywords: ['Pharmacist', 'B.Pharm', 'D.Pharm', 'M.Pharm', 'Pharm.D', 'Pharmacy Council Registration', 'Dispensing', 'Prescription Verification', 'Patient Counselling', 'Inventory Management', 'Drug Interactions', 'Pharmacovigilance', 'Clinical Pharmacy', 'Hospital Pharmacy', 'Retail Pharmacy', 'GMP', 'Regulatory Compliance', 'Cold Chain', 'Medication Safety', 'Drug Schedules'],
    mustHaveSections: ['Professional Summary', 'Registration & Licence', 'Work Experience', 'Education', 'Skills'],
    formattingRules: [
      SINGLE_COLUMN,
      SECTION_LABELS,
      'State your qualification and state pharmacy council registration number in plain text',
      'Name the setting in your headline: hospital, retail, clinical or manufacturing',
      'Write compliance areas in full: Schedule H drug handling, narcotics register, GMP',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Omitting registration details that many hospital and retail hiring teams check',
      'Writing only "pharmacy experience" without dispensing, counselling or inventory terms',
      'Using abbreviations only (B.Pharm) without the spelled-out "Bachelor of Pharmacy"',
      'Setting licences in scanned images or badges',
      'Missing software used: HIS, pharmacy billing and inventory systems',
      'Using a template with sidebars for Skills',
    ],
    keywordTips: [
      'Write degree in both forms: "Bachelor of Pharmacy (B.Pharm)"',
      'Include the care setting terms in the JD: ICU pharmacy, outpatient dispensing, OTC counselling',
      'Add systems used: HIS, billing and inventory software by name',
      'State compliance exposure in plain words: GMP, GDP, audits, drug schedules',
      'Name medicine categories you handled where relevant (cold chain, narcotics, oncology)',
    ],
    faqs: [
      { q: 'What keywords should a pharmacist CV include?', a: 'Dispensing, prescription verification, patient counselling, inventory management, drug interactions, pharmacovigilance, regulatory compliance, your degree and registration, and the software named in the JD.' },
      { q: 'Should I put my registration number on my CV?', a: 'Many employers require proof of registration. State your council and registration status in text, and share the number as needed for the application, since CVs are widely circulated.' },
      { q: 'How do I tailor for hospital versus retail roles?', a: 'Use that setting’s vocabulary: clinical pharmacy, ward rounds, formulary for hospitals; OTC counselling, billing and stock for retail.' },
    ],
  },
  'react-developer': {
    atsKeywords: ['React Developer', 'React', 'React.js', 'JavaScript', 'TypeScript', 'Next.js', 'Redux', 'Hooks', 'Context API', 'HTML5', 'CSS3', 'Tailwind CSS', 'REST API', 'GraphQL', 'Jest', 'React Testing Library', 'Webpack', 'Vite', 'Git', 'Responsive Design', 'Performance Optimisation', 'Accessibility'],
    mustHaveSections: ['Technical Skills', 'Work Experience', 'Projects', 'Education', 'Certifications (if any)'],
    formattingRules: [
      SINGLE_COLUMN,
      SECTION_LABELS,
      'Use the JD’s spelling of "React" or "React.js" and include both once',
      'Split Technical Skills into Core, State Management, Styling, Testing and Tooling',
      'Add live demo and GitHub links as plain text under each project',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Listing only "frontend development" without React and TypeScript',
      'Using a logo grid for technologies',
      'Omitting testing and tooling keywords (Jest, React Testing Library, Vite)',
      'Not naming state management you used (Redux, Zustand, Context)',
      'Skills placed in a sidebar of a two-column template',
      'Describing projects with no stack named',
    ],
    keywordTips: [
      'Write both "React" and "React.js" once',
      'Name React features used: Hooks, Context, Suspense, Server Components where true',
      'Add Next.js rendering terms the JD lists: SSR, SSG, ISR',
      'Include web-quality terms: performance optimisation, accessibility, responsive design',
      'Give each project a stack line in plain text',
    ],
    faqs: [
      { q: 'What keywords should a React developer CV include?', a: 'React, JavaScript, TypeScript, Next.js, state management (Redux or similar), HTML/CSS, testing tools, REST/GraphQL and build tools. Match the JD’s exact wording.' },
      { q: 'React or React.js?', a: 'Use whichever the JD uses and include the other form once. ATS matching is literal, so both strings on the page cover either search.' },
      { q: 'Does ATS read GitHub links?', a: 'It stores plain-text URLs, so recruiters can click through. Links do not replace the Skills section, which provides the keywords.' },
    ],
  },
  'sales-executive': {
    atsKeywords: ['Sales Executive', 'Lead Generation', 'Cold Calling', 'Client Acquisition', 'Target Achievement', 'Field Sales', 'Inside Sales', 'B2B Sales', 'B2C Sales', 'CRM', 'Negotiation', 'Product Demonstration', 'Territory Management', 'Sales Reporting', 'Upselling', 'Cross-selling', 'Customer Relationship', 'Market Mapping', 'Follow-ups', 'Retail Sales'],
    mustHaveSections: ['Professional Summary', 'Work Experience', 'Key Skills', 'Education', 'Certifications (if any)'],
    formattingRules: [
      SINGLE_COLUMN,
      SECTION_LABELS,
      'Put target and achievement figures in plain text in bullets, using your real numbers',
      'Name the sales type: field, inside, B2B, B2C, channel',
      'List CRM tools by name: Salesforce, Zoho CRM, LeadSquared',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Writing "sales" in general without lead generation, client acquisition or target achievement',
      'Omitting the product or industry sold (FMCG, insurance, SaaS, real estate)',
      'Showing results as graphics',
      'No CRM named when the JD requires one',
      'Titles shortened to "Exec" or other abbreviations',
      'Contact information in a header or footer',
    ],
    keywordTips: [
      'Match the JD’s sales motion: "inside sales", "field sales", "channel sales"',
      'Pair each skill with a result in the same bullet',
      'Mention territory or segment in text',
      'List language skills that apply to the region',
      'Name the sales cycle length or deal type if true',
    ],
    faqs: [
      { q: 'What keywords should a sales executive CV have?', a: 'Lead generation, cold calling, client acquisition, target achievement, CRM, negotiation, territory management, and the product or industry terms in the JD.' },
      { q: 'How should I present sales targets?', a: 'As text in bullets with your real figures, such as "achieved 110% of quarterly target". Charts and images are not read by ATS.' },
      { q: 'Is a fresher sales CV different?', a: 'Yes. Highlight internships, campus roles, communication skills and any measured outcomes, and keep the same single-column text format.' },
    ],
  },
  'sap-consultant': {
    atsKeywords: ['SAP Consultant', 'SAP S/4HANA', 'SAP ECC', 'SAP FICO', 'SAP MM', 'SAP SD', 'SAP ABAP', 'SAP BASIS', 'SAP HCM', 'SAP Fiori', 'SAP Activate', 'ASAP Methodology', 'Implementation', 'Rollout', 'Data Migration', 'Configuration', 'UAT', 'Blueprint', 'Support', 'Integration', 'Functional Specification', 'Business Process'],
    mustHaveSections: ['Professional Summary', 'SAP Skills / Modules', 'Work Experience (project-wise)', 'Education', 'Certifications'],
    formattingRules: [
      SINGLE_COLUMN,
      SECTION_LABELS,
      'State the module in the headline, such as "SAP FICO Consultant", since JDs are module-specific',
      'Describe each project: client industry, scope (implementation, rollout, support), your phases and release',
      'List certifications with exact names, such as SAP Certified Application Associate',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Writing "SAP" without naming the module (FICO, MM, SD, ABAP)',
      'Omitting S/4HANA or ECC version terms',
      'Describing projects in tables that break the reading order',
      'No implementation or support lifecycle keywords (blueprint, UAT, go-live)',
      'Listing modules that you have not worked on to match keywords',
      'Certifications missing from a labelled section',
    ],
    keywordTips: [
      'Use the full module and submodule names: "SAP FICO (GL, AP, AR, Asset Accounting)"',
      'Include the system version: S/4HANA, ECC 6.0',
      'Add project-phase words: blueprint, realisation, cutover, hypercare',
      'Mention methodologies: SAP Activate, ASAP',
      'Name integrations and tools you used truthfully, such as SAP Fiori, IDocs and BAPIs for technical roles',
    ],
    faqs: [
      { q: 'What keywords matter on an SAP consultant CV?', a: 'The module (FICO, MM, SD, ABAP), the system (S/4HANA, ECC), project lifecycle terms (implementation, rollout, support, UAT), methodology (SAP Activate) and certifications.' },
      { q: 'Should I list multiple SAP modules?', a: 'Only those you have real project experience in. Recruiters verify module depth, and a focused primary module with a few related ones reads better than a long list.' },
      { q: 'How do I present projects?', a: 'One block per project in plain text: client industry, SAP version, your role, scope and key deliverables.' },
    ],
  },
  'scrum-master': {
    atsKeywords: ['Scrum Master', 'Agile', 'Scrum', 'Sprint Planning', 'Daily Stand-up', 'Sprint Review', 'Retrospective', 'Backlog Grooming', 'User Stories', 'Jira', 'Confluence', 'SAFe', 'Kanban', 'Velocity', 'Burndown', 'Impediment Removal', 'Stakeholder Management', 'Coaching', 'CSM', 'PSM', 'Release Planning', 'Continuous Improvement'],
    mustHaveSections: ['Professional Summary', 'Work Experience', 'Certifications', 'Skills & Tools', 'Education'],
    formattingRules: [
      SINGLE_COLUMN,
      SECTION_LABELS,
      'Put certifications in their own section with full names: "Certified ScrumMaster (CSM)", "Professional Scrum Master (PSM I)"',
      'Name team size and delivery context in text',
      'List tools separately: Jira, Confluence, Azure DevOps, Rally',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Writing "Agile" only, without Scrum ceremonies and artifacts as keywords',
      'Certifications hidden in a paragraph or shown as badges',
      'Missing the scaling framework (SAFe, LeSS) the JD asks for',
      'No tool names such as Jira or Azure DevOps',
      'Metrics shown in charts instead of text',
      'Mixing Scrum Master and Project Manager terms without matching the JD',
    ],
    keywordTips: [
      'Use both the ceremony and artifact names: sprint planning, retrospective, product backlog',
      'Write certification names in full and short form',
      'Include metrics terms: velocity, cycle time, burndown — with real results',
      'Mention the scaling framework if used: SAFe, LeSS, Nexus',
      'Name the domain and team size to match JD filters',
    ],
    faqs: [
      { q: 'What keywords should a Scrum Master CV include?', a: 'Scrum, Agile, sprint planning, retrospectives, backlog refinement, Jira, CSM/PSM certification, SAFe if relevant, velocity and stakeholder management.' },
      { q: 'Are certifications important for ATS?', a: 'Yes, for this role they are commonly screened. List them as text with full name and year in a Certifications section.' },
      { q: 'Scrum Master or Agile Coach?', a: 'Use the title in the JD. If you work at both levels, include both phrases truthfully so each search can match.' },
    ],
  },
};
