import type { AtsGuideData } from '@/lib/atsGuideData';

// ATS guides for the roles that previously had a CV example page but no ATS guide.
// Content is qualitative (keywords, sections, parsing behaviour) — no salary or
// statistic claims — so it is safe to ship without per-figure human review.
export const atsGuideDataExtra: Record<string, AtsGuideData> = {
  'sales-executive': {
    atsKeywords: ['Sales Executive', 'Lead Generation', 'B2B Sales', 'B2C Sales', 'Cold Calling', 'Client Acquisition', 'Revenue Target', 'Sales Pipeline', 'CRM', 'Salesforce', 'Negotiation', 'Account Management', 'Territory Management', 'Upselling', 'Channel Sales'],
    mustHaveSections: ['Professional Summary', 'Work Experience', 'Key Achievements', 'Skills', 'Education'],
    formattingRules: [
      'Use a single-column layout so the experience section is read in the right order',
      'Label the section exactly "Work Experience" — not "Sales Journey" or "Career Story"',
      'Put targets and achievements as text inside bullets, never inside charts or graphics',
      'List CRM tools by name (Salesforce, Zoho CRM, HubSpot) in a dedicated Skills section',
      'Use a text-based PDF or .docx — scanned or image-based files are unreadable to ATS',
      'Write your exact job title from the JD (for example "Inside Sales Executive") at least once',
    ],
    commonAtsFailures: [
      'Showing target-vs-achievement as an image or bar graph — ATS cannot read it',
      'Writing "met targets" with no numbers — there is nothing for ATS or recruiters to match',
      'Using "BD" or "AE" without spelling out Business Development or Account Executive',
      'Hiding the CRM tools you know inside a paragraph rather than a Skills section',
      'Putting phone and email in the Word header, which many ATS parsers skip',
    ],
    keywordTips: [
      'Mirror the JD wording: "lead generation" and "lead gen" are different strings to a literal matcher',
      'Name the sales motion — B2B, B2C, inside sales, field sales, channel sales — exactly as the JD does',
      'Name your CRM and sales-engagement tools individually',
      'Include the sector (FMCG, SaaS, BFSI, real estate) because JDs often filter by domain',
      'Add numbers next to keywords: quota attainment, deal size, accounts handled',
    ],
    faqs: [
      { q: 'What keywords should a sales executive CV include to pass ATS?', a: 'Match the JD, but the commonly screened terms are lead generation, client acquisition, B2B or B2C sales, sales pipeline, CRM (Salesforce, Zoho, HubSpot), negotiation, account management, and revenue or quota targets. Use them in both a Skills section and in achievement bullets.' },
      { q: 'How do I show sales targets on a CV so ATS can read them?', a: 'Write them as plain text inside bullets, for example "Achieved 112% of quarterly revenue target across a 40-account territory". Avoid charts, tables, and images for achievements, since parsers read text only.' },
    ],
  },
  'ios-developer': {
    atsKeywords: ['iOS Developer', 'Swift', 'SwiftUI', 'UIKit', 'Objective-C', 'Xcode', 'Core Data', 'Combine', 'REST API', 'MVVM', 'Auto Layout', 'App Store', 'TestFlight', 'XCTest', 'CI/CD', 'Firebase'],
    mustHaveSections: ['Technical Skills', 'Work Experience', 'Projects / Published Apps', 'Education', 'Certifications'],
    formattingRules: [
      'Use a single-column layout with standard section headings',
      'Group skills by category: Languages, Frameworks, Architecture, Tools',
      'Write the App Store link as visible text next to each published app',
      'Spell out the architecture pattern (MVVM, VIPER, Clean Architecture) in words',
      'Submit a text-based PDF or .docx and keep the file name professional',
      'Use the exact title from the JD, such as "iOS Engineer" or "iOS Developer"',
    ],
    commonAtsFailures: [
      'Listing only "Apple development" instead of Swift, SwiftUI, and UIKit by name',
      'Mentioning Objective-C but not Swift, or the reverse, when the JD wants both',
      'Using a skills graphic or star ratings for Swift proficiency',
      'Leaving out the architecture pattern the JD asks for',
      'Burying testing tools (XCTest, XCUITest) in prose instead of a skills list',
    ],
    keywordTips: [
      'List Swift and SwiftUI separately; ATS matches each string on its own',
      'Include both "UIKit" and "SwiftUI" if you have worked in both',
      'Name Apple frameworks you used in production: Core Data, Combine, WidgetKit, StoreKit',
      'Add release tooling such as Fastlane, TestFlight, and App Store Connect',
      'Mention minimum iOS version support if the JD does',
    ],
    faqs: [
      { q: 'Which keywords matter most on an iOS developer CV?', a: 'Swift, SwiftUI, UIKit, Xcode, and the architecture pattern (MVVM, VIPER, Clean Architecture) are the most commonly screened. Add Core Data, Combine, REST APIs, XCTest, and CI/CD tools like Fastlane where you have used them.' },
      { q: 'Should I list Objective-C on an iOS developer CV?', a: 'Only if you have genuinely worked with it, usually on legacy code. Lead with Swift and SwiftUI, and put Objective-C in a "legacy maintenance" mention so the ATS still sees the keyword when a JD requests it.' },
    ],
  },
  'full-stack-developer': {
    atsKeywords: ['Full Stack Developer', 'React', 'Node.js', 'JavaScript', 'TypeScript', 'Express', 'REST API', 'GraphQL', 'PostgreSQL', 'MongoDB', 'AWS', 'Docker', 'Git', 'CI/CD', 'Next.js', 'Microservices'],
    mustHaveSections: ['Technical Skills', 'Work Experience', 'Projects', 'Education', 'Certifications'],
    formattingRules: [
      'Use one column; two-column developer templates break reading order',
      'Split skills into Frontend, Backend, Database, and Cloud/DevOps lines',
      'Use "Work Experience" as the heading, and put the title and company on one line',
      'Link GitHub and live projects as visible URLs, not hidden hyperlinks only',
      'Submit a text-based PDF or .docx',
      'Include the JD title verbatim in your header or current role',
    ],
    commonAtsFailures: [
      'Writing "MERN" without listing MongoDB, Express, React, and Node.js individually',
      'Listing "JS frameworks" instead of React, Vue, or Angular by name',
      'Putting all skills in a skills cloud or icon grid',
      'Skipping the database and cloud tools the JD names',
      'Using "full-stack" only in a header image or logo block',
    ],
    keywordTips: [
      'Expand stack acronyms: write MERN as MongoDB, Express.js, React, Node.js',
      'Match naming exactly: "Node.js" versus "NodeJS" are different strings',
      'Include both "REST APIs" and "GraphQL" if you have used both',
      'Name your database engines and ORMs: PostgreSQL, MongoDB, Prisma, Sequelize',
      'Add testing tools such as Jest, Cypress, or Playwright',
    ],
    faqs: [
      { q: 'How should a full stack developer list skills for ATS?', a: 'Use separate labelled lines such as Frontend, Backend, Databases, and Cloud/DevOps. Write each technology by name and match the spelling in the JD. Avoid umbrella terms like "web technologies" that no keyword filter looks for.' },
      { q: 'Do I need to write MERN or list each technology?', a: 'List each technology. ATS filters search for strings such as "MongoDB" and "React", and a bare acronym may not match. You can include "MERN stack" as well as the four names.' },
    ],
  },
  'machine-learning-engineer': {
    atsKeywords: ['Machine Learning Engineer', 'Python', 'PyTorch', 'TensorFlow', 'Scikit-learn', 'MLOps', 'MLflow', 'Deep Learning', 'NLP', 'Computer Vision', 'Model Deployment', 'Feature Engineering', 'SQL', 'Docker', 'Kubernetes', 'AWS SageMaker'],
    mustHaveSections: ['Technical Skills', 'Work Experience', 'Projects', 'Publications / Competitions (if any)', 'Education'],
    formattingRules: [
      'Use a single column; keep equations and diagrams out of the CV body',
      'Group skills into Languages, ML Frameworks, MLOps/Deployment, and Cloud',
      'Spell out abbreviations once: Natural Language Processing (NLP)',
      'Write model metrics as text inside bullets so they can be parsed',
      'Link publications and Kaggle profiles as visible URLs',
      'Submit a text-based PDF or .docx',
    ],
    commonAtsFailures: [
      'Writing "AI/ML" only, with no named frameworks or model types',
      'Listing models used (BERT, ResNet) with no mention of deployment or MLOps tools',
      'Presenting skills as a radar chart or progress bars',
      'Using "ML Ops" and "MLOps" inconsistently with the JD',
      'Putting research papers in an image or two-column block',
    ],
    keywordTips: [
      'Name both your framework (PyTorch or TensorFlow) and your serving/monitoring tools',
      'Include task keywords the JD uses: NLP, computer vision, recommendation, forecasting',
      'List MLOps tools individually: MLflow, Kubeflow, DVC, Weights & Biases, SageMaker',
      'Say "deployed" or "productionised" in bullets, not only "trained"',
      'Mention data tooling too: SQL, Spark, Airflow',
    ],
    faqs: [
      { q: 'What ATS keywords should a machine learning engineer include?', a: 'Python, PyTorch or TensorFlow, scikit-learn, MLOps, model deployment, feature engineering, and the cloud and orchestration tools in the JD (AWS SageMaker, Docker, Kubernetes, MLflow). Add the task area, such as NLP or computer vision, exactly as the JD words it.' },
      { q: 'How do I show production ML experience to ATS and recruiters?', a: 'Use bullets that include verbs like deployed, served, monitored, and automated, alongside the tool names. For example: "Deployed a PyTorch ranking model on Kubernetes with MLflow tracking and drift monitoring."' },
    ],
  },
  'chartered-accountant': {
    atsKeywords: ['Chartered Accountant', 'CA', 'Statutory Audit', 'Internal Audit', 'GST', 'Income Tax', 'TDS', 'Ind AS', 'IFRS', 'Financial Reporting', 'Taxation', 'Due Diligence', 'Tally', 'SAP FICO', 'Compliance', 'ICAI'],
    mustHaveSections: ['Professional Summary', 'Work Experience / Articleship', 'Qualifications (CA, ICAI)', 'Skills and Software', 'Education'],
    formattingRules: [
      'Write "Chartered Accountant (ICAI)" in full at least once, not only "CA"',
      'Include your ICAI membership year and attempt details as plain text if the JD asks',
      'Use "Work Experience" as the heading, with articleship as its own clearly labelled entry',
      'List accounting software (Tally, SAP FICO, Oracle) in a Skills section',
      'Single-column layout, text-based PDF or .docx',
      'Spell out standards and acts: Ind AS, IFRS, Companies Act, GST Act',
    ],
    commonAtsFailures: [
      'Using only "CA" so that "Chartered Accountant" searches do not match',
      'Writing "taxation" with no mention of GST, TDS, or income tax by name',
      'Hiding the qualification inside a graphic or header banner',
      'Leaving out the ERP or accounting software named in the JD',
      'Naming articleship firms without describing the work performed',
    ],
    keywordTips: [
      'Use both "Chartered Accountant" and "CA" as the JD does',
      'List each compliance area separately: GST, TDS, Income Tax, ROC, FEMA',
      'Name audit types: statutory, internal, tax, and concurrent audit',
      'State reporting frameworks: Ind AS, IFRS, IGAAP',
      'Include tools by name: Tally Prime, SAP FICO, Oracle Financials, Excel',
    ],
    faqs: [
      { q: 'Which keywords should a chartered accountant put on a CV for ATS?', a: 'Chartered Accountant (ICAI), statutory audit, internal audit, GST, TDS, income tax, Ind AS, IFRS, financial reporting, due diligence, and the accounting software in the JD such as Tally or SAP FICO. Include both the full title and "CA".' },
      { q: 'How should I list articleship on a CV?', a: 'Treat it as work experience: firm name, dates, and bullets describing the audits, tax filings, and engagements you handled. Using the same "Work Experience" heading keeps it visible to ATS.' },
    ],
  },
  'sap-consultant': {
    atsKeywords: ['SAP Consultant', 'SAP FICO', 'SAP MM', 'SAP SD', 'SAP ABAP', 'SAP S/4HANA', 'SAP HANA', 'SAP Basis', 'Implementation', 'Configuration', 'Go-Live', 'Blueprinting', 'UAT', 'Support', 'Fiori', 'Rollout'],
    mustHaveSections: ['Professional Summary', 'SAP Modules and Skills', 'Project Experience', 'Certifications', 'Education'],
    formattingRules: [
      'State your primary module in the headline: "SAP FICO Consultant"',
      'Write every module with its code and its name, for example "SAP MM (Materials Management)"',
      'Describe each project with client domain, modules, phase, and your role in text',
      'Use "Work Experience" or "Project Experience" as plain-text headings',
      'List SAP versions explicitly: ECC 6.0, S/4HANA, with release numbers if known',
      'Single-column, text-based PDF or .docx',
    ],
    commonAtsFailures: [
      'Writing only "SAP" with no module name',
      'Using "S4" or "S4H" instead of "S/4HANA"',
      'Leaving out project phase terms the JD uses, such as blueprint, realization, go-live, hypercare',
      'Listing certifications as images of badges',
      'Describing projects as "ERP implementation" without naming the modules',
    ],
    keywordTips: [
      'Name each module separately: FICO, MM, SD, PP, ABAP, Basis',
      'Include both "S/4HANA" and "SAP ECC" when you have worked on both',
      'Mention implementation versus support experience explicitly',
      'Name the lifecycle phases you owned: blueprint, configuration, UAT, cutover, go-live',
      'List certifications in text with certifying body and year',
    ],
    faqs: [
      { q: 'How should an SAP consultant list modules on a CV?', a: 'Put the primary module in your headline and list each module in a Skills section with its full name, for example "SAP FICO (Financial Accounting and Controlling)". ATS matches the module codes and names recruiters search for, so include both.' },
      { q: 'Do project details matter for SAP CVs?', a: 'Yes. For each project give the client industry, SAP version, modules, your role, and the phase (implementation, rollout, or support). JDs filter on these terms, and they are the evidence of depth that a bare list of modules is missing.' },
    ],
  },
  'react-developer': {
    atsKeywords: ['React Developer', 'React.js', 'JavaScript', 'TypeScript', 'Redux', 'Next.js', 'HTML5', 'CSS3', 'Tailwind CSS', 'REST API', 'Jest', 'React Testing Library', 'Webpack', 'Git', 'Responsive Design', 'Hooks'],
    mustHaveSections: ['Technical Skills', 'Work Experience', 'Projects', 'Education', 'Certifications'],
    formattingRules: [
      'Single-column layout with plain section headings',
      'Group skills: Languages, Frameworks and Libraries, State Management, Testing, Tools',
      'Use the JD spelling for "React", "React.js", or "ReactJS" at least once',
      'Show live project and GitHub links as visible text',
      'Submit a text-based PDF or .docx',
      'Write your headline as "React Developer" or the exact JD title',
    ],
    commonAtsFailures: [
      'Writing "front-end frameworks" instead of naming React and its ecosystem',
      'Omitting TypeScript, state management, or testing tools the JD lists',
      'Using icons or logos in place of skill names',
      'Writing React only as "React" when the JD asks for "React.js"',
      'Listing component libraries without naming them',
    ],
    keywordTips: [
      'Name the state tool: Redux Toolkit, Zustand, Context API, React Query',
      'Include HTML5, CSS3, and JavaScript (ES6+) as separate skills',
      'Add the framework layer if relevant: Next.js, Remix, Vite',
      'Name testing tools: Jest, React Testing Library, Cypress',
      'Add accessibility and performance keywords if the JD mentions them',
    ],
    faqs: [
      { q: 'Which keywords matter most on a React developer CV?', a: 'React (matching the JD spelling), JavaScript (ES6+), TypeScript, Redux or another state tool, Next.js, HTML5, CSS3, REST APIs, Jest or React Testing Library, and Git. List each as its own skill rather than grouping them under "frontend technologies".' },
      { q: 'Does it matter whether I write React.js or ReactJS?', a: 'Literal ATS matching can treat them as different strings. Use the spelling in the JD for at least one occurrence, and include the plain term "React" as well so both searches match.' },
    ],
  },
  'investment-banker': {
    atsKeywords: ['Investment Banking', 'Financial Modelling', 'Valuation', 'DCF', 'M&A', 'LBO', 'Pitch Book', 'Due Diligence', 'Equity Research', 'Capital Markets', 'IPO', 'Excel', 'Bloomberg', 'Comparable Company Analysis', 'Deal Execution', 'CFA'],
    mustHaveSections: ['Summary', 'Work Experience', 'Transaction Experience', 'Education', 'Certifications (CFA, FRM)'],
    formattingRules: [
      'Write deal experience as text bullets: deal type, sector, and your contribution',
      'Spell out acronyms once: Discounted Cash Flow (DCF), Leveraged Buyout (LBO)',
      'Use the headings "Work Experience" and "Education" exactly',
      'List tools by name: Excel, Bloomberg, Capital IQ, FactSet, PowerPoint',
      'Single column, text-based PDF; keep to one page for early-career roles',
      'Respect confidentiality: describe deals by sector and size, not client names',
    ],
    commonAtsFailures: [
      'Using only "finance" language with no valuation or modelling terms',
      'Listing "M&A" without describing buy-side or sell-side work',
      'Skipping the data and modelling tools the JD names',
      'Putting transactions inside a table or image that parsers skip',
      'Writing certifications as badges instead of text',
    ],
    keywordTips: [
      'Include both the acronym and its expansion for DCF, LBO, M&A, and IPO',
      'Name the products you worked on: M&A advisory, ECM, DCM, leveraged finance',
      'Mention sector coverage as the JD words it: technology, healthcare, industrials',
      'List Bloomberg, Capital IQ, or FactSet if you have used them',
      'State CFA level status in plain text, for example "CFA Level II candidate"',
    ],
    faqs: [
      { q: 'What keywords should an investment banking CV have for ATS?', a: 'Financial modelling, valuation, DCF, comparable company analysis, M&A, LBO, due diligence, pitch books, capital markets, and the tools in the JD such as Excel, Bloomberg, or Capital IQ. Spell out each acronym at least once.' },
      { q: 'How do I list deals without breaking confidentiality?', a: 'Describe each transaction by type, sector, size range, and your role, for example "Sell-side M&A advisory for a mid-size industrial company; built DCF and comps". Avoid client names, which are usually confidential and add no ATS value.' },
    ],
  },
  'scrum-master': {
    atsKeywords: ['Scrum Master', 'Agile', 'Scrum', 'Sprint Planning', 'Retrospective', 'Backlog Grooming', 'Kanban', 'Jira', 'Confluence', 'SAFe', 'Stakeholder Management', 'Velocity', 'Servant Leadership', 'PSM', 'CSM', 'Release Planning'],
    mustHaveSections: ['Professional Summary', 'Work Experience', 'Certifications (CSM, PSM, SAFe)', 'Skills and Tools', 'Education'],
    formattingRules: [
      'Put certifications in text with the full name and acronym: "Certified ScrumMaster (CSM)"',
      'Use "Work Experience" and describe team size, delivery model, and tools per role',
      'List tools by name: Jira, Confluence, Azure DevOps, Trello',
      'Write metrics as text: velocity trends, release frequency, team size',
      'Single column, text-based PDF or .docx',
      'Use the JD title exactly, such as "Scrum Master" or "Agile Delivery Lead"',
    ],
    commonAtsFailures: [
      'Writing "Agile" only, without Scrum, Kanban, or SAFe as the JD specifies',
      'Showing certifications as badge images',
      'Omitting team size or number of teams supported',
      'Leaving out tools such as Jira that are screened for directly',
      'Using "SM" for Scrum Master with no spelled-out form',
    ],
    keywordTips: [
      'Include both Scrum and Agile; JDs use them differently',
      'Name each ceremony you facilitate: sprint planning, daily stand-up, review, retrospective',
      'Add scaled frameworks if relevant: SAFe, LeSS, Nexus',
      'List certification bodies: Scrum Alliance, Scrum.org, Scaled Agile',
      'Mention the delivery context: product teams, services projects, or distributed teams',
    ],
    faqs: [
      { q: 'Which certifications and keywords should a Scrum Master CV include?', a: 'List the certification in full, such as Certified ScrumMaster (CSM) or Professional Scrum Master (PSM), plus SAFe if you hold it. Core keywords are Scrum, Agile, sprint planning, retrospectives, backlog refinement, Kanban, Jira, and stakeholder management.' },
      { q: 'How can I show impact as a Scrum Master?', a: 'Use text bullets with team size and outcomes, for example "Coached 3 teams of 8 engineers; reduced carry-over stories by improving sprint planning". Keep metrics in sentences instead of charts so ATS can parse them.' },
    ],
  },
  'business-development-manager': {
    atsKeywords: ['Business Development Manager', 'Business Development', 'Lead Generation', 'Strategic Partnerships', 'Client Acquisition', 'B2B Sales', 'Market Research', 'Proposal Writing', 'Negotiation', 'Revenue Growth', 'CRM', 'Pipeline Management', 'Key Account Management', 'Market Expansion', 'RFP'],
    mustHaveSections: ['Professional Summary', 'Work Experience', 'Key Achievements', 'Skills', 'Education'],
    formattingRules: [
      'Use "Work Experience" and put revenue and growth outcomes in text bullets',
      'Single-column layout; avoid graphs of revenue growth',
      'List CRM and tools by name: Salesforce, HubSpot, Zoho, LinkedIn Sales Navigator',
      'Spell out "Business Development (BD)" once',
      'Name target industries and geographies as the JD does',
      'Text-based PDF or .docx',
    ],
    commonAtsFailures: [
      'Using "BD" alone so "Business Development" searches do not match',
      'Describing results without numbers or time frames',
      'Listing "partnerships" without saying what type or scale',
      'Skipping CRM and pipeline tools named in the JD',
      'Placing contact details in the Word header',
    ],
    keywordTips: [
      'Distinguish partnerships, enterprise sales, and market expansion if the JD does',
      'Use both "business development" and "new business" where relevant',
      'Name your sales cycle stages: prospecting, proposal, negotiation, closure',
      'Include RFP or tender experience if you have it',
      'Add sector and geography keywords such as SaaS, BFSI, APAC, or Pan-India',
    ],
    faqs: [
      { q: 'What keywords should a business development manager CV include?', a: 'Business development, lead generation, strategic partnerships, client acquisition, pipeline management, negotiation, proposal writing, key account management, and the CRM tools named in the JD. Match the JD phrasing closely.' },
      { q: 'How is a BD manager CV different from a sales CV for ATS?', a: 'JDs for BD roles stress new markets, partnerships, and proposals alongside revenue, so those keywords should appear. Sales CVs focus on quota and closing. Mirror whichever vocabulary the specific JD uses.' },
    ],
  },
  'network-engineer': {
    atsKeywords: ['Network Engineer', 'Cisco', 'CCNA', 'CCNP', 'Routing', 'Switching', 'TCP/IP', 'BGP', 'OSPF', 'VLAN', 'Firewall', 'VPN', 'Palo Alto', 'Juniper', 'LAN/WAN', 'Network Security', 'SD-WAN', 'Troubleshooting'],
    mustHaveSections: ['Technical Skills', 'Work Experience', 'Certifications', 'Projects', 'Education'],
    formattingRules: [
      'Put certifications in text with exact names: "Cisco Certified Network Associate (CCNA)"',
      'Group skills: Routing and Switching, Security, Cloud Networking, Monitoring Tools',
      'Name vendors and device families you have configured',
      'Write network scale as text: number of sites, devices, or users supported',
      'Single column, text-based PDF or .docx',
      'Use "Work Experience" as the heading',
    ],
    commonAtsFailures: [
      'Listing only "networking" without protocols such as BGP, OSPF, and VLAN',
      'Showing certifications as badge images',
      'Leaving out vendor names that the JD screens for',
      'Using a network diagram image in place of written scope',
      'Omitting monitoring and ticketing tools',
    ],
    keywordTips: [
      'List protocols individually: TCP/IP, BGP, OSPF, EIGRP, VLAN, STP',
      'Include vendors: Cisco, Juniper, Palo Alto, Fortinet, Aruba',
      'Add both certification acronyms and full names',
      'Name monitoring tools: SolarWinds, Wireshark, Nagios, PRTG',
      'Include cloud networking if relevant: AWS VPC, Azure VNet',
    ],
    faqs: [
      { q: 'Which certifications and keywords should a network engineer list for ATS?', a: 'CCNA or CCNP written out in full and as acronyms, plus protocols (BGP, OSPF, VLAN, TCP/IP), vendors (Cisco, Juniper, Palo Alto), firewall and VPN technologies, and monitoring tools. Place them in a dedicated Skills section.' },
      { q: 'How do I show network scale on a CV?', a: 'State it in a sentence, for example "Managed a 12-site WAN with 400+ devices across Cisco and Juniper platforms". Text keeps the scale visible to both ATS and recruiters; diagrams are ignored by parsers.' },
    ],
  },
  'logistics-manager': {
    atsKeywords: ['Logistics Manager', 'Supply Chain', 'Warehouse Management', 'Transportation', 'Freight', 'Inventory Control', 'Last-Mile Delivery', '3PL', 'WMS', 'TMS', 'SAP', 'Route Optimization', 'Import Export', 'Customs Clearance', 'Vendor Management', 'Cost Reduction'],
    mustHaveSections: ['Professional Summary', 'Work Experience', 'Skills and Systems', 'Certifications', 'Education'],
    formattingRules: [
      'Use "Work Experience" and state fleet, warehouse, or shipment scale as text',
      'List systems by name: SAP, WMS, TMS, Oracle SCM, Excel',
      'Spell out acronyms once: Third-Party Logistics (3PL), Warehouse Management System (WMS)',
      'Single column, text-based PDF or .docx',
      'Quantify cost, on-time delivery, and inventory outcomes in bullets',
      'Name your specialisation: domestic, international, e-commerce, or cold chain',
    ],
    commonAtsFailures: [
      'Writing "logistics" only, without warehousing, transport, or inventory terms',
      'Leaving out WMS or TMS tools named in the JD',
      'Using KPIs as a graphic rather than bullet text',
      'Missing import/export and customs terms for international roles',
      'Using regional abbreviations that the JD does not use',
    ],
    keywordTips: [
      'Use the exact function names in the JD: warehouse operations, fleet management, distribution',
      'Name freight modes: road, rail, air, sea',
      'Include KPIs: on-time delivery, order accuracy, cost per shipment',
      'Mention 3PL and vendor management experience explicitly',
      'List certifications such as Six Sigma or APICS in text',
    ],
    faqs: [
      { q: 'What keywords should a logistics manager CV include?', a: 'Warehouse management, transportation, inventory control, freight, last-mile delivery, 3PL, vendor management, route optimisation, WMS/TMS tools, and customs terms for international roles. Mirror the JD wording for each.' },
      { q: 'How can I show logistics results on an ATS-friendly CV?', a: 'Write them in bullet text with the metric and scale, such as "Improved on-time delivery across 3 distribution centres by redesigning dispatch schedules". Avoid charts and tables for KPIs.' },
    ],
  },
  'interior-designer': {
    atsKeywords: ['Interior Designer', 'AutoCAD', 'SketchUp', '3ds Max', 'Revit', 'Space Planning', 'Residential Design', 'Commercial Interiors', 'Mood Board', 'Material Selection', 'Client Presentation', 'BOQ', 'Site Supervision', 'Lumion', 'V-Ray', 'Adobe Photoshop'],
    mustHaveSections: ['Professional Summary', 'Work Experience', 'Software Skills', 'Portfolio Link', 'Education'],
    formattingRules: [
      'Keep the CV text-based and put visual work in a linked portfolio',
      'Write the portfolio URL as visible text in the header or a dedicated section',
      'List software in a text Skills section rather than as logos',
      'Describe projects with type, size, and your role: concept, drawings, site supervision',
      'Single column, text-based PDF or .docx',
      'Use "Work Experience" as the heading',
    ],
    commonAtsFailures: [
      'Using image-heavy creative templates that parsers read as blank',
      'Showing software skills as icon rows',
      'Embedding the whole portfolio as images in the CV',
      'Writing "designing spaces" with no tools or project types',
      'Leaving out BOQ, site supervision, or vendor coordination terms the JD names',
    ],
    keywordTips: [
      'Name each tool separately: AutoCAD, SketchUp, 3ds Max, V-Ray, Revit',
      'Separate residential, commercial, retail, and hospitality project types',
      'Include BOQ, material schedule, and site supervision if you do them',
      'Add client-facing terms: presentations, concept development, mood boards',
      'Place the portfolio URL near the top as plain text',
    ],
    faqs: [
      { q: 'How can an interior designer make a CV ATS-friendly without losing visual appeal?', a: 'Keep the CV itself plain and text-based, and move visuals to a portfolio linked as visible text. ATS cannot read images, so skills, projects, and tools must be written as words.' },
      { q: 'Which software keywords matter for interior designer CVs?', a: 'AutoCAD, SketchUp, 3ds Max, V-Ray or Lumion, Revit, and Adobe Photoshop are the most commonly requested. List each one by name and add the project types where you used them.' },
    ],
  },
  pharmacist: {
    atsKeywords: ['Pharmacist', 'Clinical Pharmacy', 'Dispensing', 'Drug Interaction', 'Pharmacovigilance', 'Inventory Management', 'Patient Counselling', 'Prescription Verification', 'Regulatory Compliance', 'GMP', 'Hospital Pharmacy', 'Retail Pharmacy', 'D.Pharm', 'B.Pharm', 'Pharmacy Council', 'Drug Safety'],
    mustHaveSections: ['Professional Summary', 'Licensure and Registration', 'Work Experience', 'Education', 'Skills'],
    formattingRules: [
      'Put your Pharmacy Council registration in plain text with state and year',
      'Write qualifications in full: "Bachelor of Pharmacy (B.Pharm)"',
      'Use "Work Experience" and state setting: hospital, retail, clinical, or manufacturing',
      'List systems and software by name: pharmacy management systems, ERP',
      'Single column, text-based PDF or .docx',
      'Include regulatory terms the JD uses, such as GMP or Schedule H handling',
    ],
    commonAtsFailures: [
      'Omitting registration or licence details that JDs filter on',
      'Using only "B.Pharm" without the expanded form',
      'Leaving the setting (hospital versus retail versus pharma industry) unclear',
      'Skipping pharmacovigilance or compliance terms for industry roles',
      'Listing credentials as scanned images',
    ],
    keywordTips: [
      'Use both abbreviated and full degree names',
      'State the practice area: clinical, community, hospital, regulatory, or manufacturing',
      'Include patient-facing terms: counselling, prescription verification, medication adherence',
      'Add compliance terms: GMP, GDP, pharmacovigilance, drug safety reporting',
      'Name software you have used for dispensing and inventory',
    ],
    faqs: [
      { q: 'What should a pharmacist CV include to pass ATS?', a: 'Registration details, the full degree name (for example Bachelor of Pharmacy, B.Pharm), practice setting, and keywords such as dispensing, prescription verification, patient counselling, drug interaction checks, inventory management, and relevant compliance terms.' },
      { q: 'Do pharmacist CVs differ for hospital and industry roles?', a: 'Yes. Hospital and retail roles emphasise dispensing, counselling, and inventory. Industry roles lean on GMP, regulatory affairs, quality, and pharmacovigilance. Use the vocabulary of the specific JD.' },
    ],
  },
  'embedded-systems-engineer': {
    atsKeywords: ['Embedded Systems Engineer', 'Embedded C', 'C++', 'RTOS', 'FreeRTOS', 'ARM Cortex', 'Microcontroller', 'UART', 'SPI', 'I2C', 'CAN', 'Firmware', 'Device Drivers', 'Linux Kernel', 'Debugging', 'IoT'],
    mustHaveSections: ['Technical Skills', 'Work Experience', 'Projects', 'Education', 'Certifications'],
    formattingRules: [
      'Group skills: Languages, Microcontrollers and Processors, Protocols, RTOS and OS, Tools',
      'Write protocols individually: UART, SPI, I2C, CAN',
      'Describe projects with hardware platform, language, and outcome',
      'Single column, text-based PDF or .docx',
      'Use "Work Experience" as the heading',
      'Link GitHub or hardware project pages as visible URLs',
    ],
    commonAtsFailures: [
      'Writing "embedded" without languages, MCU families, or protocols',
      'Listing "C/C++" as one item when JDs search for each',
      'Leaving out RTOS names the JD lists',
      'Using block diagrams in place of written project scope',
      'Omitting debug tools such as JTAG, oscilloscope, and logic analyser',
    ],
    keywordTips: [
      'Write both "C" and "C++", and "Embedded C" if the JD uses it',
      'Name chip families: STM32, ARM Cortex-M, ESP32, PIC, AVR',
      'Name the RTOS you used: FreeRTOS, Zephyr, VxWorks',
      'Include debug and toolchain terms: JTAG, GDB, Keil, IAR',
      'Add domain terms as relevant: automotive, IoT, medical, AUTOSAR',
    ],
    faqs: [
      { q: 'Which keywords should an embedded systems engineer include for ATS?', a: 'Embedded C and C++, the microcontroller families you used (STM32, ARM Cortex-M, ESP32), RTOS names such as FreeRTOS, communication protocols (UART, SPI, I2C, CAN), firmware, device drivers, and debugging tools.' },
      { q: 'How should I present hardware projects on a CV?', a: 'Write a short text entry for each: the board or MCU, language, protocols, and the result. Include a visible link to the code repository or write-up; ATS cannot read schematics or photos.' },
    ],
  },
};
