import type { AtsGuideData } from '@/lib/atsGuideData';

// Hand-written ATS guidance for the roles that previously had no /ats-guide/[role] page.
// Deliberately keyword/format focused — no salary or statistical claims.

const SINGLE_COLUMN = 'Use a single-column layout — table-based and two-column CVs break most ATS parsers';
const FILE_FORMAT = 'Submit as .docx or a text-based PDF (not a scanned image) — follow the format the JD or portal asks for';
const HEADINGS = 'Name sections with standard labels ("Work Experience", "Education", "Skills") — ATS looks for these exact headings';

export const atsGuideGapRoles: Record<string, AtsGuideData> = {
  'business-development-manager': {
    atsKeywords: ['Business Development Manager', 'B2B Sales', 'Lead Generation', 'Pipeline Management', 'Client Acquisition', 'Account Management', 'Salesforce', 'HubSpot', 'LinkedIn Sales Navigator', 'Negotiation', 'Revenue Forecasting', 'Key Account Management', 'Go-to-market', 'Strategic Partnerships', 'SaaS Sales', 'CRM', 'Enterprise Sales', 'Proposal Writing', 'Target Achievement', 'Stakeholder Management'],
    mustHaveSections: ['Professional Summary', 'Work Experience (with revenue/target metrics)', 'Skills (CRM & Sales Tools)', 'Education', 'Key Achievements'],
    formattingRules: [
      SINGLE_COLUMN,
      HEADINGS,
      'Put a number in every experience bullet: revenue closed, quota attainment %, pipeline value, or accounts won',
      'List CRM and sales tools (Salesforce, HubSpot, Zoho) in a dedicated Skills section, not only inside bullets',
      'Write "Business Development Manager" in full at least once — ATS may not expand "BDM"',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Describing responsibilities without any revenue or quota figure — recruiters and ATS ranking both favour quantified sales results',
      'Using only "BDM" or "BD" without the full job title',
      'Leaving out the CRM tools entirely — Salesforce and HubSpot are among the most screened terms for sales roles',
      'Listing "sales skills" generically instead of naming the motion: B2B, enterprise, inside sales, channel partnerships',
      'Putting phone and email in a Word header/footer where parsers cannot read them',
    ],
    keywordTips: [
      'Mirror the JD\'s sales motion exactly — "enterprise sales", "channel partnerships", or "inside sales" are different search strings',
      'Include both "Business Development" and "Business Development Manager" so either recruiter search matches',
      'Name the industry or vertical you sell into (SaaS, BFSI, EdTech, manufacturing) — many JDs filter on domain',
      'Pair each tool with a result: "Salesforce — grew qualified pipeline from ₹X to ₹Y" beats a bare tool name',
      'Add "Sales Navigator" or "outbound prospecting" if you source leads yourself',
    ],
    faqs: [
      { q: 'What ATS keywords should a business development manager use on their CV in India?', a: 'Core terms are B2B sales, lead generation, pipeline management, client acquisition, account management, negotiation and revenue forecasting, plus the CRM you use (Salesforce, HubSpot or Zoho). Add your vertical (SaaS, BFSI, EdTech) and motion (enterprise, channel, inside sales) exactly as the job description words them.' },
      { q: 'Should I put sales targets and revenue numbers on a BDM CV?', a: 'Yes. Quantified results such as quota attainment, revenue closed, or accounts won are what separate a BDM CV from a generic sales CV. Use figures you can defend in an interview; if a number is confidential, use a percentage or a range instead.' },
    ],
  },
  'chartered-accountant': {
    atsKeywords: ['Chartered Accountant', 'CA', 'ICAI', 'Statutory Audit', 'Internal Audit', 'Tax Audit', 'GST', 'Income Tax', 'TDS', 'Ind AS', 'IFRS', 'Financial Reporting', 'Consolidation', 'Transfer Pricing', 'Internal Controls', 'SAP', 'Tally', 'Excel', 'MIS Reporting', 'Statutory Compliance', 'Companies Act', 'Due Diligence'],
    mustHaveSections: ['Professional Summary', 'Work Experience / Articleship', 'Qualifications (CA, ICAI membership year)', 'Skills (Accounting Software & Standards)', 'Education'],
    formattingRules: [
      SINGLE_COLUMN,
      HEADINGS,
      'State "Chartered Accountant (ICAI)" and your membership/qualification year in the header or qualifications section',
      'Write out standards and acronyms once: "Ind AS (Indian Accounting Standards)", "GST (Goods and Services Tax)"',
      'List ERP and accounting tools (SAP, Tally, Oracle, Excel) in a dedicated Skills section',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Writing only "CA" — ATS may not match it to "Chartered Accountant" and the abbreviation collides with other terms',
      'Omitting ICAI membership or the year of qualification, which many finance JDs filter on',
      'Burying GST, TDS and Ind AS inside a paragraph instead of a searchable Skills section',
      'Not separating articleship from post-qualification experience, so tenure gets miscounted',
      'Using a stylised layout with side panels for skills — parsers read the panel as noise or drop it',
    ],
    keywordTips: [
      'Use both "Chartered Accountant" and "CA" once each so both search strings match',
      'Name the audit type precisely — statutory, internal, tax, or concurrent audit are separate keywords',
      'Include the compliance regimes you handled: GST, TDS, Income Tax, Companies Act, FEMA',
      'Add both "Ind AS" and "IFRS" if you have worked with either; JDs frequently list one or the other',
      'Mention the ERP by name (SAP FICO, Oracle, Tally Prime) rather than "accounting software"',
    ],
    faqs: [
      { q: 'How should a chartered accountant list ICAI membership on a CV for ATS?', a: 'Write "Chartered Accountant (ICAI)" with your qualification year in the header or a Qualifications section, using the plain-text words rather than a logo or badge. That gives the parser the exact string recruiters search for and keeps the credential visible to a human reader.' },
      { q: 'Which keywords matter most for a CA fresher applying through ATS?', a: 'Lead with Chartered Accountant, articleship, statutory audit, GST, Income Tax, Ind AS and the tools you used during articleship (Tally, SAP, Excel). Describe the audits and compliance work from your articleship in bullets so those terms appear in context as well as in the Skills section.' },
    ],
  },
  'embedded-systems-engineer': {
    atsKeywords: ['Embedded Systems Engineer', 'Embedded C', 'C++', 'ARM Cortex-M', 'STM32', 'FreeRTOS', 'RTOS', 'Firmware', 'Device Drivers', 'CAN Bus', 'SPI', 'I2C', 'UART', 'JTAG', 'Linux BSP', 'Bootloader', 'IoT', 'Microcontroller', 'AUTOSAR', 'MISRA C', 'Oscilloscope', 'Embedded Linux'],
    mustHaveSections: ['Technical Skills (MCUs, Protocols, Tools)', 'Work Experience', 'Projects (with hardware/firmware detail)', 'Education', 'Certifications'],
    formattingRules: [
      SINGLE_COLUMN,
      HEADINGS,
      'Group technical skills by category: Languages, Microcontrollers/SoCs, RTOS/OS, Protocols, Debug tools',
      'Write protocols individually ("SPI", "I2C", "UART", "CAN") — a combined "SPI/I2C/UART" may not match each one',
      'Name the exact MCU or SoC families you have shipped on (STM32, NXP, TI, Nordic, ESP32)',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Writing "C/C++" only — some ATS treat it as one token; list "C", "Embedded C" and "C++" separately',
      'Saying "microcontrollers" without naming any family or vendor',
      'Leaving out debug and test tooling (JTAG, logic analyser, oscilloscope) that JDs screen for',
      'Putting project hardware details in an image or schematic — parsers cannot read images',
      'Mixing firmware and unrelated web skills in one long list, which dilutes the embedded keywords',
    ],
    keywordTips: [
      'List "Embedded C" explicitly — it is a distinct search term from plain "C"',
      'Include automotive standards if relevant: "AUTOSAR", "MISRA C", "ISO 26262", "CAN/LIN"',
      'Name the RTOS you have used (FreeRTOS, Zephyr, ThreadX) instead of only "RTOS"',
      'Add connectivity stacks you touched: BLE, Wi-Fi, LoRa, MQTT for IoT-flavoured JDs',
      'Describe one board bring-up or driver-writing project so "bring-up", "device driver" and "bootloader" appear in context',
    ],
    faqs: [
      { q: 'What ATS keywords should an embedded systems engineer include in India?', a: 'Embedded C/C++, the MCU families you have used (STM32, ARM Cortex-M, NXP, ESP32), RTOS names such as FreeRTOS, protocols (SPI, I2C, UART, CAN), JTAG debugging, device drivers, bootloader and Linux BSP if applicable. Match the JD\'s exact terms — automotive roles will screen for AUTOSAR and MISRA C.' },
      { q: 'Do hardware skills like oscilloscopes and logic analysers belong on an embedded CV?', a: 'Yes. Debug and measurement tools are commonly screened terms in embedded JDs. Put them in the Skills section and reference them in a project bullet, for example diagnosing a timing issue on an SPI bus with a logic analyser.' },
    ],
  },
  'full-stack-developer': {
    atsKeywords: ['Full Stack Developer', 'JavaScript', 'TypeScript', 'React', 'Node.js', 'Express', 'Next.js', 'REST API', 'GraphQL', 'PostgreSQL', 'MongoDB', 'MySQL', 'HTML', 'CSS', 'Docker', 'AWS', 'Git', 'CI/CD', 'Microservices', 'Redis', 'Jest', 'Agile'],
    mustHaveSections: ['Skills (Frontend / Backend / DevOps)', 'Work Experience', 'Projects (with live links)', 'Education', 'Certifications'],
    formattingRules: [
      SINGLE_COLUMN,
      HEADINGS,
      'Split skills into Frontend, Backend, Database and DevOps lines so both halves of "full stack" are visible to the parser',
      'Use the exact framework spelling from the JD: "Node.js" vs "NodeJS", "React.js" vs "React"',
      'Add GitHub and live project URLs as plain text, not embedded icons',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Listing only frontend or only backend keywords, which hurts matching on a role that screens for both',
      'Skill-bar graphics or star ratings for proficiency — ATS cannot read them',
      'Writing "MERN stack" without spelling out MongoDB, Express, React and Node.js',
      'Placing links only behind icons or hyperlinked words with no visible URL',
      'Job titles like "Web Ninja" or "Code Wizard" instead of "Full Stack Developer"',
    ],
    keywordTips: [
      'Spell out stacks: write "MERN (MongoDB, Express.js, React, Node.js)" so every component is indexed',
      'Include both "JavaScript" and "TypeScript" when you use both; they are separate keywords',
      'Add "REST API" and, where true, "GraphQL" — API design is screened on most full stack JDs',
      'Name the database types you have used, not just "databases"',
      'Mention testing and deployment: "Jest", "Cypress", "Docker", "GitHub Actions"',
    ],
    faqs: [
      { q: 'What keywords should a full stack developer CV have to pass ATS?', a: 'Cover both halves of the stack: JavaScript/TypeScript, React or Angular, Node.js or another backend language, REST API design, at least one SQL and one NoSQL database, Git, Docker, and a cloud provider. Use the same spelling as the job description and repeat key tools in the Skills section and inside project bullets.' },
      { q: 'Should I write "MERN stack" or list each technology separately?', a: 'Do both. "MERN" is a common recruiter search term, but ATS matches literal strings, so also list MongoDB, Express.js, React and Node.js individually. Writing "MERN (MongoDB, Express.js, React, Node.js)" once in your skills section covers both.' },
    ],
  },
  'interior-designer': {
    atsKeywords: ['Interior Designer', 'Interior Design', 'AutoCAD', 'SketchUp', '3ds Max', 'Revit', 'V-Ray', 'Lumion', 'Space Planning', 'BOQ', 'Material Specification', 'Furniture Layout', 'Adobe Photoshop', 'Site Supervision', 'Vendor Coordination', 'Residential Design', 'Commercial Interiors', 'Mood Boards', 'Working Drawings', 'Client Presentation'],
    mustHaveSections: ['Professional Summary', 'Work Experience (with project types)', 'Software Skills', 'Portfolio Link', 'Education'],
    formattingRules: [
      SINGLE_COLUMN,
      HEADINGS,
      'Put your portfolio URL (Behance, Instagram, personal site) as plain visible text near the top — images in the CV itself are invisible to ATS',
      'Describe projects in text: type (residential/commercial), area in sq ft, scope handled, and your role',
      'List design software by exact name in a dedicated Skills section',
      'Keep the CV itself text-first; let the portfolio carry the visuals',
    ],
    commonAtsFailures: [
      'A visually designed CV with image-based text or icon rows — parsers extract little or nothing',
      'Showing software proficiency as graphics or percentage bars',
      'Listing "design software" instead of naming AutoCAD, SketchUp, 3ds Max, Revit and V-Ray',
      'Not stating project type and scale, so the reader cannot judge residential vs commercial experience',
      'Embedding project photos in the CV instead of linking to a portfolio',
    ],
    keywordTips: [
      'Write "BOQ (Bill of Quantities)" once — both forms appear in Indian interior JDs',
      'Name rendering tools individually: V-Ray, Lumion, Enscape, Corona',
      'Use scope words such as "space planning", "working drawings", "material specification" and "site supervision"',
      'Specify segment: residential, hospitality, retail, office fit-outs',
      'Mention vendor and contractor coordination — it is a common screened term for execution-heavy roles',
    ],
    faqs: [
      { q: 'Can an interior designer use a creative CV template and still pass ATS?', a: 'Keep the CV itself simple and text-based, and put the creativity in your portfolio. Graphic-heavy CVs with image text, icons, or skill bars are parsed poorly. Link your Behance or website as plain text so a human reviewer can open the visuals after the ATS stage.' },
      { q: 'Which software should an interior designer list for ATS?', a: 'Name each tool: AutoCAD, SketchUp, 3ds Max, Revit, V-Ray or Lumion, and Adobe Photoshop, plus Excel if you prepare BOQs. Then show them in context — for example "prepared working drawings in AutoCAD and 3D renders in SketchUp with V-Ray for a 3-BHK residential project".' },
    ],
  },
  'investment-banker': {
    atsKeywords: ['Investment Banking', 'Investment Banker', 'M&A', 'Mergers and Acquisitions', 'DCF', 'LBO', 'Financial Modelling', 'Valuation', 'Comparable Company Analysis', 'Precedent Transactions', 'Pitchbook', 'Equity Capital Markets', 'Debt Capital Markets', 'IPO', 'Due Diligence', 'Bloomberg', 'Capital IQ', 'Excel', 'PowerPoint', 'Deal Execution', 'Information Memorandum', 'Analyst'],
    mustHaveSections: ['Education (with institution and CGPA)', 'Work Experience / Internships (with deal detail)', 'Transaction Experience', 'Skills (Modelling & Tools)', 'Certifications (CFA, NISM, etc.)'],
    formattingRules: [
      SINGLE_COLUMN,
      HEADINGS,
      'Keep to one page for analyst and associate roles; recruiters scan quickly',
      'Show deals as "Sell-side advisory to [sector] company on ₹X cr acquisition" — state role, deal type and sector',
      'List tools individually: Excel, Bloomberg, Capital IQ, FactSet, PowerPoint',
      'Use the standard terms — "Mergers and Acquisitions" and "M&A" together at least once',
    ],
    commonAtsFailures: [
      'Using only "M&A" or only "Mergers and Acquisitions" — include both forms',
      'Describing deals without type or sector, which hides the keywords ATS ranks on',
      'Omitting valuation methods (DCF, comps, LBO) from the Skills section',
      'Putting education below experience for candidates early in career, contrary to convention',
      'Two-column layouts or heavily formatted tables that break a dense finance CV',
    ],
    keywordTips: [
      'Name the valuation methods you performed: DCF, trading comps, precedent transactions, LBO',
      'Distinguish advisory work: sell-side, buy-side, ECM (IPO/QIP), DCM',
      'Include data terminals you have actually used: Bloomberg, Capital IQ, FactSet, Refinitiv',
      'Mention certifications by full name and acronym: "CFA Level II candidate", "NISM Series"',
      'Use deal verbs — "executed", "structured", "modelled", "prepared information memorandum" — inside bullets',
    ],
    faqs: [
      { q: 'What ATS keywords matter for an investment banking CV in India?', a: 'Financial modelling, DCF, LBO, comparable company analysis, precedent transactions, valuation, M&A, equity and debt capital markets, pitchbook preparation, due diligence, and the tools Excel, PowerPoint, Bloomberg and Capital IQ. Describe each deal in a bullet so those terms appear in context, not only in a skills list.' },
      { q: 'Should an investment banking CV be one page?', a: 'For analyst and associate applications, one page is the norm and recruiters expect it. Senior candidates may use two pages, but each line should still describe a specific transaction, valuation, or responsibility.' },
    ],
  },
  'ios-developer': {
    atsKeywords: ['iOS Developer', 'Swift', 'SwiftUI', 'UIKit', 'Objective-C', 'Xcode', 'Core Data', 'Combine', 'REST API', 'MVVM', 'Firebase', 'Unit Testing', 'XCTest', 'App Store', 'TestFlight', 'CocoaPods', 'Swift Package Manager', 'Core Animation', 'Push Notifications', 'CI/CD', 'Fastlane', 'Git'],
    mustHaveSections: ['Skills (iOS Stack)', 'Work Experience', 'Published Apps (App Store links)', 'Projects', 'Education'],
    formattingRules: [
      SINGLE_COLUMN,
      HEADINGS,
      'Add App Store links and download/rating figures for every shipped app as plain text',
      'List both "Swift" and "Objective-C" if you use both; JDs often screen for each',
      'Name architecture patterns explicitly: MVVM, MVC, VIPER, Clean Architecture',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Writing "iOS" alone without "Swift" or "SwiftUI" — the language is the primary screened term',
      'Missing "UIKit" when the JD targets a legacy codebase, or "SwiftUI" when it targets a modern one',
      'Omitting testing (XCTest, unit testing) and release tooling (TestFlight, Fastlane)',
      'Showing App Store apps as screenshots with no text or link',
      'Listing "Apple frameworks" generically instead of Core Data, Combine, Core Location and so on',
    ],
    keywordTips: [
      'Include both SwiftUI and UIKit when you have used both — JDs frequently ask for one or the other',
      'Name persistence and networking: Core Data, Realm, URLSession, Alamofire',
      'Add "TestFlight", "App Store Connect" and "Fastlane" to show release ownership',
      'State the iOS versions or devices you targeted where relevant',
      'Mention accessibility (VoiceOver) and performance profiling (Instruments) when you have done it',
    ],
    faqs: [
      { q: 'What keywords should an iOS developer put on their CV for ATS?', a: 'Swift, SwiftUI, UIKit, Xcode, Core Data, Combine, MVVM, REST API integration, XCTest, Firebase, TestFlight and App Store release. Add Objective-C if the role involves legacy code, and match the exact spelling used in the job description.' },
      { q: 'Do App Store links help an iOS developer CV?', a: 'Yes. Live app links are the strongest proof of shipped work, and the app name plus a plain-text link gives both the ATS and the recruiter something concrete to verify. Add your role and, where public, rating or download count.' },
    ],
  },
  'logistics-manager': {
    atsKeywords: ['Logistics Manager', 'Supply Chain Management', 'Warehouse Management', 'WMS', 'TMS', 'Fleet Management', 'Last Mile Delivery', 'Inventory Management', 'Route Optimisation', '3PL', 'Freight Forwarding', 'Vendor Management', 'Cost Optimisation', 'SLA Management', 'Import Export', 'Customs Clearance', 'SAP', 'KPI', 'Team Management', 'Demand Planning', 'Cold Chain', 'E-way Bill'],
    mustHaveSections: ['Professional Summary', 'Work Experience (with volume/cost metrics)', 'Skills (Systems & Operations)', 'Education', 'Certifications'],
    formattingRules: [
      SINGLE_COLUMN,
      HEADINGS,
      'Quantify scale: shipments per day, warehouse size, fleet size, team size, or cost reduced',
      'List systems by name: SAP, Oracle, WMS/TMS platforms, Excel, Power BI',
      'Write "Third-Party Logistics (3PL)" once and "3PL" thereafter',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Describing duties ("managed dispatch") without volumes, SLAs, or cost figures',
      'Mixing "supply chain" and "logistics" loosely — JDs screen for one or both specifically',
      'Leaving WMS/TMS or ERP tool names out of the Skills section',
      'Omitting domain: e-commerce, FMCG, cold chain, automotive, or B2B freight',
      'Undated or unordered roles that make tenure hard to compute',
    ],
    keywordTips: [
      'Use both "Logistics" and "Supply Chain" wording if you have covered both',
      'Name the operation: last-mile, first-mile, warehousing, line-haul, reverse logistics',
      'Include India-specific compliance terms where relevant: GST, e-way bill, customs, import/export',
      'Add KPIs you owned: on-time delivery, cost per shipment, order accuracy, inventory turns',
      'Mention vendor and 3PL management as its own skill, not only within a bullet',
    ],
    faqs: [
      { q: 'What ATS keywords should a logistics manager include on a CV in India?', a: 'Logistics, supply chain management, warehouse management, WMS, TMS, fleet operations, last-mile delivery, inventory management, 3PL, vendor management, cost optimisation and SLA management. Add compliance terms such as GST and e-way bill if relevant, and name the ERP or WMS platforms you have used.' },
      { q: 'How do I show operational scale on a logistics CV?', a: 'State volumes in each role: shipments or orders per day, number of warehouses or vehicles, team size, and the cost or delivery-time improvement you achieved. Concrete figures give ATS ranking and human reviewers something to compare across candidates.' },
    ],
  },
  'machine-learning-engineer': {
    atsKeywords: ['Machine Learning Engineer', 'Machine Learning', 'Deep Learning', 'Python', 'PyTorch', 'TensorFlow', 'Scikit-learn', 'MLOps', 'MLflow', 'Feature Engineering', 'Model Deployment', 'NLP', 'Computer Vision', 'XGBoost', 'SQL', 'Docker', 'Kubernetes', 'AWS SageMaker', 'Model Monitoring', 'A/B Testing', 'Airflow', 'Spark'],
    mustHaveSections: ['Skills (ML Frameworks & Tools)', 'Work Experience', 'Projects (with metrics)', 'Education', 'Publications / Certifications'],
    formattingRules: [
      SINGLE_COLUMN,
      HEADINGS,
      'Group skills: Languages, ML/DL frameworks, MLOps/Deployment, Data tools, Cloud',
      'Show model results in bullets with the metric named: AUC, F1, RMSE, latency, or business impact',
      'Distinguish training from deployment work — "deployed model behind an API" and "MLOps" are separately screened',
      'Add GitHub, Kaggle or publication links as plain text',
    ],
    commonAtsFailures: [
      'Listing only libraries and no production or deployment keywords (MLOps, Docker, model serving)',
      'Writing "AI/ML" only, without "Machine Learning" spelled out',
      'Omitting SQL — a screened requirement on many ML engineer JDs',
      'Bullets that describe models with no metric or outcome',
      'Academic-style CVs that bury industry work under coursework',
    ],
    keywordTips: [
      'Spell out "Machine Learning" and "Deep Learning" in full as well as abbreviations like "ML" and "DL"',
      'Name the framework for each project: PyTorch, TensorFlow, Scikit-learn, XGBoost',
      'Include MLOps terms you have actually used: MLflow, Airflow, Kubeflow, feature store, model monitoring',
      'Specify the domain: NLP, computer vision, recommender systems, forecasting',
      'Add cloud ML platforms by name: SageMaker, Vertex AI, Azure ML',
    ],
    faqs: [
      { q: 'What ATS keywords should a machine learning engineer use in India?', a: 'Machine learning, deep learning, Python, PyTorch or TensorFlow, Scikit-learn, feature engineering, model deployment, MLOps, MLflow, SQL, Docker, and a cloud ML platform such as SageMaker. Add your domain (NLP, computer vision, recommender systems) as the job description phrases it.' },
      { q: 'How is a machine learning engineer CV different from a data scientist CV for ATS?', a: 'ML engineer JDs screen more heavily for production terms — model deployment, MLOps, APIs, Docker, Kubernetes, monitoring — while data scientist JDs weight statistics, experimentation and analysis more. Lead with whichever set matches the specific role, and include the other where you have real experience.' },
    ],
  },
  'network-engineer': {
    atsKeywords: ['Network Engineer', 'CCNA', 'CCNP', 'Cisco IOS', 'Routing and Switching', 'BGP', 'OSPF', 'EIGRP', 'MPLS', 'VLAN', 'VPN', 'Firewall', 'Palo Alto', 'Fortinet', 'SD-WAN', 'Network Monitoring', 'Wireshark', 'LAN/WAN', 'ITIL', 'Network Security', 'Load Balancer', 'TCP/IP'],
    mustHaveSections: ['Certifications (CCNA/CCNP etc.)', 'Technical Skills', 'Work Experience', 'Education', 'Tools & Platforms'],
    formattingRules: [
      SINGLE_COLUMN,
      HEADINGS,
      'Put certifications near the top with the exact name and level: "Cisco Certified Network Professional (CCNP)"',
      'List routing protocols individually: BGP, OSPF, EIGRP',
      'Name vendors and platforms: Cisco, Juniper, Palo Alto, Fortinet, Aruba',
      'Quantify environment size: sites, devices, users, or uptime managed',
    ],
    commonAtsFailures: [
      'Listing certifications only as logos or badges rather than text',
      'Writing "networking" generically instead of naming protocols and vendors',
      'Combining protocols in one string like "BGP/OSPF/EIGRP" that may not match each individually',
      'Leaving out ITIL or incident-management terms for NOC and support-focused roles',
      'Omitting monitoring tools (SolarWinds, Nagios, PRTG) that JDs frequently screen for',
    ],
    keywordTips: [
      'Write certifications in both forms: "CCNP" and "Cisco Certified Network Professional"',
      'Name routing and switching technologies separately: BGP, OSPF, VLAN, STP',
      'Add the firewall and security platforms you administer',
      'Include monitoring and troubleshooting tools like Wireshark and SolarWinds',
      'Mention WAN technologies you have run: MPLS, SD-WAN, IPsec VPN',
    ],
    faqs: [
      { q: 'Which certifications should a network engineer list for ATS?', a: 'List each certification with its full name and acronym, such as CCNA, CCNP Enterprise, Palo Alto PCNSA, or Fortinet NSE, plus the year earned. Text form matters — ATS cannot read certification badges — and JDs often filter on a specific certificate level.' },
      { q: 'What keywords does a network engineer CV need for NOC and infrastructure roles?', a: 'Routing and switching, BGP, OSPF, VLAN, MPLS, VPN, firewalls, SD-WAN, network monitoring, troubleshooting, ITIL and incident management, along with the vendor platforms you manage. Show environment scale (sites, devices, uptime) in your bullets.' },
    ],
  },
  'pharmacist': {
    atsKeywords: ['Pharmacist', 'B.Pharm', 'M.Pharm', 'Pharm.D', 'Drug Dispensing', 'Prescription Verification', 'Patient Counselling', 'Pharmacovigilance', 'Drug Interaction', 'Inventory Management', 'Hospital Pharmacy', 'Retail Pharmacy', 'Clinical Pharmacy', 'Regulatory Compliance', 'Schedule H', 'GMP', 'State Pharmacy Council Registration', 'Documentation', 'Medication Safety', 'Cold Chain'],
    mustHaveSections: ['Registration & Licences (State Pharmacy Council)', 'Professional Summary', 'Work Experience', 'Education (B.Pharm / M.Pharm / Pharm.D)', 'Skills'],
    formattingRules: [
      SINGLE_COLUMN,
      HEADINGS,
      'State your pharmacy council registration number and state as plain text in a Registration section',
      'Write degrees in full and abbreviated: "Bachelor of Pharmacy (B.Pharm)"',
      'Say whether your experience is hospital, retail, clinical, or pharma industry — these are screened separately',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Omitting registration details that regulated roles require',
      'Writing "medicine" work generically without naming dispensing, counselling, or pharmacovigilance',
      'Not stating the setting (hospital vs retail vs industry), causing mismatches on filtered searches',
      'Skipping software used: hospital information systems, pharmacy management or ERP tools',
      'Dense paragraphs of duties instead of bullets with searchable terms',
    ],
    keywordTips: [
      'Include both "Pharmacist" and the degree, e.g. "B.Pharm", so both searches match',
      'Use regulatory terms you know: Schedule H, GMP, GDP, Drugs and Cosmetics Act',
      'For clinical roles, add pharmacovigilance, adverse drug reaction reporting and drug interaction checks',
      'Mention inventory tasks: expiry tracking, stock audits, cold chain handling',
      'Name pharmacy or HIS software you have used',
    ],
    faqs: [
      { q: 'Should a pharmacist include registration details on a CV?', a: 'Yes. State your State Pharmacy Council registration number and state as plain text. Most hospital and retail pharmacy roles require it, and recruiters and ATS filters look for it before shortlisting.' },
      { q: 'What ATS keywords help a hospital pharmacist CV?', a: 'Prescription verification, drug dispensing, patient counselling, drug interaction checking, pharmacovigilance, medication safety, inventory management, clinical documentation and regulatory compliance. Add the hospital information system you used and your registration details.' },
    ],
  },
  'react-developer': {
    atsKeywords: ['React Developer', 'React', 'React.js', 'JavaScript', 'TypeScript', 'Next.js', 'Redux', 'Redux Toolkit', 'React Query', 'Hooks', 'HTML5', 'CSS3', 'Tailwind CSS', 'REST API', 'GraphQL', 'Jest', 'React Testing Library', 'Webpack', 'Vite', 'Responsive Design', 'Git', 'Performance Optimisation'],
    mustHaveSections: ['Skills (Frontend Stack)', 'Work Experience', 'Projects (with live links)', 'Education', 'Certifications'],
    formattingRules: [
      SINGLE_COLUMN,
      HEADINGS,
      'List both "React" and "React.js" if the JD uses either — literal matching treats them as different strings',
      'Include GitHub and deployed project URLs as visible plain text',
      'Show measurable frontend outcomes: load time, bundle size, Lighthouse score, or conversion impact',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Writing "frontend developer" without React named in the Skills section',
      'Skipping TypeScript when the JD requires it, or listing it only in one bullet',
      'Skill-level bars or icon grids for technologies',
      'No state-management terms (Redux, Context, Zustand, React Query) despite using them',
      'Missing testing keywords such as Jest and React Testing Library',
    ],
    keywordTips: [
      'Mirror the JD\'s framework spelling: "React", "React.js" or "ReactJS"',
      'Add Next.js explicitly if you have built SSR/SSG apps',
      'Name state and data-fetching libraries: Redux Toolkit, Zustand, React Query, SWR',
      'Include styling tools: Tailwind CSS, styled-components, Sass, CSS Modules',
      'Add performance terms with results: "code splitting", "lazy loading", "Lighthouse score"',
    ],
    faqs: [
      { q: 'What keywords should a React developer include for ATS?', a: 'React, JavaScript, TypeScript, Next.js, Redux or another state manager, React Query, HTML5, CSS3 or Tailwind, REST API and GraphQL integration, Jest and React Testing Library, and Git. Use the exact spelling from the job description and back each with a project or experience bullet.' },
      { q: 'How is a React developer CV different from a general frontend CV for ATS?', a: 'React-specific JDs screen for the ecosystem: hooks, state management, Next.js, testing libraries, and TypeScript. A general frontend CV listing only HTML, CSS and JavaScript will rank lower, so name React and its surrounding tools explicitly.' },
    ],
  },
  'sales-executive': {
    atsKeywords: ['Sales Executive', 'Lead Generation', 'Cold Calling', 'Target Achievement', 'CRM', 'Salesforce', 'Zoho CRM', 'Client Acquisition', 'Negotiation', 'Territory Management', 'Upselling', 'Cross-selling', 'B2B Sales', 'B2C Sales', 'Field Sales', 'Inside Sales', 'Sales Reporting', 'Customer Relationship', 'Closing', 'Product Demo', 'Channel Sales'],
    mustHaveSections: ['Professional Summary', 'Work Experience (with targets and achievement %)', 'Skills', 'Education', 'Achievements & Awards'],
    formattingRules: [
      SINGLE_COLUMN,
      HEADINGS,
      'State targets and achievement in every role: "Achieved 112% of quarterly target" style figures you can verify',
      'Say whether it was field, inside, B2B or B2C sales — these are filtered separately',
      'List CRM tools by name in a Skills section',
      'Include the territory or region covered and account count where relevant',
    ],
    commonAtsFailures: [
      'Bullets that list tasks ("visited clients") with no target, revenue, or conversion figure',
      'Using "sales" generically without B2B/B2C or field/inside distinctions',
      'Leaving out CRM tools such as Salesforce or Zoho',
      'Omitting awards and recognition like top performer or club membership',
      'Career gaps or short stints left unexplained in a chronological layout',
    ],
    keywordTips: [
      'Use the JD\'s exact wording: "lead generation", "client acquisition", or "business development"',
      'Add "target achievement" with the actual percentage you hit',
      'Name your sales channel: field, inside, retail, channel partners, e-commerce',
      'Include product or industry keywords (FMCG, SaaS, insurance, real estate)',
      'Mention reporting: pipeline reports, MIS, forecasting and CRM hygiene',
    ],
    faqs: [
      { q: 'What should a sales executive put on a CV to pass ATS?', a: 'Lead generation, client acquisition, cold calling, negotiation, target achievement with a percentage, territory management, upselling, CRM tools, and the kind of sales you do (B2B, B2C, field, inside). Use figures you can defend and the exact terms in the job description.' },
      { q: 'How do I write a sales executive CV as a fresher?', a: 'Lead with internships, campus sales roles, or part-time customer-facing work, and quantify outcomes such as leads generated, conversion rate, or units sold. Add communication and CRM skills, and connect them to the specific sales motion in the target job description.' },
    ],
  },
  'sap-consultant': {
    atsKeywords: ['SAP Consultant', 'SAP S/4HANA', 'SAP ECC', 'SAP FICO', 'SAP MM', 'SAP SD', 'SAP ABAP', 'SAP Fiori', 'SAP Activate', 'ASAP Methodology', 'Implementation', 'Rollout', 'Support', 'Configuration', 'Integration Testing', 'UAT', 'Data Migration', 'Business Blueprint', 'Gap Analysis', 'Change Management', 'End-user Training', 'Functional Specification'],
    mustHaveSections: ['Professional Summary (module + years)', 'Work Experience (with project lifecycle detail)', 'SAP Modules & Skills', 'Certifications (SAP Certified)', 'Education'],
    formattingRules: [
      SINGLE_COLUMN,
      HEADINGS,
      'State your module(s) and version up front: "SAP FICO consultant, S/4HANA, 6 years"',
      'For each project list: client industry, scope (implementation, rollout, support), your phase involvement',
      'Write modules in full and abbreviated once: "SAP Financial Accounting and Controlling (FICO)"',
      'Include certifications by exact name and the year',
    ],
    commonAtsFailures: [
      'Listing "SAP" without the module (FICO, MM, SD, ABAP) — the module is what recruiters filter on',
      'Not specifying ECC versus S/4HANA experience',
      'Omitting project lifecycle terms such as blueprint, realisation, UAT and go-live',
      'Combining multiple modules in one line with no context of depth',
      'Leaving certifications out or writing them without the certifying body',
    ],
    keywordTips: [
      'Use the exact module names from the JD: "SAP FICO", "SAP MM", "SAP SD"',
      'Include implementation phases: business blueprint, configuration, UAT, cutover, go-live and hypercare',
      'Mention the methodology: SAP Activate or ASAP',
      'Separate implementation, rollout and support experience clearly',
      'Add integration points such as interfaces with other modules or third-party systems',
    ],
    faqs: [
      { q: 'How should an SAP consultant list modules on a CV for ATS?', a: 'Name each module explicitly — SAP FICO, MM, SD, ABAP, or Fiori — with the version (ECC or S/4HANA) and years of experience per module. Recruiters and ATS filter on module name, so avoid writing only "SAP".' },
      { q: 'What project details do SAP recruiters expect in a consultant CV?', a: 'Client industry, project type (implementation, rollout, upgrade or support), your role, the phases you took part in (blueprint, configuration, UAT, go-live) and the modules covered. State team size and location scope where you can.' },
    ],
  },
  'scrum-master': {
    atsKeywords: ['Scrum Master', 'Agile', 'Scrum', 'SAFe', 'Kanban', 'Sprint Planning', 'Daily Standup', 'Retrospective', 'Backlog Refinement', 'Jira', 'Confluence', 'Azure DevOps', 'Agile Coaching', 'Velocity', 'Impediment Removal', 'Stakeholder Management', 'CSM', 'PSM', 'Release Planning', 'Team Metrics', 'Servant Leadership'],
    mustHaveSections: ['Professional Summary', 'Certifications (CSM / PSM / SAFe)', 'Work Experience (with team and delivery metrics)', 'Skills (Tools & Frameworks)', 'Education'],
    formattingRules: [
      SINGLE_COLUMN,
      HEADINGS,
      'Put Scrum certifications in a visible section: "Certified ScrumMaster (CSM)", "Professional Scrum Master (PSM I)"',
      'State team size, number of teams and delivery cadence for each role',
      'List tools individually: Jira, Confluence, Azure DevOps, Rally',
      FILE_FORMAT,
    ],
    commonAtsFailures: [
      'Writing "Agile" only without Scrum, Kanban or SAFe named',
      'Leaving out certification acronyms in text form',
      'Describing ceremonies performed rather than outcomes such as improved predictability',
      'Omitting the number of teams coached, a common screening criterion',
      'No tools listed, even though Jira is among the most searched terms',
    ],
    keywordTips: [
      'Include both "Scrum Master" and "Certified ScrumMaster (CSM)" or "PSM"',
      'Name scaled frameworks if used: SAFe, LeSS, Scrum of Scrums',
      'Add metrics: velocity, sprint predictability, cycle time, lead time',
      'Mention coaching scope: teams, product owners, stakeholders',
      'Include both Jira and Confluence if you have administered them',
    ],
    faqs: [
      { q: 'Which certifications should a Scrum Master list for ATS?', a: 'List the certification name and acronym in plain text — Certified ScrumMaster (CSM), Professional Scrum Master (PSM I/II), SAFe Scrum Master (SSM) — along with the issuer and year. Many Scrum Master JDs filter on these strings directly.' },
      { q: 'How do I show impact on a Scrum Master CV?', a: 'Describe outcomes rather than ceremonies: improved sprint predictability, reduced cycle time, cleaner backlog, fewer carry-over stories. State the number of teams and team size, and name the metrics you tracked in Jira or your reporting tool.' },
    ],
  },
};
