export interface CoverLetterData {
  dos: string[];
  donts: string[];
  keyPoints: string[];
  sampleOpening: string;
  sampleBody: string;
  sampleClosing: string;
  faqs: Array<{ q: string; a: string }>;
}

export const coverLetterMap: Record<string, CoverLetterData> = {
  'software-engineer': {
    dos: [
      'Mention the specific tech stack from the JD — React, Node.js, AWS — in your opening line',
      'Quantify at least one technical achievement: API latency reduced, users served, uptime improved',
      'Reference the company\'s product and why the engineering challenge excites you',
      'Keep it to 3 short paragraphs — engineering hiring managers read fast',
      'End with a specific ask: "I would welcome a technical discussion about the platform"',
    ],
    donts: [
      'Don\'t restate your CV — the cover letter should add context, not duplicate content',
      'Avoid vague openers like "I am writing to express my interest" — start with impact',
      'Don\'t list every technology you know — focus on 3–5 most relevant to this role',
      'Never mention salary expectations unless the JD specifically asks for it',
      'Don\'t use a template that mentions a different company or role',
    ],
    keyPoints: [
      'Highlight one major project with measurable technical outcome',
      'Show familiarity with the company\'s tech culture (open-source contributions, engineering blog)',
      'Mention scale: data volume, users, requests per second — whatever is relevant',
      'Signal culture fit: startup speed, FAANG rigour, or enterprise stability',
    ],
    sampleOpening: 'In my three years as a backend engineer at [Company], I reduced our core API response time by 60% through GraphQL migration and Redis caching — the kind of performance engineering challenge that drew me to [Target Company]\'s infrastructure role.',
    sampleBody: 'At [Previous Company], I led the migration of a monolithic Node.js service to a Kubernetes-based microservices architecture handling 2M daily active users. This involved designing event-driven systems using Kafka, implementing circuit breakers for fault tolerance, and reducing deployment time from 45 minutes to 8 minutes via automated CI/CD pipelines. I hold an AWS Solutions Architect certification and have contributed to open-source projects in the Node.js ecosystem.',
    sampleClosing: 'I am excited by [Company]\'s engineering challenges at scale and believe my background in distributed systems aligns well with the senior backend role. I would welcome the opportunity to discuss how I can contribute to your platform\'s reliability and performance goals.',
    faqs: [
      { q: 'Do software engineers in India need a cover letter?', a: 'For most product companies and FAANG applications, a cover letter is optional but adds value when you can demonstrate genuine product knowledge or a specific technical achievement. For service companies (TCS, Infosys, Wipro), cover letters are rarely reviewed. Focus your effort on roles where it will be read.' },
      { q: 'How long should a software engineer\'s cover letter be?', a: '3 short paragraphs, under 300 words. Hiring managers at tech companies read quickly. A concise, impactful cover letter beats a detailed one that no one finishes.' },
    ],
  },
  'data-analyst': {
    dos: [
      'Lead with a specific data insight or project outcome — not a generic statement',
      'Mention the data tools from the JD: SQL, Python, Tableau, Power BI, etc.',
      'Show domain expertise: "In BFSI analytics" or "In e-commerce funnel analysis"',
      'Quantify the impact of your analysis: decisions made, costs saved, revenue influenced',
      'Express curiosity about the company\'s data problems specifically',
    ],
    donts: [
      'Don\'t claim to be "passionate about data" without showing it with a specific example',
      'Avoid listing every tool you\'ve used — focus on what\'s in the JD',
      'Don\'t write more than 300 words — data analysts know the value of brevity',
      'Never use vague language like "strong analytical skills" without proof',
      'Don\'t forget to include your portfolio or Kaggle link',
    ],
    keyPoints: [
      'One specific analysis you did and what decision it drove',
      'The data scale you have worked with (rows, transactions, users)',
      'The business context: which team consumed your analysis and how',
      'Your SQL depth (complex queries, joins, window functions)',
    ],
    sampleOpening: 'A 22% reduction in cart abandonment — that was the outcome of a funnel analysis I built in SQL and Tableau for [Previous Company]\'s e-commerce team last quarter. This kind of business-impacting analytics work is what draws me to the Data Analyst role at [Target Company].',
    sampleBody: 'At [Company], I analyse 5M+ weekly transactions using SQL and Python to surface trends for the revenue leadership team. My dashboards in Power BI are used daily by 3 business units for inventory, pricing, and campaign decisions. I recently completed a cohort analysis that identified a high-value customer segment contributing 38% of revenue but receiving no targeted retention effort — a gap that, once addressed, reduced 90-day churn by 14% for that segment.',
    sampleClosing: 'I am drawn to [Company]\'s data culture and the opportunity to work with [specific domain] data at scale. I would welcome a conversation about how my SQL and Python skills can contribute to your analytics team.',
    faqs: [
      { q: 'Should a data analyst include a portfolio link in their cover letter?', a: 'Absolutely. A link to your Kaggle profile, GitHub, or a public Tableau/Power BI dashboard is the single most impactful addition to a data analyst cover letter. It lets the hiring manager verify your skills immediately.' },
      { q: 'What is the most important thing to include in a data analyst cover letter?', a: 'A specific, quantified analysis outcome. "Identified a segment that reduced churn by 14%" is far stronger than "experienced in data analysis." Show the business impact, not just the technical activity.' },
    ],
  },
  'product-manager': {
    dos: [
      'Open with a metric you own: retention, revenue, NPS, growth — and the number',
      'Demonstrate product thinking specific to the company\'s product challenges',
      'Show cross-functional leadership: engineering, design, data collaboration',
      'Reference a specific product decision with data-backed rationale',
      'Express why this company\'s product problem excites you specifically',
    ],
    donts: [
      'Don\'t summarize your CV — add context and product conviction instead',
      'Avoid buzzwords without substance: "data-driven", "customer-centric" need proof',
      'Don\'t write a features list — show product judgement and prioritization',
      'Never claim credit without context — "I shipped X" vs "I prioritized X to drive Y"',
      'Don\'t forget a strong CTA — ask for a product discussion, not just an interview',
    ],
    keyPoints: [
      'Your biggest product metric win and the decision that drove it',
      'How you work with engineering and design — give a specific example',
      'Your approach to prioritization when resources are constrained',
      'Why you want to work on this specific product problem',
    ],
    sampleOpening: 'When I redesigned [Company]\'s onboarding flow based on session replay data, Day-30 retention increased 18%. This outcome-first, data-grounded approach to product decisions is exactly what I want to bring to [Target Company]\'s growth team.',
    sampleBody: 'As PM for [Company]\'s fintech product, I own the end-to-end lifecycle of features serving 400,000 monthly active users. I recently led a 3-month initiative to reduce payment friction — running 4 A/B tests, aligning 8 engineers and 2 designers, and coordinating compliance review — which reduced payment failure rate from 12% to 4.3% and increased GMV by ₹2.2Cr monthly. I make prioritization decisions using a scoring model combining user research, business impact, and engineering effort, presented to leadership as a monthly roadmap review.',
    sampleClosing: 'I am excited by [Company]\'s product challenges in [specific area] and believe my background in [relevant domain] positions me well to contribute quickly. I would welcome a conversation about how I approach product strategy and what I could work on in the first 90 days.',
    faqs: [
      { q: 'Should a product manager cover letter focus on features or metrics?', a: 'Metrics always. Features tell the reader what you shipped; metrics tell them why it mattered. Every bullet in your cover letter should have a number: retention improvement, revenue influenced, latency reduced, engagement increased. A PM cover letter without metrics signals weak product thinking.' },
      { q: 'How long should a product manager cover letter be?', a: '3 paragraphs, 250–350 words. PMs are expected to be concise and high-signal communicators. A bloated cover letter contradicts this expectation before you even get to the interview.' },
    ],
  },
  'marketing-manager': {
    dos: [
      'Lead with a campaign result: ROAS, organic traffic growth, CAC reduction, revenue driven',
      'Reference the specific channels in the JD: Google Ads, Meta, SEO, email, etc.',
      'Show marketing attribution knowledge — how you connect spend to revenue',
      'Mention budget ownership and scale: "managed ₹1.2Cr quarterly paid budget"',
      'Demonstrate brand or customer understanding specific to the target company',
    ],
    donts: [
      'Don\'t claim "passion for marketing" — show results instead',
      'Avoid listing every platform you have used without performance context',
      'Don\'t use marketing jargon without substance: "synergy", "360 campaign", "viral"',
      'Never skip the performance numbers — a marketing CV without metrics is immediately weak',
      'Don\'t address the letter generically — reference the company\'s actual marketing approach',
    ],
    keyPoints: [
      'Your best campaign result with full context (channel, budget, outcome)',
      'The marketing funnel stage you own: awareness, consideration, conversion, retention',
      'Tools and platforms you are certified or expert in',
      'Your approach to data and attribution',
    ],
    sampleOpening: 'When I took over [Company]\'s performance marketing in 2024, our cost per acquisition was ₹1,840. Twelve months later it was ₹720 — through a combination of audience segmentation, creative iteration, and bid strategy restructuring. This focus on efficiency and growth is what I am looking to bring to [Target Company].',
    sampleBody: 'As Marketing Manager at [Company], I manage a ₹90L annual budget across Google Ads, Meta, and SEO channels. I have grown organic traffic from 18,000 to 65,000 monthly sessions through a content cluster strategy, while simultaneously improving paid ROAS from 2.1x to 4.8x. I work closely with the product team on lifecycle marketing — our latest email automation flow for trial users increased conversion to paid by 22%. I am certified in Google Ads and have completed HubSpot\'s Advanced Marketing certification.',
    sampleClosing: 'I am drawn to [Company]\'s [specific product or category] and the opportunity to scale marketing from [current stage] to [next stage]. I would welcome a conversation about how I approach growth and what a 90-day marketing plan for [Company] would look like.',
    faqs: [
      { q: 'What metric should a marketing manager highlight in a cover letter?', a: 'Lead with your best metric in the most relevant channel for the role. If the JD emphasizes performance marketing, highlight ROAS or CAC. If it is SEO, lead with organic traffic growth. If brand, use NPS or awareness lift. Match the metric to what the company cares about.' },
      { q: 'Should a marketing manager mention their agency experience in a cover letter?', a: 'Yes, if it is relevant. Agency experience signals breadth (multiple industries, clients, budgets). Lead with the most relevant client outcome. If applying to an in-house role, clarify that you are excited to own a single brand\'s growth deeply — agencies are sometimes seen as less focused.' },
    ],
  },
  'hr-manager': {
    dos: [
      'Lead with a hiring or retention metric: time-to-hire, offer acceptance rate, attrition reduction',
      'Mention the HR tools in the JD: Darwinbox, SuccessFactors, Workday, etc.',
      'Show business partnership: how you worked with business leaders to solve people problems',
      'Reference your compliance depth: POSH, PF, ESI, labour law where relevant',
      'Express genuine interest in the company\'s culture or people challenges',
    ],
    donts: [
      'Don\'t just list HR activities — show business impact of people programs',
      'Avoid vague phrases like "people person" or "passionate about HR"',
      'Don\'t ignore the commercial angle — HR managers who show business impact stand out',
      'Never misrepresent your scope — "managed 600-person org" vs "supported" it',
      'Don\'t overlook L&D contributions if the role requires it',
    ],
    keyPoints: [
      'Headcount hired or supported — scale matters for HR roles',
      'A specific program you designed and its business outcome',
      'The HR tech systems you have implemented or managed',
      'How you partnered with business leaders to resolve a people challenge',
    ],
    sampleOpening: 'In FY24, I reduced time-to-hire from 45 days to 22 days for our 300-person technology division — not by cutting corners but by redesigning the assessment process and building a proactive talent pipeline. This outcome-driven approach to people operations is what I want to bring to [Target Company].',
    sampleBody: 'As HRBP at [Company], I partner with 4 business unit heads across Engineering, Product, Marketing, and Operations covering 620 employees. I designed and implemented a structured onboarding programme that reduced 90-day attrition from 18% to 9%. I manage our Darwinbox implementation, run bi-annual engagement surveys, lead POSH compliance, and handle all performance management cycles. I recently led a compensation benchmarking exercise using Radford and Mercer data that informed a salary revision for 180 employees.',
    sampleClosing: 'I am excited by [Company]\'s growth trajectory and the opportunity to build a people function that can scale with it. I would welcome the opportunity to discuss how I approach HRBP work and what the first 60 days might look like.',
    faqs: [
      { q: 'What is the most important thing to include in an HR manager cover letter?', a: 'A business impact metric that shows HR work driving a measurable outcome: attrition reduced, time-to-hire shortened, employee engagement increased, compliance issue resolved. Avoid listing HR activities without showing their effect on the business.' },
      { q: 'Should an HR manager mention POSH and labour law compliance in a cover letter?', a: 'Yes, especially for mid-to-senior HR roles in India. Compliance is a non-negotiable competency and demonstrating it signals professionalism and risk awareness. Be specific: "ensured POSH compliance across 3 office locations" is stronger than "handled compliance".' },
    ],
  },
  'finance-analyst': {
    dos: [
      'Lead with a financial scale: budget managed, portfolio value, cost saved',
      'Reference specific financial tools in the JD: SAP, Oracle, Excel, Power BI',
      'Show analytical depth: DCF, LBO, three-statement modelling, variance analysis',
      'Mention your qualification prominently: CA, CFA, CMA, MBA Finance',
      'Express interest in the company\'s specific financial challenge or sector',
    ],
    donts: [
      'Don\'t use vague finance language without substance: "financial analysis", "strategic thinking"',
      'Avoid listing financial tools without demonstrating what you produced with them',
      'Don\'t omit the scale of budgets or transactions you have worked with',
      'Never be imprecise about your qualification: CA vs CA Inter vs pursuing CA',
      'Don\'t write more than 300 words — finance hiring managers value concision',
    ],
    keyPoints: [
      'The size of the budget or portfolio you have managed',
      'A specific financial model or analysis and the decision it informed',
      'Your ERP proficiency: SAP FI/CO, Oracle Financials, Tally',
      'Industry context: BFSI, manufacturing, IT, consulting, real estate',
    ],
    sampleOpening: 'Managing a ₹140Cr annual budget for [Company]\'s infrastructure division, I developed a scenario-modelling framework in Excel and Power BI that reduced our budget revision cycle from 3 weeks to 4 days. The ability to bring analytical rigour to complex financial decisions is what I want to contribute to [Target Company].',
    sampleBody: 'As Finance Analyst at [Company], I support FP&A across 3 business units, preparing weekly MIS reports for the CFO and monthly board packs with variance analysis, rolling forecasts, and KPI dashboards. I have built a three-statement financial model for a ₹300Cr greenfield investment that was used to secure board approval. I am a Chartered Accountant (ICAI, November 2022, AIR 87) and proficient in SAP FI/CO and advanced Excel including Power Query and macro automation.',
    sampleClosing: 'I am drawn to [Company]\'s [sector] operations and the analytical challenges of your FP&A function at this growth stage. I would welcome the opportunity to discuss how my modelling skills and qualification can contribute to your finance team.',
    faqs: [
      { q: 'Should a finance analyst mention their CA rank in their cover letter?', a: 'Yes, if your All India Rank is in the top 100 — place it prominently. For ranks between 100–500, mention it once. Beyond 500, just state the qualification and year. For international roles, note your ICAI CA qualification as the Indian equivalent of CPA or ACA.' },
      { q: 'How should a finance analyst describe financial modelling in a cover letter?', a: 'Be specific about the model type and the decision it supported. "Built a three-statement model for a ₹300Cr investment, used to secure board approval" is far stronger than "experienced in financial modelling." Include the tool (Excel, Python, FactSet) and the business context.' },
    ],
  },
  'business-analyst': {
    dos: [
      'Lead with a process improvement or requirements delivery outcome',
      'Mention the domain: BFSI, telecom, retail, healthcare — be specific',
      'Reference BA tools in the JD: JIRA, Confluence, Visio, SQL',
      'Show stakeholder management: who you worked with and at what level',
      'Reference your Agile/Scrum experience if the role requires it',
    ],
    donts: [
      'Don\'t use vague BA language without outcomes: "gathered requirements", "worked with stakeholders"',
      'Avoid listing every tool without context of what you used it for',
      'Don\'t conflate IT BA and business-side BA — clarify your scope',
      'Never omit the business impact of the requirements or process work you did',
      'Don\'t write more than 300 words — concise communication is a core BA skill',
    ],
    keyPoints: [
      'A specific requirement or process you documented and its outcome',
      'Stakeholder level: C-suite, directors, end users, technical teams',
      'Domain expertise and industry knowledge',
      'Agile/Scrum sprint participation and artefacts produced',
    ],
    sampleOpening: 'When I documented and redesigned the loan origination workflow for [Company]\'s retail banking division, we reduced processing time by 35% and eliminated 3 manual handoffs. This ability to bridge business needs and technical delivery is what I want to bring to [Target Company].',
    sampleBody: 'As Business Analyst at [Company], I work across the intersection of IT and Operations, gathering requirements from 12 business stakeholders across 3 departments, writing BRDs and user stories, and managing requirements through JIRA sprints. I recently led the requirements definition for a ₹8Cr CRM implementation, facilitating 14 workshops with business users and translating them into 200+ user stories. I have strong SQL skills for data validation and use Visio and Lucidchart for process mapping.',
    sampleClosing: 'I am excited by [Company]\'s [specific initiative or domain] and the opportunity to contribute structured analysis and clear requirements documentation. I would welcome a discussion about your current project pipeline and where I could add immediate value.',
    faqs: [
      { q: 'What should a business analyst cover letter focus on?', a: 'Requirements delivery outcomes and stakeholder management. Show one example where your analysis led to a measurable improvement: process time reduced, system implemented, cost saved. The best BA cover letters demonstrate the ability to translate business problems into clear technical requirements.' },
      { q: 'Should a BA mention Agile in their cover letter?', a: 'Yes, if the role or JD mentions Agile or Scrum. Mention specific sprint ceremonies you participate in (planning, retrospectives, backlog refinement) and the artefacts you produce (user stories, acceptance criteria, sprint goals). Agile BA experience is significantly more valued than waterfall-only in most modern IT environments.' },
    ],
  },
  'frontend-developer': {
    dos: [
      'Lead with a performance or user impact metric: Lighthouse score, page load time, user engagement',
      'Reference the specific frontend stack in the JD: React, Vue, Angular, Next.js',
      'Include a portfolio link — it is your primary credential as a frontend developer',
      'Show your eye for design: UX awareness, accessibility, responsive design',
      'Mention TypeScript if the JD requires it — it is table stakes for most 2026 frontend roles',
    ],
    donts: [
      'Don\'t apply without a portfolio — a frontend developer without live work to show is severely disadvantaged',
      'Avoid listing jQuery or Bootstrap as primary skills in 2026',
      'Don\'t skip performance work — Lighthouse score improvements show senior-level thinking',
      'Never list technologies you cannot actually demonstrate in a code review',
      'Don\'t write a long cover letter — developers who can\'t be concise signal poor communication skills',
    ],
    keyPoints: [
      'A specific project with a live URL and measurable user or performance impact',
      'Your approach to responsive design and cross-browser compatibility',
      'Testing strategy: Jest, Cypress, React Testing Library',
      'Design-to-code workflow: how you work with Figma and designers',
    ],
    sampleOpening: 'I improved our application\'s Lighthouse performance score from 61 to 94 by implementing code splitting, lazy loading, and image optimization — resulting in a 2.8-second reduction in Time to Interactive. This obsession with performance is what I bring to frontend engineering and what drew me to [Target Company].',
    sampleBody: 'At [Company], I build and maintain a React/TypeScript application serving 80,000 monthly active users. I have implemented a component library in Storybook that reduced design-to-development handoff time by 40%, introduced automated accessibility testing with axe-core, and set up a Cypress E2E test suite covering our 12 critical user flows. My portfolio at [portfolio-url] includes 4 deployed projects with source code on GitHub, including a real-time collaboration tool built with Next.js and WebSockets.',
    sampleClosing: 'I am excited by [Company]\'s frontend challenges and would welcome a technical discussion about your architecture. My portfolio at [url] shows the depth of my React and TypeScript work.',
    faqs: [
      { q: 'How important is a portfolio for a frontend developer cover letter?', a: 'Critical. A portfolio link in your cover letter converts hiring managers into reviewers. Include a URL to deployed projects, not just your GitHub. Even 2–3 strong, well-documented projects with live demos significantly increase your shortlisting probability compared to candidates without public work.' },
      { q: 'Should a frontend developer mention TypeScript in their cover letter?', a: 'Yes, in 2026 TypeScript is expected for most mid-to-senior frontend roles. If the JD mentions it, highlight your TypeScript experience explicitly. If you use typed interfaces, generics, or strict mode, mention it — it signals engineering maturity beyond basic JavaScript skills.' },
    ],
  },
  'backend-developer': {
    dos: [
      'Lead with a scale or performance metric: QPS, latency, data volume, uptime',
      'Reference the specific backend stack: Node.js, Python, Java, Go — match the JD',
      'Show system design thinking: microservices, event-driven, caching, queues',
      'Mention cloud depth: specific AWS/GCP/Azure services, not just "cloud"',
      'Demonstrate database expertise: PostgreSQL, MongoDB, Redis, Kafka',
    ],
    donts: [
      'Don\'t write "experienced in REST APIs" without scale or architecture context',
      'Avoid claiming "experience with AWS" without naming specific services used',
      'Don\'t skip performance work — latency improvements and cost optimizations signal seniority',
      'Never list technologies you cannot discuss deeply in a technical interview',
      'Don\'t ignore monitoring/observability — it signals production engineering maturity',
    ],
    keyPoints: [
      'System you designed or significantly improved — scale and outcome',
      'Specific cloud services used in production',
      'Database design choices and performance optimizations',
      'CI/CD and deployment infrastructure you have worked with',
    ],
    sampleOpening: 'I designed and deployed a Kafka-based event streaming system at [Company] that handles 50,000 events per second at 99.97% uptime — down from 4 outages per month on our previous synchronous architecture. Building reliable systems at scale is what drew me to [Target Company]\'s platform engineering role.',
    sampleBody: 'As a backend engineer at [Company], I work primarily in Python (FastAPI) and PostgreSQL, serving a B2B SaaS platform with 400 enterprise clients. I recently led the decomposition of a 90,000-line monolith into 7 microservices, establishing API contracts via OpenAPI, implementing distributed tracing with Jaeger, and reducing mean deployment time from 35 minutes to 6 minutes. I manage infrastructure as code with Terraform on AWS (ECS, RDS, ElastiCache, SQS) and have reduced our monthly cloud bill by 28% through reserved capacity planning.',
    sampleClosing: 'I am drawn to [Company]\'s engineering challenges at [relevant scale or domain] and would welcome a technical conversation about your architecture and where I could contribute most in the first 90 days.',
    faqs: [
      { q: 'How should a backend developer describe system design experience in a cover letter?', a: 'Be specific about the architectural decision, why you made it, and the outcome. "Designed event-driven architecture using Kafka, reducing latency from 800ms to 120ms" is strong. "Experienced in microservices" is too generic. Show a specific tradeoff you evaluated and the result.' },
      { q: 'Should a backend developer mention DevOps skills in their cover letter?', a: 'Yes, especially Docker, Kubernetes, and CI/CD experience. Modern backend roles increasingly require owning the deployment pipeline. Even basic Terraform and GitHub Actions experience is worth mentioning — it signals that you care about the full lifecycle of your code.' },
    ],
  },
  'data-scientist': {
    dos: [
      'Lead with a deployed model and its business impact — not just accuracy metrics',
      'Reference the specific ML stack in the JD: TensorFlow, PyTorch, Scikit-learn, XGBoost',
      'Show domain expertise: fintech, healthcare, e-commerce, NLP, computer vision',
      'Mention MLOps experience: model deployment, monitoring, retraining pipelines',
      'Include Kaggle rankings or research papers if applicable',
    ],
    donts: [
      'Don\'t cite model accuracy alone — show the business decision the model enabled',
      'Avoid overloading on GenAI buzzwords without specific implementation details',
      'Don\'t hide weak statistics fundamentals — interviewers will probe this',
      'Never claim "experience with LLMs" without specifying model, use case, and scale',
      'Don\'t ignore data engineering skills — ETL, Spark, BigQuery are increasingly expected',
    ],
    keyPoints: [
      'A model you deployed with measurable business impact (predictions/day, cost saved)',
      'Research depth: papers, Kaggle, academic projects',
      'MLOps: how you deploy and monitor models in production',
      'Business translation: how you communicate model outputs to non-technical stakeholders',
    ],
    sampleOpening: 'I deployed a churn prediction model at [Company] that identifies at-risk customers 30 days in advance with 84% precision — enabling targeted retention outreach that recovered ₹1.8Cr in ARR in its first 6 months. This end-to-end, business-impact focus is what I want to bring to [Target Company]\'s data science team.',
    sampleBody: 'At [Company], I build and deploy ML models for our e-commerce platform using Python, Scikit-learn, and XGBoost, serving predictions via a FastAPI endpoint handling 2M requests daily. I recently fine-tuned a product recommendation model that increased average order value by 11%. I manage the full ML lifecycle using MLflow for experiment tracking and model versioning, with automated retraining pipelines on Airflow when drift is detected. I am a Kaggle Expert with a top-8% ranking in the [competition name] competition and hold an M.Tech in Computer Science from [Institution].',
    sampleClosing: 'I am excited by [Company]\'s data challenges in [domain] and the opportunity to build models that directly influence product and business decisions. I would welcome a technical conversation about your current ML infrastructure.',
    faqs: [
      { q: 'How should a data scientist show GenAI experience in a cover letter?', a: 'Be precise: specify the model (Llama 3, GPT-4, Gemini), the use case (document classification, Q&A, summarization), and the outcome (accuracy improvement, time saved, users served). "Fine-tuned Llama 3 on domain-specific data achieving 27% improvement in F1 score, deployed as an API serving 10K requests daily" is strong. "Used LLMs" is not.' },
      { q: 'Should a data scientist mention Kaggle in their cover letter?', a: 'Yes, if you are an Expert or above. A Kaggle Expert or Master title is a strong credential signal, especially for freshers or those transitioning into data science. If you have notebooks with significant upvotes or a well-documented competition submission, include the link.' },
    ],
  },
  'devops-engineer': {
    dos: [
      'Lead with a reliability, deployment frequency, or cost optimization metric',
      'Reference specific tools in the JD: Kubernetes, Terraform, Jenkins, ArgoCD',
      'Show SRE mindset: MTTR reduction, incident count decrease, SLA improvement',
      'Mention cloud depth: specific managed services used, not just "AWS/GCP"',
      'Include security credentials: certificate management, RBAC, secrets handling',
    ],
    donts: [
      'Don\'t claim "managed Kubernetes" without specifying cluster size and workload',
      'Avoid generic cloud claims: "experienced in AWS" needs specific service names',
      'Don\'t skip cost optimization — cloud cost reduction is a key differentiator',
      'Never list "CI/CD experience" without naming the tools and the pipeline improvements you made',
      'Don\'t ignore monitoring/alerting — Prometheus, Grafana, Datadog show production maturity',
    ],
    keyPoints: [
      'Infrastructure you own: cluster size, services, uptime metrics',
      'Specific CI/CD pipeline improvements with deployment frequency or time metrics',
      'Cloud cost optimization work with quantified savings',
      'Security and compliance: RBAC, secret management, scanning tools',
    ],
    sampleOpening: 'When I joined [Company]\'s platform team, deployments took 45 minutes and failed 30% of the time. Six months later, we deploy 8x daily with a 98.6% success rate, through a redesigned GitHub Actions pipeline, automated testing gates, and blue-green deployment strategy. Building reliable delivery systems is what I do.',
    sampleBody: 'I manage a 40-node Kubernetes cluster on AWS EKS serving [Company]\'s production workloads at 99.94% uptime. I have implemented infrastructure as code using Terraform across all environments, reducing environment provisioning from 3 days to 20 minutes. Our monitoring stack (Prometheus + Grafana + PagerDuty) has reduced mean time to detect from 8 minutes to 90 seconds. I recently led a cloud cost optimization initiative that reduced monthly AWS spend by ₹12L through Reserved Instance planning and right-sizing — maintaining a detailed cost dashboard in Grafana.',
    sampleClosing: 'I am drawn to [Company]\'s infrastructure challenges and the opportunity to build reliability at scale. I would welcome a technical conversation about your current stack and where automation could have the most impact.',
    faqs: [
      { q: 'What certifications should a DevOps engineer mention in a cover letter?', a: 'Mention your most relevant certification for the role: AWS Solutions Architect or DevOps Professional for AWS-heavy roles; CKA (Certified Kubernetes Administrator) for Kubernetes-focused positions; Terraform Associate if IaC is central to the role. Certifications signal commitment to the discipline and provide a common credential vocabulary for hiring managers.' },
      { q: 'Should a DevOps engineer mention SRE principles in their cover letter?', a: 'Yes, especially for roles at product companies. Mention SLOs, error budgets, chaos engineering if relevant, and your approach to blameless post-mortems. SRE thinking differentiates a platform engineer who just keeps the lights on from one who systematically improves reliability.' },
    ],
  },
  'sales-manager': {
    dos: [
      'Lead with quota attainment: percentage of target achieved and the absolute revenue number',
      'Reference the specific sales motion in the JD: B2B, SaaS, enterprise, field, inside sales',
      'Show team leadership: size, territory, and team performance improvement',
      'Mention CRM proficiency: Salesforce, HubSpot, Zoho CRM',
      'Express genuine interest in the company\'s product and market',
    ],
    donts: [
      'Don\'t write a sales cover letter without a revenue number — it undermines your sales credibility',
      'Avoid soft language: "relationship builder" needs proof of deals closed',
      'Don\'t claim team leadership without specifying team size and results',
      'Never misrepresent quota attainment — it is easily verified during reference checks',
      'Don\'t write more than 300 words — sales is a high-output profession and your cover letter should reflect it',
    ],
    keyPoints: [
      'Quota attainment percentage and the revenue number it represents',
      'Deal sizes, sales cycles, and customer profiles you have worked with',
      'Team size managed and how you improved team performance',
      'The specific sales methodology you use: SPIN, Challenger, MEDDIC',
    ],
    sampleOpening: '134% of quota in FY24 — ₹10.7Cr against an ₹8Cr annual target, managing a 9-person field sales team across Karnataka and Andhra Pradesh. Consistent overperformance in competitive B2B markets is what I bring to sales leadership roles, and what drew me to [Target Company].',
    sampleBody: 'As Regional Sales Manager at [Company], I lead 9 enterprise sales representatives covering South India for our SaaS HR platform. I have grown the region from ₹4.2Cr to ₹10.7Cr ARR in 18 months by implementing a structured MEDDIC qualification process, reducing our average sales cycle from 94 to 67 days. I mentor my team through bi-weekly deal reviews in Salesforce and have promoted 2 SDRs to AE roles based on structured development plans. My largest individual deal was a ₹1.8Cr enterprise contract with a 400-seat deployment, closed after a 6-month enterprise cycle involving procurement, IT, and HR leadership.',
    sampleClosing: 'I am drawn to [Company]\'s growth stage and the opportunity to scale a high-performance sales team in [target market]. I would welcome a conversation about your current pipeline, team structure, and what a 90-day sales plan would look like.',
    faqs: [
      { q: 'Should a sales manager mention their largest deal in a cover letter?', a: 'Yes — deal size signals the complexity and seniority of sales experience. Enterprise deals (₹50L+) with multi-stakeholder buying committees demonstrate a different skill set than transactional sales. Mention your largest deal size, the sales cycle length, and the stakeholders involved.' },
      { q: 'How should commission and variable pay be mentioned in a sales cover letter?', a: 'Don\'t mention your total compensation — focus on quota attainment as a percentage. "Achieved 134% of quota" is universally understood. If you won a President\'s Club or similar recognition, mention it — it signals consistent top performance in a credible, third-party-validated way.' },
    ],
  },
  'ui-ux-designer': {
    dos: [
      'Include your portfolio URL in the first paragraph — it is your primary credential',
      'Lead with a design outcome: conversion improved, drop-off reduced, task completion increased',
      'Show your research depth: user interviews, usability testing, heuristic evaluation',
      'Reference the design tools in the JD: Figma, Sketch, Adobe XD, Principle',
      'Demonstrate cross-functional collaboration: working with PMs and engineers',
    ],
    donts: [
      'Never apply without a portfolio URL — a designer without visible work will not be shortlisted',
      'Avoid describing aesthetics: "beautiful design" vs "reduced checkout drop-off by 22%"',
      'Don\'t claim UX skills without research evidence: interviews, usability tests, or A/B tests',
      'Never use a heavily designed cover letter — clean, ATS-readable format is appropriate',
      'Don\'t apply generically — reference the company\'s actual product design',
    ],
    keyPoints: [
      'Portfolio URL with your most relevant case study',
      'A design decision backed by user research and measured with data',
      'Design systems experience: component libraries, style guides',
      'How you work with product and engineering: handoff process, implementation support',
    ],
    sampleOpening: 'I redesigned [Company]\'s onboarding flow based on 12 user interviews and 3 rounds of usability testing — reducing the time-to-first-value from 14 minutes to 6 minutes and increasing Day-7 activation by 31%. This outcome-driven design process is what I want to bring to [Target Company]. Portfolio: [portfolio-url]',
    sampleBody: 'As Product Designer at [Company], I own the design of our B2C fintech application (1.2M monthly active users) from discovery through to design QA. I work in Figma and maintain a component library of 140+ components used across web and mobile. I conduct user research monthly — running 6–8 interviews per sprint cycle — and facilitate design critiques with the product and engineering teams. My most recent project redesigned the investment dashboard, improving task completion rate from 68% to 89% based on unmoderated usability testing with 40 participants. My portfolio at [url] includes full case studies for this and 4 other shipped projects.',
    sampleClosing: 'I am drawn to [Company]\'s product design challenges and would love to discuss how my research-driven process and systems thinking can contribute. My portfolio at [url] shows the full depth of my UX process, including research artefacts, interaction flows, and shipped outcomes.',
    faqs: [
      { q: 'How important is the portfolio link in a UX designer cover letter?', a: 'More important than anything else in the cover letter. Hiring managers for design roles navigate directly to your portfolio within the first 30 seconds of reading your application. A strong portfolio with 2–3 complete case studies (problem, process, outcome, reflection) will outperform a generic cover letter every time.' },
      { q: 'Should a UI/UX designer mention design systems in their cover letter?', a: 'Yes, especially for product design roles at companies with established design infrastructure. Design systems experience signals maturity, systems thinking, and ability to work at scale. Mention specific components you created or contributed to, and the engineering team adoption rate if you have it.' },
    ],
  },
  'project-manager': {
    dos: [
      'Lead with project scale: budget, team size, timeline, and delivery outcome',
      'Reference your certification prominently: PMP, PRINCE2, CSM, PMI-ACP',
      'Show stakeholder management at the right level: C-suite, directors, or operational leads',
      'Reference the tools in the JD: MS Project, Jira, Smartsheet, Asana',
      'Demonstrate risk management: a specific risk you identified and mitigated',
    ],
    donts: [
      'Don\'t claim "managed multiple projects" without specifying scale and outcomes',
      'Avoid listing PM tools without showing what you used them to deliver',
      'Don\'t underspecify project context: industry, geography, and team composition matter',
      'Never omit certifications if you hold PMP — it is a primary screening criterion for PM roles',
      'Don\'t write more than 350 words — effective PMs communicate at exactly the right scope',
    ],
    keyPoints: [
      'Project scale: budget, team size, duration, geography',
      'Delivery outcome: on time, under budget, scope achieved',
      'Risk management: a specific risk and how you mitigated it',
      'Stakeholder management: highest level you have presented to',
    ],
    sampleOpening: 'I delivered a ₹18Cr ERP implementation for [Company]\'s 3-state manufacturing operation — 3 weeks ahead of schedule and ₹1.4Cr under budget — despite a mid-project scope change that added 2 additional plant locations. Managing ambiguity while protecting delivery timelines is what I do as a project manager.',
    sampleBody: 'As Project Manager at [Company], I manage a portfolio of 4 simultaneous projects totalling ₹45Cr, overseeing cross-functional teams of 8–22 people across Engineering, Finance, IT, and Operations. I hold PMP certification and use a hybrid Agile-waterfall methodology adapted to project type. For the ERP implementation above, I facilitated a 3-month stakeholder alignment process involving 14 business owners and the CEO, managed a vendor team of 22, and maintained a risk register with 47 identified risks — 3 of which would have caused 8+ week delays if not mitigated proactively.',
    sampleClosing: 'I am drawn to [Company]\'s [specific project or initiative] and the opportunity to bring structured, outcome-focused project leadership to your portfolio. I would welcome a conversation about your current priorities and how I can contribute immediately.',
    faqs: [
      { q: 'Is PMP certification worth mentioning in a project manager cover letter?', a: 'Yes — mention it in your first paragraph. PMP is the most recognised PM certification globally and is a primary shortlisting criterion for mid-to-senior PM roles in India. If you hold it, lead with it. If you are pursuing it, mention your exam date — it still signals commitment.' },
      { q: 'How should a project manager describe stakeholder management in a cover letter?', a: 'Specify the highest level you have presented to and the context: "presented monthly project health reports to the CFO and VP Engineering" is specific and credible. "Managed stakeholders" is too vague to differentiate you from candidates who only deal with operational teams.' },
    ],
  },
  'content-writer': {
    dos: [
      'Include your portfolio URL in the first line — published work is your primary credential',
      'Lead with a content metric: organic traffic grown, keyword rankings achieved, engagement rate',
      'Reference the content types in the JD: blog posts, white papers, case studies, email sequences',
      'Show SEO depth: keyword research, on-page optimization, internal linking',
      'Demonstrate industry knowledge specific to the company\'s domain',
    ],
    donts: [
      'Never apply without a portfolio link — an unverifiable content writer is immediately disqualified',
      'Don\'t claim "excellent writing skills" — demonstrate them in the cover letter itself',
      'Avoid listing tools without showing what you produced with them',
      'Don\'t write a generic cover letter — tailor your opening to the company\'s content style',
      'Never use passive voice or wordy sentences — it contradicts your writing credentials',
    ],
    keyPoints: [
      'Best-performing piece with traffic, ranking, or engagement data',
      'SEO depth: keyword strategy, content clusters, technical SEO understanding',
      'Volume and consistency: how much you publish and maintain quality at scale',
      'Editorial process: how you research, structure, and edit long-form content',
    ],
    sampleOpening: 'My guide to [topic] has ranked #1 on Google India for "[keyword]" since March 2025, driving 8,200 monthly organic visits for [Company]. Building content that compounds in search while genuinely helping readers is the approach I want to bring to [Target Company]\'s content team. Portfolio: [portfolio-url]',
    sampleBody: 'As Senior Content Writer at [Company], I produce 8–10 long-form pieces per month (1,500–3,000 words) covering [domain]. My content has grown the company blog from 12,000 to 74,000 monthly organic sessions in 18 months, with 23 pieces ranking on page 1 for target keywords. I own the content calendar, conduct keyword research in Ahrefs, brief freelance writers, and manage a 6-week content pipeline. Beyond SEO, I write email sequences (our onboarding sequence achieved a 38% open rate), case studies used by the sales team, and LinkedIn thought leadership content for the founder.',
    sampleClosing: 'I am drawn to [Company]\'s content strategy and the opportunity to build [specific content type] that drives measurable organic growth. I would welcome a conversation about your content goals and where I can make the most impact.',
    faqs: [
      { q: 'What is the single most important element of a content writer cover letter?', a: 'Portfolio URL. A link to your best 3–5 published pieces is worth more than any amount of self-description. If you have pieces with organic traffic data, Google ranking screenshots, or engagement metrics, share them. The cover letter should lead the reader to your work as quickly as possible.' },
      { q: 'Should a content writer\'s cover letter demonstrate writing quality?', a: 'Yes — absolutely. Your cover letter IS a writing sample. Use clear, active sentences. No passive voice, no filler phrases. Show concision, clarity, and a distinctive voice. A cover letter that demonstrates excellent writing instantly raises confidence in your ability to produce quality content.' },
    ],
  },
  'operations-manager': {
    dos: [
      'Lead with a P&L or cost metric: budget managed, cost reduced, efficiency improved',
      'Reference the industry context: e-commerce, logistics, FMCG, manufacturing, services',
      'Show scale: team size, geography, number of locations or units',
      'Reference methodology: Lean, Six Sigma, Kaizen, 5S where relevant',
      'Demonstrate ERP proficiency: SAP, Oracle, WMS, relevant to the JD',
    ],
    donts: [
      'Don\'t describe operations activities without outcomes: "managed warehouse" vs "reduced warehouse cycle time by 35%"',
      'Avoid vague scale claims: "large team" vs "managed 180-person operations across 4 warehouses"',
      'Don\'t omit tech tool experience — modern ops roles require ERP and BI proficiency',
      'Never claim P&L ownership without the size of the P&L',
      'Don\'t use jargon without substance: "streamlined operations", "improved efficiencies"',
    ],
    keyPoints: [
      'P&L or cost budget managed with the absolute number',
      'Team scale and geographic coverage',
      'A specific process improvement with quantified outcome',
      'Vendor or partner management scope',
    ],
    sampleOpening: 'In FY24, I reduced fulfilment cost per order at [Company] from ₹87 to ₹61 — a 30% reduction — by redesigning our pick-pack-ship workflow, eliminating 3 manual handoffs, and renegotiating SLAs with 2 logistics partners. Operational efficiency at scale is what I have spent the last 7 years building.',
    sampleBody: 'As Operations Manager at [Company], I oversee fulfilment operations across 3 warehouses in Maharashtra, handling 12,000 orders daily at peak. I manage 220 operations staff across shifts, own a ₹45Cr annual operations budget, and work directly with 8 logistics partners. I have implemented SAP WM across 2 sites, deployed IoT-based inventory tracking that reduced shrinkage by 22%, and run a Six Sigma Green Belt project that eliminated ₹90L in annual waste from our returns processing workflow. OTIF delivery improved from 87% to 94% under my management.',
    sampleClosing: 'I am drawn to [Company]\'s operations scale and the challenges of [specific operational context]. I would welcome a conversation about how I approach efficiency and what a 90-day operations review would look like.',
    faqs: [
      { q: 'What metrics should an operations manager include in a cover letter?', a: 'Lead with your most impactful cost, efficiency, or quality metric: cost per unit reduced, OTIF improved, waste eliminated, cycle time shortened. Show the absolute number (₹90L saved, 30% cost reduction) and the context (team size, volume, timeframe). Operations metrics without context are as weak as no metrics at all.' },
      { q: 'Should an operations manager mention Six Sigma in their cover letter?', a: 'Yes, especially for manufacturing, FMCG, and large-scale logistics roles. Mention the level (Yellow Belt, Green Belt, Black Belt) and the project outcome. "Completed a Six Sigma Green Belt project that reduced returns processing cost by ₹90L annually" is highly credible and demonstrates structured problem-solving.' },
    ],
  },
  'civil-engineer': {
    dos: [
      'Lead with project scale: value, type (residential/commercial/infrastructure), and completion',
      'Reference software tools in the JD: AutoCAD, STAAD.Pro, Revit, MS Project, Primavera',
      'Show site execution depth: supervision scope, quality checks, safety compliance',
      'Mention budget and timeline adherence metrics',
      'Reference relevant IS codes and standards knowledge',
    ],
    donts: [
      'Don\'t describe projects without their value — "supervised construction" vs "supervised ₹45Cr residential tower"',
      'Avoid listing software without context of how you used it',
      'Don\'t omit your civil sub-discipline: structural, geotechnical, water resources, transportation',
      'Never miss site execution specifics — supervision scope, team size, trades managed',
      'Don\'t forget safety record if exceptional: "zero LTI incidents across 3 projects"',
    ],
    keyPoints: [
      'Project value and type — the foundation of any civil engineering cover letter',
      'Software proficiency with specific deliverables produced',
      'Site team managed: supervisors, subcontractors, trades',
      'Quality and safety performance metrics',
    ],
    sampleOpening: 'I managed site execution for a ₹65Cr commercial complex in Pune — completing structural work 3 weeks ahead of the monsoon deadline and maintaining a zero-incident safety record across 14 months of construction. On-time, safe delivery at scale is the standard I hold myself to.',
    sampleBody: 'As Site Engineer at [Company], I oversee structural execution for a ₹65Cr mixed-use development in Pune, managing 3 supervisors, 12 subcontractors, and a daily labour force of 180 workers. I prepare and review shop drawings in AutoCAD, conduct daily quality inspections per IS 456 specifications, and prepare weekly progress reports for the project director. I track project schedule in Primavera P6 and manage material procurement to maintain a 2-week buffer stock at all times. I have also completed my CPWD empanelment for structural supervision.',
    sampleClosing: 'I am drawn to [Company]\'s infrastructure projects and the opportunity to contribute to [specific project type]. I would welcome a discussion about the site challenges and how my experience in [relevant area] could be most useful.',
    faqs: [
      { q: 'How should a fresher civil engineer write a cover letter with limited experience?', a: 'Emphasise your final-year project in detail: type of structure, loads analysed, software used, supervisor name, and any on-site exposure during the project. Internship experience, even 1–2 months of site visits, should be detailed with the project value, location, and specific activities observed. What freshers lack in professional experience, they should compensate with demonstrated academic application and eagerness to learn.' },
      { q: 'Should a civil engineer mention CPWD empanelment in their cover letter?', a: 'Yes, for government and public sector roles. CPWD empanelment is a significant credential for civil engineers targeting NHAI, CPWD, PWD, or government infrastructure projects. For private sector roles, it still signals compliance capability and a formal verification of your engineering credentials.' },
    ],
  },
  'mechanical-engineer': {
    dos: [
      'Reference the specific CAD software in the JD: SolidWorks, CATIA, AutoCAD, ANSYS',
      'Lead with a design improvement or manufacturing efficiency outcome',
      'Show manufacturing process depth: the materials and processes you have worked with',
      'Reference quality standards: ISO 9001, GD&T, FMEA, DFMEA',
      'Mention the industry context: automotive, aerospace, FMCG, heavy engineering',
    ],
    donts: [
      'Don\'t say "proficient in CAD" — name the specific software and what you designed with it',
      'Avoid listing processes without application context: "experience in CNC" vs "programmed CNC for aluminium housing components"',
      'Don\'t underplay quality work — FMEA, DFMEA, and tolerance analysis signal engineering depth',
      'Never omit industry context — automotive, defence, and consumer goods require very different skills',
      'Don\'t use vague product descriptions: "designed components" vs "designed structural bracket assembly for two-wheeler frame"',
    ],
    keyPoints: [
      'A specific design or process improvement with quantified outcome',
      'CAD/CAE tools and what you specifically produced with them',
      'Manufacturing processes and materials you have worked with',
      'Quality certifications and methods applied',
    ],
    sampleOpening: 'I redesigned the rear suspension bracket for [Company]\'s flagship two-wheeler in SolidWorks and ANSYS, reducing component weight by 18% while meeting the same structural load requirements — saving ₹340/unit in material cost at 50,000 units/month production volume. This blend of design rigour and cost awareness is what I bring to mechanical engineering.',
    sampleBody: 'As Design Engineer at [Company], I work in SolidWorks 2024 on sheet metal and injection-moulded components for our automotive exhaust system product line. I produce 3D models, GD&T drawings, and DFMEA analyses for new part introductions. I have led 3 DFM reviews with our Tier-1 stamping vendor, resulting in tooling cost reductions totalling ₹18L. I conduct structural analysis in ANSYS Mechanical for load case validation and have experience with APQP documentation for customer submissions. I am pursuing my CATIA V5 certification alongside this role.',
    sampleClosing: 'I am drawn to [Company]\'s engineering challenges in [specific product area] and the opportunity to contribute design depth and manufacturing knowledge. I would welcome a technical discussion about your current product development priorities.',
    faqs: [
      { q: 'Which CAD software should a mechanical engineer focus on for Indian jobs?', a: 'SolidWorks for most manufacturing and product design roles. CATIA for automotive (Tata Motors, Mahindra, Bosch). ANSYS for simulation-heavy R&D and aerospace. AutoCAD for 2D drawing and civil-adjacent roles. Mention the software you are most proficient in first, then list others. Depth in one tool beats surface familiarity with five.' },
      { q: 'How should a fresher mechanical engineer approach their cover letter?', a: 'Lead with your most significant academic project: the design challenge, the CAD software used, the analysis performed, and the outcome or grade. Include any internship exposure — even 4-week plant visits are worth detailing if they gave you manufacturing process knowledge. Mention GD&T understanding and DFMEA if taught in your curriculum — these are frequently tested in interviews.' },
    ],
  },
  'nursing': {
    dos: [
      'Lead with your NMC/INC registration number and specialisation',
      'Mention the specific clinical setting: ICU, OT, emergency, paediatrics, oncology',
      'Reference patient care metrics: patient ratio, bed strength, procedures performed',
      'Include certifications: BLS, ACLS, NRP, PALS',
      'For Gulf applications, mention HAAD/DHA/SCFHS eligibility and passport details section',
    ],
    donts: [
      'Never omit NMC registration — it is the first thing any employer verifies',
      'Don\'t just list duties — specify procedures, patient ratios, and clinical outcomes',
      'Avoid vague descriptions: "worked in ICU" vs "managed 8-bed ICU independently, handling ventilated patients"',
      'Don\'t ignore international format requirements for UAE/UK/Canada applications',
      'Never apply for a specialisation you are not qualified for — licensing boards verify credentials',
    ],
    keyPoints: [
      'NMC/INC registration and its validity date',
      'Specialisation with specific procedures performed',
      'Patient care capacity: ratio, acuity level, setting',
      'Certifications and international eligibility if applying abroad',
    ],
    sampleOpening: 'I am a registered nurse (NMC No. [XXXXX], valid through [Date]) with 4 years of ICU experience at [Hospital Name], where I independently manage a 10-bed mixed ICU handling post-cardiac surgery and multi-trauma patients. My clinical focus on critically ill patient management and my ACLS certification make me well-suited for the Senior Staff Nurse position at [Target Hospital].',
    sampleBody: 'At [Hospital Name], I manage a 10-bed mixed ICU alongside one other registered nurse, overseeing patients on mechanical ventilators, central lines, arterial lines, and continuous monitoring. I am competent in haemodynamic monitoring, vasopressor titration, ventilator management (weaning protocols), and rapid response escalation. I maintain complete medication administration records in our EMR (Meditech) and participate in daily ICU ward rounds with the consultant team. I hold current BLS (AHA) and ACLS (AHA) certifications, valid until [Date].',
    sampleClosing: 'I am drawn to [Hospital]\'s reputation for clinical excellence in [specialisation] and the opportunity to contribute to a high-quality critical care team. I would welcome the opportunity to discuss the specific clinical protocols and patient profile of your ICU.',
    faqs: [
      { q: 'What format should a nurse use for a Gulf country cover letter?', a: 'Gulf nursing cover letters (UAE, Saudi Arabia, Qatar) should be formal and include: full legal name as on passport, nationality, NMC/equivalent registration details, current employer and designation, clinical specialisation and procedures competency, visa status, and availability date. Reference any HAAD, DHA, or SCFHS eligibility or dataflow verification completed.' },
      { q: 'Should an Indian nurse mention salary expectations in a cover letter?', a: 'Only if the employer has specifically requested it, particularly for Gulf placements where package negotiation is standard. If required, state your expectation as a range. For domestic Indian hospital applications, salary expectations are typically discussed at interview stage — do not include them in the cover letter.' },
    ],
  },
  'electrical-engineer': {
    dos: [
      'Reference the specific electrical systems in the JD: PLC/SCADA, power systems, panel design, solar',
      'Lead with a project metric: capacity, project value, uptime improvement',
      'Mention voltage level experience: HT vs LT — critical context for recruiters',
      'Reference software tools: EPLAN, AutoCAD Electrical, ETAP, MATLAB',
      'Include relevant certifications: IE rules, CBIP, energy auditor',
    ],
    donts: [
      'Don\'t say "electrical maintenance" without specifying systems, equipment, and voltage levels',
      'Avoid generic tool claims: "AutoCAD experience" vs "designed panel schematics in AutoCAD Electrical for 3 industrial projects"',
      'Don\'t omit project value or capacity — ₹ value and MW/MVA scale are crucial context',
      'Never misstate certification status — electrical engineers are licensed professionals',
      'Don\'t use a single generic cover letter for power systems, instrumentation, and automation roles — they are different specialisations',
    ],
    keyPoints: [
      'Specialisation clearly stated: power systems, PLC/SCADA, instrumentation, panel design',
      'Project scale: voltage level, capacity, project value',
      'Software tools with specific deliverables',
      'Vendor experience: ABB, Siemens, Schneider, L&T Switchgear',
    ],
    sampleOpening: 'I designed and commissioned a 11kV/440V substation for [Company]\'s new 20MW manufacturing facility in Pune — delivering the electrical infrastructure 2 weeks ahead of the production commissioning schedule. Power systems engineering at project scale is my core competency.',
    sampleBody: 'As Electrical Engineer at [Company], I am responsible for the design, procurement, and commissioning of LT/HT electrical systems for industrial and commercial projects ranging from ₹2Cr to ₹18Cr. I prepare single-line diagrams, panel schematics, and load schedules in AutoCAD Electrical and EPLAN. I manage vendor approvals for ABB and Schneider MCC panels, coordinate with contractors on cable routing and termination, and conduct commissioning and testing for HT switchgear. I have completed a BEE empanelment for energy auditing and hold a valid IE rules certification for the state of Maharashtra.',
    sampleClosing: 'I am drawn to [Company]\'s electrical projects in [specific sector or type] and the opportunity to contribute design expertise from concept to commissioning. I would welcome a technical discussion about your current project pipeline.',
    faqs: [
      { q: 'What is the most important credential for an electrical engineer in India to mention?', a: 'The IE rules license (under the Indian Electricity Act) for electrical supervisory work, CBIP certification for power sector roles, and BEE Certified Energy Auditor for energy management roles. For PSU applications, GATE qualification is essential. Mention whichever is most relevant to the target role in your first paragraph.' },
      { q: 'How should an electrical engineer distinguish between HT and LT experience in a cover letter?', a: 'State it explicitly: "HT systems (11kV/33kV)" or "LT distribution (415V)" in your opening or first body paragraph. Power sector recruiters immediately categorise candidates by voltage level. HT experience commands significantly higher consideration for infrastructure and utility roles.' },
    ],
  },
  'accountant': {
    dos: [
      'Lead with Tally proficiency — it is the most screened tool for Indian accounting roles',
      'Mention GST filing experience — essential for virtually every Indian accounting role',
      'Show financial scale: turnover of companies whose books you have managed',
      'Reference your qualification: CA, CA Inter, B.Com, M.Com',
      'Specify compliance depth: GST returns filed, TDS categories handled, income tax returns prepared',
    ],
    donts: [
      'Don\'t omit Tally — even senior accountants are expected to know it in India',
      'Avoid vague statements: "handled accounts" vs "maintained books for ₹12Cr turnover company in Tally ERP 9"',
      'Don\'t forget GST — it is fundamental for any accounting role post-2017',
      'Never describe duties without showing the scale and complexity of what you managed',
      'Don\'t apply for senior roles if your qualification section is unclear — be precise about CA rank, inter groups, or pursuing status',
    ],
    keyPoints: [
      'Tally proficiency and the specific version and modules used',
      'GST compliance depth: returns filed (GSTR-1, 3B, 9, 9C), frequency, and business size',
      'Financial reporting: balance sheets, P&L, cash flow statements produced',
      'Audit support: statutory audit, internal audit, or CA firm experience',
    ],
    sampleOpening: 'I manage the complete accounting function for a ₹24Cr turnover manufacturing company in Tally ERP 9 — from day-to-day bookkeeping through to GST filing, TDS compliance, and MIS reporting for the promoters. Owning the full financial record of a company at this scale has given me a comprehensive accounting foundation I want to bring to [Target Company].',
    sampleBody: 'At [Company], I handle all accounting entries in Tally ERP 9 including sales invoicing, purchase recording, bank reconciliation, and payroll processing for 45 employees. I file monthly GSTR-1 and GSTR-3B returns, quarterly TDS returns (24Q and 26Q), and prepare the annual financial statements (balance sheet, P&L, cash flow) for the statutory auditor. I assist the CA firm during the annual audit by preparing audit schedules, bank statements, and reconciliation statements. I am currently pursuing my CA Inter (Group 1 cleared, appearing for Group 2 in May 2026).',
    sampleClosing: 'I am drawn to [Company]\'s accounting requirements and the opportunity to contribute accurate, timely financial reporting. I would welcome a discussion about your current accounting processes and where I can add value.',
    faqs: [
      { q: 'Should an accountant mention their CA Inter status in their cover letter?', a: 'Absolutely. CA Inter is a strong differentiator from basic commerce graduates and signals professional accounting commitment. Specify the groups cleared, the attempt number, and whether you are currently pursuing further groups. Even partial completion of CA is highly valued in the Indian job market.' },
      { q: 'How should an accountant describe GST experience in a cover letter?', a: 'Be specific about the return types filed (GSTR-1, 3B, 9, 9C), the frequency (monthly, quarterly), the business turnover, and whether you handle GST reconciliation and audit. "Filed GSTR-3B monthly for 3 clients with aggregate turnover of ₹18Cr" is far more credible than "GST experience."' },
    ],
  },
  'supply-chain-manager': {
    dos: [
      'Lead with a procurement savings or inventory efficiency metric',
      'Reference your ERP depth: SAP MM/WM, Oracle SCM, Dynamics 365',
      'Show category expertise: direct materials, indirect procurement, or specific commodity',
      'Mention vendor base managed: count, annual spend, categories',
      'Reference certifications: CSCP, CPIM, Six Sigma if applicable',
    ],
    donts: [
      'Don\'t claim supply chain experience without quantified cost savings or efficiency metrics',
      'Avoid generic vendor management claims: "managed vendors" vs "managed 45-vendor panel with ₹8Cr annual spend"',
      'Don\'t omit ERP — SAP MM/WM is screened in most senior SCM JDs',
      'Never confuse direct and indirect procurement — clarify your category expertise',
      'Don\'t underplay logistics KPIs: OTIF, freight cost per unit, and fill rate are key metrics',
    ],
    keyPoints: [
      'Annual procurement spend managed',
      'A specific cost saving initiative with the ₹ amount',
      'Vendor base: count, categories, geographic spread',
      'Inventory KPIs: turnover ratio, fill rate, days of inventory',
    ],
    sampleOpening: 'I negotiated ₹3.8Cr in annual procurement savings at [Company] through vendor consolidation, long-term contracts, and specification standardisation — without compromising quality standards or supply reliability. This combination of commercial discipline and supply continuity focus is what I bring to supply chain leadership.',
    sampleBody: 'As Supply Chain Manager at [Company], I oversee procurement and logistics for our FMCG manufacturing operations, managing a direct materials spend of ₹42Cr annually across 68 vendors in 4 commodity categories. I have implemented SAP MM for purchase order management and integrated it with our WMS for inventory visibility across 3 warehouses. My demand planning improvements (S&OP monthly cycle) reduced our days of inventory from 38 to 24 while maintaining a 97.4% fill rate. I am a certified CPIM (ASCM) and hold a Six Sigma Green Belt focused on a procurement process improvement project.',
    sampleClosing: 'I am drawn to [Company]\'s supply chain challenges in [specific area] and the opportunity to build procurement and logistics efficiency at scale. I would welcome a conversation about your current supply chain priorities.',
    faqs: [
      { q: 'Should a supply chain manager mention S&OP in their cover letter?', a: 'Yes, if you have hands-on S&OP experience — it is a strong differentiator. Mention the cycle frequency (weekly, monthly), the stakeholders involved (sales, operations, finance), and any forecast accuracy improvement you achieved. S&OP participation at the cross-functional level signals supply chain leadership maturity.' },
      { q: 'Is CSCP or CPIM more valuable for Indian supply chain roles?', a: 'CPIM is more widely recognised in manufacturing and pharma supply chain roles in India. CSCP is preferred in FMCG and e-commerce. Either certification typically results in preferential shortlisting for SCM roles above ₹10L CTC. If you are early in your career, CPIM Part 1 is achievable in 3 months and adds immediate credibility.' },
    ],
  },
  'teacher': {
    dos: [
      'Lead with a student outcome: board exam results, competition wins, or activity achievement',
      'Specify subjects taught and grade levels clearly: "Physics, Classes 11–12, CBSE"',
      'Mention your board experience: CBSE, ICSE, IB, IGCSE, State Board',
      'Reference EdTech tools for online roles: Google Classroom, Zoom, LMS platforms',
      'Show genuine interest in the school\'s philosophy or academic focus',
    ],
    donts: [
      'Never be vague about subjects or grades — "taught science" tells nothing',
      'Don\'t omit B.Ed if you hold it — it is mandatory for most school roles in India',
      'Avoid a lengthy teaching philosophy unless applying to an international or research school',
      'Don\'t use clichés: "passion for children", "love of learning" without substance',
      'Never apply for a subject you are not qualified to teach',
    ],
    keyPoints: [
      'Subjects, classes, and board — the minimum required information',
      'Student outcome data if available — even informal metrics',
      'Extra responsibilities: class teacher, coordinator, extracurricular lead',
      'Online teaching tools if applying to EdTech or hybrid roles',
    ],
    sampleOpening: 'In the 2024–25 academic year, 91% of my Class 12 Physics students scored above 80% in CBSE board examinations — up from 74% the previous year. I attribute this improvement to a structured concept mapping approach and weekly doubt resolution sessions. Building academic confidence and measurable results is the philosophy I bring to [School Name].',
    sampleBody: 'I teach Physics to Classes 11 and 12 CBSE at [School Name], where I am also the Class 12 form teacher and Science Club coordinator. I prepare lesson plans aligned to the CBSE curriculum, conduct weekly formative assessments, and provide individual progress reports to parents at each term end. I have developed a video library of 40 concept revision videos hosted on Google Classroom, which students use for exam preparation independently. I hold a B.Ed from [University] (2021) and an M.Sc in Physics from [University] (2019).',
    sampleClosing: 'I am drawn to [School]\'s academic culture and the opportunity to contribute to your Physics department at the senior secondary level. I would welcome a discussion about your curriculum approach and how I can support your students\' academic development.',
    faqs: [
      { q: 'Should a teacher include a teaching philosophy in their cover letter?', a: 'Only if applying to progressive schools (IB, Cambridge, Waldorf) or for curriculum leadership roles where philosophy is explicitly evaluated. For standard CBSE/ICSE school applications, focus on subject expertise, board knowledge, and student outcome data. A two-line teaching philosophy in the closing paragraph is sufficient for most Indian school applications.' },
      { q: 'How should a teacher applying to an EdTech company write their cover letter?', a: 'Lead with content creation or student engagement data from your online teaching experience. Mention the platform (Unacademy, Vedantu, YouTube, Google Classroom), the subject and class level, the number of students taught, and your content performance metrics (views, ratings, completion rates). EdTech companies prioritise scalable content over traditional classroom experience.' },
    ],
  },
  'graphic-designer': {
    dos: [
      'Include your portfolio URL in the first sentence — it is your primary credential',
      'Reference the specific design types in the JD: brand identity, packaging, digital ads, social media',
      'Show output at scale if you have it: "60+ creatives per month for a 500K-follower D2C brand"',
      'Mention measurable design impact where possible: packaging redesign, conversion improvement',
      'Reference tools precisely: Illustrator, Photoshop, InDesign, After Effects, Figma',
    ],
    donts: [
      'Never apply without a portfolio URL — a graphic designer without visible work will not be shortlisted',
      'Don\'t describe design as "beautiful" or "creative" without a business outcome',
      'Avoid listing outdated software versions: "Photoshop CS6" signals years without updates',
      'Don\'t use a heavily designed cover letter — a professionally formatted plain document is appropriate',
      'Never claim motion graphics skills without work to show in your portfolio',
    ],
    keyPoints: [
      'Portfolio URL — non-negotiable',
      'Brand or campaign work with client name and output type',
      'Volume and consistency of output',
      'Motion and digital capabilities if relevant to the role',
    ],
    sampleOpening: 'I designed the full brand identity system for [Brand Name] — logo, typography, colour palette, packaging, and digital asset library — which was used across 3 product launches generating ₹4.2Cr in first-year revenue. Turning business strategy into compelling visual identity is what I do. Portfolio: [portfolio-url]',
    sampleBody: 'As Graphic Designer at [Agency/Brand], I produce 50–80 digital and print creatives monthly for 4 FMCG and D2C clients. My work includes brand identity systems, product packaging (executed through to print-ready files), performance marketing creatives (tested with A/B results), and motion graphics in After Effects for social media. I work in Illustrator, Photoshop, and InDesign for static work, and After Effects + Lottie for animation. I recently led the visual refresh of [Brand]\'s entire digital touchpoint — 12 templates across social, email, and display — reducing weekly creative production time by 6 hours through a Figma component system.',
    sampleClosing: 'I am drawn to [Company]\'s creative challenges and the opportunity to contribute systematic, high-quality visual design at scale. My portfolio at [url] shows both the strategic thinking and technical execution behind each project.',
    faqs: [
      { q: 'Should a graphic designer use a visually designed cover letter?', a: 'A lightly designed cover letter is acceptable for creative agency applications. For corporate roles, use a clean, ATS-safe format. Always have two versions: one designed for agencies and one plain document for corporate and ATS submissions. Your portfolio is where you demonstrate visual design skill — your cover letter should demonstrate clarity and professionalism.' },
      { q: 'How should a graphic designer show impact in a cover letter?', a: 'Connect design to business outcomes: "Packaging redesign increased shelf conversion by 18% in retail audit", "A/B tested ad creatives improved CTR from 1.2% to 3.8%", "Brand identity refresh resulted in 40% increase in unaided brand recall in the quarterly brand tracker." Design impact measured in business terms is the most compelling narrative for graphic design cover letters.' },
    ],
  },
  'python-developer': {
    dos: [
      'Reference the specific Python frameworks in the JD: Django, FastAPI, Flask, Celery',
      'Lead with a deployed project metric: requests/day, users served, latency improvement',
      'Show your Python ecosystem depth: async/await, pytest, type hints, virtual environments',
      'Mention deployment context: AWS, Docker, Kubernetes — where your code runs',
      'Distinguish your path: web development, data engineering, or automation',
    ],
    donts: [
      'Don\'t claim "Python developer" without naming frameworks — it signals beginner level',
      'Avoid listing Python 2 as a primary skill — Python 3.x is expected',
      'Don\'t mix web and data paths without clarity — pick the one relevant to the role',
      'Never claim async experience without specifics: asyncio, aiohttp, FastAPI async',
      'Don\'t skip testing — pytest coverage shows production engineering maturity',
    ],
    keyPoints: [
      'Primary framework and the scale/context you used it in',
      'Deployment and infrastructure: where your code runs in production',
      'Testing approach: pytest, coverage percentage, CI integration',
      'Python 3 specific features you use: type hints, dataclasses, async/await, generators',
    ],
    sampleOpening: 'I built and deployed a FastAPI microservice at [Company] that handles 180,000 API requests daily with sub-50ms P95 latency — processing asynchronous payment webhooks from 3 external payment providers. Building production-grade Python services at scale is my core competency.',
    sampleBody: 'As Python Developer at [Company], I build backend services in FastAPI and Django for our fintech SaaS platform serving 22,000 B2B customers. My most recent project was a background job processing system using Celery + Redis that handles 2M daily scheduled tasks with a 99.8% success rate and automatic retry logic. I deploy to AWS ECS with Docker containers, manage database migrations in Alembic, and maintain 87% test coverage with pytest. I use Python type hints throughout the codebase and have recently introduced Pydantic v2 for request validation, reducing validation-related bugs by 60%.',
    sampleClosing: 'I am drawn to [Company]\'s Python engineering challenges and the opportunity to contribute to [specific system or problem]. I would welcome a technical discussion about your current backend architecture.',
    faqs: [
      { q: 'Should a Python developer specify their framework in the cover letter?', a: 'Yes — always. "Python developer" without naming Django, FastAPI, or Flask is a red flag for technical hiring managers. The framework signals the type of work (web APIs, background jobs, data pipelines) and your architecture familiarity. Name your primary framework in the first sentence.' },
      { q: 'How should a Python developer show they are production-ready in their cover letter?', a: 'Mention production scale metrics (requests/day, users), your testing approach (pytest, coverage %), and your deployment context (Docker, Kubernetes, cloud). Production-readiness is demonstrated by showing that your code runs under real load in real infrastructure — not just that it works in development.' },
    ],
  },
  'java-developer': {
    dos: [
      'Specify your Java version: Java 11, 17, or 21 — it signals your currency',
      'Reference Spring Boot specifically — "Spring" alone is ambiguous',
      'Lead with a backend architecture or performance outcome',
      'Show enterprise depth: transaction management, connection pooling, JPA/Hibernate',
      'Mention microservices or cloud context if relevant to the role',
    ],
    donts: [
      'Don\'t use "J2EE developer" as a primary title in 2026 — it signals outdated skills',
      'Avoid listing EJB, Struts, or JSP as primary skills for modern roles',
      'Never claim Spring without specifying: Spring Boot, Spring MVC, Spring Security, Spring Cloud',
      'Don\'t omit your Java version — Java 8 and Java 21 signal very different skill levels',
      'Don\'t skip performance context: transaction volume, latency, or uptime signals seniority',
    ],
    keyPoints: [
      'Java version and Spring ecosystem depth',
      'System architecture: microservices, event-driven, monolith — with scale',
      'Database and persistence: JPA/Hibernate, connection pooling, query optimization',
      'Build tools and CI/CD: Maven/Gradle, Jenkins, GitHub Actions',
    ],
    sampleOpening: 'I led the decomposition of a 180,000-line Java monolith into 9 Spring Boot microservices at [Company] — reducing mean deployment time from 2 hours to 12 minutes and enabling independent scaling of our highest-traffic services. Java architecture at enterprise scale is my core expertise.',
    sampleBody: 'As Senior Java Developer at [Company], I build microservices in Java 21 with Spring Boot 3.x for our BFSI platform processing 4 million transactions daily. I have implemented reactive programming with Spring WebFlux for our event-driven services, reducing thread blocking and improving throughput by 35%. I manage database interactions through JPA/Hibernate with optimised query strategies and connection pool tuning (HikariCP), and use Apache Kafka for event streaming between services. Our deployment pipeline uses Jenkins and ArgoCD for zero-downtime rolling deployments on Kubernetes. I hold Oracle Certified Professional: Java SE 17 Developer certification.',
    sampleClosing: 'I am drawn to [Company]\'s Java engineering challenges in [domain] and the opportunity to contribute architecture depth and production experience. I would welcome a technical discussion about your current microservices strategy.',
    faqs: [
      { q: 'Is Java still relevant for Indian software companies in 2026?', a: 'Yes — Java is the dominant language in Indian IT services (TCS, Infosys, Wipro, Cognizant, HCL) and across the BFSI technology sector (banks, insurance, capital markets). Spring Boot is the standard framework. Java developers remain consistently in demand, with Java 17 and 21 (LTS versions) being the current baseline for modern roles.' },
      { q: 'Should a Java developer mention Spring Boot or Spring Framework in their cover letter?', a: 'Spring Boot specifically — it has become the de facto standard for Java web services. Mentioning "Spring Framework" without Boot is technically accurate but signals an older codebase. If you use Spring Cloud, Spring Security, or Spring WebFlux, mention these components — they signal architecture depth beyond basic REST API development.' },
    ],
  },
  'digital-marketing-executive': {
    dos: [
      'Lead with a campaign performance metric: ROAS, CPC improvement, follower growth, keyword ranking',
      'Reference the specific channels in the JD: Google Ads, Meta Ads, SEO, email, content',
      'Mention free certifications you hold: Google Ads, HubSpot, Meta Blueprint',
      'Show tool proficiency: Google Analytics, Search Console, Ahrefs, Meta Business Manager',
      'Express genuine knowledge of the company\'s marketing strategy or brand voice',
    ],
    donts: [
      'Don\'t claim channel experience without performance metrics',
      'Avoid listing certifications you are "in progress" unless close to completion',
      'Don\'t write a generic cover letter — reference the company\'s actual marketing presence',
      'Never use marketing jargon without results: "viral content", "brand awareness"',
      'Don\'t ignore analytics tools — every digital marketing role requires GA4 at minimum',
    ],
    keyPoints: [
      'Best campaign result with full context: channel, budget, outcome',
      'Platform certifications held',
      'Analytics tools and your comfort with data',
      'Content creation skills if relevant to the role',
    ],
    sampleOpening: 'I grew [Company]\'s Instagram from 8,200 to 44,000 followers in 9 months while simultaneously reducing our paid CAC by 34% through audience refinement and creative testing. Data-driven digital marketing that builds both brand and pipeline is what I focus on.',
    sampleBody: 'As Digital Marketing Executive at [Company], I manage SEO, Google Ads (₹4L monthly budget), and social media for our B2C brand. In the past year, I have grown organic search traffic from 6,000 to 28,000 monthly sessions by executing a content cluster strategy around 12 primary keywords, achieving page-1 rankings for 8 high-intent terms. Our Google Ads ROAS improved from 2.4x to 4.1x after I restructured campaigns by intent and implemented responsive search ad testing. I am certified in Google Ads Search, Google Analytics 4, and HubSpot Content Marketing, and use Ahrefs and Search Console daily for SEO monitoring.',
    sampleClosing: 'I am drawn to [Company]\'s marketing challenges and the opportunity to grow [specific channel or audience]. I would welcome a conversation about your current digital marketing priorities and where data-driven optimization can have the most impact.',
    faqs: [
      { q: 'What certifications should a digital marketing executive mention in their cover letter?', a: 'Google Ads Search Certification (most recognised), Google Analytics 4 Certification, HubSpot Content Marketing Certification, and Meta Blueprint Certification are the most valued. All are free. If you are a fresher, having 2–3 of these certifications puts you significantly ahead of uncertified candidates — mention them in your opening paragraph alongside your campaign results.' },
      { q: 'How should a digital marketing executive show SEO results in a cover letter?', a: 'Be specific: number of keywords ranked on page 1, organic traffic growth (before vs after), time period, and tools used. "Grew organic traffic from 5K to 28K monthly sessions over 12 months using Ahrefs keyword research and content cluster strategy, achieving page-1 rankings for 8 commercial-intent keywords" is the level of specificity that converts to interviews.' },
    ],
  },
  'qa-engineer': {
    dos: [
      'Specify your automation stack: Selenium + Java/Python, Appium, Playwright, Cypress',
      'Lead with a test quality metric: defect detection rate, test coverage, regression cycle time',
      'Reference the testing types in the JD: manual, automation, API, performance, mobile',
      'Mention CI/CD integration: Jenkins, GitHub Actions, GitLab CI',
      'Show API testing depth: Postman, RestAssured, SoapUI',
    ],
    donts: [
      'Don\'t apply for automation roles with only manual testing experience',
      'Avoid claiming automation experience without specifying the framework and scale',
      'Don\'t omit the application type you have tested: web, mobile, API, or embedded',
      'Never ignore bug tracking tools: JIRA, Bugzilla, Azure DevOps — they are screened',
      'Don\'t undervalue test metrics — defect density, coverage %, and cycle time signal QA maturity',
    ],
    keyPoints: [
      'Automation framework and the coverage percentage you achieved',
      'API testing capability and the tools used',
      'CI/CD integration: automated tests in the build pipeline',
      'Test strategy: the types of testing you own in the SDLC',
    ],
    sampleOpening: 'I built [Company]\'s Selenium automation suite from 0 to 94% regression coverage in 8 months, reducing manual regression testing from 3 days to 4 hours per release cycle. Automation that enables teams to ship confidently and fast is what I build.',
    sampleBody: 'As QA Engineer at [Company], I own test strategy for a React/Node.js SaaS application with 50,000 users. My automation suite uses Selenium WebDriver with Java + TestNG, covering 340 test cases across the critical user journeys. I also maintain a Postman collection of 180 API tests integrated into our Jenkins CI pipeline, providing automated API verification on every merge to main. I conduct exploratory testing for complex features, manage our JIRA-based defect lifecycle, and coordinate UAT with business stakeholders. Our deployment defect escape rate has dropped from 8% to 1.2% since I joined and systematised the test process.',
    sampleClosing: 'I am drawn to [Company]\'s quality engineering challenges and the opportunity to build test infrastructure that enables rapid, confident delivery. I would welcome a technical discussion about your current test coverage and CI/CD integration.',
    faqs: [
      { q: 'What automation framework should a QA engineer mention in India?', a: 'Selenium WebDriver with Java is the most widely required combination for Indian IT services and product companies. Cypress and Playwright are growing rapidly for modern JavaScript-heavy applications. For mobile testing, Appium is standard. Mention your primary framework and the language (Java or Python) clearly — it is the first technical filter applied to QA resumes.' },
      { q: 'Should a QA engineer mention performance testing in their cover letter?', a: 'Yes, if you have it — performance testing with JMeter or Gatling is a significant differentiator. Even basic load testing experience (creating test scenarios, identifying bottlenecks, reporting results) is worth mentioning. Full performance engineering capability (scripting, load model design, infrastructure analysis) commands a premium and should be highlighted prominently.' },
    ],
  },
  'bank-po': {
    dos: [
      'Lead with a portfolio metric: CASA portfolio value, loan book managed, business growth achieved',
      'Mention banking systems: Finacle, BaNCS, CBS, Temenos — specific to the target bank',
      'Reference certifications: JAIIB, CAIIB, NISM modules',
      'Show compliance knowledge: KYC, AML, RBI guidelines, POSH',
      'Express genuine interest in the bank\'s products or growth areas',
    ],
    donts: [
      'Don\'t omit portfolio metrics — a banking cover letter without numbers is immediately weak',
      'Avoid listing general banking activities without performance context',
      'Don\'t confuse PSB and private bank application styles — adjust tone accordingly',
      'Never misrepresent regulatory or compliance competence — banks verify credentials rigorously',
      'Don\'t write a long cover letter for PSB applications — keep it formal and factual',
    ],
    keyPoints: [
      'Portfolio managed: CASA, loans, investments with ₹ value',
      'Products sold: specific loan types, insurance, FDs, cross-sell metrics',
      'Systems: specific banking software relevant to the target institution',
      'Compliance: KYC, AML, RBI regulation adherence',
    ],
    sampleOpening: 'In FY24, I managed a CASA portfolio of ₹78Cr across 215 accounts at [Bank Name], achieving 112% of my business target while maintaining zero NPA in my assigned portfolio. Customer acquisition and portfolio quality management are the twin strengths I bring to relationship banking roles.',
    sampleBody: 'As Relationship Manager at [Bank], I service 215 priority banking customers with aggregate CASA and investment balances of ₹78Cr. I cross-sell insurance, mutual funds, home loans, and personal loans, achieving 8 new-to-bank account acquisitions and ₹3.2Cr in loan disbursals monthly on average. I work in Finacle CBS for daily transaction processing, customer profile management, and report generation. I hold JAIIB certification (passed all 3 papers) and an AMFI certification for mutual fund distribution. I am currently pursuing CAIIB to deepen my credit knowledge.',
    sampleClosing: 'I am drawn to [Bank]\'s reputation for [specific strength: retail banking, wealth management, etc.] and the opportunity to contribute to customer portfolio growth in [location]. I would welcome a discussion about your branch\'s current business priorities.',
    faqs: [
      { q: 'Should a banking professional mention NPA management in their cover letter?', a: 'Yes, especially for credit and relationship management roles. Maintaining a clean or low-NPA portfolio signals credit discipline and customer management quality. "Zero NPA in my assigned personal loan portfolio of ₹4.2Cr across 84 accounts" is a strong, concrete credential for banking roles.' },
      { q: 'How formal should a cover letter be for a PSB (public sector bank) application?', a: 'Very formal. PSBs (SBI, Bank of Baroda, Canara Bank) have traditional, hierarchical cultures. Use formal language, state your application clearly ("I wish to apply for the position of..."), list qualifications systematically, and end with "Yours faithfully." Private bank applications can be slightly more conversational while remaining professional.' },
    ],
  },
  'customer-success-manager': {
    dos: [
      'Lead with NRR or churn metric — the metrics that define CSM performance',
      'Reference CSM tools in the JD: Gainsight, Totango, Salesforce, Intercom, ChurnZero',
      'Show commercial awareness: ARR managed, expansion revenue generated, renewal rates',
      'Demonstrate executive relationship skills: QBR experience, C-suite engagement',
      'Express product knowledge specific to the company\'s category (SaaS, fintech, etc.)',
    ],
    donts: [
      'Don\'t apply for CSM roles without retention or expansion metrics — they are table stakes',
      'Avoid confusing technical CS and commercial CS — clarify your scope in the opening',
      'Don\'t claim Gainsight experience without depth — interviewers probe CSP playbook design',
      'Never omit ARR or portfolio context: "managed enterprise accounts" needs the ₹ value',
      'Don\'t write about relationship management without commercial outcomes: renewals, expansions',
    ],
    keyPoints: [
      'NRR and GRR metrics for the portfolio you managed',
      'ARR or portfolio value managed',
      'Churn prevention: a specific at-risk account saved with the ARR value',
      'Expansion revenue generated: upsells and cross-sells with ₹ values',
    ],
    sampleOpening: 'I maintained 114% NRR across a ₹4.2Cr ARR portfolio at [Company] in FY24 — recovering 3 at-risk accounts totalling ₹82L in ARR through executive engagement and tailored success plans. Growing existing customer revenue while protecting the base is the core of what I do as a CSM.',
    sampleBody: 'As Customer Success Manager at [Company], I own a portfolio of 28 mid-market and enterprise SaaS accounts with aggregate ARR of ₹4.2Cr. I manage the full customer lifecycle post-sale: structured onboarding (average time-to-value reduced from 45 to 22 days under my framework), monthly success check-ins, quarterly business reviews with C-suite stakeholders, and annual renewal negotiations. I use Gainsight for health scoring, playbook management, and renewal tracking. In FY24, I expanded 9 accounts generating ₹68L in expansion MRR, and renewed 96% of my portfolio by ARR value.',
    sampleClosing: 'I am drawn to [Company]\'s customer success philosophy and the opportunity to manage a growing enterprise portfolio in [sector]. I would welcome a discussion about your CS team structure, the current customer base, and how I can contribute to NRR growth.',
    faqs: [
      { q: 'What is the most important metric to highlight in a CSM cover letter?', a: 'Net Revenue Retention (NRR). NRR above 100% means you are growing existing customers faster than churn — the gold standard of customer success performance. State the exact NRR you achieved and the portfolio ARR context. If you do not have an exact NRR figure, cite your renewal rate by ARR value and your expansion revenue contribution instead.' },
      { q: 'How should a CSM describe a saved at-risk account in their cover letter?', a: 'Include the ARR at risk, what signals indicated the risk (low engagement, support tickets, champion departure), what intervention you designed (executive sponsor meeting, product training, commercial concession), and the outcome (renewed, expanded, or retained). "Saved ₹34L ARR account that was actively evaluating a competitor by orchestrating a CXO-level product roadmap session and providing 60-day feature commitment" is the level of specificity that demonstrates CSM excellence.' },
    ],
  },
};
