import type { CoverLetterData } from '@/lib/coverLetterData';

// Cover-letter guidance for roles that previously had a CV page but no cover-letter page.
// Sample paragraphs use [placeholders] instead of invented figures.

export const coverLetterDataExtra: Record<string, CoverLetterData> = {
  'full-stack-developer': {
    dos: [
      'Open with a feature you shipped end to end (UI, API and database) rather than a generic statement of interest',
      'Mention the full stack from the job post (e.g. React, Node.js, PostgreSQL) in the first two paragraphs, matching the job post',
      'Name the company and one specific reason you want this team, not just the sector',
      'Keep the letter to three short paragraphs and under 300 words',
      'Close with a specific, confident ask for a conversation',
    ],
    donts: [
      'Don\'t repeat your CV line by line — add the context behind your best result',
      'Avoid openers like "I am writing to apply for" — lead with your result',
      'Don\'t list every skill — pick the three or four the full stack developer job post stresses',
      'Never reuse a letter that names another company',
      'Don\'t mention salary unless the application explicitly asks',
    ],
    keyPoints: [
      'One result that proves you can do the full stack developer job, with a number you can defend',
      'The tools and context that match the role: the full stack from the job post (e.g. React, Node.js, PostgreSQL)',
      'Why this company, referencing something specific you have verified',
      'A short, forward-looking close',
    ],
    sampleOpening: 'I shipped [feature] end to end at [Company] — React frontend, Node.js API and PostgreSQL schema — cutting [metric] by [X]% — the kind of work that drew me to the Full Stack Developer role at [Target Company].',
    sampleBody: 'At [Previous Company], I handled the responsibilities a full stack developer is hired for, including [responsibility 1], [responsibility 2] and [responsibility 3]. A specific example: [project, your contribution and the measurable outcome]. I work with the full stack from the job post (e.g. React, Node.js, PostgreSQL), and I am comfortable collaborating with [teams you work with] to deliver on time.',
    sampleClosing: 'I would welcome the opportunity to discuss how my experience can support [Target Company]\'s goals in this full stack developer role. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do I need a cover letter for a full stack developer job in India?', a: 'It depends on the employer. Product companies and startups often read a short, specific cover letter when it is attached or requested; high-volume hiring may skip it. If the application allows one, a concise, tailored letter is a low-cost way to stand out.' },
      { q: 'What should a full stack developer cover letter include?', a: 'A specific opening result, the key tools or credentials from the job post, a reason you want this company, and a clear closing ask — in three short paragraphs under 300 words.' },
    ],
  },
  'react-developer': {
    dos: [
      'Open with a React app you built or improved, with a performance or UX result rather than a generic statement of interest',
      'Mention React, TypeScript and the state library in the job post in the first two paragraphs, matching the job post',
      'Name the company and one specific reason you want this team, not just the sector',
      'Keep the letter to three short paragraphs and under 300 words',
      'Close with a specific, confident ask for a conversation',
    ],
    donts: [
      'Don\'t repeat your CV line by line — add the context behind your best result',
      'Avoid openers like "I am writing to apply for" — lead with your result',
      'Don\'t list every skill — pick the three or four the react developer job post stresses',
      'Never reuse a letter that names another company',
      'Don\'t mention salary unless the application explicitly asks',
    ],
    keyPoints: [
      'One result that proves you can do the react developer job, with a number you can defend',
      'The tools and context that match the role: React, TypeScript and the state library in the job post',
      'Why this company, referencing something specific you have verified',
      'A short, forward-looking close',
    ],
    sampleOpening: 'I rebuilt [product area] in React and TypeScript at [Company], improving [load time / conversion] by [X]% — the kind of work that drew me to the React Developer role at [Target Company].',
    sampleBody: 'At [Previous Company], I handled the responsibilities a react developer is hired for, including [responsibility 1], [responsibility 2] and [responsibility 3]. A specific example: [project, your contribution and the measurable outcome]. I work with React, TypeScript and the state library in the job post, and I am comfortable collaborating with [teams you work with] to deliver on time.',
    sampleClosing: 'I would welcome the opportunity to discuss how my experience can support [Target Company]\'s goals in this react developer role. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do I need a cover letter for a react developer job in India?', a: 'It depends on the employer. Product companies and startups often read a short, specific cover letter when it is attached or requested; high-volume hiring may skip it. If the application allows one, a concise, tailored letter is a low-cost way to stand out.' },
      { q: 'What should a react developer cover letter include?', a: 'A specific opening result, the key tools or credentials from the job post, a reason you want this company, and a clear closing ask — in three short paragraphs under 300 words.' },
    ],
  },
  'ios-developer': {
    dos: [
      'Open with a shipped App Store app and what you owned in it rather than a generic statement of interest',
      'Mention Swift, SwiftUI/UIKit and your architecture pattern in the first two paragraphs, matching the job post',
      'Name the company and one specific reason you want this team, not just the sector',
      'Keep the letter to three short paragraphs and under 300 words',
      'Close with a specific, confident ask for a conversation',
    ],
    donts: [
      'Don\'t repeat your CV line by line — add the context behind your best result',
      'Avoid openers like "I am writing to apply for" — lead with your result',
      'Don\'t list every skill — pick the three or four the ios developer job post stresses',
      'Never reuse a letter that names another company',
      'Don\'t mention salary unless the application explicitly asks',
    ],
    keyPoints: [
      'One result that proves you can do the ios developer job, with a number you can defend',
      'The tools and context that match the role: Swift, SwiftUI/UIKit and your architecture pattern',
      'Why this company, referencing something specific you have verified',
      'A short, forward-looking close',
    ],
    sampleOpening: 'I shipped [app/feature] on the App Store at [Company] using Swift and SwiftUI, reaching [X] users with a [crash-free / rating] result — the kind of work that drew me to the iOS Developer role at [Target Company].',
    sampleBody: 'At [Previous Company], I handled the responsibilities a ios developer is hired for, including [responsibility 1], [responsibility 2] and [responsibility 3]. A specific example: [project, your contribution and the measurable outcome]. I work with Swift, SwiftUI/UIKit and your architecture pattern, and I am comfortable collaborating with [teams you work with] to deliver on time.',
    sampleClosing: 'I would welcome the opportunity to discuss how my experience can support [Target Company]\'s goals in this ios developer role. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do I need a cover letter for a ios developer job in India?', a: 'It depends on the employer. Consumer app and fintech companies often read a short, specific cover letter when it is attached or requested; high-volume hiring may skip it. If the application allows one, a concise, tailored letter is a low-cost way to stand out.' },
      { q: 'What should a ios developer cover letter include?', a: 'A specific opening result, the key tools or credentials from the job post, a reason you want this company, and a clear closing ask — in three short paragraphs under 300 words.' },
    ],
  },
  'machine-learning-engineer': {
    dos: [
      'Open with a model you took from experiment to production rather than a generic statement of interest',
      'Mention your ML framework, deployment stack and data tools in the first two paragraphs, matching the job post',
      'Name the company and one specific reason you want this team, not just the sector',
      'Keep the letter to three short paragraphs and under 300 words',
      'Close with a specific, confident ask for a conversation',
    ],
    donts: [
      'Don\'t repeat your CV line by line — add the context behind your best result',
      'Avoid openers like "I am writing to apply for" — lead with your result',
      'Don\'t list every skill — pick the three or four the machine learning engineer job post stresses',
      'Never reuse a letter that names another company',
      'Don\'t mention salary unless the application explicitly asks',
    ],
    keyPoints: [
      'One result that proves you can do the machine learning engineer job, with a number you can defend',
      'The tools and context that match the role: your ML framework, deployment stack and data tools',
      'Why this company, referencing something specific you have verified',
      'A short, forward-looking close',
    ],
    sampleOpening: 'I took a [model type] from notebook to production at [Company], serving [use case] and improving [business metric] by [X]% — the kind of work that drew me to the Machine Learning Engineer role at [Target Company].',
    sampleBody: 'At [Previous Company], I handled the responsibilities a machine learning engineer is hired for, including [responsibility 1], [responsibility 2] and [responsibility 3]. A specific example: [project, your contribution and the measurable outcome]. I work with your ML framework, deployment stack and data tools, and I am comfortable collaborating with [teams you work with] to deliver on time.',
    sampleClosing: 'I would welcome the opportunity to discuss how my experience can support [Target Company]\'s goals in this machine learning engineer role. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do I need a cover letter for a machine learning engineer job in India?', a: 'It depends on the employer. Ai-driven product and services companies often read a short, specific cover letter when it is attached or requested; high-volume hiring may skip it. If the application allows one, a concise, tailored letter is a low-cost way to stand out.' },
      { q: 'What should a machine learning engineer cover letter include?', a: 'A specific opening result, the key tools or credentials from the job post, a reason you want this company, and a clear closing ask — in three short paragraphs under 300 words.' },
    ],
  },
  'embedded-systems-engineer': {
    dos: [
      'Open with a firmware or hardware bring-up project with a measurable result rather than a generic statement of interest',
      'Mention your MCU family, RTOS and communication protocols in the first two paragraphs, matching the job post',
      'Name the company and one specific reason you want this team, not just the sector',
      'Keep the letter to three short paragraphs and under 300 words',
      'Close with a specific, confident ask for a conversation',
    ],
    donts: [
      'Don\'t repeat your CV line by line — add the context behind your best result',
      'Avoid openers like "I am writing to apply for" — lead with your result',
      'Don\'t list every skill — pick the three or four the embedded systems engineer job post stresses',
      'Never reuse a letter that names another company',
      'Don\'t mention salary unless the application explicitly asks',
    ],
    keyPoints: [
      'One result that proves you can do the embedded systems engineer job, with a number you can defend',
      'The tools and context that match the role: your MCU family, RTOS and communication protocols',
      'Why this company, referencing something specific you have verified',
      'A short, forward-looking close',
    ],
    sampleOpening: 'I developed firmware for [product] on [MCU] with [RTOS], implementing [CAN/SPI/I2C] drivers and reducing [defects / boot time] by [X]% — the kind of work that drew me to the Embedded Systems Engineer role at [Target Company].',
    sampleBody: 'At [Previous Company], I handled the responsibilities a embedded systems engineer is hired for, including [responsibility 1], [responsibility 2] and [responsibility 3]. A specific example: [project, your contribution and the measurable outcome]. I work with your MCU family, RTOS and communication protocols, and I am comfortable collaborating with [teams you work with] to deliver on time.',
    sampleClosing: 'I would welcome the opportunity to discuss how my experience can support [Target Company]\'s goals in this embedded systems engineer role. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do I need a cover letter for a embedded systems engineer job in India?', a: 'It depends on the employer. Automotive, iot and electronics companies often read a short, specific cover letter when it is attached or requested; high-volume hiring may skip it. If the application allows one, a concise, tailored letter is a low-cost way to stand out.' },
      { q: 'What should a embedded systems engineer cover letter include?', a: 'A specific opening result, the key tools or credentials from the job post, a reason you want this company, and a clear closing ask — in three short paragraphs under 300 words.' },
    ],
  },
  'network-engineer': {
    dos: [
      'Open with a network design, migration or outage-resolution you led rather than a generic statement of interest',
      'Mention your certifications, vendors and protocols in the first two paragraphs, matching the job post',
      'Name the company and one specific reason you want this team, not just the sector',
      'Keep the letter to three short paragraphs and under 300 words',
      'Close with a specific, confident ask for a conversation',
    ],
    donts: [
      'Don\'t repeat your CV line by line — add the context behind your best result',
      'Avoid openers like "I am writing to apply for" — lead with your result',
      'Don\'t list every skill — pick the three or four the network engineer job post stresses',
      'Never reuse a letter that names another company',
      'Don\'t mention salary unless the application explicitly asks',
    ],
    keyPoints: [
      'One result that proves you can do the network engineer job, with a number you can defend',
      'The tools and context that match the role: your certifications, vendors and protocols',
      'Why this company, referencing something specific you have verified',
      'A short, forward-looking close',
    ],
    sampleOpening: 'I led the [migration/upgrade] of [X] sites on [vendor] at [Company], improving uptime and cutting [incident metric] by [X]% — the kind of work that drew me to the Network Engineer role at [Target Company].',
    sampleBody: 'At [Previous Company], I handled the responsibilities a network engineer is hired for, including [responsibility 1], [responsibility 2] and [responsibility 3]. A specific example: [project, your contribution and the measurable outcome]. I work with your certifications, vendors and protocols, and I am comfortable collaborating with [teams you work with] to deliver on time.',
    sampleClosing: 'I would welcome the opportunity to discuss how my experience can support [Target Company]\'s goals in this network engineer role. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do I need a cover letter for a network engineer job in India?', a: 'It depends on the employer. Telecom, it services and enterprise it teams often read a short, specific cover letter when it is attached or requested; high-volume hiring may skip it. If the application allows one, a concise, tailored letter is a low-cost way to stand out.' },
      { q: 'What should a network engineer cover letter include?', a: 'A specific opening result, the key tools or credentials from the job post, a reason you want this company, and a clear closing ask — in three short paragraphs under 300 words.' },
    ],
  },
  'sap-consultant': {
    dos: [
      'Open with an implementation or rollout you worked on, with your module and phase rather than a generic statement of interest',
      'Mention your SAP module, S/4HANA experience and methodology in the first two paragraphs, matching the job post',
      'Name the company and one specific reason you want this team, not just the sector',
      'Keep the letter to three short paragraphs and under 300 words',
      'Close with a specific, confident ask for a conversation',
    ],
    donts: [
      'Don\'t repeat your CV line by line — add the context behind your best result',
      'Avoid openers like "I am writing to apply for" — lead with your result',
      'Don\'t list every skill — pick the three or four the sap consultant job post stresses',
      'Never reuse a letter that names another company',
      'Don\'t mention salary unless the application explicitly asks',
    ],
    keyPoints: [
      'One result that proves you can do the sap consultant job, with a number you can defend',
      'The tools and context that match the role: your SAP module, S/4HANA experience and methodology',
      'Why this company, referencing something specific you have verified',
      'A short, forward-looking close',
    ],
    sampleOpening: 'I configured [SAP module] for a [industry] S/4HANA implementation at [Company], covering blueprint through go-live for [X] users — the kind of work that drew me to the SAP Consultant role at [Target Company].',
    sampleBody: 'At [Previous Company], I handled the responsibilities a sap consultant is hired for, including [responsibility 1], [responsibility 2] and [responsibility 3]. A specific example: [project, your contribution and the measurable outcome]. I work with your SAP module, S/4HANA experience and methodology, and I am comfortable collaborating with [teams you work with] to deliver on time.',
    sampleClosing: 'I would welcome the opportunity to discuss how my experience can support [Target Company]\'s goals in this sap consultant role. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do I need a cover letter for a sap consultant job in India?', a: 'It depends on the employer. It services firms and consulting practices often read a short, specific cover letter when it is attached or requested; high-volume hiring may skip it. If the application allows one, a concise, tailored letter is a low-cost way to stand out.' },
      { q: 'What should a sap consultant cover letter include?', a: 'A specific opening result, the key tools or credentials from the job post, a reason you want this company, and a clear closing ask — in three short paragraphs under 300 words.' },
    ],
  },
  'scrum-master': {
    dos: [
      'Open with a team you coached and the delivery improvement that followed rather than a generic statement of interest',
      'Mention your certifications, frameworks and tooling in the first two paragraphs, matching the job post',
      'Name the company and one specific reason you want this team, not just the sector',
      'Keep the letter to three short paragraphs and under 300 words',
      'Close with a specific, confident ask for a conversation',
    ],
    donts: [
      'Don\'t repeat your CV line by line — add the context behind your best result',
      'Avoid openers like "I am writing to apply for" — lead with your result',
      'Don\'t list every skill — pick the three or four the scrum master job post stresses',
      'Never reuse a letter that names another company',
      'Don\'t mention salary unless the application explicitly asks',
    ],
    keyPoints: [
      'One result that proves you can do the scrum master job, with a number you can defend',
      'The tools and context that match the role: your certifications, frameworks and tooling',
      'Why this company, referencing something specific you have verified',
      'A short, forward-looking close',
    ],
    sampleOpening: 'I coached [X] Scrum teams at [Company], improving [predictability / cycle time] by [X]% through [practice] — the kind of work that drew me to the Scrum Master role at [Target Company].',
    sampleBody: 'At [Previous Company], I handled the responsibilities a scrum master is hired for, including [responsibility 1], [responsibility 2] and [responsibility 3]. A specific example: [project, your contribution and the measurable outcome]. I work with your certifications, frameworks and tooling, and I am comfortable collaborating with [teams you work with] to deliver on time.',
    sampleClosing: 'I would welcome the opportunity to discuss how my experience can support [Target Company]\'s goals in this scrum master role. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do I need a cover letter for a scrum master job in India?', a: 'It depends on the employer. It services and product organisations often read a short, specific cover letter when it is attached or requested; high-volume hiring may skip it. If the application allows one, a concise, tailored letter is a low-cost way to stand out.' },
      { q: 'What should a scrum master cover letter include?', a: 'A specific opening result, the key tools or credentials from the job post, a reason you want this company, and a clear closing ask — in three short paragraphs under 300 words.' },
    ],
  },
  'business-development-manager': {
    dos: [
      'Open with a revenue or pipeline result you owned rather than a generic statement of interest',
      'Mention your vertical, sales motion and CRM in the first two paragraphs, matching the job post',
      'Name the company and one specific reason you want this team, not just the sector',
      'Keep the letter to three short paragraphs and under 300 words',
      'Close with a specific, confident ask for a conversation',
    ],
    donts: [
      'Don\'t repeat your CV line by line — add the context behind your best result',
      'Avoid openers like "I am writing to apply for" — lead with your result',
      'Don\'t list every skill — pick the three or four the business development manager job post stresses',
      'Never reuse a letter that names another company',
      'Don\'t mention salary unless the application explicitly asks',
    ],
    keyPoints: [
      'One result that proves you can do the business development manager job, with a number you can defend',
      'The tools and context that match the role: your vertical, sales motion and CRM',
      'Why this company, referencing something specific you have verified',
      'A short, forward-looking close',
    ],
    sampleOpening: 'I built a [₹X] pipeline in [vertical] at [Company] and closed [X] enterprise accounts through [outbound / partnerships] — the kind of work that drew me to the Business Development Manager role at [Target Company].',
    sampleBody: 'At [Previous Company], I handled the responsibilities a business development manager is hired for, including [responsibility 1], [responsibility 2] and [responsibility 3]. A specific example: [project, your contribution and the measurable outcome]. I work with your vertical, sales motion and CRM, and I am comfortable collaborating with [teams you work with] to deliver on time.',
    sampleClosing: 'I would welcome the opportunity to discuss how my experience can support [Target Company]\'s goals in this business development manager role. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do I need a cover letter for a business development manager job in India?', a: 'It depends on the employer. B2b, saas and services companies often read a short, specific cover letter when it is attached or requested; high-volume hiring may skip it. If the application allows one, a concise, tailored letter is a low-cost way to stand out.' },
      { q: 'What should a business development manager cover letter include?', a: 'A specific opening result, the key tools or credentials from the job post, a reason you want this company, and a clear closing ask — in three short paragraphs under 300 words.' },
    ],
  },
  'sales-executive': {
    dos: [
      'Open with a target you hit or exceeded and how rather than a generic statement of interest',
      'Mention your territory, product category and channel in the first two paragraphs, matching the job post',
      'Name the company and one specific reason you want this team, not just the sector',
      'Keep the letter to three short paragraphs and under 300 words',
      'Close with a specific, confident ask for a conversation',
    ],
    donts: [
      'Don\'t repeat your CV line by line — add the context behind your best result',
      'Avoid openers like "I am writing to apply for" — lead with your result',
      'Don\'t list every skill — pick the three or four the sales executive job post stresses',
      'Never reuse a letter that names another company',
      'Don\'t mention salary unless the application explicitly asks',
    ],
    keyPoints: [
      'One result that proves you can do the sales executive job, with a number you can defend',
      'The tools and context that match the role: your territory, product category and channel',
      'Why this company, referencing something specific you have verified',
      'A short, forward-looking close',
    ],
    sampleOpening: 'I achieved [X]% of target in [territory/product] at [Company], acquiring [X] new accounts through [field visits / calling] — the kind of work that drew me to the Sales Executive role at [Target Company].',
    sampleBody: 'At [Previous Company], I handled the responsibilities a sales executive is hired for, including [responsibility 1], [responsibility 2] and [responsibility 3]. A specific example: [project, your contribution and the measurable outcome]. I work with your territory, product category and channel, and I am comfortable collaborating with [teams you work with] to deliver on time.',
    sampleClosing: 'I would welcome the opportunity to discuss how my experience can support [Target Company]\'s goals in this sales executive role. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do I need a cover letter for a sales executive job in India?', a: 'It depends on the employer. Fmcg, bfsi, retail and consumer companies often read a short, specific cover letter when it is attached or requested; high-volume hiring may skip it. If the application allows one, a concise, tailored letter is a low-cost way to stand out.' },
      { q: 'What should a sales executive cover letter include?', a: 'A specific opening result, the key tools or credentials from the job post, a reason you want this company, and a clear closing ask — in three short paragraphs under 300 words.' },
    ],
  },
  'logistics-manager': {
    dos: [
      'Open with an operations improvement with cost or service numbers rather than a generic statement of interest',
      'Mention your operation type, systems and KPIs in the first two paragraphs, matching the job post',
      'Name the company and one specific reason you want this team, not just the sector',
      'Keep the letter to three short paragraphs and under 300 words',
      'Close with a specific, confident ask for a conversation',
    ],
    donts: [
      'Don\'t repeat your CV line by line — add the context behind your best result',
      'Avoid openers like "I am writing to apply for" — lead with your result',
      'Don\'t list every skill — pick the three or four the logistics manager job post stresses',
      'Never reuse a letter that names another company',
      'Don\'t mention salary unless the application explicitly asks',
    ],
    keyPoints: [
      'One result that proves you can do the logistics manager job, with a number you can defend',
      'The tools and context that match the role: your operation type, systems and KPIs',
      'Why this company, referencing something specific you have verified',
      'A short, forward-looking close',
    ],
    sampleOpening: 'I managed [X] warehouses / a fleet of [X] vehicles at [Company], improving [OTIF / TAT] by [X]% and cutting [cost per shipment] by [X]% — the kind of work that drew me to the Logistics Manager role at [Target Company].',
    sampleBody: 'At [Previous Company], I handled the responsibilities a logistics manager is hired for, including [responsibility 1], [responsibility 2] and [responsibility 3]. A specific example: [project, your contribution and the measurable outcome]. I work with your operation type, systems and KPIs, and I am comfortable collaborating with [teams you work with] to deliver on time.',
    sampleClosing: 'I would welcome the opportunity to discuss how my experience can support [Target Company]\'s goals in this logistics manager role. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do I need a cover letter for a logistics manager job in India?', a: 'It depends on the employer. E-commerce, 3pl and fmcg supply chains often read a short, specific cover letter when it is attached or requested; high-volume hiring may skip it. If the application allows one, a concise, tailored letter is a low-cost way to stand out.' },
      { q: 'What should a logistics manager cover letter include?', a: 'A specific opening result, the key tools or credentials from the job post, a reason you want this company, and a clear closing ask — in three short paragraphs under 300 words.' },
    ],
  },
  'chartered-accountant': {
    dos: [
      'Open with an audit, close or compliance improvement you led rather than a generic statement of interest',
      'Mention your standards (Ind AS/IFRS), taxes and ERP in the first two paragraphs, matching the job post',
      'Name the company and one specific reason you want this team, not just the sector',
      'Keep the letter to three short paragraphs and under 300 words',
      'Close with a specific, confident ask for a conversation',
    ],
    donts: [
      'Don\'t repeat your CV line by line — add the context behind your best result',
      'Avoid openers like "I am writing to apply for" — lead with your result',
      'Don\'t list every skill — pick the three or four the chartered accountant job post stresses',
      'Never reuse a letter that names another company',
      'Don\'t mention salary unless the application explicitly asks',
    ],
    keyPoints: [
      'One result that proves you can do the chartered accountant job, with a number you can defend',
      'The tools and context that match the role: your standards (Ind AS/IFRS), taxes and ERP',
      'Why this company, referencing something specific you have verified',
      'A short, forward-looking close',
    ],
    sampleOpening: 'As a Chartered Accountant with [X] years in [audit/tax/finance] at [Company], I led [process] covering [Ind AS / GST] and reduced [close time / errors] by [X]% — the kind of work that drew me to the Chartered Accountant role at [Target Company].',
    sampleBody: 'At [Previous Company], I handled the responsibilities a chartered accountant is hired for, including [responsibility 1], [responsibility 2] and [responsibility 3]. A specific example: [project, your contribution and the measurable outcome]. I work with your standards (Ind AS/IFRS), taxes and ERP, and I am comfortable collaborating with [teams you work with] to deliver on time.',
    sampleClosing: 'I would welcome the opportunity to discuss how my experience can support [Target Company]\'s goals in this chartered accountant role. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do I need a cover letter for a chartered accountant job in India?', a: 'It depends on the employer. Audit firms, corporates and financial services often read a short, specific cover letter when it is attached or requested; high-volume hiring may skip it. If the application allows one, a concise, tailored letter is a low-cost way to stand out.' },
      { q: 'What should a chartered accountant cover letter include?', a: 'A specific opening result, the key tools or credentials from the job post, a reason you want this company, and a clear closing ask — in three short paragraphs under 300 words.' },
    ],
  },
  'investment-banker': {
    dos: [
      'Open with a transaction you worked on and your role in it rather than a generic statement of interest',
      'Mention your modelling skills, sectors and deal types in the first two paragraphs, matching the job post',
      'Name the company and one specific reason you want this team, not just the sector',
      'Keep the letter to three short paragraphs and under 300 words',
      'Close with a specific, confident ask for a conversation',
    ],
    donts: [
      'Don\'t repeat your CV line by line — add the context behind your best result',
      'Avoid openers like "I am writing to apply for" — lead with your result',
      'Don\'t list every skill — pick the three or four the investment banker job post stresses',
      'Never reuse a letter that names another company',
      'Don\'t mention salary unless the application explicitly asks',
    ],
    keyPoints: [
      'One result that proves you can do the investment banker job, with a number you can defend',
      'The tools and context that match the role: your modelling skills, sectors and deal types',
      'Why this company, referencing something specific you have verified',
      'A short, forward-looking close',
    ],
    sampleOpening: 'I worked on [X] [M&A / capital-markets] transactions in [sector] at [Company], building the [valuation / model] and leading [workstream] — the kind of work that drew me to the Investment Banker role at [Target Company].',
    sampleBody: 'At [Previous Company], I handled the responsibilities a investment banker is hired for, including [responsibility 1], [responsibility 2] and [responsibility 3]. A specific example: [project, your contribution and the measurable outcome]. I work with your modelling skills, sectors and deal types, and I am comfortable collaborating with [teams you work with] to deliver on time.',
    sampleClosing: 'I would welcome the opportunity to discuss how my experience can support [Target Company]\'s goals in this investment banker role. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do I need a cover letter for a investment banker job in India?', a: 'It depends on the employer. Investment banks and advisory boutiques often read a short, specific cover letter when it is attached or requested; high-volume hiring may skip it. If the application allows one, a concise, tailored letter is a low-cost way to stand out.' },
      { q: 'What should a investment banker cover letter include?', a: 'A specific opening result, the key tools or credentials from the job post, a reason you want this company, and a clear closing ask — in three short paragraphs under 300 words.' },
    ],
  },
  'pharmacist': {
    dos: [
      'Open with a patient-safety, compliance or inventory improvement rather than a generic statement of interest',
      'Mention your registration, setting and systems in the first two paragraphs, matching the job post',
      'Name the company and one specific reason you want this team, not just the sector',
      'Keep the letter to three short paragraphs and under 300 words',
      'Close with a specific, confident ask for a conversation',
    ],
    donts: [
      'Don\'t repeat your CV line by line — add the context behind your best result',
      'Avoid openers like "I am writing to apply for" — lead with your result',
      'Don\'t list every skill — pick the three or four the pharmacist job post stresses',
      'Never reuse a letter that names another company',
      'Don\'t mention salary unless the application explicitly asks',
    ],
    keyPoints: [
      'One result that proves you can do the pharmacist job, with a number you can defend',
      'The tools and context that match the role: your registration, setting and systems',
      'Why this company, referencing something specific you have verified',
      'A short, forward-looking close',
    ],
    sampleOpening: 'As a registered pharmacist at [Company], I verified [X] prescriptions daily and introduced [process] that reduced [dispensing errors / stock-outs] by [X]% — the kind of work that drew me to the Pharmacist role at [Target Company].',
    sampleBody: 'At [Previous Company], I handled the responsibilities a pharmacist is hired for, including [responsibility 1], [responsibility 2] and [responsibility 3]. A specific example: [project, your contribution and the measurable outcome]. I work with your registration, setting and systems, and I am comfortable collaborating with [teams you work with] to deliver on time.',
    sampleClosing: 'I would welcome the opportunity to discuss how my experience can support [Target Company]\'s goals in this pharmacist role. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do I need a cover letter for a pharmacist job in India?', a: 'It depends on the employer. Hospitals, retail chains and pharma companies often read a short, specific cover letter when it is attached or requested; high-volume hiring may skip it. If the application allows one, a concise, tailored letter is a low-cost way to stand out.' },
      { q: 'What should a pharmacist cover letter include?', a: 'A specific opening result, the key tools or credentials from the job post, a reason you want this company, and a clear closing ask — in three short paragraphs under 300 words.' },
    ],
  },
  'interior-designer': {
    dos: [
      'Open with a project you designed and delivered, with scope and outcome rather than a generic statement of interest',
      'Mention your software, project types and portfolio in the first two paragraphs, matching the job post',
      'Name the company and one specific reason you want this team, not just the sector',
      'Keep the letter to three short paragraphs and under 300 words',
      'Close with a specific, confident ask for a conversation',
    ],
    donts: [
      'Don\'t repeat your CV line by line — add the context behind your best result',
      'Avoid openers like "I am writing to apply for" — lead with your result',
      'Don\'t list every skill — pick the three or four the interior designer job post stresses',
      'Never reuse a letter that names another company',
      'Don\'t mention salary unless the application explicitly asks',
    ],
    keyPoints: [
      'One result that proves you can do the interior designer job, with a number you can defend',
      'The tools and context that match the role: your software, project types and portfolio',
      'Why this company, referencing something specific you have verified',
      'A short, forward-looking close',
    ],
    sampleOpening: 'I designed and delivered a [residential/commercial] project of [X] sq ft at [Studio], from concept and BOQ to site handover — the kind of work that drew me to the Interior Designer role at [Target Company].',
    sampleBody: 'At [Previous Company], I handled the responsibilities a interior designer is hired for, including [responsibility 1], [responsibility 2] and [responsibility 3]. A specific example: [project, your contribution and the measurable outcome]. I work with your software, project types and portfolio, and I am comfortable collaborating with [teams you work with] to deliver on time.',
    sampleClosing: 'I would welcome the opportunity to discuss how my experience can support [Target Company]\'s goals in this interior designer role. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do I need a cover letter for a interior designer job in India?', a: 'It depends on the employer. Design studios, real-estate and furniture brands often read a short, specific cover letter when it is attached or requested; high-volume hiring may skip it. If the application allows one, a concise, tailored letter is a low-cost way to stand out.' },
      { q: 'What should a interior designer cover letter include?', a: 'A specific opening result, the key tools or credentials from the job post, a reason you want this company, and a clear closing ask — in three short paragraphs under 300 words.' },
    ],
  },
};
