import type { CoverLetterData } from '@/lib/coverLetterData';

interface RoleSeed {
  title: string;
  plural: string;
  proof: string;
  tools: string;
  metric: string;
  keyAsk: string;
  avoid: string;
  opening: string;
  body: string;
  closing: string;
  skipFaq: string;
}

function build(seed: RoleSeed): CoverLetterData {
  return {
    dos: [
      `Open with ${seed.proof} instead of a generic statement of interest`,
      `Name the specific ${seed.tools} that appear in the job description`,
      `Quantify at least one result using ${seed.metric} — use your own real figures`,
      `Show you have read about the employer: mention a product, client segment or initiative by name`,
      `End with a specific ask: ${seed.keyAsk}`,
    ],
    donts: [
      'Don\'t restate your CV line by line — a cover letter should add context the CV cannot',
      'Avoid "I am writing to express my interest" — it wastes your strongest line',
      seed.avoid,
      'Never reuse a letter that names a different company or role',
      'Don\'t exceed one page — three short paragraphs is the target',
    ],
    keyPoints: [
      `One concrete achievement that proves ${seed.proof}`,
      `The ${seed.tools} you have genuinely used, named exactly as the job description spells them`,
      `A measurable outcome expressed in ${seed.metric}`,
      'A clear reason you want this employer, not just this job title',
    ],
    sampleOpening: seed.opening,
    sampleBody: seed.body,
    sampleClosing: seed.closing,
    faqs: [
      {
        q: `Do ${seed.plural} need a cover letter in India?`,
        a: `${seed.skipFaq} A short, specific cover letter helps most when the posting asks for one, when you apply directly to a hiring manager or recruiter, or when your background needs context (career change, gap, relocation). Always follow the application instructions in the posting.`,
      },
      {
        q: `How long should a ${seed.title.toLowerCase()} cover letter be?`,
        a: 'Three short paragraphs and under 300 words, on one page. Paragraph one states your strongest relevant achievement, paragraph two connects your experience to the role requirements, and paragraph three closes with a specific ask. Replace every bracketed placeholder in the sample with your own real details and numbers.',
      },
    ],
  };
}

export const coverLetterDataMore: Record<string, CoverLetterData> = {
  'full-stack-developer': build({
    title: 'Full Stack Developer',
    plural: 'full stack developers',
    proof: 'a feature you shipped end to end, from database schema to UI',
    tools: 'frontend, backend and database technologies',
    metric: 'page load time, API latency, users served or release frequency',
    keyAsk: '"I would welcome a technical conversation about your product roadmap"',
    avoid: 'Don\'t list every framework you have touched — focus on the stack the role actually uses',
    opening: 'At [Company], I built and shipped [feature] end to end — React front end, Node.js API and PostgreSQL schema — which [result, e.g. cut checkout time by X%]. That ownership across the stack is what I want to bring to [Target Company].',
    body: 'In my [X] years as a full stack developer I have designed REST APIs, built responsive interfaces in [React/Next.js], and managed deployments through [Docker/CI-CD]. On [project] I owned the work from requirements to production, including [testing approach] and [monitoring], which resulted in [your measured outcome]. I am comfortable moving between layers, and I pair this with clear communication so product and design teams can ship faster.',
    closing: 'I am keen on [Target Company]\'s [product/initiative] and would welcome a technical conversation about where a full stack engineer could contribute first. Thank you for your time.',
    skipFaq: 'Many large IT services employers screen only the CV, while product companies and startups are more likely to read a cover letter.',
  }),
  'react-developer': build({
    title: 'React Developer',
    plural: 'React developers',
    proof: 'a React application or component library you built and maintained',
    tools: 'React tooling (hooks, state management, testing and build tools)',
    metric: 'Lighthouse scores, bundle size, render performance or reduced UI defects',
    keyAsk: '"I would welcome a code review style conversation about your front-end architecture"',
    avoid: 'Don\'t claim framework expertise you cannot defend in a technical round',
    opening: 'I rebuilt [Company]\'s [dashboard/app] in React and TypeScript, [result, e.g. improving load performance and reducing UI bugs] — the kind of front-end quality work I would like to do at [Target Company].',
    body: 'I work daily with [React hooks, Redux/Zustand/React Query, React Testing Library] and care about accessibility and performance. On [project] I [specific action, e.g. introduced code splitting and memoisation] which led to [your measured outcome]. I collaborate closely with designers and back-end engineers, and I write components that other developers can reuse and test.',
    closing: 'I would be glad to walk you through my work on [project/GitHub link] and discuss how I could support [Target Company]\'s front-end roadmap.',
    skipFaq: 'Startups and product companies often skim a cover letter alongside a GitHub or portfolio link, while bulk-hiring IT services rarely read one.',
  }),
  'ios-developer': build({
    title: 'iOS Developer',
    plural: 'iOS developers',
    proof: 'an app you shipped to the App Store, named with its role in the product',
    tools: 'Swift, SwiftUI or UIKit, and the Apple frameworks',
    metric: 'crash-free sessions, app launch time, App Store rating or active users',
    keyAsk: '"I would welcome the chance to demo my apps and discuss your iOS roadmap"',
    avoid: 'Don\'t describe apps without saying what you personally built or owned',
    opening: 'I shipped [App name] to the App Store as [role], building [feature] in Swift and SwiftUI, and [result, e.g. improving crash-free sessions] — experience I would like to apply to [Target Company]\'s iOS app.',
    body: 'My iOS work covers [SwiftUI/UIKit, Combine or async/await, Core Data, networking, push notifications]. On [project] I [specific action, e.g. migrated a screen to SwiftUI or fixed a launch-time bottleneck], which resulted in [your measured outcome]. I follow Apple\'s Human Interface Guidelines, write unit and UI tests, and have handled App Store review and release processes.',
    closing: 'I would welcome the opportunity to demo my apps and discuss how I can help [Target Company] improve its iOS experience. Thank you for considering my application.',
    skipFaq: 'Product companies and app startups may read a cover letter alongside your App Store links, while larger IT services employers rarely do.',
  }),
  'machine-learning-engineer': build({
    title: 'Machine Learning Engineer',
    plural: 'machine learning engineers',
    proof: 'a model you took from experiment to production',
    tools: 'ML frameworks, data tools and deployment stack',
    metric: 'model accuracy, precision/recall, inference latency or business impact',
    keyAsk: '"I would welcome a discussion about the ML problems your team is solving"',
    avoid: 'Don\'t list algorithms without showing a problem you solved with them',
    opening: 'I took [model/system] from notebook to production at [Company], [result, e.g. improving a business metric by X] — the end-to-end ML engineering I want to bring to [Target Company].',
    body: 'My work spans [data pipelines, feature engineering, training in PyTorch/TensorFlow/scikit-learn, and deployment via Docker/Kubernetes or a managed platform]. On [project] I [specific action, e.g. reduced inference latency or added drift monitoring], leading to [your measured outcome]. I document experiments, track them with [MLflow/Weights & Biases], and work with product teams to define metrics that matter.',
    closing: 'I am interested in [Target Company]\'s work on [problem area] and would welcome a conversation about how I could contribute. Thank you for your time.',
    skipFaq: 'Research-led teams and product companies are more likely to read a cover letter than high-volume recruiters.',
  }),
  'chartered-accountant': build({
    title: 'Chartered Accountant',
    plural: 'chartered accountants',
    proof: 'a specific audit, tax, compliance or finance outcome you delivered',
    tools: 'accounting standards, tax regimes and finance systems (such as Ind AS, GST, Tally, SAP)',
    metric: 'audit findings closed, cost savings, reporting turnaround or compliance accuracy',
    keyAsk: '"I would welcome a discussion about your finance and compliance priorities"',
    avoid: 'Don\'t list articleship duties without stating what you personally delivered',
    opening: 'As a Chartered Accountant with [X] years in [audit/taxation/corporate finance], I [specific outcome, e.g. led a statutory audit close X days faster] — the rigour and delivery I would bring to [Target Company]\'s finance team.',
    body: 'My experience covers [Ind AS/IFRS reporting, GST and income tax compliance, internal controls, budgeting, MIS]. At [Previous Employer] I [specific action], which resulted in [your measured outcome]. I use [Tally/SAP/Excel/Power BI] to automate recurring work and I am used to coordinating with auditors, regulators and business heads under tight deadlines.',
    closing: 'I would welcome the opportunity to discuss how my background can support [Target Company]\'s finance function. Thank you for your consideration.',
    skipFaq: 'Big-four and large corporate recruiters often screen via CV and campus processes, while mid-size firms and direct applications benefit from a brief note.',
  }),
  'sap-consultant': build({
    title: 'SAP Consultant',
    plural: 'SAP consultants',
    proof: 'an SAP implementation, rollout or support engagement you delivered',
    tools: 'SAP modules, versions and tools (such as FI/CO, MM, SD, S/4HANA, ABAP)',
    metric: 'go-live success, tickets resolved within SLA, process time saved or user adoption',
    keyAsk: '"I would welcome a conversation about your SAP landscape and upcoming projects"',
    avoid: 'Don\'t list modules you have only trained in — name those you have configured or supported',
    opening: 'I have delivered [implementation/rollout/support] for [module] on [SAP version] at [Client/Company], [result, e.g. completing go-live on schedule] — the delivery experience I want to bring to [Target Company].',
    body: 'My SAP experience includes [requirements gathering, configuration, testing, data migration, UAT and hypercare] in [FI/CO, MM, SD or other]. On [project] I [specific action], which led to [your measured outcome]. I work comfortably with business users and technical teams, and I document processes so support handovers are clean.',
    closing: 'I would be glad to discuss how my SAP experience fits [Target Company]\'s current and planned projects. Thank you for your time.',
    skipFaq: 'Consulting firms and system integrators often rely on CV-based screening, while direct hiring managers at end clients may read a short note.',
  }),
  'investment-banker': build({
    title: 'Investment Banker',
    plural: 'investment bankers',
    proof: 'a transaction, model or pitch you contributed to, with your specific role',
    tools: 'valuation methods, financial modelling and deal workflow',
    metric: 'deal size, number of transactions supported or modelling turnaround',
    keyAsk: '"I would welcome the chance to discuss how I can support your deal team"',
    avoid: 'Don\'t disclose confidential client or deal details — describe transactions at a level your employer permits',
    opening: 'I supported [type of transaction, e.g. a sell-side mandate] at [Firm], building the [valuation/financial model] and [pitch materials] — the deal execution experience I would bring to [Target Firm].',
    body: 'My work has included [DCF, comparable company and precedent transaction analysis, LBO or merger models, information memoranda, and buyer or investor outreach lists]. On [transaction] I [specific action], contributing to [your measured, non-confidential outcome]. I am comfortable with long hours, tight timelines and attention to detail, and I proof every number twice.',
    closing: 'I would welcome the opportunity to discuss how I can support [Target Firm]\'s deal team. Thank you for your consideration.',
    skipFaq: 'Many banks run structured campus and lateral processes where the CV carries most weight.',
  }),
  'scrum-master': build({
    title: 'Scrum Master',
    plural: 'scrum masters',
    proof: 'a team you coached and the delivery improvement that followed',
    tools: 'Agile frameworks, certifications and tooling (such as Scrum, Kanban, Jira)',
    metric: 'velocity stability, cycle time, sprint goal completion or release predictability',
    keyAsk: '"I would welcome a conversation about your teams and delivery challenges"',
    avoid: 'Don\'t describe the role as ticket administration — show coaching and impact on outcomes',
    opening: 'I coached [team size] engineers at [Company] through [change, e.g. a move to two-week sprints], [result, e.g. making releases more predictable] — the facilitation and coaching I would bring to [Target Company].',
    body: 'As a Scrum Master I facilitate [planning, daily scrum, review and retrospectives], remove impediments, and use [Jira/Azure DevOps] metrics such as cycle time and sprint goal completion to guide improvement. On [project] I [specific action], which led to [your measured outcome]. I hold [PSM/CSM certification, if applicable] and work with product owners to keep backlogs clear and prioritised.',
    closing: 'I would welcome the opportunity to discuss how I can help [Target Company]\'s teams deliver more predictably. Thank you for your time.',
    skipFaq: 'Large IT services employers usually screen via CV, but a short letter helps when you apply directly to an engineering or delivery head.',
  }),
  'business-development-manager': build({
    title: 'Business Development Manager',
    plural: 'business development managers',
    proof: 'a partnership, account or revenue result you personally drove',
    tools: 'sales methods, CRM tools and target segments',
    metric: 'revenue generated, pipeline created, deals closed or new accounts won',
    keyAsk: '"I would welcome a conversation about your growth targets and target segments"',
    avoid: 'Don\'t claim team revenue as your own — separate what you owned from what your team delivered',
    opening: 'At [Company], I [specific outcome, e.g. opened a new customer segment] and generated [your real revenue or pipeline figure] — the growth ownership I want to bring to [Target Company].',
    body: 'My approach combines [prospecting, discovery calls, proposal and negotiation] with disciplined pipeline management in [Salesforce/HubSpot/Zoho]. On [account/project] I [specific action], resulting in [your measured outcome]. I understand the buying process in [industry/segment] and I partner with product and marketing teams to turn conversations into repeatable wins.',
    closing: 'I would welcome the opportunity to discuss how I can contribute to [Target Company]\'s growth plans. Thank you for considering my application.',
    skipFaq: 'Sales hiring is often fast and CV-led, but a specific letter stands out when applying to a founder or sales head.',
  }),
  'sales-executive': build({
    title: 'Sales Executive',
    plural: 'sales executives',
    proof: 'a target you met or exceeded, stated with real numbers',
    tools: 'products, customer segments and CRM tools',
    metric: 'target achievement percentage, revenue, leads converted or customers retained',
    keyAsk: '"I would welcome a conversation about your territory and sales targets"',
    avoid: 'Don\'t exaggerate numbers — interviewers frequently ask you to explain how you reached them',
    opening: 'In my [X] years in sales at [Company], I achieved [your real target percentage] of my target in [period] by [specific approach] — and I would like to bring that drive to [Target Company].',
    body: 'I handle the full sales cycle from lead generation and cold outreach to demos, negotiation and closing, tracking activity in [CRM]. At [Previous Company] I [specific action], which led to [your measured outcome]. I am comfortable with field and inside sales, and I focus on understanding customer needs so recommendations are credible rather than pushy.',
    closing: 'I would welcome the opportunity to discuss how I can help [Target Company] reach its sales goals. Thank you for your time.',
    skipFaq: 'High-volume sales hiring often screens on CV and interview alone.',
  }),
  'network-engineer': build({
    title: 'Network Engineer',
    plural: 'network engineers',
    proof: 'a network design, migration or troubleshooting outcome you delivered',
    tools: 'routing, switching, firewall and monitoring technologies, and certifications (such as CCNA/CCNP)',
    metric: 'uptime, incident resolution time, sites migrated or latency improvements',
    keyAsk: '"I would welcome a conversation about your network environment and priorities"',
    avoid: 'Don\'t list certifications without showing hands-on work that uses them',
    opening: 'I [designed/migrated/stabilised] the network for [scope, e.g. X sites] at [Company], [result, e.g. improving uptime] — the infrastructure reliability I would bring to [Target Company].',
    body: 'My experience covers [routing and switching (OSPF, BGP, VLANs), firewalls, VPNs, wireless and monitoring tools]. On [project] I [specific action], which resulted in [your measured outcome]. I hold [CCNA/CCNP or other certification, if applicable], document changes carefully, and stay calm during incidents.',
    closing: 'I would welcome the opportunity to discuss how I can support [Target Company]\'s network operations. Thank you for your consideration.',
    skipFaq: 'IT services and infrastructure employers usually screen on CV and certifications.',
  }),
  'logistics-manager': build({
    title: 'Logistics Manager',
    plural: 'logistics managers',
    proof: 'a supply chain, transport or warehouse improvement you led',
    tools: 'logistics systems and methods (such as WMS, TMS, route planning)',
    metric: 'on-time delivery rate, cost per shipment, inventory accuracy or turnaround time',
    keyAsk: '"I would welcome a conversation about your network and service-level goals"',
    avoid: 'Don\'t describe duties only — show a cost, speed or service outcome',
    opening: 'At [Company], I [specific outcome, e.g. restructured delivery routes across X hubs], [result, e.g. improving on-time delivery] — the operational improvement I want to bring to [Target Company].',
    body: 'I manage [transport, warehousing, vendor and carrier relationships, and inventory flow] using [WMS/TMS/ERP tools]. On [project] I [specific action], which led to [your measured outcome]. I lead teams on the ground, negotiate with carriers, and use data to find bottlenecks before they affect customers.',
    closing: 'I would welcome the opportunity to discuss how I can strengthen [Target Company]\'s logistics operations. Thank you for your time.',
    skipFaq: 'Many logistics employers hire through CV screening and interviews, but a brief letter helps for senior or operations-head roles.',
  }),
  'interior-designer': build({
    title: 'Interior Designer',
    plural: 'interior designers',
    proof: 'a completed project, with your role from concept to handover',
    tools: 'design software and materials knowledge (such as AutoCAD, SketchUp, 3ds Max)',
    metric: 'projects delivered, budget adherence, client satisfaction or on-time handovers',
    keyAsk: '"I would welcome the chance to walk you through my portfolio"',
    avoid: 'Don\'t send a letter without a portfolio link — design work must be seen',
    opening: 'I designed [project type, e.g. a 3BHK residence] at [Studio] from concept through handover, [result, e.g. delivering on time and within budget] — the end-to-end delivery I would bring to [Target Studio].',
    body: 'My process covers [client briefing, space planning, 3D visualisation in SketchUp/3ds Max, working drawings in AutoCAD, vendor coordination and site supervision]. On [project] I [specific action], which resulted in [your measured outcome]. My portfolio at [link] shows [relevant project types].',
    closing: 'I would welcome the opportunity to walk you through my portfolio and discuss how I can contribute to [Target Studio]. Thank you for your consideration.',
    skipFaq: 'Design studios decide mostly on portfolio, so the letter matters most as a short, personal introduction.',
  }),
  'pharmacist': build({
    title: 'Pharmacist',
    plural: 'pharmacists',
    proof: 'a dispensing, compliance, clinical or quality responsibility you handled',
    tools: 'pharmacy systems, regulations and licences (such as State Pharmacy Council registration, GMP/GDP)',
    metric: 'prescriptions handled, audit results, error reduction or inventory accuracy',
    keyAsk: '"I would welcome the opportunity to discuss the role and your pharmacy operations"',
    avoid: 'Don\'t omit your registration details — employers need to confirm your licence status',
    opening: 'As a registered pharmacist (registration no. [number], [State] Pharmacy Council) with [X] years in [hospital/retail/industry] pharmacy, I [specific responsibility or outcome] — the accuracy and patient focus I would bring to [Target Employer].',
    body: 'My experience includes [dispensing, patient counselling, inventory and expiry management, regulatory documentation, and pharmacovigilance or quality tasks as relevant]. At [Previous Employer] I [specific action], which led to [your measured outcome]. I follow documented procedures carefully and communicate clearly with doctors, nurses and patients.',
    closing: 'I would welcome the opportunity to discuss how I can support [Target Employer]. Thank you for your time and consideration.',
    skipFaq: 'Hospitals and pharma companies often screen on registration, degree and experience.',
  }),
  'embedded-systems-engineer': build({
    title: 'Embedded Systems Engineer',
    plural: 'embedded systems engineers',
    proof: 'a firmware or hardware-software product you built and brought to release',
    tools: 'microcontrollers, languages and protocols (such as C/C++, RTOS, I2C, SPI, UART, CAN)',
    metric: 'memory footprint, boot time, power consumption or defect rate',
    keyAsk: '"I would welcome a technical conversation about your hardware and firmware stack"',
    avoid: 'Don\'t list boards and protocols without saying what you built with them',
    opening: 'I wrote the firmware for [product] on [microcontroller] in C, [result, e.g. reducing power consumption or boot time] — the low-level engineering I would like to bring to [Target Company].',
    body: 'My work covers [C/C++, RTOS, device drivers, communication protocols such as I2C/SPI/UART/CAN, debugging with oscilloscopes and logic analysers]. On [project] I [specific action], which resulted in [your measured outcome]. I work closely with hardware and test teams and document interfaces clearly.',
    closing: 'I would welcome a technical conversation about [Target Company]\'s embedded products and where I could contribute. Thank you for your time.',
    skipFaq: 'Hardware and automotive employers frequently screen on technical CV content and tests first.',
  }),
};
