import type { CoverLetterData } from '@/lib/coverLetterData';

// Sample paragraphs use placeholders and illustrative figures — candidates must replace
// them with their own verified achievements.
export const coverLetterDataMore: Record<string, CoverLetterData> = {
  'sales-executive': {
    dos: [
      'Open with a target-achievement figure, such as quota attained or revenue closed',
      'Name the product category, customer segment and territory you have sold into',
      'Mention the CRM or sales tools you use and how you keep pipeline data clean',
      'Show how you generate leads yourself rather than waiting for them',
      'Close by proposing a conversation about the territory or targets for the role',
    ],
    donts: [
      'Don’t say you are “a people person” without evidence of results',
      'Avoid exaggerated claims — recruiters verify sales numbers in references',
      'Don’t send the same letter to every company; reference their product and customers',
      'Never criticise a former employer’s targets or product',
      'Don’t push salary demands in the first letter',
    ],
    keyPoints: [
      'One quarter or year where you exceeded target, with the percentage',
      'Your sales approach: prospecting method, follow-up discipline, objection handling',
      'Familiarity with the customer segment the company sells to',
      'Willingness to travel or work a field territory if the role requires it',
    ],
    sampleOpening: 'Last financial year I closed 118% of my annual target selling [Product] across [Territory] for [Company], and I would like to bring the same follow-through to the Sales Executive role at [Target Company].',
    sampleBody: 'At [Company] I manage around [N] active accounts in [Territory], mixing cold outreach, field visits and distributor follow-ups. I log every interaction in [CRM], which helped me spot that repeat orders dropped after 60 days of silence; a simple reorder call cadence recovered [X]% of those accounts. I enjoy consultative selling — understanding the customer’s margin and stock problems before proposing a plan — and I am comfortable handling price objections without discounting by default.',
    sampleClosing: 'I would welcome the chance to discuss the territory, targets and onboarding plan for this role. I am ready to start with a field-visit plan for the first 30 days.',
    faqs: [
      { q: 'Do sales executives need a cover letter in India?', a: 'It is often optional for high-volume hiring, but a short, results-led cover letter helps in competitive roles such as B2B, SaaS, BFSI and FMCG. Keep it brief and centred on numbers.' },
      { q: 'What should a fresher sales executive write in a cover letter?', a: 'Use internships, campus drives, college events or part-time selling as evidence. Mention a concrete outcome — units sold, sign-ups gained or funds raised — and show enthusiasm for field work and targets.' },
    ],
  },
  'ios-developer': {
    dos: [
      'Link your App Store apps or TestFlight builds in the first paragraph',
      'State the Swift, SwiftUI or UIKit stack you work in and the iOS versions supported',
      'Quantify user impact: crash-free rate, load time, retention or rating improvements',
      'Mention architecture patterns you have used, such as MVVM, Clean Architecture or modularisation',
      'Reference something specific about the company’s app and what you would improve or build',
    ],
    donts: [
      'Don’t list every framework you have touched; focus on those in the job description',
      'Avoid writing “passionate about Apple products” without evidence of shipped work',
      'Don’t repeat your CV line by line',
      'Never claim App Store ownership you cannot show',
      'Don’t exceed one page',
    ],
    keyPoints: [
      'One shipped feature with a measurable outcome',
      'Experience with app performance, accessibility or release processes',
      'Familiarity with testing and CI/CD for mobile',
      'Collaboration with design, backend and QA teams',
    ],
    sampleOpening: 'I led the SwiftUI migration of [App]’s onboarding and payments flows, cutting crash rates by [X]% and lifting the App Store rating from [A] to [B] — exactly the kind of product ownership I hope to bring to [Target Company]’s iOS team.',
    sampleBody: 'Over [N] years at [Company] I have built and shipped iOS features used by [N]+ users, working in Swift with SwiftUI and UIKit, MVVM and Combine and async/await for concurrency. I introduced a modular package structure that reduced build times by [X]%, set up Fastlane-based releases and added snapshot and unit tests that caught regressions before review. I care about the details users notice: smooth scrolling, accessibility support and thoughtful offline behaviour.',
    sampleClosing: 'I would be glad to walk through my apps and discuss how I could contribute to [Target Company]’s roadmap. Thank you for considering my application.',
    faqs: [
      { q: 'Should an iOS developer include App Store links in a cover letter?', a: 'Yes. A live app link or TestFlight demo is the strongest proof of skill and lets the reader verify your work immediately.' },
      { q: 'How long should an iOS developer cover letter be?', a: 'Three short paragraphs and under 300 words. Engineering managers prefer concise letters that highlight shipped apps and measurable outcomes.' },
    ],
  },
  'full-stack-developer': {
    dos: [
      'Name the stack from the job description in your first paragraph',
      'Describe one feature you owned end to end, from database design to deployment',
      'Quantify results: latency, uptime, users served or deployment time saved',
      'Show collaboration with design, product and QA',
      'Link a GitHub repository or live project',
    ],
    donts: [
      'Don’t present yourself as an expert in every technology you have ever used',
      'Avoid generic claims like “quick learner” without an example',
      'Don’t paste your CV’s project list into the letter',
      'Never send a letter naming a different company or stack',
      'Don’t write more than three short paragraphs',
    ],
    keyPoints: [
      'A project that shows both frontend and backend ownership',
      'Your approach to testing, deployment and monitoring',
      'Evidence of prioritising user-facing impact',
      'Interest in the company’s product and engineering culture',
    ],
    sampleOpening: 'I recently built and shipped [Product] solo — a React and Node.js application with PostgreSQL that serves [N] users — and I am excited to bring that end-to-end ownership to the Full Stack Developer role at [Target Company].',
    sampleBody: 'At [Company] I own features across the stack: React and TypeScript on the frontend, Node.js and Express services, and PostgreSQL with carefully designed schemas. I reduced a slow dashboard query from [A]s to [B]s by adding indexes and caching, and set up a CI/CD pipeline on GitHub Actions with Docker so releases take minutes instead of hours. I enjoy working closely with designers and product managers to ship in small, testable increments.',
    sampleClosing: 'I would welcome the opportunity to discuss how my full-stack experience can support [Target Company]’s product goals. Thank you for your time.',
    faqs: [
      { q: 'What should a full stack developer highlight in a cover letter?', a: 'Highlight a project where you owned both frontend and backend decisions, the stack you used, and a measurable result. Employers want proof that you can deliver features end to end.' },
      { q: 'Do freshers need a cover letter for full stack roles?', a: 'A short letter is useful for freshers because it lets you point to projects, internships and open-source work that a CV can only list. Include a GitHub link.' },
    ],
  },
  'machine-learning-engineer': {
    dos: [
      'Lead with a model you put into production and the business metric it moved',
      'Mention data scale, latency or cost constraints you worked within',
      'Name your stack: Python, PyTorch or TensorFlow, MLflow, Docker, cloud ML services',
      'Describe how you evaluate and monitor models after deployment',
      'Show awareness of the company’s data or ML problem space',
    ],
    donts: [
      'Don’t only list algorithms; explain the problem and the outcome',
      'Avoid claiming deep-learning expertise you cannot discuss in interview',
      'Don’t rely on Kaggle scores as your only evidence of impact',
      'Never overstate accuracy numbers without describing the baseline',
      'Don’t forget to mention deployment, not just training',
    ],
    keyPoints: [
      'One production model with before-and-after metrics',
      'MLOps experience: pipelines, monitoring, retraining',
      'Collaboration with data engineers, product and backend teams',
      'Awareness of data quality, bias and evaluation limits',
    ],
    sampleOpening: 'I built and deployed a ranking model at [Company] that improved click-through by [X]% while holding p95 latency under [N] ms — the kind of production ML work I would like to continue as an ML Engineer at [Target Company].',
    sampleBody: 'My work covers the full ML lifecycle: feature engineering on [N]M+ rows, training in PyTorch, experiment tracking with MLflow, packaging with Docker and serving through [framework] on [cloud]. After launch I added drift monitoring and a retraining schedule, which caught a data pipeline issue before it affected users. I focus on a clear baseline, honest evaluation and keeping infrastructure costs predictable.',
    sampleClosing: 'I would welcome a conversation about the models and data challenges your team is tackling and where I could help. Thank you for your consideration.',
    faqs: [
      { q: 'What makes a strong machine learning engineer cover letter?', a: 'A concrete production result with its metric, a short description of how you deploy and monitor models, and a clear link between your experience and the company’s problem. Avoid listing algorithms without outcomes.' },
      { q: 'Can I apply for ML engineer roles with only academic projects?', a: 'Yes, if you frame the projects like production work: the problem, data, baseline, evaluation and any deployment. Link code and results, and show you understand what production would require.' },
    ],
  },
  'chartered-accountant': {
    dos: [
      'State your CA qualification date and attempt details only if they strengthen your profile',
      'Highlight the engagement types you handled: statutory audit, tax, transfer pricing, due diligence',
      'Mention frameworks and systems: Ind AS, IFRS, GST, SAP, Tally',
      'Give a measurable outcome, such as cost savings, audit findings resolved or closing timelines cut',
      'Explain why you are moving to industry or to this firm',
    ],
    donts: [
      'Don’t simply restate your articleship; describe what you learned and delivered',
      'Avoid jargon-heavy paragraphs that bury the main point',
      'Don’t mention confidential client details',
      'Never leave out your membership status or registration',
      'Don’t write more than one page',
    ],
    keyPoints: [
      'Industries or client types you have worked with',
      'A process improvement or compliance outcome you led',
      'Technical depth in the area the role needs',
      'Professionalism and ethics, which hiring managers expect from CAs',
    ],
    sampleOpening: 'As a Chartered Accountant with [N] years of statutory audit and Ind AS reporting experience at [Firm], I am keen to bring rigorous financial reporting to the [Role] position at [Target Company].',
    sampleBody: 'At [Firm] I led audits for clients across [sectors], including a group consolidation with [N] entities. I identified a revenue recognition issue that prevented a material misstatement and helped a client shorten its monthly close from [A] to [B] days by standardising reconciliations in SAP. I am comfortable with GST, tax audits and IFRS conversions, and I communicate findings clearly to both finance teams and senior management.',
    sampleClosing: 'I would value the opportunity to discuss how my audit and reporting background can support [Target Company]’s finance function. Thank you for your time.',
    faqs: [
      { q: 'Do chartered accountants need a cover letter?', a: 'Yes for corporate, banking and consulting roles, where a concise cover letter explaining your specialisation and motivation adds context beyond the CV.' },
      { q: 'How should a newly qualified CA write a cover letter?', a: 'Focus on articleship exposure, the clients and engagements you handled, technical strengths and your readiness to take responsibility. Be specific about the area you want to grow in.' },
    ],
  },
  'sap-consultant': {
    dos: [
      'State your SAP module and S/4HANA version experience in the first sentence',
      'Mention the number of full implementations, rollouts or migrations you took part in',
      'Describe your role: requirements, configuration, testing, cutover or hypercare',
      'Quantify business benefits delivered, such as close time or process automation',
      'Include relevant SAP certifications',
    ],
    donts: [
      'Don’t list every SAP module you have glanced at',
      'Avoid vague phrases like “worked on SAP” without module and project detail',
      'Don’t name confidential client data',
      'Never exaggerate your role on a large programme',
      'Don’t skip the business context of the project',
    ],
    keyPoints: [
      'Industry and scale of the implementation',
      'Your contribution to design, testing and go-live',
      'Experience working with business users and developers',
      'Familiarity with SAP Activate or ASAP methodology',
    ],
    sampleOpening: 'As an SAP FICO consultant with [N] years across two S/4HANA implementations and one ECC migration, I am eager to contribute to [Target Company]’s finance transformation as your next SAP Consultant.',
    sampleBody: 'On my most recent programme at [Client], I was responsible for gathering requirements, configuring general ledger, accounts payable and receivable, and leading user acceptance testing for [N] company codes. I documented the cutover plan, supported go-live and managed hypercare, closing [N] tickets in the first month. The new design reduced manual reconciliation effort by [X]% and improved month-end visibility for finance leadership.',
    sampleClosing: 'I would welcome the chance to discuss your SAP roadmap and where my module and project experience can help. Thank you for considering my application.',
    faqs: [
      { q: 'What should an SAP consultant mention in a cover letter?', a: 'Your module, S/4HANA experience, number of implementations, your role at each project phase and a quantified business result. Add certifications if you hold them.' },
      { q: 'Should a functional SAP consultant mention technical skills?', a: 'Yes, briefly. Familiarity with ABAP debugging, Fiori or integration helps functional consultants collaborate with technical teams, but keep the focus on your module and project contribution.' },
    ],
  },
  'react-developer': {
    dos: [
      'Link a live project or GitHub repository in the first paragraph',
      'Mention React, TypeScript and the tooling named in the job description',
      'Quantify performance or UX improvements, such as Lighthouse scores or load time',
      'Describe how you test components and manage state',
      'Show interest in the company’s product and its user experience',
    ],
    donts: [
      'Don’t list every library you have installed',
      'Avoid saying “I love frontend” without a project to back it up',
      'Don’t forget to mention TypeScript if the role expects it',
      'Never send a letter that ignores the company’s product',
      'Don’t write more than three short paragraphs',
    ],
    keyPoints: [
      'A shipped feature and its user impact',
      'Performance, accessibility or design-system work',
      'Testing approach and code review habits',
      'Collaboration with designers and backend engineers',
    ],
    sampleOpening: 'I cut the initial load time of [Product]’s dashboard from [A]s to [B]s by code-splitting and moving heavy components to server rendering in Next.js — the kind of frontend performance work I would like to do as a React Developer at [Target Company].',
    sampleBody: 'At [Company] I build React and TypeScript interfaces used by [N]+ users, with Redux Toolkit and React Query for state and data fetching. I contributed to our design system, wrote Jest and React Testing Library tests that raised coverage from [A]% to [B]%, and fixed accessibility issues that raised our audit score. I enjoy reviewing code, improving DX and working closely with designers to get details right.',
    sampleClosing: 'I would be glad to show you my work and discuss how I can help improve [Target Company]’s frontend. Thank you for your time.',
    faqs: [
      { q: 'What should a React developer put in a cover letter?', a: 'A project link, your React and TypeScript experience, one measurable improvement (performance, conversion, bugs) and why the company’s product interests you.' },
      { q: 'Is a portfolio necessary for React roles?', a: 'It is not mandatory, but a portfolio or well-documented repository is the strongest evidence of skill, especially for freshers and career switchers.' },
    ],
  },
  'investment-banker': {
    dos: [
      'Lead with transaction experience: deal type, size and your role',
      'Name the sectors and products you have covered',
      'Mention modelling and valuation skills such as DCF, LBO and comparable analysis',
      'Show familiarity with the firm’s recent deals and positioning',
      'Keep a formal, precise tone',
    ],
    donts: [
      'Don’t disclose confidential deal information that has not been made public',
      'Avoid generic “passion for finance” lines',
      'Don’t overstate your role in team-led transactions',
      'Never include typos — attention to detail is itself a screening test',
      'Don’t go beyond one page',
    ],
    keyPoints: [
      'Deal exposure with size, sector and outcome',
      'Technical skills and the work product you owned (models, pitchbooks)',
      'Fit with the firm’s sector coverage',
      'Ability to work under tight deadlines',
    ],
    sampleOpening: 'Having supported [N] M&A and capital-markets transactions totalling over ₹[X] crore at [Firm], I am applying for the [Level] position at [Target Company] to contribute to your [sector] coverage.',
    sampleBody: 'In my current role I build DCF, LBO and merger models, prepare pitchbooks and run diligence workstreams. On a recent [sector] transaction, I led the financial model and valuation analysis that supported the client’s negotiation, and I coordinated with legal and accounting advisers to keep the timetable on track. I take pride in accuracy, speed and clear communication with senior bankers and clients.',
    sampleClosing: 'I would welcome the chance to discuss how I can support your team’s upcoming mandates. Thank you for your consideration.',
    faqs: [
      { q: 'Do investment bankers need cover letters in India?', a: 'Often yes, particularly for campus, lateral and boutique applications. The letter should be short, precise and focused on deals, technical skills and why you want that specific firm.' },
      { q: 'How can a fresher write an investment banking cover letter?', a: 'Use finance internships, valuation projects, case competitions and certifications such as CFA progress. Show knowledge of the firm’s deals and a clear reason for choosing investment banking.' },
    ],
  },
  'scrum-master': {
    dos: [
      'Open with a team outcome you improved: predictability, cycle time or quality',
      'State certifications such as PSM, CSM or SAFe and the frameworks you use',
      'Describe the size and number of teams you have served',
      'Show how you handle impediments, stakeholders and conflicts',
      'Mention tools like Jira, Confluence or Azure DevOps',
    ],
    donts: [
      'Don’t define Scrum; assume the reader knows it',
      'Avoid listing ceremonies without results',
      'Don’t present yourself as a project manager unless the role asks for it',
      'Never blame teams or stakeholders in examples',
      'Don’t exceed one page',
    ],
    keyPoints: [
      'A change you introduced and its measurable effect',
      'Coaching and facilitation experience',
      'Working with product owners and leadership',
      'Experience in distributed or scaled agile setups',
    ],
    sampleOpening: 'Over the last year, the two teams I serve as Scrum Master at [Company] improved sprint predictability from [A]% to [B]% — an outcome I would like to bring to [Target Company].',
    sampleBody: 'I facilitate planning, reviews and retrospectives for teams of [N] engineers, track flow metrics in Jira and coach product owners on backlog refinement. When a recurring dependency kept blocking delivery, I set up a weekly cross-team sync that cut waiting time by [X]%. I hold a [certification] and enjoy helping teams own their process rather than follow it mechanically.',
    sampleClosing: 'I would value the opportunity to discuss how I can support [Target Company]’s teams and delivery goals. Thank you for your time.',
    faqs: [
      { q: 'What should a Scrum Master mention in a cover letter?', a: 'A measurable team improvement, your certification, the number and size of teams served and your approach to coaching and impediment removal.' },
      { q: 'Should I mention project management experience as a Scrum Master?', a: 'Yes if it is relevant, but frame it as supporting flow and stakeholder alignment rather than command-and-control, because Scrum Master roles emphasise facilitation and coaching.' },
    ],
  },
  'business-development-manager': {
    dos: [
      'Open with revenue or pipeline you generated and the deal size',
      'Describe the markets, industries and buyer personas you target',
      'Mention your prospecting method, sales cycle and tools',
      'Show strategic partnership or account-expansion wins',
      'Tie your experience to the company’s growth stage and product',
    ],
    donts: [
      'Don’t quote revenue you cannot verify',
      'Avoid saying you “build relationships” without examples',
      'Don’t send a generic letter to every company',
      'Never disparage competitors or past employers',
      'Don’t write more than three short paragraphs',
    ],
    keyPoints: [
      'Closed-won revenue and quota attainment',
      'Experience opening new accounts or markets',
      'Familiarity with the company’s sales model, such as SaaS or enterprise',
      'Collaboration with marketing, product and customer success',
    ],
    sampleOpening: 'In the past 18 months I opened [N] new enterprise accounts and closed ₹[X] crore in revenue at [Company], and I would like to bring that growth focus to [Target Company] as Business Development Manager.',
    sampleBody: 'I run the full sales cycle from prospecting through LinkedIn Sales Navigator and referrals to negotiation and contract closure, managing a pipeline of ₹[Y] crore in [CRM]. A partnership I built with [type of partner] now contributes [X]% of new leads. I work closely with product and customer success so that accounts I win expand rather than churn.',
    sampleClosing: 'I would welcome the opportunity to discuss your growth priorities and how I could help achieve them. Thank you for considering my application.',
    faqs: [
      { q: 'What should a business development manager emphasise in a cover letter?', a: 'Revenue, new accounts and partnerships you created, with figures. Show you understand the company’s market and can open doors, not just manage existing relationships.' },
      { q: 'Should I mention salary in a business development cover letter?', a: 'Not unless asked. Focus on value delivered and discuss compensation after the employer has shown interest.' },
    ],
  },
  'network-engineer': {
    dos: [
      'State your certifications (CCNA, CCNP, CCIE) near the beginning',
      'Describe the network scale you manage: sites, devices, users, uptime',
      'Mention routing, switching, firewall and WAN technologies you have worked with',
      'Give an incident or project outcome, such as downtime reduced or migration completed',
      'Show interest in automation and security',
    ],
    donts: [
      'Don’t list only device models without describing what you did',
      'Avoid unexplained acronyms outside the job description',
      'Don’t overlook security experience',
      'Never claim hands-on skills you cannot demonstrate',
      'Don’t write more than one page',
    ],
    keyPoints: [
      'Network size and criticality',
      'Troubleshooting approach and incident ownership',
      'Experience with change windows and documentation',
      'Willingness for on-call or shift-based support if required',
    ],
    sampleOpening: 'As a CCNP-certified network engineer managing a [N]-site WAN with 99.9% uptime at [Company], I am applying for the Network Engineer role at [Target Company].',
    sampleBody: 'My responsibilities include BGP and OSPF routing, MPLS and SD-WAN connectivity and Palo Alto firewall policies. I recently led a branch migration to SD-WAN, which reduced link costs by [X]% and cut provisioning time from [A] days to [B]. I automate repetitive configuration checks with Python and document every change so that on-call teams can troubleshoot quickly.',
    sampleClosing: 'I would be glad to discuss how my experience fits your network and security roadmap. Thank you for your time.',
    faqs: [
      { q: 'Do network engineers need a cover letter?', a: 'It is often optional, but a short letter helps for roles at enterprises, telecoms and data centres where your certifications and incident experience need context.' },
      { q: 'What should a fresher network engineer include?', a: 'Lab projects, CCNA preparation or certification, internships and any home-lab or simulation work (Packet Tracer, GNS3), plus your interest in troubleshooting and automation.' },
    ],
  },
  'logistics-manager': {
    dos: [
      'Lead with operations metrics: on-time delivery, cost per shipment, damage rate',
      'State the scale you manage: fleet size, warehouses, shipments per day, team size',
      'Mention WMS/TMS tools and process-improvement methods',
      'Describe cost savings or service improvements you delivered',
      'Show knowledge of the company’s network and customers',
    ],
    donts: [
      'Don’t write only about duties; show results',
      'Avoid vague phrases such as “hardworking and dedicated”',
      'Don’t ignore safety and compliance',
      'Never exaggerate the scale of operations you ran',
      'Don’t exceed one page',
    ],
    keyPoints: [
      'Scale and complexity of operations',
      'Cost, speed or reliability improvements',
      'People and vendor management',
      'Use of technology and data to optimise routes and inventory',
    ],
    sampleOpening: 'At [Company] I manage a [N]-vehicle fleet and a [N] sq ft warehouse handling [N] shipments a day, and last year I raised on-time delivery from [A]% to [B]% while cutting cost per shipment by [X]%.',
    sampleBody: 'I optimised routes with our TMS, renegotiated rates with 3PL partners and introduced daily dashboards that exposed bottlenecks at the dock. I lead a team of [N] supervisors and drivers, and I focus on safety, accurate inventory and clear escalation paths. I am comfortable working with sales and procurement to match capacity to demand during peak seasons.',
    sampleClosing: 'I would welcome the opportunity to discuss how I can help [Target Company] improve reliability and cost in its logistics network. Thank you for your consideration.',
    faqs: [
      { q: 'What should a logistics manager highlight in a cover letter?', a: 'Operational scale, service and cost improvements with figures, the systems you use and your ability to manage people and vendors.' },
      { q: 'Is a cover letter needed for supply chain and logistics roles?', a: 'It is helpful for managerial positions, where it can summarise your impact more clearly than a CV and explain your fit with the company’s network.' },
    ],
  },
  'interior-designer': {
    dos: [
      'Link your portfolio in the first paragraph',
      'Describe the types of projects you have completed: residential, commercial, hospitality',
      'Mention software skills: AutoCAD, SketchUp, 3ds Max, V-Ray, Revit',
      'Show that you can handle budgets, vendors and site coordination',
      'Reference the studio’s style or a project you admire and why',
    ],
    donts: [
      'Don’t send a letter without a portfolio link',
      'Avoid generic phrases about “creative passion”',
      'Don’t claim credit for team projects without specifying your role',
      'Never use client details without permission',
      'Don’t write more than one page',
    ],
    keyPoints: [
      'Your design approach and how you work with clients',
      'Project scale, budget and timeline handled',
      'Technical drawing and 3D visualisation strength',
      'Site coordination and vendor management experience',
    ],
    sampleOpening: 'My portfolio at [link] includes [N] completed residential and commercial interiors, including a [size] sq ft office delivered on budget and two weeks early. I would like to bring that attention to detail to [Target Company] as Interior Designer.',
    sampleBody: 'I prepare space plans, working drawings and 3D visualisations in AutoCAD, SketchUp and V-Ray, and I prepare BOQs that clients can approve with confidence. On site, I coordinate carpenters, electricians and vendors to keep quality and timelines intact. I enjoy balancing client preferences with function, materials and budget.',
    sampleClosing: 'I would be glad to walk you through my portfolio and discuss how I can contribute to your upcoming projects. Thank you for your time.',
    faqs: [
      { q: 'Should an interior designer attach a portfolio with a cover letter?', a: 'Yes. Include a link or attached PDF. The portfolio is the primary evidence of your skill, and the cover letter should guide the reader to its most relevant projects.' },
      { q: 'What should a fresher interior designer write?', a: 'Highlight academic projects, internships, software skills and any live site exposure. Show how you would learn from the studio and contribute from day one.' },
    ],
  },
  'pharmacist': {
    dos: [
      'State your registration and qualification (D.Pharm, B.Pharm, M.Pharm, Pharm.D)',
      'Describe the setting: hospital, retail, clinical, pharma company or CRO',
      'Mention compliance, accuracy and patient-counselling experience',
      'Include relevant systems: pharmacy software, safety databases, inventory systems',
      'Show interest in the specific role and organisation',
    ],
    donts: [
      'Don’t forget to mention your registration number or status',
      'Avoid vague statements about “helping people” without examples',
      'Don’t disclose patient information',
      'Never overstate clinical responsibilities',
      'Don’t write more than one page',
    ],
    keyPoints: [
      'Dispensing accuracy and regulatory compliance',
      'Patient counselling or clinical interventions',
      'Inventory, expiry and cost control',
      'Teamwork with doctors, nurses and suppliers',
    ],
    sampleOpening: 'As a registered pharmacist with [N] years at [Hospital], where I managed dispensing for a [N]-bed unit with zero audit non-compliances, I am applying for the Pharmacist role at [Target Company].',
    sampleBody: 'I verify prescriptions, check drug interactions, counsel patients on correct use and maintain inventory with careful expiry tracking, which cut wastage by [X]% last year. I follow schedule and documentation requirements closely and collaborate with doctors and nurses to resolve queries quickly. I am keen to keep developing in areas such as clinical pharmacy and pharmacovigilance.',
    sampleClosing: 'I would value the chance to discuss how my experience can support your pharmacy team. Thank you for considering my application.',
    faqs: [
      { q: 'What should a pharmacist include in a cover letter?', a: 'Registration, qualifications, setting, accuracy and compliance outcomes, counselling experience and your interest in the specific role.' },
      { q: 'Can a pharmacist move into pharmacovigilance or regulatory roles?', a: 'Yes. Explain in the letter how your dispensing, documentation and compliance experience relates to drug safety or regulatory work, and mention any training or certification you have started.' },
    ],
  },
  'embedded-systems-engineer': {
    dos: [
      'Name the microcontrollers, RTOS and protocols you work with, matching the job description',
      'Describe a shipped product or board you brought up and your role',
      'Quantify results: power consumption, boot time, memory footprint or defect reduction',
      'Mention debugging tools such as JTAG, oscilloscope and logic analyser',
      'Link a repository or hardware project if you can',
    ],
    donts: [
      'Don’t list every microcontroller you have powered on',
      'Avoid claiming experience with safety standards you have not applied',
      'Don’t forget to mention testing and validation',
      'Never use buzzwords without a project to support them',
      'Don’t write more than one page',
    ],
    keyPoints: [
      'A product-level contribution, from firmware to validation',
      'Experience with communication protocols (CAN, SPI, I2C, UART, BLE)',
      'Debugging methodology and documentation habits',
      'Domain knowledge: automotive, industrial, medical or IoT',
    ],
    sampleOpening: 'I wrote the CAN and bootloader firmware for [Product] on an STM32 platform at [Company], reducing boot time by [X]% and enabling over-the-air updates — the kind of end-to-end firmware ownership I hope to bring to [Target Company].',
    sampleBody: 'I develop in C/C++ on ARM Cortex-M with FreeRTOS, write drivers for SPI, I2C and UART peripherals and debug using JTAG and logic analysers. I reduced power consumption of an IoT sensor node by [X]% through sleep-mode redesign and added unit tests and hardware-in-the-loop checks that reduced field defects. I document interfaces clearly so hardware, firmware and test teams can work in parallel.',
    sampleClosing: 'I would welcome a technical conversation about your products and how I can contribute. Thank you for your time.',
    faqs: [
      { q: 'What should an embedded engineer highlight in a cover letter?', a: 'A shipped product or board, your microcontroller and RTOS stack, protocol experience, debugging skills and one measurable improvement.' },
      { q: 'Do embedded freshers need a cover letter?', a: 'A short letter helps because it lets you describe academic and hobby projects, such as STM32 or Arduino-based builds, that a CV can only list.' },
    ],
  },
};
