import type { CoverLetterData } from '@/lib/coverLetterData';

// Hand-written cover letter guidance for roles that previously had no /cover-letter-examples/[role] page.
// Sample figures inside sample letters are illustrative placeholders (as in the existing samples), not statistics.

export const coverLetterGapRoles: Record<string, CoverLetterData> = {
  'business-development-manager': {
    dos: [
      'Open with a revenue or pipeline result you owned — the number first, the context second',
      'Name the sales motion you run (enterprise, channel, inside) and the vertical you sell into',
      'Reference the target company\'s market and the specific growth problem you would tackle',
      'Mention the CRM and prospecting tools you use, briefly',
      'Close by proposing a concrete next step, such as a 30-minute discussion on their 90-day pipeline plan',
    ],
    donts: [
      'Don\'t list duties — a BDM cover letter without a result reads as a job description',
      'Avoid generic claims like "excellent communication skills" with no proof',
      'Don\'t exaggerate numbers; hiring managers will probe them in the interview',
      'Never send one letter to multiple companies with the name unchanged',
      'Don\'t criticise a former employer or competitor',
    ],
    keyPoints: [
      'One headline result: quota attainment, revenue closed, or new accounts won',
      'Your deal size and sales-cycle context so the number is comparable',
      'Evidence you can open new markets or partnerships, not only close inbound leads',
      'Why this company\'s product and market interest you specifically',
    ],
    sampleOpening: 'Last year I grew my region\'s qualified pipeline from ₹[X] cr to ₹[Y] cr by building a partner-led outbound motion at [Company] — the same kind of new-market growth [Target Company] is pursuing with its expansion into [segment].',
    sampleBody: 'At [Company], I own B2B business development for [vertical], managing a pipeline of [N] enterprise accounts and closing deals in the ₹[range] band. I built a Sales Navigator-driven outbound programme, partnered with [N] channel partners, and introduced weekly pipeline reviews in Salesforce that improved forecast accuracy. I hit [X]% of target in each of the last [N] quarters and mentored two junior executives. I would bring the same discipline to [Target Company]\'s [segment] push.',
    sampleClosing: 'I would welcome a short conversation about your growth plan for [segment] and how I could contribute to your first 90 days. Thank you for your time and consideration.',
    faqs: [
      { q: 'Should a business development cover letter include revenue numbers?', a: 'Yes, where you can share them. Even a percentage such as "achieved 115% of quota" or a range gives the reader a concrete signal. If exact revenue is confidential, use growth percentages or deal counts instead.' },
      { q: 'How long should a business development manager cover letter be?', a: 'About 250–300 words across three short paragraphs: your headline result, how you generate and close business, and why this company. Hiring managers for sales roles read quickly and value directness.' },
    ],
  },
  'chartered-accountant': {
    dos: [
      'State your ICAI qualification and the area you specialise in (audit, tax, FP&A, treasury) in the first paragraph',
      'Reference one engagement or project with its scope: type of audit, entity size, compliance area',
      'Show knowledge of the employer\'s regulatory context — Ind AS, GST, listed-company reporting',
      'Mention tools such as SAP, Tally and advanced Excel where they matter',
      'Keep a professional, precise tone with no filler',
    ],
    donts: [
      'Don\'t repeat your CV\'s list of articleship firms and dates',
      'Avoid vague statements such as "strong knowledge of accounting"',
      'Don\'t claim experience in regimes you have not handled directly',
      'Never include confidential client names or figures without permission',
      'Don\'t send a letter that fails to match the role\'s function (audit vs finance vs tax)',
    ],
    keyPoints: [
      'Your qualification, membership year and specialisation',
      'A representative engagement: what you did and what improved or was detected',
      'The compliance frameworks and systems you are fluent in',
      'Why you are moving to this employer or function',
    ],
    sampleOpening: 'As a Chartered Accountant with [N] years of statutory and tax audit experience, I have led audits for companies with turnover up to ₹[X] cr — experience I would like to bring to [Target Company]\'s finance function as [role].',
    sampleBody: 'At [Firm/Company], I lead the statutory audit for [N] clients across [sectors], covering Ind AS reporting, internal financial controls testing and GST reconciliation. In my last engagement I identified a recurring input-tax credit mismatch and worked with the client team on a monthly reconciliation process that reduced year-end adjustments. I also mentor two articled assistants and am comfortable with SAP and Tally-based ledgers. I hold the ICAI qualification and additional ICAI certification training in [area].',
    sampleClosing: 'I would value the opportunity to discuss how my audit and compliance background can support [Target Company]\'s reporting and control priorities. Thank you for your consideration.',
    faqs: [
      { q: 'Do chartered accountants need a cover letter in India?', a: 'It depends on the employer. Big audit firms often rely on campus and online forms, while corporates, startups and finance leadership roles do read cover letters. A short, specific letter helps when you are changing sector, function, or city.' },
      { q: 'What should a fresher CA highlight in a cover letter?', a: 'Articleship depth: the types of audits, industries and compliance work you handled, plus any ICAI additional courses and tools. Be specific about your responsibilities and avoid claiming results that belonged to the team.' },
    ],
  },
  'embedded-systems-engineer': {
    dos: [
      'Name the exact product, board, or firmware you shipped and what it does',
      'Mention the MCU family, RTOS, and protocols in the first two paragraphs',
      'Give one measurable outcome: boot time, power consumption, memory footprint, defect rate',
      'Show how you debug — logic analyser, JTAG, oscilloscope — with a real example',
      'Connect your experience to the employer\'s domain (automotive, IoT, medical, industrial)',
    ],
    donts: [
      'Don\'t just list every microcontroller you have touched',
      'Avoid buzzwords like "passionate about IoT" without a project to back them',
      'Don\'t describe university coursework as production work',
      'Never leave out safety or compliance standards when the domain requires them',
      'Don\'t write more than one page',
    ],
    keyPoints: [
      'A shipped firmware or hardware-software project with clear scope',
      'Your depth in low-level debugging and real-time constraints',
      'Familiarity with the standards of the target domain (AUTOSAR, MISRA C, IEC 62304)',
      'Ability to work with hardware and software teams',
    ],
    sampleOpening: 'I reduced the standby power draw of [Company]\'s battery-powered sensor node by [X]% by restructuring its FreeRTOS task scheduling and sleep states on an STM32L4 — the kind of low-level optimisation I hope to bring to [Target Company]\'s [product] team.',
    sampleBody: 'At [Company], I develop firmware in Embedded C for ARM Cortex-M based products, including bootloader, CAN and SPI drivers, and OTA update logic. I bring up new boards, debug timing issues with a logic analyser and JTAG, and write unit tests for hardware abstraction layers. I follow MISRA C guidelines and worked with the hardware team to resolve a noise issue affecting ADC readings. I have contributed to [N] production releases.',
    sampleClosing: 'I am keen to contribute to [Target Company]\'s embedded roadmap and would welcome a technical discussion about your current platform and challenges. Thank you for your time.',
    faqs: [
      { q: 'Should an embedded engineer mention hardware projects in a cover letter?', a: 'Yes. Concrete hardware-software projects show practical ability. Describe the board or product, your responsibility, the tools used, and one measurable result, such as reduced memory usage or improved reliability.' },
      { q: 'How do I write an embedded systems cover letter as a fresher?', a: 'Lead with your best project — a firmware or board bring-up you can explain in detail — and link to code or a demo. Name the MCU, peripherals and protocols used, and state clearly what you personally built.' },
    ],
  },
  'full-stack-developer': {
    dos: [
      'Lead with a product or feature you built end to end, from database to UI',
      'Name your stack in the opening lines and match it to the job description',
      'Include one measurable result: performance gain, user growth, or delivery speed',
      'Link a live project or GitHub repository',
      'Show you understand the company\'s product and technical challenges',
    ],
    donts: [
      'Don\'t claim mastery of every framework — focus on the stack in the JD',
      'Avoid restating your CV skills list',
      'Don\'t open with "I am writing to apply for..." — start with what you built',
      'Never leave out deployment and testing when the role expects ownership',
      'Don\'t exceed one page',
    ],
    keyPoints: [
      'An end-to-end feature or product you owned',
      'Your strongest layer (frontend, backend or infrastructure) and comfort with the others',
      'Evidence of shipping: deployments, users, uptime, code review habits',
      'Interest in the company\'s product',
    ],
    sampleOpening: 'I built and shipped [Company]\'s customer dashboard end to end — React and TypeScript on the front end, Node.js and PostgreSQL behind it — and cut its median page load from [X]s to [Y]s. I would like to bring that ownership to [Target Company]\'s product engineering team.',
    sampleBody: 'At [Company], I design REST APIs in Node.js, model data in PostgreSQL, and build the React interfaces that consume them. I set up a GitHub Actions pipeline with automated tests and Docker-based deployments to AWS, which shortened our release cycle. I regularly review pull requests and pair with designers on implementation details. My open-source work and side projects are linked on my CV.',
    sampleClosing: 'I would enjoy discussing how I could contribute to [Target Company]\'s roadmap, and I am happy to walk through any of my projects in detail. Thank you for your time.',
    faqs: [
      { q: 'Do full stack developers need a cover letter?', a: 'Not always, but a short, specific one helps at startups and product companies where hiring managers read applications directly. Focus on one shipped project and your fit with the company\'s stack.' },
      { q: 'How should a fresher full stack developer write a cover letter?', a: 'Lead with a deployed project, name the stack, and link the live app and repository. Explain what you built, the problems you solved, and what you learned. A working project outweighs a list of technologies.' },
    ],
  },
  'interior-designer': {
    dos: [
      'Lead with a project — type, area, and what made it distinctive',
      'Link to your portfolio in the first paragraph',
      'Describe your role across concept, working drawings, and execution',
      'Mention software proficiency in context of real deliverables',
      'Show understanding of the studio\'s style and typical clientele',
    ],
    donts: [
      'Don\'t just say you have "a creative eye" — show it through a project',
      'Avoid copying a studio\'s own marketing language back to them',
      'Don\'t claim sole credit for team projects',
      'Never attach large image files instead of linking a portfolio',
      'Don\'t ignore budget and timeline realities in project descriptions',
    ],
    keyPoints: [
      'One representative project with type, scale and scope',
      'Your balance of design creativity and execution (BOQ, vendors, site supervision)',
      'Software tools used for concept, drawings, and rendering',
      'Client handling and presentation experience',
    ],
    sampleOpening: 'Redesigning a [X] sq ft [residential/commercial] space within a [N]-week timeline while staying inside the client\'s budget taught me how to combine strong concepts with practical execution — the approach I would like to bring to [Studio]\'s residential team.',
    sampleBody: 'At [Company], I take projects from moodboards and space planning through AutoCAD working drawings, SketchUp and V-Ray visualisation, BOQ preparation and vendor coordination on site. I have delivered [N] residential and [N] commercial projects and regularly present concepts to clients. My portfolio at [link] shows the range from concept to completed spaces.',
    sampleClosing: 'I would love to discuss how my design and execution experience could support [Studio]\'s upcoming projects. Thank you for reviewing my portfolio.',
    faqs: [
      { q: 'Should an interior designer\'s cover letter include a portfolio link?', a: 'Yes, place it in the first paragraph. Design studios decide on the portfolio first, so a plain-text link (Behance, Instagram, or a website) is more useful than any description.' },
      { q: 'How can a fresher interior designer stand out in a cover letter?', a: 'Highlight your strongest academic or internship project with its scope and your contribution, show software skills through actual deliverables, and mention site exposure or internship supervision experience.' },
    ],
  },
  'investment-banker': {
    dos: [
      'Open with a transaction or analytical project and your specific role in it',
      'Show sector interest with a real reason and knowledge of recent deals',
      'Mention modelling and valuation skills through concrete work',
      'Keep it to three tight paragraphs; bankers read quickly',
      'Address it to a specific person or team wherever possible',
    ],
    donts: [
      'Don\'t include confidential deal information',
      'Avoid saying you are "passionate about finance" without evidence',
      'Don\'t make errors in the firm\'s name, deals, or division — accuracy matters here',
      'Never overstate your deal role',
      'Don\'t exceed one page',
    ],
    keyPoints: [
      'A specific deal, model, or pitch you contributed to',
      'Technical fluency: DCF, comps, LBO, financial statements',
      'Why this firm and this sector or product group',
      'Attention to detail and work ethic, shown through examples',
    ],
    sampleOpening: 'During my internship at [Firm], I built the DCF and comparable-company analysis for a sell-side mandate in the [sector] sector, an experience that confirmed my wish to join [Target Bank]\'s [group] team.',
    sampleBody: 'I have built three-statement models, DCF and trading comps, and prepared pitchbook pages and information memorandum drafts. I hold a [degree] from [institution] with a [CGPA], completed CFA Level [N], and use Excel, PowerPoint and Capital IQ daily. I followed [Target Bank]\'s work on [recent public transaction] and am interested in how [group] approaches [sector] advisory.',
    sampleClosing: 'I would welcome the opportunity to discuss how I can contribute to your team. Thank you for your time and consideration.',
    faqs: [
      { q: 'Do investment banking applications need a cover letter?', a: 'Many banks make it optional, but a targeted letter helps you explain your interest in the firm and group. It should be concise and free of errors, and it should never repeat the CV line by line.' },
      { q: 'What should be in an investment banking cover letter for a fresher?', a: 'A relevant internship, project, or case competition, technical skills shown through concrete work, and specific reasons for the firm and product group. Keep confidentiality in mind and never overstate what you did.' },
    ],
  },
  'ios-developer': {
    dos: [
      'Open with an app you shipped and a metric: rating, users, crash-free rate, or performance',
      'Include the App Store link',
      'Name Swift/SwiftUI/UIKit and your architecture approach',
      'Show ownership of releases: testing, TestFlight, App Store review',
      'Explain why the employer\'s product interests you as a user first',
    ],
    donts: [
      'Don\'t list every Apple framework you have touched',
      'Avoid saying "I love Apple products" as your main motivation',
      'Don\'t claim experience with SwiftUI if you only used UIKit',
      'Never omit testing and stability',
      'Don\'t exceed one page',
    ],
    keyPoints: [
      'A shipped app with a link and scale indicators',
      'Architecture and testing practices',
      'Release ownership and collaboration with design and backend',
      'A thoughtful observation about the employer\'s app',
    ],
    sampleOpening: 'I improved [Company]\'s iOS app crash-free rate from [X]% to [Y]% and rebuilt its onboarding in SwiftUI, work that raised our App Store rating to [Z] — the type of quality focus I would like to bring to [Target Company]\'s iOS team.',
    sampleBody: 'At [Company], I build features in Swift using MVVM, Combine and Core Data, integrate REST APIs, and write XCTest unit tests for view models. I own the release process through TestFlight and App Store Connect, and use Instruments to profile memory and performance. My app is live at [link].',
    sampleClosing: 'I would be glad to discuss how I could contribute to [Target Company]\'s iOS roadmap. Thank you for your time.',
    faqs: [
      { q: 'Should an iOS developer include App Store links in a cover letter?', a: 'Yes. A live app is the strongest evidence of your ability. Include the link and one or two facts about your contribution and its results.' },
      { q: 'How does a fresher iOS developer write a strong cover letter?', a: 'Lead with a personal or academic app, ideally published or on TestFlight, and link its repository. Describe the architecture, the problems you solved, and the testing you did.' },
    ],
  },
  'logistics-manager': {
    dos: [
      'Lead with an operational result: cost reduced, delivery time improved, or accuracy raised',
      'State the scale you have managed — shipments, sites, fleet or team size',
      'Mention the systems and tools you use, such as WMS, TMS and SAP',
      'Show how you manage vendors and service levels',
      'Connect your experience to the employer\'s supply chain model',
    ],
    donts: [
      'Don\'t describe duties without figures',
      'Avoid blaming past employers for operational failures',
      'Don\'t promise results you cannot support',
      'Never ignore safety and compliance',
      'Don\'t write more than one page',
    ],
    keyPoints: [
      'One headline improvement with numbers',
      'The scale and complexity of operations you have run',
      'Vendor, 3PL and team management approach',
      'Systems and process improvement experience',
    ],
    sampleOpening: 'By redesigning delivery routes and renegotiating two 3PL contracts, I reduced cost per shipment by [X]% across [N] daily deliveries at [Company] — the kind of operational improvement I hope to deliver at [Target Company].',
    sampleBody: 'At [Company], I manage a team of [N] across [N] warehouses and a [N]-vehicle network, tracking on-time delivery, order accuracy and inventory turns in our WMS and Excel dashboards. I introduced a daily SLA review with vendors and a cycle-count process that reduced stock discrepancies. I am familiar with GST and e-way bill compliance.',
    sampleClosing: 'I would welcome the chance to discuss how my experience could support [Target Company]\'s logistics operations. Thank you for your consideration.',
    faqs: [
      { q: 'What should a logistics manager cover letter highlight?', a: 'Operational results with numbers — cost, delivery time, accuracy — plus the scale of the operation, vendor and team management, and systems used. Tie these to the employer\'s specific supply chain challenge.' },
      { q: 'Is a cover letter needed for logistics roles in India?', a: 'It is often optional but useful for management roles or when moving between sectors such as e-commerce, FMCG or manufacturing. A short letter that explains your relevant scale and results helps.' },
    ],
  },
  'machine-learning-engineer': {
    dos: [
      'Lead with a model you deployed and the business or performance outcome',
      'Name the problem type, framework and the metric you improved',
      'Show production awareness: serving, monitoring, retraining',
      'Link to GitHub, a paper, or a Kaggle profile',
      'Explain why the company\'s data problem interests you',
    ],
    donts: [
      'Don\'t equate coursework with production experience',
      'Avoid listing algorithms without a project',
      'Don\'t oversell accuracy numbers without context',
      'Never ignore data quality and evaluation',
      'Don\'t exceed one page',
    ],
    keyPoints: [
      'A model in production and its measurable effect',
      'Data volume, latency and constraints',
      'MLOps practices: versioning, monitoring, CI/CD',
      'Collaboration with product and data engineers',
    ],
    sampleOpening: 'I built and deployed a [problem] model at [Company] that improved [metric] by [X]% and now serves [N] predictions a day — the kind of production ML work I would like to do at [Target Company].',
    sampleBody: 'At [Company], I develop models in PyTorch and Scikit-learn, build feature pipelines in SQL and Airflow, and deploy through Docker and SageMaker with MLflow tracking. I monitor drift and set up retraining triggers, and I work with product managers to define evaluation metrics before modelling. My project code is at [link].',
    sampleClosing: 'I would enjoy discussing how I could contribute to [Target Company]\'s ML roadmap. Thank you for your time.',
    faqs: [
      { q: 'What makes a machine learning engineer cover letter effective?', a: 'A deployed model with a measured outcome, a clear description of your tools, and evidence that you care about production concerns like monitoring and evaluation.' },
      { q: 'How can a fresher ML engineer write a cover letter without work experience?', a: 'Use a well-documented project or internship: the problem, data, model, metric and what you learned. Link the repository and, where possible, a demo or write-up.' },
    ],
  },
  'network-engineer': {
    dos: [
      'Open with the network you managed and its scale',
      'Name your certifications and the platforms you administer',
      'Give one example of resolving a critical incident or improving uptime',
      'Mention monitoring, security and change-management practices',
      'Match the vendors to the employer\'s environment',
    ],
    donts: [
      'Don\'t list every device you have touched',
      'Avoid claiming security expertise without specifics',
      'Don\'t omit certification details',
      'Never disclose confidential network designs',
      'Don\'t exceed one page',
    ],
    keyPoints: [
      'Scale: sites, devices, users, and uptime targets',
      'Core technologies: routing, switching, firewalls, WAN',
      'An incident or migration you led',
      'Process discipline: ITIL, change control, documentation',
    ],
    sampleOpening: 'I led the migration of [N] branch sites from MPLS to SD-WAN at [Company] with no unplanned downtime, an experience I would like to bring to [Target Company]\'s network operations team.',
    sampleBody: 'I hold CCNP Enterprise and manage routing and switching with BGP and OSPF, Palo Alto firewalls and site-to-site VPNs. I monitor with SolarWinds, troubleshoot with Wireshark, and follow ITIL change management. In my last role I resolved a recurring routing flap by redesigning route filtering, improving stability across [N] sites.',
    sampleClosing: 'I would be glad to discuss how I can support [Target Company]\'s network. Thank you for your time.',
    faqs: [
      { q: 'What should a network engineer highlight in a cover letter?', a: 'Your certifications, the scale and technologies of the networks you have run, and one concrete example of an incident, migration, or improvement. Be specific and avoid listing tools with no context.' },
      { q: 'Do network engineers need cover letters in India?', a: 'Not always, but they help for infrastructure roles at MNCs and when changing vendor or domain. Keep it short and factual.' },
    ],
  },
  'pharmacist': {
    dos: [
      'State your qualification and council registration',
      'Describe your setting: hospital, retail, clinical, or industry',
      'Show patient-safety practices: verification, counselling, interaction checks',
      'Mention inventory, compliance and documentation experience',
      'Explain why you want to join this employer',
    ],
    donts: [
      'Don\'t make claims about clinical outcomes you cannot support',
      'Avoid vague phrases like "love helping people"',
      'Don\'t omit registration details',
      'Never include patient information',
      'Don\'t exceed one page',
    ],
    keyPoints: [
      'Qualification and registration',
      'The setting and volume of your practice',
      'Patient counselling and safety practices',
      'Compliance and inventory management',
    ],
    sampleOpening: 'As a registered pharmacist with [N] years in hospital dispensing, I verify and dispense prescriptions for [N] patients a day while maintaining rigorous safety checks — the standard I hope to bring to [Target Organisation].',
    sampleBody: 'I hold a B.Pharm from [institution] and am registered with the [State] Pharmacy Council. I check prescriptions for interactions and dosage, counsel patients on use and adherence, manage inventory and expiry tracking, and support pharmacovigilance reporting. I follow Schedule H and documentation requirements.',
    sampleClosing: 'I would welcome the opportunity to discuss how I can support your pharmacy team. Thank you for your consideration.',
    faqs: [
      { q: 'What should a pharmacist include in a cover letter?', a: 'Your qualification, council registration, practice setting, and examples of patient safety and compliance work. Keep it factual and specific.' },
      { q: 'Can a fresher pharmacist write a strong cover letter?', a: 'Yes. Use internships, hospital training, and projects to show dispensing, counselling and documentation skills, and state your registration status.' },
    ],
  },
  'react-developer': {
    dos: [
      'Lead with a React app you built and an outcome: performance, users, or reliability',
      'Name React, TypeScript, and the surrounding tools you used',
      'Link a live demo and repository',
      'Mention testing, accessibility and performance work',
      'Show you have studied the employer\'s product interface',
    ],
    donts: [
      'Don\'t list every library from your projects',
      'Avoid claiming senior-level architecture experience without examples',
      'Don\'t ignore UX and accessibility',
      'Never omit testing',
      'Don\'t exceed one page',
    ],
    keyPoints: [
      'A shipped UI with measurable outcome',
      'State management and data-fetching approach',
      'Testing and performance practices',
      'Collaboration with designers and backend engineers',
    ],
    sampleOpening: 'I rebuilt [Company]\'s checkout flow in React and TypeScript, cutting its bundle size by [X]% and lifting its Lighthouse performance score from [Y] to [Z] — the kind of frontend quality I would like to bring to [Target Company].',
    sampleBody: 'At [Company], I build React interfaces with Redux Toolkit and React Query, write tests with Jest and React Testing Library, and optimise rendering through code splitting and memoisation. I work with designers on accessible components and with backend engineers on API contracts. My work is live at [link].',
    sampleClosing: 'I would enjoy discussing how I can contribute to [Target Company]\'s frontend. Thank you for your time.',
    faqs: [
      { q: 'What should a React developer cover letter include?', a: 'A shipped project with an outcome, your stack, testing and performance habits, and links to a live demo and code.' },
      { q: 'How can a fresher React developer stand out?', a: 'Deploy two or three well-built projects, describe the problems solved and decisions made, and link the live apps and repositories.' },
    ],
  },
  'sales-executive': {
    dos: [
      'Open with a target achievement figure you can prove',
      'State the type of sales: field, inside, B2B or B2C',
      'Mention your territory, product and customer segment',
      'Show your approach to prospecting and follow-up',
      'Explain why you want to sell this product',
    ],
    donts: [
      'Don\'t say you are a "people person" without evidence',
      'Avoid exaggerated numbers',
      'Don\'t criticise previous employers',
      'Never send a generic letter',
      'Don\'t exceed one page',
    ],
    keyPoints: [
      'Target achievement and ranking',
      'Sales method and customer segment',
      'CRM use and reporting discipline',
      'Motivation and product interest',
    ],
    sampleOpening: 'I achieved [X]% of my annual target at [Company], ranking [Nth] among [N] executives in [region] — the kind of results I would like to bring to [Target Company]\'s sales team.',
    sampleBody: 'In my role, I manage [N] accounts in [territory], generate leads through cold calling and referrals, run product demonstrations, and negotiate to close. I log every interaction in the CRM, review my pipeline weekly, and consistently upsell existing customers.',
    sampleClosing: 'I would welcome the chance to discuss how I can help [Target Company] meet its sales goals. Thank you for your time.',
    faqs: [
      { q: 'What should a sales executive cover letter highlight?', a: 'Target achievement, the kind of sales you do, your prospecting approach, and why you are interested in the product. Use numbers you can defend.' },
      { q: 'Can a fresher write a sales executive cover letter?', a: 'Yes. Use internships or part-time customer work, quantify results, and show communication skills and coachability.' },
    ],
  },
  'sap-consultant': {
    dos: [
      'State your module, version and years of experience in the first line',
      'Describe one implementation or rollout with your role',
      'Mention lifecycle involvement: blueprint, configuration, UAT, go-live, support',
      'Reference industry experience the employer values',
      'Show communication with business users',
    ],
    donts: [
      'Don\'t write only "SAP experience" without a module',
      'Avoid listing every module you have looked at',
      'Don\'t claim S/4HANA experience if you worked only on ECC',
      'Never ignore change management',
      'Don\'t exceed one page',
    ],
    keyPoints: [
      'Module, version and industry',
      'A project with scope, team and outcome',
      'Configuration, testing and support involvement',
      'Business-user engagement',
    ],
    sampleOpening: 'As an SAP FICO consultant with [N] years across [N] S/4HANA implementations, I have led finance workstreams from blueprint to go-live — experience I would like to bring to [Target Company].',
    sampleBody: 'On my most recent project for a [industry] client, I configured [modules], ran UAT with finance users, managed data migration checks and provided hypercare support. I follow SAP Activate methodology and document functional specifications for ABAP developers. I hold SAP certification in [module].',
    sampleClosing: 'I would welcome a discussion on how I can contribute to your SAP programme. Thank you for your consideration.',
    faqs: [
      { q: 'What should an SAP consultant cover letter contain?', a: 'Your module and version, a specific implementation or support engagement, your role in each project phase, certifications, and the industries you have worked in.' },
      { q: 'How should a fresher SAP consultant write a cover letter?', a: 'Highlight SAP training and certification, any hands-on practice or internship, and your understanding of the business process behind your chosen module.' },
    ],
  },
  'scrum-master': {
    dos: [
      'Open with a team improvement: predictability, cycle time, or delivery quality',
      'State how many teams and people you have coached',
      'Name your certifications and frameworks',
      'Show how you handle impediments and stakeholders',
      'Explain your coaching approach briefly',
    ],
    donts: [
      'Don\'t describe Scrum ceremonies as your achievements',
      'Avoid jargon without outcomes',
      'Don\'t claim credit for the whole team\'s results',
      'Never present Scrum as rigid dogma',
      'Don\'t exceed one page',
    ],
    keyPoints: [
      'Outcome-focused impact',
      'Team and organisational scale',
      'Certifications and frameworks',
      'Coaching and facilitation style',
    ],
    sampleOpening: 'By reshaping backlog refinement and reducing work in progress, I helped a [N]-person team at [Company] improve sprint predictability from [X]% to [Y]% — the kind of team improvement I would like to support at [Target Company].',
    sampleBody: 'I serve as Scrum Master for [N] teams, facilitate planning, standups and retrospectives, and track velocity and cycle time in Jira. I remove impediments with stakeholders and coach product owners on backlog quality. I hold CSM and PSM I certifications and have supported a SAFe programme increment.',
    sampleClosing: 'I would enjoy discussing how I can help your teams deliver more predictably. Thank you for your time.',
    faqs: [
      { q: 'What should a Scrum Master cover letter emphasise?', a: 'Measurable team outcomes, the number of teams you coach, certifications, and how you remove impediments and facilitate improvement.' },
      { q: 'How can an aspiring Scrum Master write a cover letter without the title?', a: 'Use experience facilitating agile ceremonies as a developer, analyst, or project coordinator, list your certification, and describe a process improvement you drove.' },
    ],
  },
};
