import type { CoverLetterData } from '@/lib/coverLetterData';

// Qualitative cover-letter guidance for roles not hand-curated in coverLetterData.ts.
// Sample paragraphs use bracketed placeholders — no invented statistics.

interface Seed {
  focus: string; // what to open with
  proof: string; // what evidence to quantify
  tools: string; // tools/skills to name
  context: string; // what to research about the employer
  opening: string;
  body: string;
  closing: string;
  roleName: string;
  extraDo: string;
  extraDont: string;
  faq: { q: string; a: string };
}

function build(s: Seed): CoverLetterData {
  return {
    dos: [
      `Open with ${s.focus} rather than a generic statement of interest`,
      `Name the relevant ${s.tools} that appear in the job description`,
      `Quantify your impact: ${s.proof}`,
      `Research ${s.context} and reference it specifically`,
      s.extraDo,
    ],
    donts: [
      "Don't repeat your CV line by line — the letter should add context and motivation",
      'Avoid clichés like "I am writing to express my interest" or "hard-working team player"',
      "Don't send one generic letter to every employer — change the company name, role and one specific detail each time",
      s.extraDont,
      "Don't exceed one page; three short paragraphs is enough",
    ],
    keyPoints: [
      `One concrete achievement that shows ${s.focus}`,
      `Evidence of ${s.tools} used in a real project or role`,
      `Why this employer specifically — ${s.context}`,
      'A confident, specific closing that invites a conversation',
    ],
    sampleOpening: s.opening,
    sampleBody: s.body,
    sampleClosing: s.closing,
    faqs: [
      s.faq,
      {
        q: `How long should a ${s.roleName} cover letter be?`,
        a: 'Aim for 200–300 words across three short paragraphs: a specific opening, one or two pieces of proof, and a clear closing. Recruiters in India typically skim, so brevity helps.',
      },
    ],
  };
}

export const coverLetterDataMore: Record<string, CoverLetterData> = {
  'sales-executive': build({
    roleName: 'sales executive',
    focus: 'a concrete sales result such as target attainment or revenue closed',
    proof: 'quota achieved, deals closed, pipeline built or revenue added',
    tools: 'CRM tools and sales methods (Salesforce, HubSpot, cold outreach, demos)',
    context: "the company's product, buyer segment and sales motion",
    extraDo: 'Show you understand the buyer: name the segment or industry you have sold into',
    extraDont: "Don't claim to be a \"people person\" without a number that proves it",
    opening: 'Last year I closed [X]% of my annual target selling [product type] to [segment] accounts — the same buyer profile [Target Company] serves in [region].',
    body: 'At [Company], I built and worked a pipeline of [N] accounts using [CRM], running discovery calls, demos and follow-ups through to close. My strongest results came from [specific tactic, e.g. referral outreach or account mapping], which I would bring to your team.',
    closing: 'I would welcome a conversation about how my track record can help [Target Company] reach its targets in [region/segment].',
    faq: { q: 'Should a sales executive include numbers in a cover letter?', a: 'Yes. Sales hiring is result-driven, so one or two verifiable figures — target attainment, deal size or accounts won — are the strongest content you can include.' },
  }),
  'ios-developer': build({
    roleName: 'iOS developer',
    focus: 'a shipped app or feature on the App Store',
    proof: 'App Store rating, downloads, crash-free rate or load-time improvements',
    tools: 'Swift, SwiftUI, UIKit, Xcode and architecture patterns (MVVM, Combine)',
    context: "the company's app, its App Store reviews and its release cadence",
    extraDo: 'Link to your App Store listing or GitHub so the reader can verify your work',
    extraDont: "Don't list every framework you've touched — focus on those in the job description",
    opening: 'I shipped [App Name] to the App Store using Swift and SwiftUI, and I have followed [Target Company]\'s iOS app closely — especially [specific feature].',
    body: 'At [Company], I owned [feature] end to end: architecture in MVVM, networking, offline caching and release through TestFlight. I focused on stability and performance, and I am comfortable working with designers and backend teams to ship on a regular cadence.',
    closing: 'I would be glad to walk through my App Store work and discuss how I can contribute to your iOS roadmap.',
    faq: { q: 'Should an iOS developer link App Store apps in a cover letter?', a: 'Yes. A live App Store link or public GitHub repository is the quickest proof of capability and lets the hiring manager review your work directly.' },
  }),
  'full-stack-developer': build({
    roleName: 'full stack developer',
    focus: 'an end-to-end product you built, from database to UI',
    proof: 'users served, latency improved, features shipped or deployment time reduced',
    tools: 'frontend and backend stack (React, Node.js, databases, cloud, CI/CD)',
    context: "the company's tech stack, engineering blog and product",
    extraDo: 'Show breadth with depth: name one layer where you are strongest',
    extraDont: "Don't claim expertise in every technology — it reads as shallow",
    opening: 'I recently built and deployed [project] end to end — React frontend, Node.js API and a [database] backend — which is exactly the full-ownership role [Target Company] describes.',
    body: 'At [Company], I shipped features across the stack, wrote the API and data layer, and set up CI/CD so changes reached production safely. I enjoy moving between UI and backend work and treating the product, not just the ticket, as my responsibility.',
    closing: 'I would welcome the chance to discuss how I can help your team ship reliably across the stack.',
    faq: { q: 'What should a full stack developer emphasise in a cover letter?', a: 'Emphasise ownership: a project or feature you delivered across frontend, backend and deployment, with a measurable outcome.' },
  }),
  'machine-learning-engineer': build({
    roleName: 'machine learning engineer',
    focus: 'a model you took from experiment to production',
    proof: 'accuracy or business-metric lift, inference latency, cost savings or data volume',
    tools: 'ML frameworks and MLOps tools (Python, PyTorch, TensorFlow, scikit-learn, MLflow, cloud ML)',
    context: "the company's ML use cases, data scale and published research or engineering posts",
    extraDo: 'Distinguish research from production work and highlight deployment experience',
    extraDont: "Don't list algorithms without explaining the problem and result",
    opening: 'I took a [model type] model from prototype to production at [Company], improving [business metric] by [X]% — the kind of applied ML work [Target Company] is hiring for.',
    body: 'My work covers data pipelines, feature engineering, training, evaluation and deployment with monitoring. I focus on measurable outcomes and reproducibility, and I am comfortable collaborating with data engineers and product teams.',
    closing: 'I would value a conversation about the ML problems your team is solving and how I can contribute.',
    faq: { q: 'Should an ML engineer include research papers or Kaggle results?', a: 'Include them if they are relevant to the role, briefly. Production deployment experience usually matters more to employers than competition rankings.' },
  }),
  'chartered-accountant': build({
    roleName: 'chartered accountant',
    focus: 'your CA qualification together with a specific finance or audit outcome',
    proof: 'audit scope, cost savings, compliance turnaround or reporting accuracy',
    tools: 'Ind AS, GST, income tax, statutory audit and tools (Tally, SAP, Excel)',
    context: "the firm's or company's industry, clients and regulatory exposure",
    extraDo: 'State your CA attempt/qualification status and articleship firm clearly',
    extraDont: "Don't be vague about your area — say whether it is audit, tax, FP&A or advisory",
    opening: 'As a qualified Chartered Accountant with experience in [audit/tax/finance] at [Company], I am applying for the [role] at [Target Company] where [specific reason].',
    body: 'My work has covered statutory audits, GST and income-tax compliance and financial reporting under Ind AS. I have improved [process] by [outcome] and I am comfortable working with ERP systems and senior stakeholders.',
    closing: 'I would welcome the opportunity to discuss how my CA background can support your finance function.',
    faq: { q: 'Do chartered accountants need a cover letter in India?', a: 'It is optional for campus and Big 4 hiring but helpful for corporate finance and senior roles, where it can explain your specialisation and motivation.' },
  }),
  'sap-consultant': build({
    roleName: 'SAP consultant',
    focus: 'a full-cycle SAP implementation or support engagement',
    proof: 'modules delivered, go-lives completed, tickets resolved or process time saved',
    tools: 'SAP modules (FICO, MM, SD, ABAP, S/4HANA) and methodologies (SAP Activate)',
    context: "the client's industry, SAP landscape and migration plans",
    extraDo: 'Name your module and version (ECC, S/4HANA) and your certification, if any',
    extraDont: "Don't list every module — state your primary one and relevant adjacent skills",
    opening: 'As an SAP [module] consultant with [N] years across implementation and support, I have delivered [go-lives] — experience that matches the S/4HANA work at [Target Company].',
    body: 'I have run requirement workshops, configured and tested [module], supported cutover and handled post-go-live issues. I work closely with business users to translate process needs into system design.',
    closing: 'I would be glad to discuss how my SAP experience can support your programme.',
    faq: { q: 'Which SAP details belong in a cover letter?', a: 'Your primary module, system version, number of implementations or support engagements, and any SAP certification.' },
  }),
  'react-developer': build({
    roleName: 'React developer',
    focus: 'a React application you built, with a measurable result',
    proof: 'performance gains (Lighthouse, load time), users served or components reused',
    tools: 'React, TypeScript, state management, testing and Next.js',
    context: "the company's product UI, design system and frontend practices",
    extraDo: 'Link to a live demo or GitHub repo of a React project',
    extraDont: "Don't just list libraries — explain what you built with them",
    opening: 'I built [project] in React and TypeScript, improving [metric] by [X]% — which is why the frontend role at [Target Company] stood out.',
    body: 'At [Company], I built reusable components, managed state with [Redux/Context/Zustand], and wrote tests with Jest and React Testing Library. I care about accessibility and performance and enjoy working closely with designers.',
    closing: 'I would love to show you my work and discuss how I can contribute to your frontend team.',
    faq: { q: 'Should a React developer link a portfolio?', a: 'Yes — a live app or repository demonstrates code quality and UI judgement far better than a description.' },
  }),
  'investment-banker': build({
    roleName: 'investment banker',
    focus: 'a transaction or deal you worked on and your specific role in it',
    proof: 'deal size, number of models built, pitchbooks produced or transactions supported',
    tools: 'financial modelling (DCF, LBO, comps), valuation and tools (Excel, PowerPoint, Bloomberg/CapIQ)',
    context: "the bank's sector coverage, recent deals and team structure",
    extraDo: 'Be precise about deal types (M&A, ECM, DCM) and your contribution — within confidentiality limits',
    extraDont: "Don't disclose confidential client information or exaggerate your deal role",
    opening: 'Having supported [deal type] transactions across [sector] at [Company], I am keen to join [Target Company]\'s [group] team, which advised on [public deal].',
    body: 'My work includes building valuation and merger models, preparing pitchbooks and supporting due diligence under tight timelines. I am accurate, comfortable with long hours and keen to learn from senior bankers.',
    closing: 'I would welcome the opportunity to discuss how I can contribute to your team.',
    faq: { q: 'Is a cover letter expected for investment banking applications?', a: 'Often yes. Banks use it to assess motivation and sector fit, so name the group, a recent deal and why you want that desk.' },
  }),
  'scrum-master': build({
    roleName: 'Scrum Master',
    focus: 'a team you helped improve delivery or predictability for',
    proof: 'velocity stability, cycle-time reduction, release frequency or team satisfaction',
    tools: 'Scrum, Kanban, Jira and certifications (CSM, PSM, SAFe)',
    context: "the company's delivery model, team structure and agile maturity",
    extraDo: 'Mention your certification and the team size you have coached',
    extraDont: "Don't describe Scrum theory — show outcomes you achieved",
    opening: 'As a Certified Scrum Master supporting [N] teams at [Company], I helped improve [delivery outcome] — the agility focus I see in [Target Company]\'s role.',
    body: 'I facilitate sprint ceremonies, remove impediments, coach product owners on backlog quality and use metrics like cycle time to guide improvement. I focus on servant leadership and a healthy team culture.',
    closing: 'I would welcome a conversation about how I can help your teams deliver with greater clarity and pace.',
    faq: { q: 'Which certifications should a Scrum Master mention?', a: 'CSM, PSM or SAFe certifications, stated briefly alongside the team sizes and results you have supported.' },
  }),
  'business-development-manager': build({
    roleName: 'business development manager',
    focus: 'new revenue, partnerships or markets you opened',
    proof: 'revenue added, partnerships signed, pipeline value or new accounts',
    tools: 'lead generation, partnership strategy, negotiation and CRM tools',
    context: "the company's growth strategy, target markets and competitors",
    extraDo: 'Describe how you found and closed opportunities, not only the outcomes',
    extraDont: "Don't confuse BD with sales targets alone — show strategic thinking too",
    opening: 'I opened [new market/partnership] for [Company], adding [revenue/pipeline] in [timeframe] — the kind of growth [Target Company] is seeking.',
    body: 'My approach combines market research, outreach, negotiation and cross-team coordination with product and operations. I track a pipeline in [CRM] and focus on long-term partnerships rather than one-off deals.',
    closing: 'I would be glad to discuss how I can help drive [Target Company]\'s next phase of growth.',
    faq: { q: 'What makes a strong business development cover letter?', a: 'Specific growth outcomes — a market opened, partnership signed or revenue added — plus a view on the target company\'s growth opportunities.' },
  }),
  'network-engineer': build({
    roleName: 'network engineer',
    focus: 'a network you designed, migrated or kept reliable',
    proof: 'uptime achieved, sites supported, incidents reduced or bandwidth improved',
    tools: 'routing and switching, firewalls, VPN, SD-WAN and certifications (CCNA, CCNP)',
    context: "the company's network scale, vendors and cloud footprint",
    extraDo: 'List your certifications (CCNA/CCNP) and the vendors you have worked with',
    extraDont: "Don't list every device you've used — focus on scale and outcomes",
    opening: 'With [N] years managing enterprise networks and a CCNA/CCNP background, I have kept [N] sites online at [X]% uptime — relevant to the network role at [Target Company].',
    body: 'I configure and troubleshoot routing, switching and firewalls, monitor with [tool], and plan upgrades with minimal downtime. I document changes carefully and work well under incident pressure.',
    closing: 'I would welcome the opportunity to discuss how I can support your network reliability goals.',
    faq: { q: 'Should network engineers list certifications in the cover letter?', a: 'Yes, briefly: CCNA, CCNP or vendor certifications are a primary screening signal for network roles.' },
  }),
  'logistics-manager': build({
    roleName: 'logistics manager',
    focus: 'a supply-chain or delivery improvement you led',
    proof: 'on-time delivery rate, cost per shipment, inventory turns or lead-time reduction',
    tools: 'WMS/TMS, ERP systems, vendor management and route planning',
    context: "the company's network, warehouses, carriers and service levels",
    extraDo: 'Mention the scale you managed: shipments, warehouses, fleet or team size',
    extraDont: "Don't describe duties only — show cost, speed or accuracy improvements",
    opening: 'I led a [process] improvement at [Company] that cut [cost/lead time] by [X]%, managing [scale] — experience that fits [Target Company]\'s logistics operations.',
    body: 'I coordinate carriers, warehouses and customer service, track KPIs such as on-time delivery and cost per shipment, and use [WMS/TMS/ERP] for visibility. I handle disruptions calmly and negotiate carrier rates.',
    closing: 'I would welcome a discussion on how I can strengthen your logistics performance.',
    faq: { q: 'What KPIs belong in a logistics manager cover letter?', a: 'On-time delivery, cost per shipment, inventory accuracy and lead-time reduction — whichever you have improved.' },
  }),
  'interior-designer': build({
    roleName: 'interior designer',
    focus: 'a completed project that shows your design approach',
    proof: 'project value or area, number of projects delivered, on-time completion or client retention',
    tools: 'AutoCAD, SketchUp, 3ds Max, Revit and material/vendor knowledge',
    context: "the studio's portfolio, style and typical client segment",
    extraDo: 'Attach or link a portfolio — it matters more than the letter itself',
    extraDont: "Don't describe your style in vague terms; show it through a project",
    opening: 'My recent [residential/commercial] project, [project name], delivered a [style] design on time and within budget — a sensibility I noticed in [Target Studio]\'s portfolio.',
    body: 'I handle concept development, 2D/3D drawings in [software], material selection and site coordination with contractors. I balance aesthetics with budget and buildability.',
    closing: 'I have attached my portfolio and would welcome the chance to discuss your upcoming projects.',
    faq: { q: 'Is a portfolio more important than a cover letter for interior designers?', a: 'Yes. The letter should guide the reader to your best projects in the portfolio and explain why you fit the studio.' },
  }),
  pharmacist: build({
    roleName: 'pharmacist',
    focus: 'your registration and a relevant pharmacy practice area',
    proof: 'prescriptions handled, compliance audits passed, patients counselled or inventory accuracy',
    tools: 'pharmacy software, drug-interaction checks, regulatory compliance and counselling',
    context: "the employer's setting — hospital, retail, clinical or pharma industry",
    extraDo: 'State your registration (State Pharmacy Council) and degree clearly',
    extraDont: "Don't omit regulatory knowledge — compliance is central to the role",
    opening: 'As a registered pharmacist with [N] years in [hospital/retail/clinical] pharmacy at [Company], I am applying for the [role] at [Target Employer].',
    body: 'I dispense accurately, counsel patients on safe medicine use, manage inventory and ensure compliance with Drugs and Cosmetics regulations. I maintain careful documentation and work well with doctors and nurses.',
    closing: 'I would welcome the opportunity to discuss how I can contribute to your pharmacy team.',
    faq: { q: 'What registration details should a pharmacist include?', a: 'Your degree (B.Pharm/M.Pharm/Pharm.D) and State Pharmacy Council registration number, if the role requires it.' },
  }),
  'embedded-systems-engineer': build({
    roleName: 'embedded systems engineer',
    focus: 'a firmware or hardware-software product you brought to working hardware',
    proof: 'memory footprint, boot time, power consumption or defect reductions',
    tools: 'C/C++, RTOS, microcontrollers (ARM Cortex), protocols (I2C, SPI, CAN, UART) and debugging tools',
    context: "the company's products, target hardware and certification requirements",
    extraDo: 'Name the microcontrollers, RTOS and protocols you have used hands-on',
    extraDont: "Don't list only coursework — show a project running on real hardware",
    opening: 'I developed firmware in C for an ARM Cortex-M based [product], reducing [power/memory/boot time] by [X]% — which fits the embedded work at [Target Company].',
    body: 'I write and debug drivers and RTOS tasks, work with I2C, SPI and CAN, and use oscilloscopes and logic analysers for bring-up. I document designs and collaborate closely with hardware teams.',
    closing: 'I would welcome the opportunity to discuss how I can contribute to your embedded team.',
    faq: { q: 'Should embedded engineers mention hardware projects?', a: 'Yes. A project that runs on real hardware, with the MCU, peripherals and result named, is strong evidence for the role.' },
  }),
};
