import { roleSlugs } from '@/lib/roleData';

export interface InterviewData {
  slug: string;
  displayTitle: string;
  questions: Array<{
    q: string;
    answer: string;
    type: 'behavioural' | 'technical' | 'situational';
  }>;
  tips: string[];
}

export const interviewData: Record<string, InterviewData> = {
  'software-engineer': {
    slug: 'software-engineer',
    displayTitle: 'Software Engineer',
    questions: [
      { type: 'technical', q: 'Explain the difference between a process and a thread.', answer: 'A process is an independent program with its own memory space. A thread is a lightweight unit of execution within a process that shares the process\'s memory. Multiple threads within a process can run concurrently and share data, but context switching between threads is faster than between processes. In Java, threads are managed via the Thread class or Runnable interface; in Python, the GIL limits true CPU parallelism for threads.' },
      { type: 'technical', q: 'What is the time complexity of binary search, and when should you use it?', answer: 'Binary search is O(log n) time and O(1) space. Use it on sorted arrays or sorted data structures when you need to find an element quickly. It halves the search space on each comparison. Prefer linear search for unsorted or very small arrays where sorting overhead isn\'t worth it.' },
      { type: 'technical', q: 'How does a HashMap work internally in Java?', answer: 'A HashMap uses an array of buckets. When you call put(key, value), it computes the hash of the key, maps it to a bucket index (hash % array_size), and stores the entry. Hash collisions are handled via chaining (linked list in Java 7, balanced tree in Java 8+ when chain length > 8). Retrieval is O(1) average, O(n) worst case with poor hash distribution. Load factor (default 0.75) triggers resizing.' },
      { type: 'technical', q: 'What is the CAP theorem?', answer: 'CAP states that a distributed system can only guarantee two of three properties simultaneously: Consistency (all nodes see the same data), Availability (every request gets a response), and Partition Tolerance (system works despite network partitions). Since partitions are unavoidable in practice, you choose between CP (consistent but may be unavailable under partition — e.g., HBase, ZooKeeper) and AP (available but eventually consistent — e.g., Cassandra, DynamoDB).' },
      { type: 'technical', q: 'Walk me through how you would design a URL shortener like bit.ly.', answer: 'Key components: (1) Hash function to generate a 6-8 character short code from the long URL — use base62 encoding of a counter or MD5 truncated; (2) Database to store short→long mapping — Redis for cache, PostgreSQL for persistence; (3) 301 vs 302 redirect — 301 is permanent (browser caches, reduces server load), 302 is temporary (better for analytics); (4) Scale with CDN, read replicas, and horizontal scaling of the redirect service. Address collisions with retry logic on hash generation.' },
      { type: 'behavioural', q: 'Tell me about a time you had a major production incident. What did you do?', answer: 'Structure your answer using STAR: Situation (describe the incident and its impact), Task (your role — were you on-call, lead, contributor?), Action (how you diagnosed — logs, metrics, distributed tracing; what you did to mitigate — rollback, feature flag, hotfix), Result (how quickly you restored service, and what post-mortem actions prevented recurrence). Recruiters want to see calmness under pressure, clear communication, and a bias toward mitigation first, root cause second.' },
      { type: 'technical', q: 'What is the difference between SQL and NoSQL databases? When would you choose each?', answer: 'SQL databases (PostgreSQL, MySQL) are relational, schema-defined, ACID-compliant, and excel at complex joins and transactions. NoSQL (MongoDB, Cassandra, Redis) are schema-flexible, horizontally scalable, and optimised for specific access patterns. Choose SQL for financial transactions, complex reporting, and structured data with relationships. Choose NoSQL for high-write-throughput, flexible/evolving schemas, time-series data, or when you need horizontal scale beyond what a single SQL instance handles.' },
      { type: 'situational', q: 'Your team is debating between two technical approaches. You strongly prefer one. How do you handle it?', answer: 'Acknowledge both approaches have merits. Present your preference with data: performance benchmarks, maintainability trade-offs, team familiarity, and long-term cost. Use an RFC (Request for Comments) document for significant decisions. If the team disagrees after full discussion, support the majority decision and commit fully — unless the disagreement is about correctness or security, in which case escalate appropriately.' },
    ],
    tips: [
      'Prepare to whiteboard: data structures, sorting algorithms, and system design are all fair game',
      'For Indian product companies (Groww, CRED, Swiggy), expect system design from SDE-2 level',
      'For IT services (TCS, Infosys), expect more Java/framework-specific questions',
      'Always clarify constraints before coding — interviewers want to see your thought process',
      'Practice on LeetCode with Indian company-specific question lists (available on Glassdoor India)',
    ],
  },
  'data-analyst': {
    slug: 'data-analyst',
    displayTitle: 'Data Analyst',
    questions: [
      { type: 'technical', q: 'Write a SQL query to find the second highest salary in a table.', answer: 'SELECT MAX(salary) FROM employees WHERE salary < (SELECT MAX(salary) FROM employees). Alternative with DENSE_RANK: SELECT salary FROM (SELECT salary, DENSE_RANK() OVER (ORDER BY salary DESC) AS rnk FROM employees) t WHERE rnk = 2. The window function approach handles ties correctly — if two employees share the highest salary, DENSE_RANK still returns a meaningful second.' },
      { type: 'technical', q: 'Explain the difference between INNER JOIN, LEFT JOIN, and FULL OUTER JOIN.', answer: 'INNER JOIN returns rows where the join condition matches in BOTH tables. LEFT JOIN returns ALL rows from the left table and matching rows from the right (NULLs where no match). FULL OUTER JOIN returns all rows from both tables, with NULLs where no match on either side. Most analytical queries use LEFT JOINs to preserve all records from the primary dataset while enriching with dimension data.' },
      { type: 'technical', q: 'What is the difference between a measure and a dimension in a data model?', answer: 'A dimension is a qualitative attribute used to slice/filter data — e.g., product category, geography, customer segment. A measure is a quantitative value that can be aggregated — e.g., revenue, units sold, session count. In a star schema, dimension tables surround the central fact table which contains measures and foreign keys to dimensions. This distinction drives dashboard design in Tableau and Power BI.' },
      { type: 'behavioural', q: 'Describe a time your analysis led to a business decision. What was the impact?', answer: 'Use STAR with these elements: What data you had access to, what question the business had, what analytical technique you used (cohort analysis, funnel analysis, regression, A/B test), what you found, how you communicated it (chart, dashboard, executive summary), and what decision was made. Quantify the outcome: "Led to a ₹40L cost reduction" or "Increased conversion by 12%".' },
      { type: 'technical', q: 'How would you handle missing data in a dataset?', answer: 'First understand WHY data is missing: Missing Completely at Random (MCAR), Missing at Random (MAR), or Missing Not at Random (MNAR). Options: (1) Drop rows if <5% missing and MCAR; (2) Mean/median imputation for numerical, mode for categorical; (3) Forward/backward fill for time-series; (4) Model-based imputation (KNN, MICE) for complex patterns; (5) Flag as a separate category for categorical. Never impute blindly — understand business context first.' },
      { type: 'situational', q: 'A stakeholder disputes your analysis findings. How do you respond?', answer: 'Never dismiss pushback — a stakeholder disputing data often knows something about the business context you don\'t. First, listen to their specific objection. Then: (1) Show your methodology transparently — data source, cleaning steps, aggregation logic; (2) Check if their counter-example reveals a data quality issue; (3) Run the analysis from their perspective and compare; (4) If the dispute is about interpretation not data, involve a neutral third party or senior stakeholder.' },
    ],
    tips: [
      'Expect an SQL test for almost every data analyst role — practice window functions, CTEs, and aggregations',
      'Know your Python or R basics: pandas, matplotlib, and basic statistical functions',
      'Prepare 2-3 stories about business impact from your analyses — not just the methodology',
      'For BFSI roles, expect questions on financial metrics: NPA, CAR, CASA ratio',
      'Dashboard tool questions are common: "How would you design this dashboard in Tableau/Power BI?"',
    ],
  },
  'product-manager': {
    slug: 'product-manager',
    displayTitle: 'Product Manager',
    questions: [
      { type: 'technical', q: 'How would you prioritise a backlog of 50 features with limited engineering bandwidth?', answer: 'Use a structured framework: (1) Map each feature to a business goal and quantify expected impact (revenue, retention, acquisition); (2) Estimate engineering effort in story points or weeks; (3) Calculate ICE score (Impact × Confidence ÷ Effort) or RICE (Reach × Impact × Confidence ÷ Effort); (4) Group into must-have (strategic/committed), should-have, and nice-to-have; (5) Validate top 10 with engineering and stakeholders for feasibility. Communicate rationale transparently to avoid "HiPPO" (Highest Paid Person\'s Opinion) prioritisation.' },
      { type: 'situational', q: 'Tell me about a product you think is poorly designed. How would you improve it?', answer: 'Pick a real product — preferably one your interviewer uses. Diagnose the problem with user empathy: who is the user, what are they trying to do, where does the product fail them? Propose improvements with a user story and success metric. Show that you understand constraints (business model, technical, regulatory) and that your solution is practical, not just aesthetic.' },
      { type: 'behavioural', q: 'Describe a time you had to ship a product with compromises you didn\'t agree with. What did you do?', answer: 'Interviewers want to see: you advocated for your position with data, you understood the business constraint that drove the compromise, you committed fully to the decision once made, and you tracked the impact to validate or disprove the concern. Avoid: blaming stakeholders, pretending you had no concerns, or describing a situation where you overrode the decision unilaterally.' },
      { type: 'technical', q: 'How do you measure the success of a feature after launch?', answer: 'Define success metrics BEFORE launch (not after, to avoid p-hacking). Use a metrics hierarchy: (1) North Star metric — what ultimately matters; (2) Feature-level metric — direct usage signal; (3) Guardrail metrics — things that must not degrade (latency, error rate, other feature engagement). Measure with A/B test where possible. Give it enough time to see statistically significant results. Then do a post-launch review: did the feature solve the user problem, did metrics move, what did we learn?' },
      { type: 'situational', q: 'Engineering says a feature will take 3 months. Business wants it in 4 weeks. What do you do?', answer: 'First clarify: is the 4-week deadline a genuine business constraint (contract, competitive threat, regulatory) or a preference? Then explore: what is the MVP that delivers the core value in 4 weeks? Negotiate scope — not timeline. Work with engineering to identify what can be cut. If 4 weeks is truly impossible for a safe launch, communicate clearly with data on risk, not just "engineering said no". Propose a phased release: limited rollout in 4 weeks, full feature in 3 months.' },
      { type: 'technical', q: 'What is your approach to user research when you have no time or budget?', answer: 'You always have some option: (1) 5 user interviews — 5 well-selected users reveal 80% of usability issues; (2) Analyse existing data — support tickets, NPS verbatims, session recordings (Hotjar/FullStory), search queries; (3) Competitive analysis — what have others validated so you don\'t repeat their experiments; (4) Smoke tests — put up a landing page for an unbuilt feature and measure click-through; (5) Dog-fooding — use the product yourself in the user context. The question tests whether you give up or improvise.' },
    ],
    tips: [
      'Prepare a structured answer for "design a product for X" using Jobs-to-be-Done and user persona frameworks',
      'Know basic SQL — PMs at Indian product companies (Zomato, CRED, Groww) are expected to query data themselves',
      'Study the company\'s product deeply before the interview — use it, read their engineering blog, understand their business model',
      'For APM (Associate PM) roles, leadership potential matters as much as product knowledge',
      'Metric-setting questions are almost universal — practice setting North Star + supporting metrics for common product types',
    ],
  },
};

// Generate stub data for roles without full interview questions
function generateStubInterviewData(slug: string, displayTitle: string): InterviewData {
  return {
    slug,
    displayTitle,
    questions: [
      { type: 'behavioural', q: `Tell me about yourself and why you want this ${displayTitle} role.`, answer: 'Structure your answer in 3 parts: (1) Your current role and key achievements in 2 sentences; (2) What you have done that is specifically relevant to this role — pick 1-2 achievements with metrics; (3) Why this company and role excites you specifically — do your research and be genuine. Keep it under 2 minutes. End with a forward-looking statement that invites the conversation.' },
      { type: 'behavioural', q: 'What is your greatest professional achievement in the last 2 years?', answer: 'Pick an achievement that is: quantified, relevant to the role, and something you owned significantly (not just participated in). Use STAR format — be specific about your contribution vs the team\'s. If you led a team achievement, describe your specific leadership actions. Prepare to go deep — interviewers will ask follow-up questions.' },
      { type: 'situational', q: 'Describe a time you dealt with a difficult stakeholder or colleague. What did you do?', answer: 'Pick a real situation — interviewers detect fabricated stories quickly. Show that you: (1) Sought to understand their perspective before reacting; (2) Used data or structured reasoning to address disagreements; (3) Escalated appropriately when needed; (4) Maintained the professional relationship. Avoid making the other person sound completely unreasonable — that signals low emotional intelligence.' },
      { type: 'behavioural', q: 'Where do you see yourself in 3 years?', answer: 'Show ambition without being unrealistic. Align your answer with the growth trajectory this role offers. Research the company\'s career ladder and articulate how this role fits. Avoid generic answers like "I want to be a manager" — be specific about the skills, impact, and scope you want to develop. Companies want people who will stay and grow, not use the role as a 6-month stepping stone.' },
      { type: 'situational', q: 'How do you handle situations when you have multiple deadlines competing at the same time?', answer: 'Show a system: (1) List everything out to get clarity; (2) Identify true deadlines vs flexible ones by checking with stakeholders; (3) Prioritise by impact and dependency; (4) Communicate proactively if something will be delayed — never go silent; (5) Ask for help early, not at the last minute. Demonstrate that you own your workload management rather than being reactive.' },
      { type: 'behavioural', q: `Why are you leaving your current role, and why does a ${displayTitle} role at this company appeal to you?`, answer: 'Be honest but professional about why you are leaving — growth ceiling, scope limitation, relocation, or company instability are all valid. Never speak negatively about your current employer. Pair your "leaving" reason with a "joining" reason: what specific aspects of this company, team, or role draw you. Research matters here — generic answers like "I want new challenges" signal low engagement.' },
    ],
    tips: [
      `Research the company's ${displayTitle.toLowerCase()} team structure and recent product/business news before your interview`,
      'Prepare 3-4 STAR stories covering: a success, a failure/learning, stakeholder management, and working under pressure',
      'Have intelligent questions ready — asking about team culture, success metrics for the role, and growth paths signals seriousness',
      'For Indian companies, salary negotiation typically happens after offer — research market rates on Glassdoor and LinkedIn Salary',
      'Follow up with a thank-you note within 24 hours — rare in India but consistently impresses hiring managers',
    ],
  };
}

// Detailed interview data for new roles
const newRoleInterviewData: Record<string, InterviewData> = {
  'cloud-architect': {
    slug: 'cloud-architect',
    displayTitle: 'Cloud Architect / Solutions Architect (Cloud)',
    questions: [
      { type: 'technical', q: 'Walk me through how you would design a highly available, multi-region architecture on AWS for a fintech application.', answer: 'Design for active-active or active-passive multi-region depending on RTO/RPO requirements. Core components: (1) Route 53 latency-based or failover routing; (2) Application load balancers per region; (3) EKS clusters in each region with identical workloads; (4) Aurora Global Database for multi-region relational data with sub-1-second replication lag; (5) S3 cross-region replication for object storage; (6) ElastiCache with Redis for session state (with cross-region replication); (7) AWS WAF + Shield Advanced for DDoS protection. For RBI compliance (fintech), ensure data residency is in ap-south-1 (Mumbai). Discuss RTO/RPO: active-active achieves near-zero RTO; active-passive with Aurora Global typically achieves < 1 minute RPO. Cost trade-off: active-active is 2x infrastructure cost but eliminates downtime risk.' },
      { type: 'technical', q: 'Explain the difference between IaC approaches: Terraform vs AWS CloudFormation vs AWS CDK.', answer: 'Terraform (HashiCorp): provider-agnostic, works across AWS/Azure/GCP, state file managed separately (local or S3 backend), HCL language, large module ecosystem. Best for multi-cloud or teams that want vendor neutrality. CloudFormation: AWS-native, tightly integrated with all AWS services, YAML/JSON, managed state in AWS, no additional tooling needed. Best for AWS-only shops that want native integration. AWS CDK: uses real programming languages (Python, TypeScript, Java), compiles to CloudFormation, enables reusable constructs and testing of infrastructure code. Best when your team prefers imperative/OOP patterns. For most Indian enterprise scenarios in 2026, Terraform is the default recommendation due to multi-cloud optionality and ecosystem size. Key interview angle: always discuss state management and drift detection regardless of tool choice.' },
      { type: 'technical', q: 'How do you approach cloud cost optimisation for a company spending ₹2Cr per month on AWS?', answer: 'Start with a FinOps framework: Inform → Optimise → Operate. Immediate wins (30-60 days): (1) Right-sizing — use AWS Compute Optimizer to identify over-provisioned EC2/RDS instances; typical 20-30% waste found; (2) Reserved Instances or Savings Plans — commit 1 or 3 years for predictable workloads; 30-72% discount; (3) Identify unattached EBS volumes, idle Elastic IPs, old EBS snapshots. Medium-term: (4) Spot Instances for fault-tolerant batch workloads (80% discount); (5) S3 lifecycle policies — move infrequent data to Glacier; (6) NAT Gateway cost optimisation — often 15-20% of bills come from data transfer. For ₹2Cr/month spend, realistically target 25-35% reduction (₹50L-₹70L/month savings) with 3-6 months of focused FinOps work. Present findings in a tagged cost allocation report by team/product to drive accountability.' },
      { type: 'behavioural', q: 'Tell me about a cloud migration project you led. What went wrong and how did you handle it?', answer: 'Use STAR format. Key elements to include: (1) Migration scope and complexity — number of workloads, legacy dependencies; (2) Discovery phase — what you found that was not in the original scoping (always something); (3) A specific challenge: database compatibility, network latency, application dependency that was undocumented; (4) How you resolved it — parallel run strategy, phased cutover, rollback plan; (5) What you would do differently. Strong candidates discuss the importance of a detailed discovery and dependency mapping phase before any migration work begins, and the value of running workloads in parallel (pilot migration) before full cutover.' },
      { type: 'technical', q: 'What is a VPC and how would you design the network architecture for a 3-tier application?', answer: 'VPC (Virtual Private Cloud) is an isolated network environment in AWS. 3-tier architecture design: (1) Public Subnet: ALB (Application Load Balancer) and NAT Gateway — internet-facing only; (2) Private Subnet (App Tier): EC2/EKS instances running the application — no direct internet access, outbound via NAT Gateway; (3) Private Subnet (Data Tier): RDS, ElastiCache — no internet routing, only accessible from App Tier via security groups. Across at least 2 AZs for HA. Security controls: Security Groups at instance level (stateful), NACLs at subnet level (stateless). VPC Flow Logs for audit. Transit Gateway for multi-VPC connectivity. For India production environments, always deploy in ap-south-1 Mumbai with multi-AZ.' },
      { type: 'situational', q: 'A business unit wants to use a cloud service that is not in your approved cloud governance framework. How do you handle it?', answer: 'Do not simply block the request — understand the business need first. Steps: (1) Meet with the BU to understand the use case and urgency; (2) Review the service for compliance, security, and cost implications; (3) Check if an approved alternative meets the need; (4) If not, run a fast-track evaluation with security and compliance teams; (5) Document the risk assessment and business case; (6) Escalate to the Cloud Governance Board if above your approval authority. The goal is to enable the business within a governed framework — not to be a blocker. Establish a cloud service approval process that is fast enough that BUs do not feel they need to circumvent governance.' },
    ],
    tips: [
      'Expect deep AWS/GCP service questions — know the difference between ECS and EKS, CloudFront and API Gateway, RDS and Aurora',
      'Prepare cost optimisation case studies with rupee figures — Indian companies expect FinOps awareness at architect level',
      'Know your IaC deeply — Terraform state management and module design questions are common',
      'For Indian IT services interviews (Infosys, Wipro, TCS), expect more process and governance questions; for product companies, expect deeper technical architecture design',
      'Review RBI cybersecurity framework and IT Act compliance — mandatory context for fintech and BFSI cloud roles in India',
    ],
  },
  'cybersecurity-analyst': {
    slug: 'cybersecurity-analyst',
    displayTitle: 'Cybersecurity Analyst',
    questions: [
      { type: 'technical', q: 'Explain the OWASP Top 10 and walk me through how you would test for SQL injection.', answer: 'OWASP Top 10 (2021): A01 Broken Access Control, A02 Cryptographic Failures, A03 Injection, A04 Insecure Design, A05 Security Misconfiguration, A06 Vulnerable Components, A07 Auth Failures, A08 Data Integrity Failures, A09 Logging Failures, A10 SSRF. SQL Injection testing methodology: (1) Identify input fields: URL params, form inputs, headers, cookies; (2) Basic tests: add a single quote \' and observe errors; (3) Boolean-based: input\' AND 1=1-- vs input\' AND 1=2-- and observe response differences; (4) Time-based: \'; WAITFOR DELAY \'0:0:5\'-- for blind SQLi; (5) Tools: SQLmap for automated detection, Burp Suite for manual interception and fuzzing; (6) Verify in a controlled environment only — never test production without written authorisation. Always include false positive verification and document every finding with CVSS score, reproduction steps, and remediation recommendation.' },
      { type: 'technical', q: 'You are a SOC analyst and receive an alert for a large data exfiltration event at 2 AM. Walk me through your incident response.', answer: 'Follow the IR lifecycle: (1) Identification — validate the alert in SIEM (Splunk/QRadar): confirm data volume, source IP, destination IP, user account involved, time range; correlate with other alerts in the same window; (2) Containment — isolate the affected endpoint (network quarantine), disable the user account, block destination IP at firewall; do not shut down the system if forensic preservation is needed; (3) Eradication — identify the attack vector: malware? credential theft? insider? Remove malware, rotate credentials, patch the vulnerability; (4) Recovery — restore from clean backup if system was compromised, monitor for re-infection; (5) Post-incident — document timeline, write IR report, conduct root cause analysis, update runbooks. Communication: notify CISO and relevant BU stakeholders per IR policy. For Indian companies, CERT-IN reporting obligation (within 6 hours for incidents impacting critical infrastructure, under CERT-IN directions 2022).' },
      { type: 'technical', q: 'What is the difference between a vulnerability scan and a penetration test?', answer: 'Vulnerability scan: automated, uses tools (Nessus, Qualys, OpenVAS) to identify known vulnerabilities by comparing system configurations and versions against CVE databases. Fast, broad, low risk. Does not attempt exploitation — only identifies potential weaknesses. Output: list of CVEs with CVSS scores. Penetration test: manual and tool-assisted attempt to actively exploit vulnerabilities to understand real-world impact. Requires scoping document and rules of engagement. Tests for both known and unknown vulnerabilities, business logic flaws, and chained attacks. Output: proof-of-concept exploits, impact assessment, and remediation roadmap. In India, most organisations conduct annual pen tests (required for PCI-DSS and ISO 27001) and continuous vulnerability scanning. Key exam question follow-up: explain the difference between white-box (full system knowledge provided), grey-box (partial knowledge), and black-box (no prior knowledge) penetration testing.' },
      { type: 'behavioural', q: 'Describe a time you discovered a critical security vulnerability. What did you do?', answer: 'Use STAR format. Include: how you discovered it (routine scan, code review, alert, bug bounty research), what the vulnerability was (SQL injection, exposed credentials, misconfigured S3 bucket — be specific), what the potential business impact was (data at risk, compliance violation, regulatory penalty), your responsible disclosure process (who you notified, timeline, escalation path), how it was remediated, and what you did to prevent recurrence. If you have a bug bounty finding or a CVE submission, this is the ideal answer. If describing internal discovery, emphasise the professional handling and the speed of escalation.' },
      { type: 'technical', q: 'How does a man-in-the-middle attack work and how do you defend against it?', answer: 'MITM attack: attacker positions themselves between two communicating parties (client and server) to intercept, read, or modify traffic without either party knowing. Common methods: ARP spoofing (on local network), DNS spoofing, SSL stripping (downgrade HTTPS to HTTP), rogue Wi-Fi hotspot. Defences: (1) TLS/HTTPS with HSTS (HTTP Strict Transport Security) prevents SSL stripping; (2) Certificate pinning in mobile apps; (3) DNSSEC to prevent DNS spoofing; (4) VPN for all remote access; (5) Dynamic ARP Inspection (DAI) on switches to prevent ARP spoofing; (6) Network monitoring with Wireshark or IDS to detect anomalous ARP patterns. In practical terms for Indian corporate environments: enforce HTTPS everywhere, implement HSTS with preloading, deploy a corporate VPN, and use certificate management tools to prevent expired/self-signed certificates.' },
      { type: 'situational', q: 'Your organisation\'s CEO receives a very convincing spear-phishing email that appears to come from the CFO requesting an urgent ₹50L wire transfer. How do you respond?', answer: 'This is a Business Email Compromise (BEC) scenario. Immediate response: (1) Do NOT process the transfer; (2) Contact the real CFO via phone (out-of-band channel — not reply to email) to verify the request; (3) Preserve the phishing email as evidence (headers, content); (4) Analyse the email headers: spoofed domain vs legitimate domain, SPF/DKIM/DMARC failures; (5) Report to IR team and escalate to CISO; (6) If any transfer was attempted, immediately contact the bank to reverse. Preventive measures: DMARC enforcement (p=reject) on company domains, dual-approval policy for wire transfers above a threshold, executive training on BEC patterns. In India, file a cybercrime complaint on cybercrime.gov.in and notify CERT-IN for significant financial fraud attempts.' },
    ],
    tips: [
      'Know the OWASP Top 10 in detail — it comes up in almost every cybersecurity interview in India',
      'Be able to demo or describe Burp Suite, Metasploit, and Nmap workflows — tool-based questions are common in pen test roles',
      'For SOC roles, understand MITRE ATT&CK framework — many Indian SOC teams use it for threat categorisation',
      'BFSI and fintech security roles often ask about RBI Cybersecurity Framework (2016, updated 2023) and CERT-IN reporting obligations',
      'Have 2-3 real incident response stories prepared using the PICERL model (Preparation, Identification, Containment, Eradication, Recovery, Lessons Learned)',
    ],
  },
  'management-consultant': {
    slug: 'management-consultant',
    displayTitle: 'Management Consultant',
    questions: [
      { type: 'technical', q: 'How would you estimate the market size of food delivery apps in India?', answer: 'This is a market sizing (Fermi estimation) question. Use a top-down or bottom-up approach — show your method clearly. Bottom-up: India population ~1.45B. Urban population ~35% = ~500M. Smartphone users in urban India ~350M. App users likely to order online (upper-middle class + young professionals) ~15-20% = ~60-70M active food delivery users. Average order frequency: 4-6 orders/month. Average order value: ₹250-350. Monthly market size: 65M × 5 orders × ₹300 = ₹97,500Cr annually. Adjust for seasonality (10-15% uplift in winters, IPL, Diwali). Cross-check top-down: Zomato + Swiggy combined GMV ~₹60,000-70,000Cr in FY24 — our estimate is in the right range. State assumptions explicitly at each step and invite the interviewer to challenge them.' },
      { type: 'situational', q: 'Your client is an Indian FMCG company facing declining market share in the mid-tier shampoo segment. How would you structure the problem?', answer: 'Use the issue tree or MECE approach. Start by clarifying: What is declining — revenue, volume, or share? Over what time period? Which geographies and channels? Root cause diagnosis: (1) Demand side: consumer preferences changing (premiumisation, naturalisation trend), brand perception weakening; (2) Competition: new entrants (D2C brands) or incumbents with better pricing; (3) Distribution: reduced shelf share, e-commerce gap; (4) Product: formulation, packaging, or value proposition misalignment; (5) Pricing: positioned too high for mid-tier or squeezed by private labels. Hypothesis: Based on the shampoo market context, likely diagnosis involves combination of D2C brand incursion and channel mix shift (e-commerce underdeveloped). Data needed: category scanner data (Nielsen), brand track (awareness, consideration, preference), channel-wise sell-through, competitor pricing and promotion analysis. Solutions will follow diagnosis — avoid jumping to recommendations before data.' },
      { type: 'technical', q: 'Walk me through how you would build a financial model for a new product launch decision.', answer: 'A business case financial model for a product launch should include: (1) Revenue assumptions: TAM → SAM → market share ramp (Year 1: 2%, Year 3: 8%), price per unit, volume forecast by channel; (2) Cost structure: COGS (variable — raw materials, packaging, manufacturing), Gross Margin; then fixed costs (marketing investment, distribution set-up, head count); (3) P&L: Revenue → Gross Profit → EBITDA → EBIT. Project 5 years; (4) Break-even analysis: how many units/months to cover fixed investment; (5) NPV / IRR: discount future cash flows at WACC (typically 12-15% for Indian consumer companies); (6) Scenario analysis: base, bull, bear — vary key assumptions (market share, price, volume); (7) Sensitivities: tornado chart to show which variables most impact NPV. Deliver a clear investment thesis: this launch is NPV-positive if we achieve X% market share at Y price point within Z months.' },
      { type: 'behavioural', q: 'Tell me about a time you had to deliver difficult news to a client or senior stakeholder. How did you handle it?', answer: 'Consulting interviews heavily probe communication under pressure. Strong answer structure: (1) Context: who was the stakeholder and what was the difficult finding; (2) Preparation: how did you validate the finding before presenting it (data, cross-checks, peer review); (3) Delivery: what framing you used (data-first vs empathy-first), what you anticipated as pushback; (4) Reaction: how the stakeholder responded; (5) Outcome: what decision was ultimately made and what the result was. The ideal example shows that you delivered an unwelcome truth professionally, maintained the client relationship, and the difficult news ultimately led to a better outcome. Avoid examples where you softened findings to avoid conflict — consultants are hired for honest counsel.' },
      { type: 'technical', q: 'A retailer\'s profitability is declining. Their revenue is growing but EBITDA margins have compressed by 5 percentage points over 2 years. What would you investigate?', answer: 'Revenue growing but margins declining means cost growth is outpacing revenue growth. Decompose the P&L: (1) Gross margin: has COGS grown disproportionately? Input cost inflation? Product mix shift to lower-margin categories? Discounting to drive volume? (2) Sales & Distribution: new channel investments (quick commerce, D2C) with high cost-to-serve? Delivery subsidies? (3) Marketing spend: CAC increasing for the same revenue? Paid media inflation? (4) Employee costs: headcount growth, compensation inflation? (5) Occupancy/supply chain: new warehouses, dark stores, last-mile infrastructure? Each hypothesis needs data to validate. Prioritise: quick commerce expansion is a common culprit for Indian retailers — high customer acquisition cost and delivery subsidy destroys unit economics even when GMV grows. Present findings in a 2x2: revenue contribution vs profitability drag.' },
      { type: 'situational', q: 'You are 2 days before a major client presentation. Your team\'s analysis reveals a finding that contradicts the hypothesis you have been pursuing for 3 weeks. What do you do?', answer: 'This tests intellectual honesty, time management, and stakeholder management under pressure. Do not ignore the finding or selectively present data. Steps: (1) Validate the finding quickly — have another team member replicate the analysis to rule out error; (2) If valid, immediately discuss with your engagement manager; (3) Decide: does this change the recommendation materially? Can the presentation be restructured in 48 hours? Is a partial delivery + follow-up the right answer?; (4) Notify the client proactively if the presentation narrative will change significantly — never surprise a client with a 180-degree pivot in the room; (5) Reframe the story: new finding may actually be more valuable than the original hypothesis. In consulting, early revelation of a counterintuitive truth is a mark of intellectual rigour, not a failure.' },
    ],
    tips: [
      'Practice case interviews extensively — MBB and Big 4 use structured case formats (market sizing, profitability, market entry, M&A) in every round',
      'Know Indian business context deeply: FMCG market dynamics, BFSI regulatory landscape, e-commerce unit economics, government policy levers',
      'Develop a consistent problem-structuring framework: MECE issue trees, hypothesis-driven approach, 80/20 prioritisation of analysis',
      'Be ready for "personal experience" questions that probe your leadership, analytical rigour, and professional conduct — these are weighted equally to case performance at MBB',
      'For Big 4 consulting interviews in India, sector-specific knowledge (healthcare, BFSI, consumer) matters more than for MBB, which prizes problem-solving generalism',
    ],
  },
  'data-engineer': {
    slug: 'data-engineer',
    displayTitle: 'Data Engineer',
    questions: [
      { type: 'technical', q: 'Explain the difference between batch processing and stream processing. When would you choose each?', answer: 'Batch processing: processes large volumes of data at scheduled intervals (hourly, daily). Tools: Apache Spark, AWS Glue, dbt. Characteristics: high latency (data is not fresh until next batch), simpler error handling (re-run the batch), lower infrastructure cost. Use cases: daily reporting, end-of-day reconciliation, model training data preparation, historical analysis. Stream processing: processes data in real-time as events arrive. Tools: Apache Kafka + Flink, Kinesis Data Analytics, Spark Structured Streaming. Characteristics: low latency (seconds to milliseconds), more complex state management and fault tolerance, higher cost. Use cases: fraud detection, real-time dashboards, user activity feeds, IoT sensor alerting. Lambda architecture combines both. In practice (India 2026): most data teams start with batch and add streaming for specific high-value use cases (fraud, recommendations). dbt + Airflow for batch; Kafka + Flink for streaming are the standard stacks.' },
      { type: 'technical', q: 'Walk me through how you would design a data pipeline to ingest 500GB of daily transaction data from 10 source systems into a data warehouse.', answer: 'Design in 3 layers: Ingestion → Processing → Serving. Ingestion: Use CDC (Change Data Capture) tools like Debezium for databases, or Kafka Connectors for event sources; store raw data in S3 (data lake) in Parquet format, partitioned by date. Processing: Apache Airflow for orchestration — one DAG per source system; PySpark or AWS Glue for transformation; dbt for business logic transformation in the warehouse layer. Warehouse: Snowflake or BigQuery — partition tables by transaction_date; cluster by merchant_id or user_id for query performance. Data Quality: Great Expectations or dbt tests for null checks, referential integrity, volume anomaly detection. Monitoring: Airflow alerts for DAG failures; data freshness SLA monitoring. Error handling: DLQ (Dead Letter Queue) for failed records, automated retry with exponential backoff. For 500GB daily, Spark on EMR or Glue can process this in under 1 hour in practice.' },
      { type: 'technical', q: 'What is dbt and how does it improve the data transformation workflow?', answer: 'dbt (data build tool) is a transformation framework that allows data analysts and engineers to write transformation logic as SQL SELECT statements, with dbt handling the materialisation (views, tables, incremental models), dependency management, testing, and documentation. Key improvements: (1) Version control: all transformation SQL lives in Git, enabling code review, rollbacks, and CI/CD; (2) Testing: built-in data quality tests (not_null, unique, accepted_values, relationships) run automatically; (3) Documentation: auto-generated data lineage and column-level docs; (4) Dependency management: dbt automatically resolves model dependencies and executes in the right order; (5) Incremental models: only process new/changed records, not full table refreshes. In practice, dbt sits in the T of ELT pipelines — after data is loaded into the warehouse, dbt transforms it into clean, tested, documented data models. Used with Snowflake, BigQuery, Redshift, or Databricks.' },
      { type: 'behavioural', q: 'Tell me about a time a data pipeline you owned went down in production. How did you respond?', answer: 'Use STAR. Key elements: (1) What was the pipeline and what it supported (downstream dashboards, ML models, business reports); (2) How you detected the failure (monitoring alert, stakeholder complaint, scheduled check); (3) Diagnosis process: what you checked first (recent code changes, source system issues, resource constraints, upstream data anomalies); (4) Remediation: hotfix, backfill strategy, communication to stakeholders; (5) Root cause and prevention. Good answer characteristics: proactive monitoring (not discovered by a stakeholder), systematic diagnosis, clear communication to affected business users, and a post-mortem that led to a durable fix (improved tests, alerts, runbooks). Demonstrates: technical problem-solving, ownership mindset, communication under pressure.' },
      { type: 'technical', q: 'What is the difference between a data warehouse, data lake, and data lakehouse?', answer: 'Data Warehouse: structured, schema-on-write, optimised for SQL query performance, typically holds curated, business-ready data. Examples: Snowflake, BigQuery, Redshift. Best for business analysts running complex aggregation queries. Data Lake: stores raw data in any format (Parquet, JSON, CSV, binary) at low cost in object storage (S3, GCS). Schema-on-read. Scales to petabytes cheaply. Requires data engineering to make usable. Best for data science (raw feature extraction) and archival. Data Lakehouse: combines the cost advantages of data lakes with the performance and governance of data warehouses. Open table formats: Delta Lake (Databricks), Apache Iceberg (Snowflake, BigQuery, EMR), Apache Hudi. Supports ACID transactions, time travel, and schema enforcement on object storage. Best of both worlds. In India 2026: most modern data platforms are moving toward lakehouse architectures — Databricks (Delta Lake) and Snowflake (Iceberg support) are the leading implementations.' },
      { type: 'situational', q: 'The analytics team reports that your dashboard numbers do not match the finance team\'s numbers for the same metric. How do you investigate?', answer: 'Data discrepancy investigation process: (1) Identify the specific metric, time period, and the magnitude of the discrepancy; (2) Trace both numbers to their source: what query or report generates each figure? (3) Compare data sources: do the analytics and finance teams use the same underlying data source? (4) Check business logic differences: is "revenue" defined the same way — is it gross or net? Does it include or exclude cancelled orders, refunds, GST? (5) Check the time zone and cut-off time: analytics may use UTC, finance may use IST; (6) Check for double-counting or data quality issues: duplicate transaction IDs, unprocessed records. Most data discrepancies in Indian companies come from different business logic definitions, not technical errors. Resolution: document the agreed definition and create a single source of truth data model that all teams use, governed by a data dictionary.' },
    ],
    tips: [
      'Know Airflow concepts deeply — DAG design, XComs, task dependencies, and backfill strategy are common interview topics',
      'Be able to write SQL window functions, CTEs, and incremental refresh logic on a whiteboard — SQL depth is tested at every level',
      'Understand the difference between Spark RDDs, DataFrames, and Datasets conceptually — even if you only work at the DataFrame level day-to-day',
      'For Flipkart, Swiggy, Zomato, and PhonePe interviews, expect system design questions for data platforms: design a real-time fraud detection pipeline, design an event tracking system at 1M events/second',
      'Know dbt architecture (models, tests, sources, macros) in detail — it is now a standard expectation at most product company data engineering roles in India',
    ],
  },
  'android-developer': {
    slug: 'android-developer',
    displayTitle: 'Android Developer',
    questions: [
      { type: 'technical', q: 'Explain the Android Activity lifecycle and what happens when a user rotates the screen.', answer: 'Activity lifecycle: onCreate → onStart → onResume (active) → onPause → onStop → onDestroy. When the screen rotates: the current Activity is destroyed and recreated (onDestroy → onCreate). This causes data loss unless preserved. Solutions: (1) ViewModel (Jetpack): survives configuration changes; the ViewModel is NOT destroyed on rotation, so UI state stored in ViewModel is preserved; (2) onSaveInstanceState(): bundle-based state preservation for simple data (strings, primitives) — called before onStop; (3) rememberSaveable in Jetpack Compose: equivalent to onSaveInstanceState for Compose state. Best practice: store ephemeral UI state in ViewModel (user input, list scroll position), persistent data in Room or DataStore, and avoid putting large objects in savedInstanceState bundles. In Jetpack Compose, Activity is often used as a host; composables manage their own lifecycle through LaunchedEffect, DisposableEffect, and LifecycleOwner.' },
      { type: 'technical', q: 'What is the difference between MVVM and MVI architectures in Android? Which do you prefer and why?', answer: 'MVVM (Model-View-ViewModel): ViewModel exposes state via LiveData or StateFlow; View observes and renders; user actions call ViewModel methods directly. Bidirectional data flow — View can directly call ViewModel methods. MVI (Model-View-Intent): strict unidirectional data flow; user interactions produce Intents; Reducer function maps current State + Intent → new State; View only renders State. More predictable, easier to test, better for complex screens. Differences: MVI enforces single source of truth (one immutable state object), prevents multiple subscribers from seeing inconsistent state, and makes debugging easier (replay events to reproduce bugs). MVVM is simpler for straightforward screens. In production Android (India 2026): MVVM with Kotlin StateFlow is the most common pattern; MVI is increasingly preferred for complex screens (checkout flows, form-heavy UIs). Jetpack Compose pairs naturally with both — prefer MVI for composable screens with complex state interactions.' },
      { type: 'technical', q: 'How do Kotlin Coroutines work and how do you handle errors in a coroutine?', answer: 'Coroutines are Kotlin\'s approach to asynchronous programming. Key concepts: CoroutineScope (defines the lifetime — viewModelScope, lifecycleScope), CoroutineContext (Dispatchers: Main for UI, IO for network/disk, Default for CPU), and suspension points (functions marked with suspend). Launch vs async: launch fires and forgets; async returns a Deferred that you await for a result. Error handling: (1) try/catch inside the coroutine: catches exceptions at the point of failure; (2) CoroutineExceptionHandler: catches uncaught exceptions in the coroutine scope (last resort); (3) SupervisorScope vs CoroutineScope: in a regular CoroutineScope, a child failure cancels all siblings; in a SupervisorScope, child failures are independent. For Android ViewModel: use viewModelScope.launch { try { /* network call */ } catch (e: Exception) { /* update error state */ } }. Structured concurrency ensures that when a scope is cancelled (e.g., ViewModel cleared), all coroutines in it are cancelled.' },
      { type: 'behavioural', q: 'Tell me about a time you significantly improved the performance of an Android app. What did you measure and what did you change?', answer: 'Use STAR. Performance improvement examples: (1) Cold start time: measured with Android Studio Profiler and reportFullyDrawn() API; identified heavy synchronous work in Application.onCreate() — moved database initialisation to a background thread and used App Startup library for sequential initialisation; reduced cold start from 3.2s to 1.4s; (2) ANR (Application Not Responding) reduction: analysed ANR traces via Android Vitals in Play Console; found main thread blocking on SharedPreferences read; migrated to DataStore (async API) and eliminated the ANR category; (3) Memory leaks: used LeakCanary to identify Activity reference held by a static singleton; fixed with WeakReference and scope correction. Key: always tie performance work to measurable Play Store metrics (ANR rate, crash-free rate, Play Store rating) — these are the business outcomes that matter to product companies.' },
      { type: 'technical', q: 'Explain Jetpack Compose and how it differs from the traditional View-based UI system.', answer: 'Jetpack Compose is Android\'s declarative UI framework, replacing XML-based View inflation. Key differences: (1) Declarative vs imperative: Compose describes what the UI should look like given current state; View system requires explicit update calls (setText(), setVisibility()); (2) Composition vs inheritance: Compose uses function composition (smaller, composable UI functions); View system uses class inheritance hierarchies; (3) State-driven: Compose re-renders when state changes (using remember, mutableStateOf, StateFlow); View system requires manual view updates; (4) No XML: all UI in Kotlin code, enabling type safety, code reuse, and IDE refactoring support; (5) Performance: Compose skips re-composing unchanged parts (smart recomposition); View system redraws entire subtrees. When migrating from Views: use ComposeView to embed Compose in existing Activities/Fragments (interoperability API). In India 2026: Compose is the default for new Android development at product companies; XML is still dominant in legacy IT services codebases.' },
      { type: 'situational', q: 'Your app\'s crash rate on Play Console spikes from 0.5% to 3.5% after a release. How do you investigate and respond?', answer: 'Immediate response within the first hour: (1) Check Play Console: identify the crash by package name, exception type, and top affected devices/OS versions; (2) Check if it is a crash or ANR — different root causes; (3) Look at the crash stack trace in Crashlytics or Play Console; (4) Identify the release that caused it: which commit, which feature? (5) Decision: if crash rate is above 1.5% on a core flow, initiate an emergency rollback via Play Console\'s rollout management (halt the rollout percentage at current level or roll back to previous version); (6) Fix in development: reproduce locally, write a regression test, fix the root cause; (7) Re-release with the fix after testing. Communication: notify product and QA teams immediately; update status page if the app is a critical service. Prevention: add crash rate monitoring to the CI/CD pipeline — block release if Crashlytics reports above a threshold in staged rollout.' },
    ],
    tips: [
      'Know Kotlin Coroutines, Flow, and StateFlow deeply — they are tested in every Android interview at product companies in India',
      'Be prepared to explain MVVM vs MVI vs Clean Architecture — and defend your preferred choice with concrete reasoning',
      'For Jetpack Compose questions, know recomposition, state hoisting, side effects (LaunchedEffect, DisposableEffect), and remember vs rememberSaveable',
      'Swiggy, Zomato, PhonePe, and CRED interviews often include system design for mobile: design an offline-first app, design an image caching layer, design a payment flow with retry logic',
      'Know Play Console metrics — ANR rate, crash-free rate, Core Web Vitals for Android — product companies expect Android engineers to monitor and own app quality metrics',
    ],
  },
};

export const interviewMap: Record<string, InterviewData> = {};

// Import roleSlugs is done at module level via the export above
// We build this at module-init time using the roleSlugs list
for (const slug of roleSlugs) {
  const displayTitle = slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');

  interviewMap[slug] =
    interviewData[slug] ?? newRoleInterviewData[slug] ?? generateStubInterviewData(slug, displayTitle);
}
