export interface RoleData {
  slug: string;
  title: string;
  displayTitle: string;
  industry: string;
  metaDescription: string;
  keywords: string[];
  heroHeading: string;
  heroSubheading: string;
  whatToInclude: string[];
  commonMistakes: string[];
  keySkills: string[];
  salaryRange: string;
  topCompanies: string[];
  faqs: Array<{ q: string; a: string }>;
}

export const roles: RoleData[] = [
  {
    slug: 'software-engineer',
    title: 'Software Engineer CV',
    displayTitle: 'Software Engineer',
    industry: 'Technology',
    metaDescription:
      'Free software engineer CV example and template for India. ATS-optimised, with skills, projects, and experience sections for SDE roles at TCS, Infosys, Amazon, and startups.',
    keywords: ['software engineer cv', 'software developer resume india', 'SDE resume template', 'software engineer resume example', 'backend developer cv', 'full stack developer resume', 'software engineer cv india'],
    heroHeading: 'Software Engineer CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised software engineer CV for Indian tech companies, MNCs, and startups. Includes skills section, project highlights, and GitHub portfolio linking.',
    whatToInclude: ['Technical skills section with languages, frameworks, and tools (grouped by category)', 'Project highlights with GitHub links and impact metrics', 'Work experience with outcome-driven bullets (not just "built X")', 'Education with CGPA if above 7.5 (for freshers and campus hires)', 'Certifications: AWS, GCP, Azure, Kubernetes, etc.', 'Open-source contributions if any'],
    commonMistakes: ['Listing every technology you\'ve ever touched — focus on what you\'re strong in', 'Generic bullets like "Worked on backend systems" — quantify impact', 'Missing the skills section ATS needs to extract technology keywords', 'Including a photo — not expected in tech CVs in India', 'Using a table-based layout — breaks most ATS parsers'],
    keySkills: ['Python', 'Java', 'JavaScript', 'React', 'Node.js', 'AWS', 'Docker', 'SQL', 'Git', 'System Design'],
    salaryRange: '₹4L – ₹45L+ depending on experience and company',
    topCompanies: ['Google', 'Amazon', 'Microsoft', 'Flipkart', 'Swiggy', 'Zomato', 'TCS', 'Infosys', 'Wipro', 'Razorpay'],
    faqs: [
      { q: 'How long should a software engineer CV be in India?', a: 'For 0–3 years experience: 1 page. For 4–8 years: 1–2 pages. For 8+ years: 2 pages maximum. Recruiters at product companies (Amazon, Google) prefer 1 page regardless of experience.' },
      { q: 'Should I include my CGPA on my software engineer CV?', a: 'Yes, if it is 7.5 or above and you have less than 3 years of experience. For experienced engineers, CGPA is irrelevant — drop it after your second job.' },
      { q: 'How do I write bullets for a software engineer CV?', a: 'Use the format: Action verb + what you built/did + measurable impact. Example: "Reduced API response time by 40% by migrating from REST to GraphQL, cutting server costs by ₹2L/month."' },
    ],
  },
  {
    slug: 'data-analyst',
    title: 'Data Analyst CV',
    displayTitle: 'Data Analyst',
    industry: 'Analytics',
    metaDescription: 'Free data analyst CV example for India. ATS-ready template with SQL, Python, Tableau, and Power BI skills. Used by analysts at Flipkart, Swiggy, consulting firms, and banks.',
    keywords: ['data analyst cv', 'data analyst resume india', 'data analyst resume example', 'business analyst cv template', 'sql analyst resume', 'data analyst cv india 2026'],
    heroHeading: 'Data Analyst CV — example, template & writing guide for India 2026',
    heroSubheading: 'Build an ATS-optimised data analyst CV highlighting your SQL, Python, and visualisation skills. Used by analysts at top Indian startups, consulting firms, and banks.',
    whatToInclude: ['Technical skills: SQL, Python/R, Tableau/Power BI, Excel, Google Sheets', 'Work experience with data-driven bullets: "Analysed 2M+ rows of transactional data to..."', 'Projects section with dataset source, tools used, and business impact', 'Education — data analytics certifications (Google Data Analytics, Coursera, etc.)', 'Domain expertise: BFSI, e-commerce, healthcare, etc.'],
    commonMistakes: ['Listing tools without showing output — always include what the analysis produced', 'No mention of business impact — "built a dashboard" vs "built a dashboard that reduced reporting time by 60%"', 'Missing SQL explicitly — it is the most screened keyword for analyst roles', 'Overly long paragraphs — bullet points are easier to parse for recruiters'],
    keySkills: ['SQL', 'Python', 'Excel', 'Power BI', 'Tableau', 'R', 'Google Analytics', 'A/B Testing', 'Statistical Analysis'],
    salaryRange: '₹3.5L – ₹25L depending on experience and sector',
    topCompanies: ['Flipkart', 'Amazon', 'McKinsey', 'Deloitte', 'HDFC Bank', 'Paytm', 'Swiggy', 'Meesho', 'Ola'],
    faqs: [
      { q: 'What is the most important skill to show on a data analyst CV?', a: 'SQL. Every data analyst JD screens for it. Make sure SQL appears in your Skills section and at least 2 experience bullets mention it explicitly.' },
      { q: 'Should a data analyst CV include a portfolio?', a: 'Yes. Include a link to your Kaggle profile, GitHub, or a personal dashboard. Even one well-documented project with a public dataset significantly improves conversion.' },
    ],
  },
  {
    slug: 'product-manager',
    title: 'Product Manager CV',
    displayTitle: 'Product Manager',
    industry: 'Product Management',
    metaDescription: 'Free product manager CV example for India. ATS-optimised PM resume template with metrics, roadmap experience, and cross-functional leadership. For FAANG, startups, and Indian tech.',
    keywords: ['product manager cv', 'product manager resume india', 'PM resume example', 'product manager cv template india', 'APM resume', 'senior product manager cv'],
    heroHeading: 'Product Manager CV — example, template & tips for Indian PM roles 2026',
    heroSubheading: 'Build a metrics-driven product manager CV that demonstrates your impact on growth, retention, and revenue. Used by PMs at Zomato, Razorpay, Flipkart, and FAANG.',
    whatToInclude: ['Metrics-rich bullets: "Increased Day-30 retention by 12% by redesigning onboarding flow"', 'Product sense examples: discovery, prioritisation, roadmap decisions', 'Cross-functional collaboration: worked with engineering, design, data', 'Tools: Jira, Mixpanel, Amplitude, Figma, SQL (even basic)', 'User research and A/B test experience'],
    commonMistakes: ['Listing features shipped without business impact — always add the metric', '"Managed product roadmap" is table stakes — show what the roadmap achieved', 'No evidence of data-driven decisions — PMs without analytics signal are weak candidates', 'Oversized summaries — 3 lines max, lead with your biggest metric'],
    keySkills: ['Product Strategy', 'Roadmapping', 'A/B Testing', 'SQL', 'Jira', 'Amplitude', 'Figma', 'Agile', 'OKRs', 'User Research'],
    salaryRange: '₹12L – ₹60L+ depending on company tier and experience',
    topCompanies: ['Google', 'Amazon', 'Zomato', 'Razorpay', 'CRED', 'PhonePe', 'Meesho', 'Groww', 'Flipkart'],
    faqs: [
      { q: 'Do I need an MBA to be a product manager in India?', a: 'No. Most Indian startups and product companies prefer engineering backgrounds with demonstrated product thinking over MBA credentials. A strong portfolio and metrics-driven CV matters more.' },
      { q: 'How many bullet points per role on a PM CV?', a: '3–5 bullets per role. Each bullet must have a metric. One bullet without a number is fine if the impact is clear; two bullets without numbers is too many.' },
    ],
  },
  {
    slug: 'marketing-manager',
    title: 'Marketing Manager CV',
    displayTitle: 'Marketing Manager',
    industry: 'Marketing',
    metaDescription: 'Free marketing manager CV example for India. ATS-optimised template covering digital marketing, performance, brand, and content roles. Templates for FMCG, D2C, and SaaS.',
    keywords: ['marketing manager cv', 'marketing resume india', 'digital marketing cv template', 'marketing manager resume example india', 'brand manager cv', 'performance marketing resume'],
    heroHeading: 'Marketing Manager CV — example, template & tips for India 2026',
    heroSubheading: 'Write a results-driven marketing manager CV that shows CAC reduction, revenue influenced, and campaign ROI. Covers digital, brand, content, and performance marketing.',
    whatToInclude: ['Campaign metrics: ROAS, CAC, MQL volume, email open rates, organic traffic growth', 'Channels managed: Google Ads, Meta, SEO, CRM, influencer, ATL/BTL', 'Tools: HubSpot, Salesforce, Clevertap, Google Analytics, Meta Ads Manager', 'Budget ownership — "managed ₹1.2Cr annual marketing budget"', 'Team leadership and agency management'],
    commonMistakes: ['No metrics — "ran campaigns" tells recruiters nothing; "grew organic traffic 3x" does', 'Listing channels without results — every channel should have a performance metric attached', 'Ignoring MarTech tools — they are heavily screened in most JDs for marketing roles'],
    keySkills: ['Google Ads', 'Meta Ads', 'SEO', 'Email Marketing', 'HubSpot', 'Google Analytics', 'Content Strategy', 'Brand Management', 'A/B Testing'],
    salaryRange: '₹6L – ₹35L depending on specialisation and seniority',
    topCompanies: ['HUL', 'P&G', 'Myntra', 'Nykaa', 'boAt', 'Mamaearth', 'Bombay Shaving Company', 'Razorpay', 'Freshworks'],
    faqs: [
      { q: 'Should a marketing CV focus on digital or traditional skills?', a: 'For most Indian companies in 2026, digital-first. Even FMCG giants now weigh digital marketing heavily. Lead with digital metrics; include traditional (ATL/BTL) only if the JD asks for it.' },
    ],
  },
  {
    slug: 'hr-manager',
    title: 'HR Manager CV',
    displayTitle: 'HR Manager',
    industry: 'Human Resources',
    metaDescription: 'Free HR manager CV example for India. ATS-optimised template covering talent acquisition, HRBP, L&D, and operations. For IT, FMCG, and services sector HR roles.',
    keywords: ['hr manager cv', 'human resources resume india', 'HR resume template', 'talent acquisition resume', 'HRBP resume india', 'HR generalist cv', 'hr manager resume example'],
    heroHeading: 'HR Manager CV — example, template & writing tips for India 2026',
    heroSubheading: 'Build an ATS-optimised HR manager CV covering recruitment, HRBP, L&D, and operations. Includes metrics for time-to-hire, attrition, and employee engagement.',
    whatToInclude: ['Hiring metrics: "Reduced time-to-hire from 45 to 22 days", "Sourced 120+ hires in FY24"', 'HRBP work: grievance resolution, performance management, succession planning', 'Tools: Darwinbox, SuccessFactors, BambooHR, Workday, LinkedIn Recruiter', 'Attrition and engagement metrics where available', 'L&D programs designed or delivered', 'Labour law compliance: POSH, PF, ESI, Shops Act'],
    commonMistakes: ['"Managed recruitment" without numbers — always add headcount, TAT, or source mix', 'Missing HR tech tools — screened heavily in most JDs', 'Not differentiating generalist vs specialist scope — be specific'],
    keySkills: ['Talent Acquisition', 'HRBP', 'Darwinbox', 'SAP SuccessFactors', 'Performance Management', 'Labour Law', 'L&D', 'Employee Engagement'],
    salaryRange: '₹4L – ₹25L depending on specialisation and company size',
    topCompanies: ['TCS', 'Infosys', 'HUL', 'Amazon India', 'Deloitte', 'Accenture', 'Zomato', 'HDFC Bank'],
    faqs: [
      { q: 'Should an HR CV include employee count managed?', a: 'Yes, always. "HR Business Partner for 600-employee engineering division" is far more impactful than "Handled HRBP responsibilities". Scale shows scope.' },
    ],
  },
  {
    slug: 'finance-analyst',
    title: 'Finance Analyst CV',
    displayTitle: 'Finance Analyst',
    industry: 'Finance',
    metaDescription: 'Free finance analyst CV example for India. ATS-optimised template for FP&A, corporate finance, investment banking, and CA roles. For BFSI, Big 4, and corporate finance teams.',
    keywords: ['finance analyst cv', 'finance resume india', 'FP&A resume', 'investment banking cv india', 'CA resume template', 'financial analyst resume example', 'corporate finance cv'],
    heroHeading: 'Finance Analyst CV — example, template & tips for Indian finance roles 2026',
    heroSubheading: 'Build an ATS-optimised finance analyst CV for FP&A, investment banking, Big 4, and corporate finance. Covers financial modelling, budgeting, and reporting.',
    whatToInclude: ['Financial modelling skills: DCF, LBO, three-statement, scenario analysis', 'ERP tools: SAP, Oracle Financials, Tally, QuickBooks', 'Key metrics: "Managed ₹50Cr annual budget", "Reduced reporting cycle from 5 to 2 days"', 'CA / CFA / CMA qualifications prominently placed', 'Industry exposure: BFSI, manufacturing, IT, consulting'],
    commonMistakes: ['No scale indicators — always show the size of budgets, portfolios, or transactions you\'ve handled', 'Missing qualifications section — CA rank, CFA level, and CMA are heavily screened', 'Generic bullets like "Prepared MIS reports" — add the frequency, stakeholder, and decision impact'],
    keySkills: ['Financial Modelling', 'SAP', 'Excel', 'FP&A', 'Budgeting', 'Variance Analysis', 'DCF', 'Power BI', 'SQL', 'IFRS/Ind AS'],
    salaryRange: '₹5L – ₹40L+ depending on qualification and company tier',
    topCompanies: ['Goldman Sachs', 'JP Morgan', 'HDFC Bank', 'Deloitte', 'PWC', 'EY', 'KPMG', 'Bajaj Finance', 'Reliance', 'Tata Group'],
    faqs: [
      { q: 'Should a CA include their AIR rank on their CV?', a: 'Yes, if it is in the top 500. For ranks beyond 500, just state "Chartered Accountant (ICAI)" with your passing year — the rank adds less signal at that range.' },
    ],
  },
  // ── New roles added for programmatic SEO scale ────────────────────────────
  {
    slug: 'business-analyst',
    title: 'Business Analyst CV',
    displayTitle: 'Business Analyst',
    industry: 'Consulting & Strategy',
    metaDescription: 'Free business analyst CV example for India. ATS-optimised BA resume template with requirement gathering, process mapping, and stakeholder management. For IT, BFSI, and consulting.',
    keywords: ['business analyst cv', 'business analyst resume india', 'BA resume template', 'business analyst cv example', 'business analyst resume 2026', 'IT business analyst cv india'],
    heroHeading: 'Business Analyst CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised business analyst CV covering requirements, process improvement, and stakeholder management. Used by BAs at IT companies, banks, and consulting firms across India.',
    whatToInclude: ['Requirements elicitation and documentation experience', 'Process mapping tools: Visio, Lucidchart, BPMN', 'Agile/Scrum experience with sprint participation', 'Stakeholder management and workshop facilitation', 'Domain knowledge: BFSI, retail, telecom, or healthcare', 'Tools: JIRA, Confluence, MS Project, SQL for data validation'],
    commonMistakes: ['Vague bullets like "gathered requirements" — specify the domain, scale, and outcome', 'Not distinguishing IT BA from business-side BA — be explicit about your scope', 'Missing process improvement metrics — e.g., "Reduced process cycle time by 30%"', 'No mention of Agile if the company uses it — check the JD'],
    keySkills: ['Requirements Gathering', 'Process Mapping', 'JIRA', 'Agile', 'SQL', 'Stakeholder Management', 'BPMN', 'User Stories', 'Visio', 'Gap Analysis'],
    salaryRange: '₹4L – ₹22L depending on domain and experience',
    topCompanies: ['Accenture', 'Infosys BPM', 'Wipro', 'TCS', 'Capgemini', 'HDFC Bank', 'ICICI Bank', 'Mu Sigma', 'ThoughtWorks'],
    faqs: [
      { q: 'What is the difference between a Business Analyst and a Data Analyst CV?', a: 'A Business Analyst CV emphasises process improvement, requirements gathering, and stakeholder management. A Data Analyst CV focuses on data querying (SQL), visualisation (Tableau/Power BI), and statistical analysis. BAs bridge business and IT; DAs focus on insights from data.' },
      { q: 'Should I include UML diagrams or wireframes in a BA CV?', a: 'Mention the tools and types of artefacts you produce (use case diagrams, wireframes, process flows) rather than attaching them. Include a portfolio link if you have one.' },
    ],
  },
  {
    slug: 'frontend-developer',
    title: 'Frontend Developer CV',
    displayTitle: 'Frontend Developer',
    industry: 'Technology',
    metaDescription: 'Free frontend developer CV example for India. ATS-optimised template with React, Next.js, JavaScript, and UI/UX skills. For fresher and experienced frontend engineers at Indian startups and MNCs.',
    keywords: ['frontend developer cv', 'react developer resume india', 'frontend engineer resume', 'javascript developer cv', 'UI developer resume india', 'frontend developer cv template'],
    heroHeading: 'Frontend Developer CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised frontend developer CV showcasing your React, JavaScript, and UI skills. Perfect for roles at Indian product companies, startups, and MNCs.',
    whatToInclude: ['Core skills: HTML, CSS, JavaScript/TypeScript, React, Next.js, Vue', 'Performance metrics: "Improved Lighthouse score from 62 to 94"', 'Project portfolio with live links and GitHub repos', 'Testing experience: Jest, Cypress, React Testing Library', 'Accessibility (a11y) experience if any', 'Design collaboration: Figma, Zeplin'],
    commonMistakes: ['No live links — always include deployed projects', 'Listing jQuery/Bootstrap in 2026 as primary skills — show modern stack', 'Missing TypeScript — screened in almost all mid-to-senior frontend JDs', 'Underemphasising performance work — page speed is a key signal'],
    keySkills: ['React', 'Next.js', 'TypeScript', 'JavaScript', 'CSS', 'Tailwind CSS', 'REST APIs', 'Git', 'Jest', 'Figma'],
    salaryRange: '₹3.5L – ₹35L depending on seniority and stack',
    topCompanies: ['Flipkart', 'Razorpay', 'CRED', 'Swiggy', 'Dunzo', 'Zoho', 'Freshworks', 'Cleartax', 'BrowserStack'],
    faqs: [
      { q: 'Should a frontend developer include design skills on their CV?', a: 'Yes, especially Figma proficiency. Even basic ability to read and interpret designs is worth listing. Full UI/UX skills are a significant differentiator for frontend roles at product companies.' },
      { q: 'How important is a portfolio for frontend developer roles?', a: 'Critical. A deployed portfolio with 2–3 strong projects can outweigh a weaker academic background. Include a link in your CV header. GitHub alone is insufficient — show live, working products.' },
    ],
  },
  {
    slug: 'backend-developer',
    title: 'Backend Developer CV',
    displayTitle: 'Backend Developer',
    industry: 'Technology',
    metaDescription: 'Free backend developer CV example for India. ATS-optimised with Node.js, Python, Java, databases, and API design. For mid-level and senior backend engineers at Indian tech companies.',
    keywords: ['backend developer cv', 'backend engineer resume india', 'node.js developer resume', 'java developer cv india', 'python backend developer resume', 'API developer cv'],
    heroHeading: 'Backend Developer CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-ready backend developer CV emphasising system design, API architecture, and database performance. Trusted by engineers targeting Indian product companies and MNCs.',
    whatToInclude: ['Languages and runtimes: Node.js, Python, Java, Go, Rust', 'Databases: PostgreSQL, MySQL, MongoDB, Redis, Elasticsearch', 'System design concepts: microservices, event-driven, caching, queues', 'Performance wins: "Reduced DB query time by 70% through indexing"', 'Cloud: AWS/GCP/Azure services you have used in production', 'Message queues: Kafka, RabbitMQ, SQS'],
    commonMistakes: ['No mention of scale — always include data volume, QPS, or uptime metrics', 'Missing database work — backend engineers who don\'t mention SQL/NoSQL look incomplete', 'Not listing specific cloud services (just "AWS" is weaker than "AWS Lambda, S3, RDS, SQS")', 'Ignoring monitoring and observability — Datadog, Grafana, CloudWatch signal maturity'],
    keySkills: ['Node.js', 'Python', 'Java', 'PostgreSQL', 'MongoDB', 'Redis', 'REST APIs', 'AWS', 'Docker', 'Microservices'],
    salaryRange: '₹5L – ₹40L depending on experience, stack, and company',
    topCompanies: ['Amazon', 'Microsoft', 'Razorpay', 'PhonePe', 'CRED', 'Zepto', 'Meesho', 'Groww', 'Zerodha'],
    faqs: [
      { q: 'Should a backend developer include system design on their CV?', a: 'Yes, from mid-level onwards. Mention specific architectural decisions you\'ve made: "Designed event-driven architecture using Kafka that reduced latency by 40%." It signals seniority and is heavily assessed in interviews.' },
    ],
  },
  {
    slug: 'data-scientist',
    title: 'Data Scientist CV',
    displayTitle: 'Data Scientist',
    industry: 'Data Science & AI',
    metaDescription: 'Free data scientist CV example for India. ATS-optimised with ML, Python, TensorFlow, and statistics skills. For data science roles at Flipkart, Ola, startups, and research labs.',
    keywords: ['data scientist cv', 'data scientist resume india', 'machine learning engineer resume', 'ML engineer cv india', 'data science resume template', 'AI engineer cv'],
    heroHeading: 'Data Scientist CV — example, template & tips for India 2026',
    heroSubheading: 'Write an ATS-optimised data scientist CV that proves your ML skills with deployed models and business impact. Used by data scientists at top Indian and global tech companies.',
    whatToInclude: ['ML frameworks: TensorFlow, PyTorch, Scikit-learn, XGBoost', 'Projects with model accuracy, business impact, and deployment context', 'Research papers or Kaggle competition rankings if applicable', 'Statistics depth: hypothesis testing, regression, Bayesian methods', 'Big data: Spark, Hadoop, BigQuery, Databricks', 'MLOps: model deployment, monitoring, retraining pipelines'],
    commonMistakes: ['Listing ML libraries without deployment context — "trained a model" vs "deployed model serving 2M predictions/day"', 'No business impact — academic accuracy metrics alone don\'t impress product companies', 'Overloading with buzzwords (GPT, LLM, GenAI) without substance — be specific about what you built', 'Missing statistics fundamentals — data scientists who can\'t explain p-values fail basic screening'],
    keySkills: ['Python', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'SQL', 'Statistics', 'Spark', 'MLflow', 'AWS SageMaker', 'Feature Engineering'],
    salaryRange: '₹8L – ₹60L depending on experience and specialisation',
    topCompanies: ['Google', 'Amazon', 'Microsoft Research', 'Flipkart', 'Ola', 'Fractal Analytics', 'Mu Sigma', 'Tiger Analytics', 'Tata AI'],
    faqs: [
      { q: 'Should a data scientist include Kaggle rankings on their CV?', a: 'Yes, if you are in the top 10% for any competition. A Kaggle Expert or Master title is a strong signal. For freshers, a well-documented Kaggle notebook is often more valuable than academic coursework.' },
      { q: 'How do I show GenAI/LLM experience on my data scientist CV?', a: 'Specify the model, use case, and impact. "Fine-tuned Llama 3 on domain-specific data, achieving 23% improvement in task accuracy, deployed via FastAPI serving 50K requests/day" is strong. Generic "worked with LLMs" is not.' },
    ],
  },
  {
    slug: 'devops-engineer',
    title: 'DevOps Engineer CV',
    displayTitle: 'DevOps Engineer',
    industry: 'Technology',
    metaDescription: 'Free DevOps engineer CV example for India. ATS-optimised with Kubernetes, Docker, CI/CD, AWS, and infrastructure-as-code. For DevOps and SRE roles at Indian tech companies.',
    keywords: ['devops engineer cv', 'devops resume india', 'kubernetes engineer resume', 'cloud engineer cv india', 'SRE resume template', 'infrastructure engineer cv', 'CI/CD engineer resume'],
    heroHeading: 'DevOps Engineer CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised DevOps engineer CV showcasing Kubernetes, CI/CD, infrastructure-as-code, and SRE practices. Used by DevOps engineers at cloud-first Indian and global companies.',
    whatToInclude: ['Container orchestration: Kubernetes, Docker, Helm, Docker Compose', 'CI/CD pipelines: Jenkins, GitLab CI, GitHub Actions, ArgoCD', 'Infrastructure as Code: Terraform, Ansible, Pulumi, CloudFormation', 'Cloud platforms: AWS, GCP, Azure (list specific services)', 'Monitoring: Prometheus, Grafana, Datadog, ELK stack', 'SRE metrics: uptime improvements, MTTR reduction, incident reduction'],
    commonMistakes: ['No reliability metrics — always include uptime, MTTR, or deployment frequency improvements', 'Listing tools without scale: "managed Kubernetes" vs "managed 50-node Kubernetes cluster serving 10M requests/day"', 'Missing security: certificate management, secrets handling, RBAC', 'Not mentioning cost optimisation — cloud cost reduction is a strong differentiator'],
    keySkills: ['Kubernetes', 'Docker', 'Terraform', 'AWS', 'Jenkins', 'GitHub Actions', 'Prometheus', 'Grafana', 'Linux', 'Python/Bash'],
    salaryRange: '₹6L – ₹45L depending on seniority and cloud depth',
    topCompanies: ['Amazon AWS', 'Microsoft Azure', 'Google Cloud', 'Atlassian', 'ThoughtWorks', 'Razorpay', 'Flipkart', 'Swiggy', 'Urban Company'],
    faqs: [
      { q: 'What certifications matter most for a DevOps CV in India?', a: 'AWS Solutions Architect, CKA (Certified Kubernetes Administrator), and Terraform Associate are the most recognised. AWS certifications have the widest recognition among Indian employers. CKA is essential for infrastructure-heavy roles.' },
    ],
  },
  {
    slug: 'sales-manager',
    title: 'Sales Manager CV',
    displayTitle: 'Sales Manager',
    industry: 'Sales & Business Development',
    metaDescription: 'Free sales manager CV example for India. ATS-optimised with revenue targets, quota attainment, and team leadership metrics. For B2B, SaaS, FMCG, and enterprise sales roles.',
    keywords: ['sales manager cv', 'sales manager resume india', 'business development resume', 'B2B sales cv india', 'enterprise sales resume', 'sales director cv india'],
    heroHeading: 'Sales Manager CV — example, template & tips for India 2026',
    heroSubheading: 'Write a quota-driven sales manager CV packed with revenue numbers, team size, and client portfolio metrics. Covers B2B, SaaS, FMCG, and enterprise sales roles in India.',
    whatToInclude: ['Revenue metrics: "Achieved 134% of ₹8Cr annual quota in FY24"', 'Team size and territory: "Managed 12-person team across South India"', 'Client portfolio: key accounts, industry segments, deal sizes', 'CRM proficiency: Salesforce, HubSpot, Zoho CRM', 'Sales methodology: SPIN, Challenger, MEDDIC, consultative selling', 'Pipeline metrics: conversion rates, average deal cycle, win rates'],
    commonMistakes: ['No revenue numbers — a sales CV without numbers is immediately weak', 'Generic bullets like "managed client relationships" — specify account value and outcome', 'Missing quota attainment percentage — it\'s the primary signal recruiters look for', 'Not specifying B2B vs B2C — they are very different skill sets'],
    keySkills: ['Revenue Generation', 'Salesforce', 'B2B Sales', 'Team Leadership', 'Key Account Management', 'Pipeline Management', 'Negotiation', 'CRM', 'Forecasting'],
    salaryRange: '₹6L – ₹40L fixed + variable depending on industry and seniority',
    topCompanies: ['HUL', 'ITC', 'Freshworks', 'Zoho', 'Tata Motors', 'Asian Paints', 'Marico', 'Swiggy for Business', 'Razorpay'],
    faqs: [
      { q: 'How should I present commission and variable pay on a sales CV?', a: 'Show your total compensation range or on-target earnings (OTE) in your summary if relevant. In bullets, focus on quota attainment percentage rather than absolute rupee figures — 134% quota is more universally understood than "earned ₹32L".' },
    ],
  },
  {
    slug: 'ui-ux-designer',
    title: 'UI/UX Designer CV',
    displayTitle: 'UI/UX Designer',
    industry: 'Design',
    metaDescription: 'Free UI/UX designer CV example for India. ATS-optimised designer resume with Figma, user research, and design systems skills. For product design roles at startups and MNCs.',
    keywords: ['ui ux designer cv', 'product designer resume india', 'UX designer cv template', 'UI designer resume example', 'figma designer cv', 'ux designer resume india 2026'],
    heroHeading: 'UI/UX Designer CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised UI/UX designer CV showcasing your Figma skills, design systems experience, and user research outcomes. Portfolio links essential.',
    whatToInclude: ['Portfolio link prominently in the header — this is your primary credential', 'Tools: Figma, Sketch, Adobe XD, InVision, Principle', 'Design systems experience: created or contributed to component libraries', 'User research methods: user interviews, usability testing, heuristic evaluation', 'Outcome-driven bullets: "Redesigned checkout flow that reduced drop-off by 22%"', 'Cross-functional collaboration with product and engineering'],
    commonMistakes: ['No portfolio link — a designer CV without a portfolio is almost always rejected', 'Describing aesthetics instead of outcomes — "designed a beautiful dashboard" vs "redesigned dashboard that reduced support tickets by 40%"', 'Missing research skills — pure visual designers are less competitive than research + design profiles', 'Using a heavily designed CV template — ironically, these often fail ATS'],
    keySkills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Usability Testing', 'Wireframing', 'Information Architecture', 'Adobe Creative Suite', 'Interaction Design'],
    salaryRange: '₹4L – ₹30L depending on portfolio strength and company tier',
    topCompanies: ['Razorpay', 'CRED', 'Swiggy', 'Urban Company', 'Dream11', 'Navi', 'Groww', 'PhonePe', 'Myntra'],
    faqs: [
      { q: 'Should a UI/UX designer use a designed CV or a plain one?', a: 'Use a clean, minimally designed CV for job applications. Heavily designed CVs with sidebars, columns, and icons frequently fail ATS parsing. Your portfolio is where you demonstrate visual design — your CV should demonstrate clarity.' },
    ],
  },
  {
    slug: 'project-manager',
    title: 'Project Manager CV',
    displayTitle: 'Project Manager',
    industry: 'Project Management',
    metaDescription: 'Free project manager CV example for India. ATS-optimised PM resume with PMP, Agile, and delivery metrics. For IT, construction, consulting, and infrastructure project management roles.',
    keywords: ['project manager cv', 'project manager resume india', 'PMP resume template', 'IT project manager cv', 'agile project manager resume', 'scrum master cv india'],
    heroHeading: 'Project Manager CV — example, template & tips for India 2026',
    heroSubheading: 'Write an ATS-optimised project manager CV with delivery metrics, budget ownership, and stakeholder management. Covers IT, infrastructure, and consulting PM roles.',
    whatToInclude: ['Project scale: budget managed, team size, timeline, geography', 'Delivery metrics: "Delivered ₹12Cr ERP implementation 2 weeks ahead of schedule"', 'Certifications: PMP, PRINCE2, CSM, PMI-ACP', 'Tools: MS Project, Jira, Asana, Monday.com, Smartsheet', 'Risk management and mitigation examples', 'Stakeholder management up to C-suite level'],
    commonMistakes: ['No project scale — recruiters cannot assess seniority without budget/team/timeline figures', '"Managed multiple projects" with no specifics — every PM manages multiple projects', 'Missing certifications section — PMP is a strong signal in India for PM roles', 'Neglecting soft skill evidence — stakeholder conflicts resolved, escalations handled'],
    keySkills: ['Project Planning', 'Agile/Scrum', 'PMP', 'Risk Management', 'MS Project', 'Jira', 'Budget Management', 'Stakeholder Management', 'Resource Allocation'],
    salaryRange: '₹7L – ₹35L depending on domain and years of experience',
    topCompanies: ['Accenture', 'Infosys', 'Wipro', 'L&T', 'IBM', 'Cognizant', 'Capgemini', 'HCL Technologies', 'Tata Projects'],
    faqs: [
      { q: 'Is PMP certification worth listing on an Indian project manager CV?', a: 'Yes, significantly. PMP is the most recognised PM certification globally and among Indian employers. It typically results in a 10–20% salary premium and preferential shortlisting. List it prominently near your name if you hold it.' },
    ],
  },
  {
    slug: 'content-writer',
    title: 'Content Writer CV',
    displayTitle: 'Content Writer',
    industry: 'Marketing & Content',
    metaDescription: 'Free content writer CV example for India. ATS-optimised writer resume with SEO, content strategy, and portfolio links. For D2C brands, SaaS, media, and digital agencies.',
    keywords: ['content writer cv', 'content writer resume india', 'copywriter resume template', 'SEO content writer cv', 'content strategist cv', 'digital content writer resume india'],
    heroHeading: 'Content Writer CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised content writer CV with portfolio links, SEO metrics, and audience growth data. Used by writers at D2C brands, SaaS companies, and digital agencies.',
    whatToInclude: ['Portfolio link in the header — essential for content roles', 'SEO metrics: keyword rankings, organic traffic grown, DA of publications', 'Content types: blog posts, white papers, case studies, email sequences, ad copy', 'Volume and output: "Published 40+ long-form articles/month"', 'Tools: WordPress, HubSpot, Ahrefs, SEMrush, Grammarly, Hemingway', 'Industries covered: SaaS, fintech, health, e-commerce'],
    commonMistakes: ['No portfolio link — the single biggest mistake on a content writer CV', 'Generic bullets — "wrote blog posts" without traffic, ranking, or engagement data', 'Missing SEO skills — most content writer JDs in 2026 require at least basic SEO', 'Not specifying tone/brand voice experience — enterprise and D2C require different skills'],
    keySkills: ['SEO Writing', 'Content Strategy', 'WordPress', 'Ahrefs', 'Email Marketing', 'Copywriting', 'Long-form Content', 'Social Media', 'Editorial Planning'],
    salaryRange: '₹2.5L – ₹18L depending on niche, SEO depth, and seniority',
    topCompanies: ['Razorpay', 'Cleartax', 'Nykaa', 'Sprinklr', 'Freshworks', 'UpGrad', 'Unacademy', 'HubSpot India', 'Zoho'],
    faqs: [
      { q: 'What is the most important element of a content writer CV?', a: 'Portfolio. A link to 5 published, high-quality articles outweighs any amount of experience description. Use Contently, a personal site, or a curated Google Drive folder. Include traffic data where you can.' },
    ],
  },
  {
    slug: 'operations-manager',
    title: 'Operations Manager CV',
    displayTitle: 'Operations Manager',
    industry: 'Operations & Supply Chain',
    metaDescription: 'Free operations manager CV example for India. ATS-optimised ops resume with process improvement, P&L, and team leadership metrics. For e-commerce, logistics, FMCG, and manufacturing.',
    keywords: ['operations manager cv', 'operations resume india', 'supply chain manager cv', 'logistics manager resume india', 'operations manager cv template', 'COO resume india'],
    heroHeading: 'Operations Manager CV — example, template & tips for India 2026',
    heroSubheading: 'Write an ATS-optimised operations manager CV with P&L ownership, cost reduction, and process improvement metrics. Covers e-commerce, logistics, FMCG, and manufacturing.',
    whatToInclude: ['P&L ownership or cost budgets managed', 'Process improvement metrics: "Reduced warehouse cycle time by 35%"', 'Team size and geography: "Managed 200-person operations across 3 states"', 'ERP and tech: SAP, Oracle, WMS, Salesforce', 'Lean/Six Sigma experience if applicable', 'Vendor management and SLA performance'],
    commonMistakes: ['No operational metrics — ops CVs without numbers signal lack of impact ownership', 'Missing scale — headcount, revenue influenced, or geography are essential context', 'Generic process descriptions — be specific about the methodology (Lean, 5S, Kaizen, Six Sigma)', 'Ignoring tech tools — modern ops roles require ERP, WMS, and BI tool proficiency'],
    keySkills: ['Process Improvement', 'P&L Management', 'SAP', 'Lean Six Sigma', 'Supply Chain', 'Vendor Management', 'Team Leadership', 'KPI Management', 'WMS'],
    salaryRange: '₹6L – ₹40L depending on industry, scale, and seniority',
    topCompanies: ['Amazon India', 'Flipkart', 'Delhivery', 'Blue Dart', 'ITC', 'HUL', 'Marico', 'Zomato', 'Swiggy'],
    faqs: [
      { q: 'Is Six Sigma certification valuable on an operations manager CV in India?', a: 'Yes, especially in manufacturing, FMCG, and large-scale operations. Green Belt is the minimum meaningful level; Black Belt is a strong differentiator. Mention specific projects with quantified savings if you have them.' },
    ],
  },
  {
    slug: 'civil-engineer',
    title: 'Civil Engineer CV',
    displayTitle: 'Civil Engineer',
    industry: 'Engineering & Infrastructure',
    metaDescription: 'Free civil engineer CV example for India. ATS-optimised template with project management, AutoCAD, and site execution skills. For infrastructure, construction, and government projects.',
    keywords: ['civil engineer cv', 'civil engineer resume india', 'structural engineer resume', 'site engineer cv india', 'construction engineer resume', 'civil engineer cv freshers india'],
    heroHeading: 'Civil Engineer CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised civil engineer CV covering site execution, structural design, and project management. Covers infrastructure, government, and private construction roles in India.',
    whatToInclude: ['Project portfolio with value, location, and completion status', 'Technical skills: AutoCAD, STAAD.Pro, Revit, MS Project, Primavera', 'Site execution experience: supervision, quality control, safety compliance', 'Contractors and vendors managed', 'Budget and timeline adherence metrics', 'IS codes and standards knowledge relevant to the role'],
    commonMistakes: ['No project values — "supervised construction" vs "supervised ₹45Cr residential tower construction"', 'Missing software tools — AutoCAD and MS Project are screened in most JDs', 'Not specifying civil sub-discipline: structural, geotechnical, water resources, transportation', 'Leaving out certifications: PE exam, CPWD approvals, safety certifications'],
    keySkills: ['AutoCAD', 'STAAD.Pro', 'MS Project', 'Revit', 'Structural Design', 'Site Execution', 'Quality Control', 'Quantity Surveying', 'Project Management'],
    salaryRange: '₹3L – ₹20L for freshers to experienced; higher for senior/project director roles',
    topCompanies: ['L&T Construction', 'Shapoorji Pallonji', 'Tata Projects', 'NCC Limited', 'GMR Group', 'NHAI', 'CPWD', 'Godrej Properties', 'DLF'],
    faqs: [
      { q: 'Should a fresh civil engineering graduate include college projects in their CV?', a: 'Absolutely. For freshers with no work experience, final-year projects, internships, and site visits during studies are the primary evidence of technical capability. Include the project type, methods used, software tools, and any faculty or industry supervisor who can verify the work.' },
    ],
  },
  {
    slug: 'mechanical-engineer',
    title: 'Mechanical Engineer CV',
    displayTitle: 'Mechanical Engineer',
    industry: 'Engineering & Manufacturing',
    metaDescription: 'Free mechanical engineer CV example for India. ATS-optimised with CAD, manufacturing, and product design skills. For automotive, aerospace, FMCG, and heavy engineering roles.',
    keywords: ['mechanical engineer cv', 'mechanical engineer resume india', 'manufacturing engineer resume', 'CAD engineer cv india', 'product design engineer resume', 'mechanical engineer freshers cv'],
    heroHeading: 'Mechanical Engineer CV — example, template & tips for India 2026',
    heroSubheading: 'Write an ATS-optimised mechanical engineer CV covering CAD, manufacturing processes, and product development. For automotive, defence, FMCG, and engineering companies in India.',
    whatToInclude: ['CAD software: SolidWorks, AutoCAD, CATIA, ANSYS, Creo', 'Manufacturing processes: CNC, injection moulding, sheet metal, welding', 'Product development lifecycle experience', 'Quality standards: ISO 9001, GD&T, FMEA', 'Internships with reputed manufacturers if fresher', 'Metrics: "Reduced component weight by 18% through design optimisation"'],
    commonMistakes: ['Not specifying CAD software — "proficient in CAD" without naming the tool is meaningless to ATS', 'No manufacturing context — show which processes and materials you have worked with', 'Missing quality certification knowledge — ISO, GD&T, and QMS are frequently screened', 'Overselling theory without practical application'],
    keySkills: ['SolidWorks', 'AutoCAD', 'ANSYS', 'CATIA', 'Manufacturing Processes', 'GD&T', 'FMEA', 'Lean Manufacturing', 'Project Management'],
    salaryRange: '₹2.5L – ₹18L depending on specialisation and industry',
    topCompanies: ['Tata Motors', 'Mahindra', 'Bajaj Auto', 'L&T', 'Bosch India', 'Cummins', 'Caterpillar India', 'ISRO', 'DRDO'],
    faqs: [
      { q: 'What is the best software to know as a mechanical engineer in India?', a: 'SolidWorks and AutoCAD are most widely used in Indian manufacturing. CATIA is essential for automotive (Tata Motors, Mahindra). ANSYS is valued for R&D and simulation roles. For aerospace and defence, Creo and NASTRAN are relevant.' },
    ],
  },
  {
    slug: 'nursing',
    title: 'Nurse CV',
    displayTitle: 'Nurse / Nursing Professional',
    industry: 'Healthcare',
    metaDescription: 'Free nurse CV example for India. ATS-optimised nursing resume with clinical skills, specialisations, and registrations. For hospital, clinic, and international nursing roles.',
    keywords: ['nurse cv india', 'nursing resume india', 'staff nurse cv template', 'RN resume india', 'nursing cv example', 'hospital nurse resume india'],
    heroHeading: 'Nurse CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised nurse CV showcasing clinical skills, patient care experience, and regulatory registrations. For staff nurses, ICU nurses, and international nursing applicants.',
    whatToInclude: ['NMC/INC registration number and validity', 'Specialisation: ICU, OT, paediatrics, emergency, oncology, etc.', 'Patient care capacity: "Managed 12-patient ICU ward independently"', 'Clinical procedures: IV cannulation, wound care, ventilator management', 'Certifications: BLS, ACLS, NRP', 'Hospital name, bed strength, and department type for each role'],
    commonMistakes: ['Missing NMC registration — mandatory for Indian nursing CVs', 'No specialisation mentioned — "worked in a hospital" is not enough', 'Listing duties only — include patient ratios and procedures performed', 'Ignoring international format requirements for UAE/UK/Canada applications'],
    keySkills: ['Patient Care', 'ICU Management', 'BLS/ACLS', 'Medication Administration', 'Wound Care', 'Ventilator Management', 'EMR/EHR', 'Triage', 'IV Cannulation'],
    salaryRange: '₹2.5L – ₹12L in India; ₹25L–₹60L+ for Gulf/UK placements',
    topCompanies: ['Apollo Hospitals', 'Fortis Healthcare', 'Manipal Hospitals', 'AIIMS', 'Aster DM Healthcare', 'Max Healthcare', 'Medanta', 'KIMS Hospitals'],
    faqs: [
      { q: 'What format should a nurse CV follow for Gulf countries?', a: 'Gulf nursing CVs (UAE, Saudi Arabia, Qatar) should include: full name, nationality, date of birth, NMC/equivalent registration, HAAD/DHA/SCFHS eligibility if applicable, passport details section, and a professional photo. Use a 2-page format and include every hospital and department you have worked in.' },
      { q: 'Should Indian nurses include their NMC registration on their CV?', a: 'Absolutely — it is the first thing any employer verifies. Place it immediately after your name and contact details. Include the registration number, issuing council (INC/State NMC), and validity date.' },
    ],
  },
  {
    slug: 'electrical-engineer',
    title: 'Electrical Engineer CV',
    displayTitle: 'Electrical Engineer',
    industry: 'Engineering',
    metaDescription: 'Free electrical engineer CV example for India. ATS-optimised with power systems, PLC, AutoCAD Electrical, and panel design skills. For energy, manufacturing, and infrastructure roles.',
    keywords: ['electrical engineer cv', 'electrical engineer resume india', 'power systems engineer cv', 'PLC engineer resume', 'electrical engineer cv freshers', 'panel design engineer resume india'],
    heroHeading: 'Electrical Engineer CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised electrical engineer CV covering power systems, PLC/SCADA, panel design, and project execution for energy and manufacturing roles across India.',
    whatToInclude: ['Specialisation: power systems, instrumentation, PLC/SCADA, panel design', 'Software: EPLAN, AutoCAD Electrical, MATLAB, ETAP', 'Project scale and type: HT/LT, solar, DG, substations, MCC panels', 'Certifications: IE rules, CBIP, energy auditor', 'Vendors managed: ABB, Siemens, Schneider, L&T Switchgear', 'Standards: IS, IEC, IEEE compliance experience'],
    commonMistakes: ['Not specifying voltage level — HT vs LT experience is critical context', 'Missing software tools — AutoCAD Electrical and EPLAN are heavily screened', 'No project value or capacity figures', 'Generic "electrical maintenance" without specifying systems or equipment'],
    keySkills: ['AutoCAD Electrical', 'EPLAN', 'PLC/SCADA', 'Power Systems', 'Panel Design', 'ETAP', 'Switchgear', 'Energy Audit', 'Project Management'],
    salaryRange: '₹2.5L – ₹20L depending on specialisation and industry',
    topCompanies: ['L&T', 'Siemens', 'ABB India', 'Schneider Electric', 'Tata Power', 'BHEL', 'NTPC', 'Power Grid', 'Adani Energy'],
    faqs: [
      { q: 'What certifications are most valuable for an electrical engineer in India?', a: 'CBIP (Central Board of Irrigation and Power) for power sector roles. BEE Certified Energy Auditor for energy management. GATE qualification for PSU roles (NTPC, BHEL, Power Grid). For instrumentation roles, ISA certifications are respected.' },
    ],
  },
  {
    slug: 'accountant',
    title: 'Accountant CV',
    displayTitle: 'Accountant',
    industry: 'Finance & Accounting',
    metaDescription: 'Free accountant CV example for India. ATS-optimised with Tally, SAP, GST, and financial reporting skills. For accounting roles at CA firms, corporates, and SMEs.',
    keywords: ['accountant cv india', 'accountant resume india', 'accounts executive cv', 'tally accountant resume', 'GST accountant cv', 'senior accountant resume india'],
    heroHeading: 'Accountant CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised accountant CV covering Tally, SAP, GST compliance, and financial reporting for CA firms, corporations, and SMEs across India.',
    whatToInclude: ['Software: Tally ERP, SAP FI/CO, QuickBooks, Zoho Books', 'Compliance: GST filing, TDS, ROC, income tax returns', 'Financial reporting: balance sheets, P&L, cash flow statements', 'Audit experience if any: internal audit, statutory audit', 'Volume handled: "Managed books for ₹12Cr turnover company"', 'CA qualification or inter level if pursuing'],
    commonMistakes: ['Not listing Tally — it is the most screened tool for Indian accountant roles', 'Missing GST experience — essential for almost every accounting role post-2017', 'No financial scale — always mention turnover or transaction volume', 'Vague compliance experience — specify return types and filing frequency'],
    keySkills: ['Tally ERP', 'SAP FI', 'GST Filing', 'TDS', 'Financial Reporting', 'Bank Reconciliation', 'Accounts Payable/Receivable', 'MIS', 'Audit'],
    salaryRange: '₹2.5L – ₹15L depending on experience and company size',
    topCompanies: ['Deloitte', 'PwC', 'EY', 'KPMG', 'Grant Thornton', 'HDFC Bank', 'Reliance', 'Tata Group', 'Infosys BPO'],
    faqs: [
      { q: 'Is CA Inter qualification worth mentioning on an accountant CV?', a: 'Absolutely. CA Inter (Intermediate) is a strong signal that distinguishes you from basic commerce graduates. Mention the groups cleared, attempt number, and percentage/marks. Even a failed attempt followed by re-attempt shows persistence, so only omit if asked.' },
    ],
  },
  {
    slug: 'supply-chain-manager',
    title: 'Supply Chain Manager CV',
    displayTitle: 'Supply Chain Manager',
    industry: 'Operations & Logistics',
    metaDescription: 'Free supply chain manager CV example for India. ATS-optimised with procurement, logistics, inventory, and vendor management skills. For FMCG, e-commerce, manufacturing, and pharma.',
    keywords: ['supply chain manager cv', 'supply chain resume india', 'procurement manager cv', 'logistics manager resume india', 'inventory manager cv', 'SCM resume india'],
    heroHeading: 'Supply Chain Manager CV — example, template & tips for India 2026',
    heroSubheading: 'Write an ATS-optimised supply chain manager CV covering procurement, inventory, logistics, and vendor management. For FMCG, e-commerce, manufacturing, and pharma roles in India.',
    whatToInclude: ['Procurement savings: "Negotiated ₹3.2Cr annual savings through vendor consolidation"', 'Inventory metrics: turnover ratio, fill rate, days of inventory', 'Vendor base managed: number, categories, annual spend', 'ERP: SAP MM/SD, Oracle SCM, Dynamics 365', 'Logistics KPIs: on-time delivery, freight cost per unit, OTIF', 'Certifications: CSCP, CPIM, Six Sigma'],
    commonMistakes: ['No cost savings — supply chain CVs without financial impact signal are weak', 'Missing ERP — SAP MM/WM is screened in most senior SCM JDs', 'Not specifying category — direct vs indirect procurement are different skills', 'Generic "managed vendors" without vendor count, spend, or categories'],
    keySkills: ['SAP MM', 'Procurement', 'Inventory Management', 'Vendor Management', 'Logistics', 'Demand Planning', 'S&OP', 'CPIM', 'Cost Reduction', 'Warehouse Management'],
    salaryRange: '₹6L – ₹35L depending on company size and specialisation',
    topCompanies: ['Amazon India', 'Flipkart', 'HUL', 'ITC', 'Marico', 'Dr Reddy\'s', 'Cipla', 'Delhivery', 'Blue Dart', 'Mahindra Logistics'],
    faqs: [
      { q: 'Is CSCP or CPIM more recognised in India?', a: 'Both are well-regarded. CPIM (Certified in Production and Inventory Management) is more widely recognised in manufacturing and pharma. CSCP (Certified Supply Chain Professional) is preferred in e-commerce and FMCG. Either certification typically results in preferential shortlisting for SCM roles above ₹10L CTC.' },
    ],
  },
  {
    slug: 'teacher',
    title: 'Teacher CV',
    displayTitle: 'Teacher / Educator',
    industry: 'Education',
    metaDescription: 'Free teacher CV example for India. ATS-optimised teaching resume with subject expertise, board experience, and curriculum delivery. For school, coaching, and EdTech roles.',
    keywords: ['teacher cv india', 'teacher resume india', 'school teacher cv template', 'teacher cv example', 'B.Ed resume india', 'teaching resume india 2026'],
    heroHeading: 'Teacher CV — example, template & tips for India 2026',
    heroSubheading: 'Write an ATS-optimised teacher CV showcasing your subject expertise, board experience, and student outcomes. For CBSE, ICSE, IB, and EdTech teaching roles across India.',
    whatToInclude: ['Subjects taught and grade levels (e.g., "Physics, Classes 11–12, CBSE")', 'Board experience: CBSE, ICSE, IB, IGCSE, State Board', 'Student results if notable: "92% of students scored above 80% in board exams"', 'Qualifications: B.Ed, M.Ed, subject degree', 'Extra responsibilities: class teacher, activity coordinator, curriculum design', 'EdTech tools: Google Classroom, Zoom, Khan Academy, LMS platforms'],
    commonMistakes: ['Not specifying subject and grade level — "taught science" is too vague', 'Missing board curriculum — CBSE and IB require very different skills', 'No student outcome data — even informal metrics strengthen the CV', 'Omitting B.Ed qualification — it is mandatory for most school roles in India'],
    keySkills: ['Curriculum Design', 'Lesson Planning', 'CBSE/ICSE', 'Student Assessment', 'Classroom Management', 'Google Classroom', 'Parent Communication', 'Differentiated Instruction'],
    salaryRange: '₹2.5L – ₹12L for school roles; ₹6L–₹30L for senior EdTech roles',
    topCompanies: ['Delhi Public School', 'Kendriya Vidyalaya', 'Ryan International', 'Orchids The International School', 'BYJU\'S', 'Unacademy', 'Vedantu', 'WhiteHat Jr'],
    faqs: [
      { q: 'Should a teacher CV include a teaching philosophy?', a: 'Only for senior positions, research roles, or international school applications. For most school teacher applications in India, keep the CV factual — subjects, boards, results, and qualifications. A two-line summary is sufficient for most applications.' },
    ],
  },
  {
    slug: 'graphic-designer',
    title: 'Graphic Designer CV',
    displayTitle: 'Graphic Designer',
    industry: 'Design & Creative',
    metaDescription: 'Free graphic designer CV example for India. ATS-optimised with Adobe Creative Suite, brand identity, and print/digital design skills. For agencies, brands, and in-house design teams.',
    keywords: ['graphic designer cv india', 'graphic designer resume india', 'visual designer cv template', 'adobe designer resume', 'creative designer cv india', 'graphic designer resume example'],
    heroHeading: 'Graphic Designer CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised graphic designer CV showcasing your Adobe Creative Suite skills, brand identity work, and portfolio. For agency, brand, and in-house design roles in India.',
    whatToInclude: ['Portfolio link in the header — non-negotiable', 'Software: Illustrator, Photoshop, InDesign, After Effects, Figma', 'Output types: brand identity, packaging, digital ads, social media, print', 'Client or brand work with brief descriptions of the design problem solved', 'Measurable impact where possible: "Packaging redesign increased shelf conversion by 18%"', 'Animation/motion graphics skills if applicable (After Effects, Lottie)'],
    commonMistakes: ['No portfolio link — a graphic designer CV without a portfolio link will be skipped', 'Listing software versions — "Photoshop CS6" signals you haven\'t updated in years; just say "Photoshop"', 'No context for work — "designed social media creatives" vs "designed 60+ creatives/month for D2C brand with 500K followers"', 'Over-designed CV — heavy visual CVs often fail ATS'],
    keySkills: ['Adobe Illustrator', 'Photoshop', 'InDesign', 'Figma', 'Brand Identity', 'Typography', 'Print Design', 'Digital Advertising', 'Motion Graphics'],
    salaryRange: '₹2.5L – ₹20L depending on specialisation and agency vs in-house',
    topCompanies: ['Ogilvy', 'FCB Ulka', 'Leo Burnett', 'Publicis', 'Dentsu', 'Wunderman Thompson', 'Myntra', 'Nykaa', 'Swiggy Design Team'],
    faqs: [
      { q: 'Should a graphic designer use a visually designed CV?', a: 'For creative agencies, a lightly designed CV is expected and appreciated. For corporate in-house roles (banking, IT, FMCG), keep it clean and ATS-safe. Always have two versions: one designed for agencies and one plain-text ATS version.' },
    ],
  },
  {
    slug: 'python-developer',
    title: 'Python Developer CV',
    displayTitle: 'Python Developer',
    industry: 'Technology',
    metaDescription: 'Free Python developer CV example for India. ATS-optimised with Django, Flask, FastAPI, and data skills. For backend, data engineering, and automation roles at Indian tech companies.',
    keywords: ['python developer cv', 'python developer resume india', 'django developer cv', 'python backend developer resume', 'fastapi developer cv', 'python engineer resume india'],
    heroHeading: 'Python Developer CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised Python developer CV highlighting your frameworks, APIs, and deployment skills. For backend, data, and automation engineering roles across India.',
    whatToInclude: ['Python frameworks: Django, Flask, FastAPI, Celery', 'Database: PostgreSQL, MySQL, MongoDB, Redis', 'Cloud deployment: AWS Lambda, EC2, GCP, Azure', 'Testing: pytest, unittest, coverage', 'APIs: REST, GraphQL, gRPC', 'Automation and scripting projects with measurable impact'],
    commonMistakes: ['Not specifying framework — "Python developer" without naming Django or FastAPI is weak', 'Listing Python 2 as a primary skill — signal expertise in Python 3.x specifically', 'No deployment context — show where your code runs (AWS, Docker, Kubernetes)', 'Missing asynchronous programming experience — async/await and asyncio are increasingly screened'],
    keySkills: ['Python', 'Django', 'FastAPI', 'Flask', 'PostgreSQL', 'Redis', 'AWS', 'Docker', 'REST APIs', 'Celery'],
    salaryRange: '₹4L – ₹35L depending on seniority and stack',
    topCompanies: ['Razorpay', 'Zepto', 'Swiggy', 'Meesho', 'Groww', 'Zoho', 'Freshworks', 'Cleartax', 'BrowserStack', 'Postman'],
    faqs: [
      { q: 'Should a Python developer specialise in web or data?', a: 'Both are valid career paths in India. Web (Django/FastAPI) roles are more numerous and offer faster career progression in product companies. Data engineering (PySpark, Airflow, dbt) offers higher salaries at senior levels. Choose based on what energises you, and make sure your CV is clearly positioned for one path — not both.' },
    ],
  },
  {
    slug: 'java-developer',
    title: 'Java Developer CV',
    displayTitle: 'Java Developer',
    industry: 'Technology',
    metaDescription: 'Free Java developer CV example for India. ATS-optimised with Spring Boot, microservices, and enterprise architecture skills. For Java backend roles at IT services and product companies.',
    keywords: ['java developer cv', 'java developer resume india', 'spring boot developer resume', 'java backend engineer cv', 'j2ee developer resume india', 'senior java developer cv'],
    heroHeading: 'Java Developer CV — example, template & tips for India 2026',
    heroSubheading: 'Write an ATS-optimised Java developer CV with Spring Boot, microservices, and cloud skills. For service-based IT companies, product companies, and enterprise application roles.',
    whatToInclude: ['Core Java: version (Java 11/17/21), OOPs, collections, multithreading', 'Frameworks: Spring Boot, Spring MVC, Hibernate, JPA', 'Architecture: microservices, REST APIs, event-driven', 'Build tools: Maven, Gradle', 'Cloud: AWS, Azure, GCP', 'Performance and memory tuning experience if senior-level'],
    commonMistakes: ['Not specifying Java version — "Java 8 developer" and "Java 21 developer" signal very different currency', '"Worked on Spring" without specifying Boot, MVC, Security, or Cloud', 'No architecture context — CRUD apps vs distributed systems vs event-driven show different seniority', 'Listing J2EE technologies prominently — EJB, Struts, JSP are outdated signals for most roles'],
    keySkills: ['Java', 'Spring Boot', 'Microservices', 'Hibernate', 'REST APIs', 'Maven', 'MySQL', 'AWS', 'Docker', 'Kafka'],
    salaryRange: '₹4L – ₹40L depending on experience and company tier',
    topCompanies: ['TCS', 'Infosys', 'Wipro', 'Cognizant', 'HCL', 'IBM India', 'Oracle India', 'SAP Labs', 'JP Morgan', 'Deutsche Bank Technology'],
    faqs: [
      { q: 'Is Java still in demand in India in 2026?', a: 'Yes — Java is the dominant language in Indian IT services (TCS, Infosys, Wipro, Cognizant) and in BFSI technology teams (banking, insurance, capital markets). Spring Boot is the standard framework. While newer languages like Go and Rust are growing, Java developers are consistently in demand, especially for enterprise and BFSI roles.' },
    ],
  },
  {
    slug: 'digital-marketing-executive',
    title: 'Digital Marketing Executive CV',
    displayTitle: 'Digital Marketing Executive',
    industry: 'Marketing & Digital',
    metaDescription: 'Free digital marketing executive CV example for India. ATS-optimised with SEO, Google Ads, Meta Ads, and email marketing skills. For entry-level and mid-level digital marketing roles.',
    keywords: ['digital marketing executive cv', 'digital marketing resume india', 'SEO executive cv', 'google ads executive resume', 'social media executive cv india', 'digital marketing fresher cv'],
    heroHeading: 'Digital Marketing Executive CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised digital marketing executive CV covering SEO, paid ads, social media, and email marketing. For entry to mid-level roles at agencies, D2C brands, and SaaS companies.',
    whatToInclude: ['Channel expertise: SEO, Google Ads, Meta Ads, email, social media', 'Metrics: ROAS, CPC, CTR, organic traffic growth, email open rates', 'Tools: Google Analytics, Search Console, Ahrefs, Meta Business Manager, Mailchimp', 'Campaign budgets managed (even small amounts show experience)', 'Certifications: Google Ads, HubSpot, Meta Blueprint, SEMrush Academy', 'Content skills if applicable: copywriting, social media calendars'],
    commonMistakes: ['No performance metrics — "managed social media" vs "grew Instagram from 5K to 42K followers in 6 months"', 'Listing every platform without specifics — depth beats breadth for most roles', 'Missing certifications — Google Ads and HubSpot certifications are free and heavily weighted', 'Not mentioning analytics tools — every digital marketing role requires Google Analytics at minimum'],
    keySkills: ['Google Ads', 'SEO', 'Meta Ads', 'Google Analytics', 'Email Marketing', 'Social Media', 'Content Marketing', 'Ahrefs', 'HubSpot', 'Copywriting'],
    salaryRange: '₹2.5L – ₹12L for executive; ₹12L–₹35L for senior/specialist',
    topCompanies: ['iProspect', 'WATConsult', 'Schbang', 'Dentsu Digital', 'Razorpay', 'Nykaa', 'boAt', 'Myntra', 'HubSpot India', 'Freshworks'],
    faqs: [
      { q: 'What certifications should a digital marketing fresher include on their CV?', a: 'Google Ads Search Certification, Google Analytics 4 Certification, HubSpot Content Marketing, and Meta Blueprint are the most recognised. All are free and each typically takes 4–8 hours to complete. Having even 2–3 of these puts a fresher significantly ahead of uncertified applicants.' },
    ],
  },
  {
    slug: 'qa-engineer',
    title: 'QA Engineer CV',
    displayTitle: 'QA Engineer / Software Tester',
    industry: 'Technology',
    metaDescription: 'Free QA engineer CV example for India. ATS-optimised with Selenium, API testing, Jira, and automation skills. For manual and automation testing roles at IT companies and product startups.',
    keywords: ['qa engineer cv', 'software tester resume india', 'selenium tester resume', 'automation tester cv india', 'QA analyst resume', 'test engineer cv india 2026'],
    heroHeading: 'QA Engineer CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised QA engineer CV covering manual testing, Selenium automation, API testing, and CI/CD. For testing roles at Indian IT services companies and product startups.',
    whatToInclude: ['Test types: manual, automation, API, performance, mobile', 'Automation stack: Selenium, Appium, Playwright, Cypress, TestNG', 'API testing: Postman, RestAssured, SoapUI', 'CI/CD integration: Jenkins, GitHub Actions', 'Bug tracking: JIRA, Bugzilla, Azure DevOps', 'Test metrics: defect density, test coverage %, regression cycle time'],
    commonMistakes: ['Manual testing only with no automation — most mid-level QA JDs now require Selenium or equivalent', 'Not mentioning the type of application tested — web, mobile, API, or embedded systems', 'No test metrics — "performed testing" vs "maintained 95% regression coverage with 4-hour cycle time"', 'Missing API testing — REST API testing is now table stakes for most QA roles'],
    keySkills: ['Selenium', 'Java/Python for automation', 'Postman', 'JIRA', 'TestNG', 'API Testing', 'Appium', 'CI/CD', 'SQL', 'Agile/Scrum'],
    salaryRange: '₹3L – ₹22L depending on manual vs automation and experience',
    topCompanies: ['TCS', 'Infosys', 'Wipro', 'Cognizant', 'Capgemini', 'ThoughtWorks', 'Razorpay', 'Browserstack', 'Postman', 'Freshworks'],
    faqs: [
      { q: 'Is manual testing a dying career in India?', a: 'Not completely, but the market has shifted dramatically. Manual-only QA engineers face shrinking opportunities above ₹6L. Learning automation (Selenium + Java or Python) doubles your marketable salary range and opens significantly more roles. Start with Selenium WebDriver + TestNG — it is the most in-demand stack in India.' },
    ],
  },
  {
    slug: 'bank-po',
    title: 'Banking Professional CV',
    displayTitle: 'Banking Professional / Bank PO',
    industry: 'Banking & Financial Services',
    metaDescription: 'Free banking professional CV example for India. ATS-optimised bank CV with relationship management, credit analysis, and compliance skills. For public sector banks, private banks, and NBFCs.',
    keywords: ['bank po cv india', 'banking resume india', 'relationship manager cv bank', 'credit analyst resume india', 'bank branch manager cv', 'banking professional resume india'],
    heroHeading: 'Banking Professional CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised banking professional CV covering retail banking, credit analysis, and compliance. For public sector banks, private banks, NBFCs, and fintech companies in India.',
    whatToInclude: ['Portfolio managed: "CASA portfolio of ₹85Cr across 240 accounts"', 'Products sold: savings, FDs, home loans, personal loans, insurance', 'Compliance: KYC, AML, RBI guidelines adherence', 'Systems: Finacle, BaNCS, CBS, Temenos', 'Certifications: JAIIB, CAIIB, NCFM modules', 'Branch-level metrics: business growth %, NPA management'],
    commonMistakes: ['No portfolio size or business metrics — banking CVs without numbers are immediately weak', 'Missing system names — Finacle vs Temenos signal public vs private bank experience', 'Not listing relevant certifications — JAIIB/CAIIB are screened for senior banking roles', 'Ignoring cross-sell metrics — fee income contribution is a key recruiter interest area'],
    keySkills: ['Credit Analysis', 'Relationship Management', 'Finacle', 'KYC/AML', 'CASA', 'Loan Origination', 'NPA Management', 'JAIIB/CAIIB', 'Compliance'],
    salaryRange: '₹3.5L – ₹25L depending on sector (PSB vs private) and level',
    topCompanies: ['SBI', 'HDFC Bank', 'ICICI Bank', 'Axis Bank', 'Kotak Mahindra Bank', 'Bank of Baroda', 'Yes Bank', 'IndusInd Bank', 'Bajaj Finance'],
    faqs: [
      { q: 'Is JAIIB/CAIIB certification worth mentioning on a banking CV?', a: 'Yes — especially for PSB (public sector bank) roles, it is frequently mandatory or preferred. CAIIB is valued for credit and risk roles. For private banking and NBFCs, domain expertise and performance metrics matter more than these certifications, but they still signal commitment to banking as a profession.' },
    ],
  },
  {
    slug: 'customer-success-manager',
    title: 'Customer Success Manager CV',
    displayTitle: 'Customer Success Manager',
    industry: 'SaaS & Tech',
    metaDescription: 'Free customer success manager CV example for India. ATS-optimised CSM resume with NRR, churn reduction, and onboarding metrics. For SaaS, B2B tech, and enterprise customer success roles.',
    keywords: ['customer success manager cv', 'CSM resume india', 'customer success resume', 'account manager SaaS cv', 'customer success cv india 2026', 'B2B customer success resume'],
    heroHeading: 'Customer Success Manager CV — example, template & tips for India 2026',
    heroSubheading: 'Build an ATS-optimised CSM CV with NRR, churn, and expansion revenue metrics. For SaaS, fintech, and B2B tech customer success roles in India.',
    whatToInclude: ['Key metrics: NRR, GRR, churn rate, expansion MRR, CSAT/NPS', 'Customer portfolio: ARR managed, number of accounts, enterprise vs SMB mix', 'Tools: Gainsight, Totango, Salesforce, Intercom, Zendesk', 'QBR and business review experience', 'Onboarding: time-to-value reduction metrics', 'Renewal management: on-time renewal rate, upsell win rate'],
    commonMistakes: ['No retention or expansion metrics — the only metrics that matter in CSM roles', '"Managed customer relationships" without portfolio size or business impact', 'Not differentiating commercial CS from technical CS — be specific about your scope', 'Missing CSM tools — Gainsight is the most screened platform for senior CSM roles'],
    keySkills: ['Net Revenue Retention', 'Gainsight', 'Churn Management', 'Salesforce', 'QBR', 'Onboarding', 'Renewal Management', 'Expansion Revenue', 'CSAT/NPS', 'Stakeholder Management'],
    salaryRange: '₹6L – ₹35L depending on company tier and portfolio ARR',
    topCompanies: ['Freshworks', 'Zoho', 'Chargebee', 'Clevertap', 'WebEngage', 'Capillary Technologies', 'Sprinklr', 'Druva', 'Postman', 'Razorpay'],
    faqs: [
      { q: 'What is the most important metric on a Customer Success Manager CV?', a: 'Net Revenue Retention (NRR). An NRR above 110% signals you are growing existing customers faster than churn, which is the gold standard. GRR (Gross Revenue Retention) shows how well you prevent churn. Even approximate figures based on your actual performance are better than no metrics at all.' },
    ],
  },
];

export const roleMap = new Map(roles.map((r) => [r.slug, r]));
export const roleSlugs = roles.map((r) => r.slug);
