import type { SalaryData } from '@/lib/salaryData';

// Salary ranges are indicative estimates for India (annual, INR, fixed + typical variable),
// aligned with each role's `salaryRange` in lib/roleData.ts. Actual offers vary by employer.
export const salaryDataMore: Record<string, SalaryData> = {
  'sales-executive': {
    byExperience: {
      fresher: '₹2.2L – ₹4.5L fixed (0–2 years; field sales, inside sales, BFSI and FMCG trainee roles)',
      midLevel: '₹4L – ₹7L fixed + incentives (3–6 years; senior executive or territory owner)',
      senior: '₹6L – ₹9L fixed + incentives (7–12 years; key account or area sales roles)',
      leadership: '₹9L+ fixed with larger variable (13+ years; usually moves into sales manager and regional head titles)',
    },
    byCompanyType: {
      startup: '₹2.5L – ₹6L fixed + incentives (targets can be aggressive; ESOPs are uncommon at this level)',
      midSize: '₹2.5L – ₹7L fixed + incentives (stable base, structured incentive slabs)',
      mnc: '₹3.5L – ₹9L fixed + incentives (FMCG, insurance, telecom and consumer-durables majors)',
      faang: '₹6L – ₹9L+ fixed with higher incentive potential (top-tier FMCG, SaaS and BFSI sales teams)',
    },
    byLocation: {
      bangalore: '₹2.5L – ₹9L (strong for SaaS and consumer-tech sales)',
      mumbai: '₹2.5L – ₹9L (BFSI, FMCG and distribution hub)',
      delhi: '₹2.4L – ₹8.5L (large NCR market across FMCG, telecom and real estate)',
      hyderabad: '₹2.3L – ₹8L (pharma, BFSI and IT-product sales)',
      chennai: '₹2.2L – ₹7.5L (auto, manufacturing and consumer sales)',
      pune: '₹2.3L – ₹8L (auto, industrial and IT sales)',
      other: '₹2L – ₹6L (Tier-2 cities; incentives often make up a larger share)',
    },
    topPayingSkills: ['B2B Sales', 'Key Account Management', 'CRM (Salesforce/Zoho)', 'Negotiation', 'Territory Planning', 'Channel / Distributor Management', 'Consultative Selling', 'Sales Forecasting'],
    salaryBoostFactors: [
      'Consistent target achievement with numbers you can show (for example 110% of quota for four quarters)',
      'Moving from B2C field sales to B2B or enterprise sales, which usually carries a higher fixed base',
      'Experience in high-ticket sectors such as insurance, SaaS, real estate or industrial equipment',
      'CRM fluency and clean pipeline reporting, which employers treat as a sign of a manager-ready candidate',
      'Team-handling experience, even informal, such as mentoring new joiners',
    ],
    negotiationTips: [
      'Ask for the incentive plan in writing: slabs, caps, payout frequency and what counts toward quota',
      'Compare fixed pay and variable separately — a high "CTC" built on an unrealistic variable is a common trap',
      'Share your last two to three quarters of achievement figures as evidence for a higher base',
      'Clarify territory, lead source and whether leads are provided or self-generated before accepting the target',
    ],
    faqs: [
      { q: 'What is the average sales executive salary in India?', a: 'Most sales executives in India earn roughly ₹2.2L – ₹9L a year in fixed pay depending on sector, city and experience, with incentives on top. Freshers in field and inside sales are typically at the lower end, while B2B, SaaS and BFSI roles with several years of experience reach the upper end.' },
      { q: 'Is the fixed salary or the incentive more important for a sales executive?', a: 'Both matter, but the fixed component is what you can rely on. Incentives depend on targets, territory and lead quality, so compare offers on fixed pay first and then judge how achievable the variable is from the incentive plan and how many current team members hit target.' },
    ],
  },
  'ios-developer': {
    byExperience: {
      fresher: '₹5L – ₹10L (0–2 years; product startups and mobile-focused service teams)',
      midLevel: '₹12L – ₹25L (3–6 years; owning features end to end in Swift/SwiftUI)',
      senior: '₹25L – ₹40L (7–12 years; senior and staff mobile engineers)',
      leadership: '₹40L+ (13+ years; mobile architects, engineering managers, with stock components at product companies)',
    },
    byCompanyType: {
      startup: '₹6L – ₹25L (ESOPs add upside; scope is broad)',
      midSize: '₹8L – ₹28L (stable base, moderate equity)',
      mnc: '₹10L – ₹32L (global product centres and consulting firms)',
      faang: '₹25L – ₹60L+ (large global tech and top Indian unicorns; base + stock + bonus)',
    },
    byLocation: {
      bangalore: '₹6L – ₹55L (largest concentration of consumer-app and fintech iOS teams)',
      mumbai: '₹5L – ₹40L (fintech, media and trading apps)',
      delhi: '₹5L – ₹38L (NCR product companies and unicorns)',
      hyderabad: '₹5L – ₹40L (global tech centres and product firms)',
      chennai: '₹4.5L – ₹30L (SaaS and fintech product teams)',
      pune: '₹4.5L – ₹30L (product engineering and automotive-tech teams)',
      other: '₹3.5L – ₹20L (smaller hubs and remote roles for Bangalore-based firms)',
    },
    topPayingSkills: ['SwiftUI', 'Swift Concurrency (async/await)', 'Combine', 'Modular Architecture', 'App Performance Profiling', 'CI/CD for Mobile (Fastlane)', 'Core Data / SwiftData', 'Unit and UI Testing'],
    salaryBoostFactors: [
      'Shipping apps with a public App Store link and real user numbers',
      'Strength in SwiftUI plus UIKit, since many large codebases still mix both',
      'Experience with performance, accessibility and app-size optimisation at scale',
      'Ownership of release pipelines, feature flags and crash monitoring',
      'Cross-platform awareness (Android collaboration, Kotlin Multiplatform or React Native) for lead roles',
    ],
    negotiationTips: [
      'Link your App Store apps and quote measurable outcomes: crash-free rate, load time or retention improvements',
      'Separate base, joining bonus and stock when comparing offers across companies',
      'Ask which iOS versions and architecture the team uses; modern stacks (SwiftUI, concurrency) often justify a stronger offer',
      'Use competing offers from other product companies as honest leverage after you hold a written offer',
    ],
    faqs: [
      { q: 'What is the average iOS developer salary in India?', a: 'iOS developers in India commonly earn about ₹5L – ₹40L a year, depending on experience and company type. Freshers sit around ₹5L – ₹10L, mid-level developers around ₹12L – ₹25L, and senior engineers at product companies can go beyond ₹40L including stock.' },
      { q: 'Does knowing SwiftUI increase an iOS developer salary?', a: 'It helps. Most employers now expect SwiftUI alongside UIKit, and engineers who can modernise a codebase, handle async/await and ship polished apps tend to receive stronger offers than those who know UIKit alone.' },
    ],
  },
  'full-stack-developer': {
    byExperience: {
      fresher: '₹5L – ₹12L (0–2 years; startups pay more than IT service campus roles)',
      midLevel: '₹12L – ₹25L (3–6 years; owning features across frontend, backend and database)',
      senior: '₹25L – ₹40L (7–12 years; senior and lead engineers)',
      leadership: '₹40L – ₹45L+ (13+ years; tech leads, architects, engineering managers)',
    },
    byCompanyType: {
      startup: '₹6L – ₹30L (plus ESOPs; wide scope and fast progression)',
      midSize: '₹8L – ₹30L (stable pay, moderate equity)',
      mnc: '₹10L – ₹35L (product engineering centres and consulting firms)',
      faang: '₹25L – ₹60L+ (large global tech and top Indian unicorns; base + stock + bonus)',
    },
    byLocation: {
      bangalore: '₹6L – ₹50L (highest demand and pay for full stack roles)',
      mumbai: '₹5L – ₹40L (fintech, media and e-commerce)',
      delhi: '₹5L – ₹40L (NCR product companies and unicorns)',
      hyderabad: '₹5L – ₹42L (global tech centres and SaaS companies)',
      chennai: '₹4.5L – ₹32L (SaaS, fintech and IT services)',
      pune: '₹4.5L – ₹32L (product and services mix)',
      other: '₹3.5L – ₹22L (smaller hubs; remote roles often pay above local rates)',
    },
    topPayingSkills: ['System Design', 'TypeScript', 'Node.js + React', 'Cloud (AWS/GCP)', 'PostgreSQL and Data Modelling', 'Docker / Kubernetes', 'Next.js', 'Testing and CI/CD'],
    salaryBoostFactors: [
      'Depth on both sides of the stack rather than a shallow list of tools',
      'Production ownership: deployments, monitoring, performance and security basics',
      'Experience at product companies with real scale (users, traffic, data volume)',
      'System design ability, which separates senior offers from mid-level ones',
      'Open-source work or well-documented projects that prove delivery',
    ],
    negotiationTips: [
      'Anchor on scope — owning a product area across stack layers justifies a higher band than a single-layer role',
      'Ask about on-call expectations and ownership so the level offered matches the work',
      'Compare offers on total compensation including stock vesting schedule, not only fixed pay',
      'Bring specific impact figures such as latency reduced, features shipped or revenue influenced',
    ],
    faqs: [
      { q: 'What is the average full stack developer salary in India?', a: 'Full stack developers in India typically earn about ₹5L – ₹45L a year. Freshers are usually at ₹5L – ₹12L, mid-level developers at ₹12L – ₹25L, and senior engineers at strong product companies at ₹25L – ₹40L or more, with stock adding to the total.' },
      { q: 'Do full stack developers earn more than frontend or backend developers?', a: 'Not automatically. Pay follows depth, scale and company tier more than the title. Full stack engineers who can own a feature end to end and handle deployment and design decisions are valued highly, particularly at startups where one engineer covers several layers.' },
    ],
  },
  'machine-learning-engineer': {
    byExperience: {
      fresher: '₹8L – ₹18L (0–2 years; strong projects or research background help)',
      midLevel: '₹18L – ₹35L (3–6 years; shipping models to production)',
      senior: '₹35L – ₹60L (7–12 years; senior and staff ML engineers)',
      leadership: '₹60L+ (13+ years; ML leads, principal engineers, heads of ML)',
    },
    byCompanyType: {
      startup: '₹10L – ₹40L (ESOPs; broad ownership of data to deployment)',
      midSize: '₹12L – ₹40L (analytics and applied-AI teams)',
      mnc: '₹15L – ₹50L (global AI and research centres, consulting AI practices)',
      faang: '₹35L – ₹90L+ (large global tech and top AI-focused firms; base + stock + bonus)',
    },
    byLocation: {
      bangalore: '₹9L – ₹80L (largest ML hiring market in India)',
      mumbai: '₹8L – ₹55L (BFSI, risk and fintech ML)',
      delhi: '₹8L – ₹55L (NCR product companies and AI startups)',
      hyderabad: '₹8L – ₹65L (global AI and R&D centres)',
      chennai: '₹8L – ₹45L (analytics, SaaS and BFSI)',
      pune: '₹8L – ₹45L (analytics, automotive and product teams)',
      other: '₹6L – ₹30L (smaller hubs; remote roles can pay more)',
    },
    topPayingSkills: ['MLOps (MLflow, Kubeflow)', 'Deep Learning (PyTorch)', 'LLMs and Fine-tuning', 'Model Deployment and Serving', 'Distributed Training', 'Feature Stores and Data Pipelines', 'Experiment Tracking and Evaluation', 'Cloud ML (SageMaker/Vertex AI)'],
    salaryBoostFactors: [
      'Models in production with measurable business impact, not only notebooks',
      'MLOps skills: monitoring, drift detection, retraining and serving at scale',
      'Experience with LLMs, retrieval or fine-tuning, which is in strong demand',
      'Research publications or well-documented open-source work at senior levels',
      'Domain depth in areas that pay well such as fintech risk, ads, search or recommendations',
    ],
    negotiationTips: [
      'Lead with production outcomes: latency, accuracy lift, cost saved or revenue influenced',
      'Ask about compute budget, data access and team ownership — they affect how much impact you can have',
      'Negotiate stock and joining bonus separately from base, especially at AI-focused product firms',
      'Distinguish ML engineer from data scientist expectations; engineering ownership often justifies a higher band',
    ],
    faqs: [
      { q: 'What is the average machine learning engineer salary in India?', a: 'Machine learning engineers in India commonly earn about ₹8L – ₹60L+ a year. Early-career engineers are around ₹8L – ₹18L, mid-level engineers who ship models to production around ₹18L – ₹35L, and senior engineers at top product and AI firms can exceed ₹60L including stock.' },
      { q: 'Does an ML engineer earn more than a data scientist in India?', a: 'Often yes at comparable experience, because ML engineers are expected to deploy and maintain models in production, which is scarcer than analysis and prototyping skills. Titles vary by company, so compare the actual responsibilities listed in the job description.' },
    ],
  },
  'chartered-accountant': {
    byExperience: {
      fresher: '₹7L – ₹12L (newly qualified CAs; Big 4 starting packages sit around ₹7L – ₹9L)',
      midLevel: '₹12L – ₹22L (3–6 years post-qualification; manager-track in audit, tax or corporate finance)',
      senior: '₹22L – ₹35L (7–12 years; senior manager, associate director, finance controller)',
      leadership: '₹35L – ₹40L+ (13+ years; partner track, CFO and finance head roles can go well beyond)',
    },
    byCompanyType: {
      startup: '₹8L – ₹25L (finance lead roles; some ESOPs)',
      midSize: '₹8L – ₹25L (corporate finance, audit and tax roles)',
      mnc: '₹10L – ₹30L (global capability centres, shared services and large corporates)',
      faang: '₹9L – ₹35L+ (Big 4, large banks and top corporates; partner economics are separate)',
    },
    byLocation: {
      bangalore: '₹7L – ₹32L (large GCC and Big 4 presence)',
      mumbai: '₹7L – ₹38L (financial capital; banking, markets and Big 4 head offices)',
      delhi: '₹7L – ₹32L (NCR corporates, consulting and PSU-linked finance)',
      hyderabad: '₹7L – ₹30L (global capability centres and pharma finance)',
      chennai: '₹6.5L – ₹26L (manufacturing, auto and financial services)',
      pune: '₹6.5L – ₹26L (manufacturing, IT and captive finance centres)',
      other: '₹5L – ₹20L (smaller markets; practice and SME roles)',
    },
    topPayingSkills: ['Ind AS / IFRS', 'Transfer Pricing', 'Direct and Indirect Tax (GST)', 'Statutory and Internal Audit', 'M&A and Due Diligence', 'Financial Reporting', 'SAP / ERP', 'Treasury and Financial Planning'],
    salaryBoostFactors: [
      'Experience at a Big 4 or reputed firm, which strongly influences next-role offers',
      'Specialisations such as international tax, transfer pricing, IFRS or deal advisory',
      'Additional credentials like DISA, CFA, ACCA or CPA for global roles',
      'Movement from practice into industry finance roles, often with a pay step-up after two to four years',
      'Strong ERP and analytics skills alongside technical accounting',
    ],
    negotiationTips: [
      'Compare practice and industry offers on fixed pay, bonus and working-hours expectations together',
      'Ask whether the package includes a performance bonus and how it has been paid in recent years',
      'Use specialisation and certifications to justify a higher band rather than years of experience alone',
      'For CFO-track roles, discuss scope, reporting line and stock or long-term incentives, not just salary',
    ],
    faqs: [
      { q: 'What is the starting salary of a chartered accountant in India?', a: 'Newly qualified chartered accountants commonly start around ₹7L – ₹12L a year, with Big 4 firms typically in the ₹7L – ₹9L range and some corporate, banking or investment roles paying more. Pay rises quickly with specialisation and a few years of experience.' },
      { q: 'Do CAs earn more in industry or in practice?', a: 'It depends on the stage. Practice and Big 4 roles offer strong early-career learning and partner-track upside, while industry roles in large corporates, startups and capability centres often pay more around the three to seven year mark and offer better predictability of hours.' },
    ],
  },
  'sap-consultant': {
    byExperience: {
      fresher: '₹5L – ₹9L (0–2 years; trainee or associate consultant, module-specific training)',
      midLevel: '₹10L – ₹20L (3–6 years; functional or technical consultant on implementations)',
      senior: '₹20L – ₹32L (7–12 years; senior consultant, solution architect)',
      leadership: '₹32L – ₹35L+ (13+ years; lead architects and practice heads can go well beyond)',
    },
    byCompanyType: {
      startup: '₹6L – ₹20L (boutique SAP partners and product-adjacent firms)',
      midSize: '₹7L – ₹25L (SAP partners and regional consulting firms)',
      mnc: '₹8L – ₹32L (large IT services and consulting firms with SAP practices)',
      faang: '₹15L – ₹40L+ (top consulting firms and global SAP delivery centres)',
    },
    byLocation: {
      bangalore: '₹5.5L – ₹35L (largest concentration of SAP delivery centres)',
      mumbai: '₹5L – ₹32L (BFSI and large enterprise clients)',
      delhi: '₹5L – ₹32L (NCR consulting and enterprise delivery)',
      hyderabad: '₹5L – ₹32L (global delivery centres and consulting firms)',
      chennai: '₹5L – ₹28L (IT services and manufacturing clients)',
      pune: '₹5L – ₹30L (manufacturing, automotive and IT services)',
      other: '₹4L – ₹20L (smaller delivery locations)',
    },
    topPayingSkills: ['SAP S/4HANA Implementation', 'SAP FICO', 'SAP BTP and Fiori', 'SAP ABAP on HANA', 'SAP SuccessFactors', 'SAP Ariba', 'Solution Architecture', 'Data Migration'],
    salaryBoostFactors: [
      'Full-cycle S/4HANA implementation or migration experience',
      'Scarce modules and skills such as BTP, Fiori, SuccessFactors or Ariba',
      'SAP certification in your module, which signals depth to recruiters',
      'Onsite or client-facing experience for global projects',
      'Combining functional knowledge with technical skills like ABAP or integration',
    ],
    negotiationTips: [
      'List the number of full implementation cycles and go-lives you have taken part in',
      'Know your module’s market demand — newer S/4HANA and BTP skills usually justify a higher ask',
      'Clarify onsite travel, project location and notice-period buyout before agreeing on CTC',
      'Use certifications and migration experience as evidence rather than only total years',
    ],
    faqs: [
      { q: 'What is the average SAP consultant salary in India?', a: 'SAP consultants in India typically earn about ₹5L – ₹35L a year depending on module, experience and firm. Freshers are generally at ₹5L – ₹9L, mid-level consultants at ₹10L – ₹20L, and senior consultants or architects with S/4HANA experience at ₹20L and above.' },
      { q: 'Which SAP module pays the most in India?', a: 'Newer and scarcer skills such as S/4HANA, BTP, Fiori and SuccessFactors often command higher pay than legacy-only profiles. Within core modules, FICO and ABAP remain widely demanded, and architects who span modules earn the most.' },
    ],
  },
  'react-developer': {
    byExperience: {
      fresher: '₹4L – ₹10L (0–2 years; product startups pay above service-company campus offers)',
      midLevel: '₹10L – ₹25L (3–6 years; owning UI architecture and performance)',
      senior: '₹25L – ₹40L (7–12 years; senior frontend engineers and tech leads)',
      leadership: '₹40L+ (13+ years; staff engineers, frontend architects, engineering managers)',
    },
    byCompanyType: {
      startup: '₹5L – ₹28L (plus ESOPs; fast ownership of product UI)',
      midSize: '₹7L – ₹28L (stable pay and moderate equity)',
      mnc: '₹8L – ₹32L (product engineering centres and consulting firms)',
      faang: '₹22L – ₹55L+ (large global tech and top Indian unicorns; base + stock + bonus)',
    },
    byLocation: {
      bangalore: '₹5L – ₹50L (largest React and product-engineering market)',
      mumbai: '₹4.5L – ₹38L (fintech, media and e-commerce)',
      delhi: '₹4.5L – ₹38L (NCR product companies and unicorns)',
      hyderabad: '₹4.5L – ₹40L (global tech centres and SaaS firms)',
      chennai: '₹4L – ₹30L (SaaS and fintech)',
      pune: '₹4L – ₹30L (product and services mix)',
      other: '₹3L – ₹20L (smaller hubs; remote roles often pay above local rates)',
    },
    topPayingSkills: ['TypeScript', 'Next.js (SSR/SSG)', 'Web Performance and Core Web Vitals', 'State Management at Scale', 'Design Systems', 'Frontend Testing (Jest, Playwright)', 'Accessibility (WCAG)', 'Micro-frontends'],
    salaryBoostFactors: [
      'Proven performance work with Core Web Vitals or bundle-size improvements and numbers to match',
      'TypeScript and Next.js fluency, now expected at most product companies',
      'Design-system ownership or contribution, which signals senior-level thinking',
      'Testing discipline and accessibility experience',
      'Product-company experience with real traffic and release pressure',
    ],
    negotiationTips: [
      'Bring metrics: Lighthouse scores, load-time reductions, conversion lift or bug-rate improvements',
      'Ask which React version, build tooling and testing standards the team uses — modern stacks justify better offers',
      'Compare total compensation including stock and bonus, not only fixed pay',
      'Show a portfolio or public repository to back up a mid-to-senior band',
    ],
    faqs: [
      { q: 'What is the average React developer salary in India?', a: 'React developers in India typically earn about ₹4L – ₹40L a year. Freshers are around ₹4L – ₹10L, mid-level developers around ₹10L – ₹25L, and senior frontend engineers at strong product companies at ₹25L – ₹40L or more including stock.' },
      { q: 'Does TypeScript knowledge increase a React developer’s salary?', a: 'It is now close to a baseline expectation at product companies, so lacking it can limit offers, while strong TypeScript plus Next.js, performance and testing skills put you in the higher bands for your experience level.' },
    ],
  },
  'investment-banker': {
    byExperience: {
      fresher: '₹15L – ₹25L (analyst, 0–3 years; top MBA and global bank analyst roles are at the upper end)',
      midLevel: '₹35L – ₹60L (associate, 3–6 years)',
      senior: '₹60L – ₹80L (vice president, 7–10 years)',
      leadership: '₹80L+ (director and managing director; bonuses can be a large share of pay)',
    },
    byCompanyType: {
      startup: '₹12L – ₹35L (boutique advisory and fintech corporate finance teams)',
      midSize: '₹15L – ₹45L (domestic investment banks and boutique advisory firms)',
      mnc: '₹20L – ₹70L (global banks’ India teams)',
      faang: '₹25L – ₹80L+ (bulge-bracket and top advisory franchises; bonus-heavy)',
    },
    byLocation: {
      bangalore: '₹12L – ₹45L (limited front-office presence; some captive and tech-banking roles)',
      mumbai: '₹15L – ₹90L (India’s investment banking centre)',
      delhi: '₹14L – ₹65L (NCR advisory and corporate banking)',
      hyderabad: '₹10L – ₹35L (mostly operations and analytics support centres)',
      chennai: '₹10L – ₹30L (limited front-office roles)',
      pune: '₹10L – ₹30L (support and analytics centres)',
      other: '₹8L – ₹25L (few front-office opportunities)',
    },
    topPayingSkills: ['M&A Advisory', 'LBO and DCF Modelling', 'Equity and Debt Capital Markets', 'Pitchbook Preparation', 'Valuation', 'Cross-border Transactions', 'Sector Specialisation', 'Client Origination'],
    salaryBoostFactors: [
      'Deal experience on closed transactions you can describe by size and your role',
      'Brand of the institution and the prestige of the team',
      'MBA from a top school or CFA charter for lateral entry and progression',
      'Sector depth in areas with active deal flow',
      'Cross-border mandates and exposure to global bank platforms',
    ],
    negotiationTips: [
      'Separate base salary from the performance bonus, which often makes up a large share of total pay',
      'Ask how bonuses were distributed in recent years and what is guaranteed in the first year',
      'Discuss title and level carefully — moving up a grade at joining shifts your whole progression',
      'Use competing offers from comparable firms; the market is small and information travels',
    ],
    faqs: [
      { q: 'What is an investment banker’s salary in India?', a: 'Investment bankers in India commonly earn about ₹15L – ₹80L+ a year. Analysts start around ₹15L – ₹25L, associates around ₹35L – ₹60L, and vice presidents and above at ₹60L or more, with bonuses forming a significant part of total pay.' },
      { q: 'Is the bonus included in an investment banker’s salary?', a: 'Often it is quoted separately. Total compensation combines base salary and a discretionary bonus linked to individual, team and firm performance, so always ask how the figure on offer is structured.' },
    ],
  },
  'scrum-master': {
    byExperience: {
      fresher: '₹5L – ₹9L (0–2 years; usually after PSM/CSM certification and project coordination exposure)',
      midLevel: '₹10L – ₹20L (3–6 years; running one or more teams)',
      senior: '₹20L – ₹28L (7–12 years; agile coaches and release train engineers)',
      leadership: '₹28L – ₹30L+ (13+ years; enterprise agile coaches and transformation leads)',
    },
    byCompanyType: {
      startup: '₹8L – ₹22L (broader product and delivery scope)',
      midSize: '₹8L – ₹24L (delivery and PMO-linked roles)',
      mnc: '₹10L – ₹30L (large IT services, banks and global capability centres)',
      faang: '₹18L – ₹35L+ (top product and consulting firms with mature agile practices)',
    },
    byLocation: {
      bangalore: '₹9L – ₹32L (highest density of agile roles)',
      mumbai: '₹8L – ₹28L (BFSI and enterprise delivery)',
      delhi: '₹8L – ₹28L (NCR IT services and enterprise clients)',
      hyderabad: '₹8L – ₹28L (global delivery centres)',
      chennai: '₹8L – ₹25L (IT services and BFSI technology)',
      pune: '₹8L – ₹26L (IT services and product engineering)',
      other: '₹6L – ₹18L (smaller delivery locations)',
    },
    topPayingSkills: ['SAFe (SPC)', 'Agile Coaching', 'Scaled Agile / Release Train Engineering', 'Metrics and Flow (Kanban)', 'Stakeholder Management', 'Facilitation', 'Jira and Confluence Administration', 'DevOps Collaboration'],
    salaryBoostFactors: [
      'Recognised certifications such as PSM, CSM, SAFe SPC or ICAgile',
      'Experience scaling agile across multiple teams or programmes',
      'Measurable outcomes such as cycle time or predictability improvements',
      'Coaching leaders and teams, not only running ceremonies',
      'Domain familiarity in regulated or complex sectors like banking and healthcare',
    ],
    negotiationTips: [
      'Quantify team outcomes: velocity stability, lead time, defect escape rate or delivery predictability',
      'Clarify whether the role is pure Scrum Master or combined with project management, which changes the right band',
      'Ask how many teams you will serve and the team size',
      'Use scaled-agile certifications and coaching experience to justify moving to the next band',
    ],
    faqs: [
      { q: 'What is the average Scrum Master salary in India?', a: 'Scrum Masters in India typically earn about ₹8L – ₹30L a year. Mid-level Scrum Masters running a team or two are often around ₹10L – ₹20L, while agile coaches and release train engineers at large organisations reach the upper bands.' },
      { q: 'Does a Scrum certification raise pay in India?', a: 'It helps with getting shortlisted and often with the starting band, but experience and demonstrable results carry more weight. Scaled-agile credentials such as SAFe SPC usually matter more for senior roles.' },
    ],
  },
  'business-development-manager': {
    byExperience: {
      fresher: '₹6L – ₹10L base (0–2 years; usually inside sales or associate BD roles)',
      midLevel: '₹10L – ₹20L base + commission (3–6 years; owning a territory or segment)',
      senior: '₹20L – ₹35L base + commission (7–12 years; senior BD, enterprise accounts)',
      leadership: '₹35L – ₹40L+ base with commission; total compensation can reach ₹80L at senior levels',
    },
    byCompanyType: {
      startup: '₹6L – ₹30L base + commission (ESOPs; fast growth, high targets)',
      midSize: '₹8L – ₹30L base + commission',
      mnc: '₹10L – ₹40L base + commission (SaaS and enterprise technology majors)',
      faang: '₹20L – ₹60L+ total (top global SaaS and enterprise firms; variable pay can be substantial)',
    },
    byLocation: {
      bangalore: '₹7L – ₹45L (SaaS and enterprise tech hub)',
      mumbai: '₹7L – ₹42L (BFSI, media and consumer sectors)',
      delhi: '₹7L – ₹42L (NCR enterprise sales)',
      hyderabad: '₹6.5L – ₹38L (IT services and pharma-related BD)',
      chennai: '₹6L – ₹32L (manufacturing, SaaS and services)',
      pune: '₹6L – ₹32L (industrial, IT and services)',
      other: '₹5L – ₹22L (smaller markets)',
    },
    topPayingSkills: ['Enterprise B2B Sales', 'SaaS Sales', 'Strategic Partnerships', 'Pipeline and Forecasting', 'Negotiation and Deal Structuring', 'CRM (Salesforce/HubSpot)', 'Account-based Selling', 'Channel Development'],
    salaryBoostFactors: [
      'A track record of closed revenue and quota attainment with figures to back it',
      'Enterprise or high-ticket deal experience with long sales cycles',
      'Experience in SaaS, fintech or other sectors with strong variable pay',
      'Strong network and ability to open new accounts, not only manage existing ones',
      'Team or partnership leadership exposure',
    ],
    negotiationTips: [
      'Quote revenue closed, quota attained and average deal size from your last roles',
      'Review the commission structure line by line: accelerators, clawbacks, caps and payout timing',
      'Negotiate the realistic On-Target Earnings and the quota that supports it',
      'Check whether leads are provided or self-sourced, which changes how achievable the target is',
    ],
    faqs: [
      { q: 'What is the salary of a business development manager in India?', a: 'Business development managers in India commonly earn about ₹6L – ₹40L in base pay, with commission on top, and senior professionals in SaaS or enterprise sales can reach total compensation of ₹80L. Pay depends heavily on sector, deal size and quota attainment.' },
      { q: 'Is commission a big part of a business development manager’s pay?', a: 'In many B2B and SaaS roles, yes. Variable pay can be a significant share of on-target earnings, so review the quota, accelerators and payout timing before comparing offers.' },
    ],
  },
  'network-engineer': {
    byExperience: {
      fresher: '₹4L – ₹6.5L (0–2 years; NOC or L1/L2 support, CCNA-level)',
      midLevel: '₹7L – ₹14L (3–6 years; L2/L3 with CCNP and firewall exposure)',
      senior: '₹14L – ₹22L (7–12 years; network architect or lead)',
      leadership: '₹22L – ₹25L+ (13+ years; infrastructure heads and principal architects)',
    },
    byCompanyType: {
      startup: '₹5L – ₹16L (cloud-first teams with broader scope)',
      midSize: '₹5L – ₹18L (system integrators and enterprise IT)',
      mnc: '₹6L – ₹24L (global IT services, telecom and large enterprises)',
      faang: '₹14L – ₹30L+ (large cloud providers and top enterprise network teams)',
    },
    byLocation: {
      bangalore: '₹4.5L – ₹28L (large IT and telecom infrastructure market)',
      mumbai: '₹4.5L – ₹26L (BFSI and telecom data centres)',
      delhi: '₹4.2L – ₹25L (NCR enterprise and government projects)',
      hyderabad: '₹4.2L – ₹25L (IT services and data centres)',
      chennai: '₹4L – ₹24L (IT services and manufacturing)',
      pune: '₹4L – ₹24L (IT services and industrial)',
      other: '₹3L – ₹16L (smaller hubs)',
    },
    topPayingSkills: ['SD-WAN', 'Palo Alto / Fortinet Firewalls', 'Cloud Networking (AWS/Azure)', 'BGP and MPLS Design', 'Network Automation (Python/Ansible)', 'Zero Trust Architecture', 'CCIE-level Troubleshooting', 'Wireless Design'],
    salaryBoostFactors: [
      'Advanced certifications such as CCNP and CCIE',
      'Network automation skills with Python or Ansible',
      'Security and firewall specialisation',
      'Cloud networking and hybrid design experience',
      'Large-scale or data-centre migration projects',
    ],
    negotiationTips: [
      'Highlight uptime and incident-resolution improvements you contributed to',
      'Use certification level and hands-on vendor stack (Cisco, Palo Alto, Fortinet) as pay leverage',
      'Clarify shift allowances and on-call duties; they change effective pay',
      'Show automation experience when moving from operations to engineering roles',
    ],
    faqs: [
      { q: 'What is the average network engineer salary in India?', a: 'Network engineers in India typically earn about ₹4L – ₹25L a year. Freshers with CCNA-level skills are around ₹4L – ₹6.5L, mid-level engineers with CCNP and firewall skills around ₹7L – ₹14L, and architects at the upper end.' },
      { q: 'Does CCNP or CCIE increase a network engineer’s salary?', a: 'Yes. Advanced certifications validate depth and are frequently required for senior and architect roles, and they usually lift offers compared with profiles at the same experience level that lack them.' },
    ],
  },
  'logistics-manager': {
    byExperience: {
      fresher: '₹3.5L – ₹6L (0–2 years; operations executive or management trainee)',
      midLevel: '₹7L – ₹14L (3–6 years; hub, warehouse or fleet manager)',
      senior: '₹14L – ₹22L (7–12 years; regional or city head)',
      leadership: '₹22L – ₹28L+ (13+ years; heads of logistics and supply chain)',
    },
    byCompanyType: {
      startup: '₹5L – ₹20L (quick-commerce and logistics start-ups; ESOPs)',
      midSize: '₹5L – ₹18L (3PLs and manufacturers)',
      mnc: '₹7L – ₹26L (global logistics and large corporates)',
      faang: '₹10L – ₹30L+ (top e-commerce and logistics players)',
    },
    byLocation: {
      bangalore: '₹5L – ₹26L (e-commerce and quick-commerce operations)',
      mumbai: '₹5.5L – ₹28L (ports, freight and distribution hub)',
      delhi: '₹5L – ₹26L (NCR distribution and e-commerce)',
      hyderabad: '₹5L – ₹24L (warehousing and pharma logistics)',
      chennai: '₹5L – ₹24L (port and auto logistics)',
      pune: '₹5L – ₹24L (auto and industrial logistics)',
      other: '₹3.5L – ₹16L (regional hubs and smaller markets)',
    },
    topPayingSkills: ['WMS / TMS Systems', 'Last-mile Optimisation', 'Network Design', 'Cost and Route Optimisation', 'Vendor and 3PL Management', 'Cold Chain', 'Data Analytics for Operations', 'Process Excellence (Six Sigma)'],
    salaryBoostFactors: [
      'Scale of operations managed: shipments, fleet size, warehouse area or team headcount',
      'Measurable cost, on-time delivery or damage-rate improvements',
      'Experience at large e-commerce or quick-commerce operations',
      'Cold chain, pharma or other specialised logistics expertise',
      'Process-improvement certifications and technology adoption experience',
    ],
    negotiationTips: [
      'Present operations metrics: on-time delivery rate, cost per shipment, cost savings achieved',
      'Clarify location, shift pattern and travel expectations — they strongly affect effective pay',
      'Ask about the team size and operating budget you will own',
      'Use the scale you have managed to justify a higher level',
    ],
    faqs: [
      { q: 'What is the average logistics manager salary in India?', a: 'Logistics managers in India typically earn about ₹5L – ₹28L a year depending on scale and company type. Mid-level managers are generally around ₹7L – ₹14L, while regional heads and logistics leaders at large firms earn more.' },
      { q: 'Which companies pay logistics managers the most in India?', a: 'Large e-commerce, quick-commerce and global logistics firms generally pay at the higher end, along with big manufacturers with complex networks. Pay depends more on the scale you manage and the results you show than on the title alone.' },
    ],
  },
  'interior-designer': {
    byExperience: {
      fresher: '₹3L – ₹4.5L (0–2 years; junior designer or design trainee)',
      midLevel: '₹5L – ₹9L (3–6 years; independent project handling)',
      senior: '₹9L – ₹15L (7–12 years; senior designer, design lead)',
      leadership: '₹15L – ₹20L+ (13+ years; principal designers, studio heads; practice owners can earn more)',
    },
    byCompanyType: {
      startup: '₹3L – ₹10L (home-interiors start-ups; high project volume)',
      midSize: '₹3.5L – ₹12L (regional design-and-build firms)',
      mnc: '₹5L – ₹18L (large architecture and workplace-design firms)',
      faang: '₹8L – ₹20L+ (top-tier design studios and global workplace-design practices)',
    },
    byLocation: {
      bangalore: '₹3.5L – ₹18L (home-interiors and corporate fit-out demand)',
      mumbai: '₹4L – ₹20L (premium residential and hospitality)',
      delhi: '₹3.8L – ₹19L (NCR residential and commercial projects)',
      hyderabad: '₹3.3L – ₹16L (growing real estate and office fit-outs)',
      chennai: '₹3L – ₹14L (residential and commercial)',
      pune: '₹3L – ₹14L (residential and commercial)',
      other: '₹2.5L – ₹10L (smaller markets; often project-based)',
    },
    topPayingSkills: ['3D Visualisation (V-Ray, 3ds Max)', 'Revit and BIM', 'Space Planning for Workplaces', 'BOQ and Cost Estimation', 'Project Management on Site', 'Hospitality and Luxury Design', 'Client Presentation', 'Material and Vendor Knowledge'],
    salaryBoostFactors: [
      'A strong portfolio of completed, photographed projects',
      'Experience with commercial, hospitality or luxury residential work',
      'BIM and Revit proficiency alongside AutoCAD and SketchUp',
      'Ability to manage budgets, vendors and on-site execution',
      'Client acquisition or business-development ability at studio-owner level',
    ],
    negotiationTips: [
      'Lead with your portfolio and project values rather than only years of experience',
      'Ask whether the role is design-only or includes site supervision and client management',
      'Discuss whether incentives or project commissions apply',
      'Compare offers on learning, project scale and portfolio-building potential as well as pay',
    ],
    faqs: [
      { q: 'What is the average interior designer salary in India?', a: 'Interior designers in India typically earn about ₹3L – ₹20L a year depending on firm type, city and project complexity. Freshers are usually around ₹3L – ₹4.5L, mid-level designers around ₹5L – ₹9L, and senior designers or studio leads earn more.' },
      { q: 'Does a portfolio matter more than a degree for interior designer pay?', a: 'For most hiring decisions the portfolio carries the most weight, because it shows taste, technical drawing quality and execution. A relevant degree helps with entry, but employers pay for demonstrated project work.' },
    ],
  },
  'pharmacist': {
    byExperience: {
      fresher: '₹2.5L – ₹3.5L (0–2 years; retail or hospital pharmacy entry roles)',
      midLevel: '₹3.5L – ₹6L (3–6 years; senior pharmacist, pharmacovigilance or quality roles)',
      senior: '₹6L – ₹10L (7–12 years; pharmacy in-charge, regulatory or QA lead)',
      leadership: '₹10L – ₹15L+ (13+ years; heads of pharmacy, regulatory affairs or quality)',
    },
    byCompanyType: {
      startup: '₹2.5L – ₹6L (online pharmacy and health-tech)',
      midSize: '₹2.5L – ₹7L (retail chains and mid-sized pharma)',
      mnc: '₹4L – ₹12L (large pharma, CROs and corporate hospitals)',
      faang: '₹6L – ₹15L+ (top pharma, global CROs and leading hospital groups)',
    },
    byLocation: {
      bangalore: '₹2.8L – ₹13L (hospitals, CROs and pharma)',
      mumbai: '₹2.8L – ₹14L (pharma headquarters and corporate hospitals)',
      delhi: '₹2.7L – ₹13L (hospitals and regulatory roles)',
      hyderabad: '₹2.8L – ₹15L (India’s pharma and CRO hub)',
      chennai: '₹2.6L – ₹11L (hospitals and pharma)',
      pune: '₹2.6L – ₹11L (pharma and hospital pharmacy)',
      other: '₹2.2L – ₹8L (smaller markets; retail and local hospitals)',
    },
    topPayingSkills: ['Pharmacovigilance', 'Regulatory Affairs', 'Clinical Research', 'Quality Assurance', 'Medical Writing', 'Clinical Pharmacy', 'Drug Safety Databases', 'GMP and GxP Compliance'],
    salaryBoostFactors: [
      'Moving from retail dispensing into pharmacovigilance, regulatory or clinical research roles',
      'Postgraduate qualification such as M.Pharm or Pharm.D',
      'Experience with international regulatory submissions and safety databases',
      'Hospital pharmacy leadership or accreditation exposure',
      'Quality and compliance expertise in manufacturing',
    ],
    negotiationTips: [
      'Highlight compliance, audit outcomes and error-reduction results from past roles',
      'Compare shift patterns and rotational duties across retail, hospital and pharma offers',
      'Use specialised skills such as drug safety or regulatory submissions to justify a higher band',
      'Ask about growth paths, as corporate and pharma tracks often progress faster than retail',
    ],
    faqs: [
      { q: 'What is the average pharmacist salary in India?', a: 'Pharmacists in India typically earn about ₹2.5L – ₹15L a year depending on sector, experience and qualification. Retail and entry-level hospital roles are at the lower end, while pharmacovigilance, regulatory and quality roles at pharma companies and CROs pay more.' },
      { q: 'Which pharmacy career pays the most in India?', a: 'Specialised roles in pharmacovigilance, regulatory affairs, clinical research and quality assurance at pharma firms and CROs generally pay more than retail pharmacy, particularly with a postgraduate qualification and several years of experience.' },
    ],
  },
  'embedded-systems-engineer': {
    byExperience: {
      fresher: '₹4L – ₹8L (0–2 years; graduate engineer trainee, firmware or testing roles)',
      midLevel: '₹9L – ₹18L (3–6 years; owning drivers, RTOS or board bring-up)',
      senior: '₹18L – ₹28L (7–12 years; senior firmware engineer or architect)',
      leadership: '₹28L – ₹30L+ (13+ years; principal engineers and engineering managers)',
    },
    byCompanyType: {
      startup: '₹5L – ₹22L (IoT, EV and hardware start-ups; ESOPs)',
      midSize: '₹5L – ₹22L (engineering services and product companies)',
      mnc: '₹7L – ₹28L (semiconductor, automotive and industrial majors)',
      faang: '₹15L – ₹40L+ (top semiconductor and global product teams)',
    },
    byLocation: {
      bangalore: '₹5L – ₹32L (largest semiconductor and embedded hub)',
      mumbai: '₹4L – ₹22L (industrial and electronics)',
      delhi: '₹4L – ₹24L (NCR electronics and telecom)',
      hyderabad: '₹4.5L – ₹28L (semiconductor and defence electronics)',
      chennai: '₹4.5L – ₹26L (automotive and electronics manufacturing)',
      pune: '₹4.5L – ₹28L (automotive embedded and engineering services)',
      other: '₹3.5L – ₹18L (smaller hubs)',
    },
    topPayingSkills: ['Automotive Embedded (AUTOSAR)', 'RTOS (FreeRTOS, Zephyr)', 'Linux BSP and Device Drivers', 'Functional Safety (ISO 26262)', 'Low-power Firmware Design', 'Secure Boot and OTA Updates', 'Wireless Stacks (BLE, LoRa, Wi-Fi)', 'FPGA / SoC Bring-up'],
    salaryBoostFactors: [
      'Automotive or defence domain experience with safety standards',
      'Linux BSP and driver development alongside bare-metal firmware',
      'Hands-on board bring-up, debugging with oscilloscopes and logic analysers',
      'Product-shipped firmware with measurable reliability or power improvements',
      'Security and over-the-air update expertise',
    ],
    negotiationTips: [
      'Describe shipped products and the firmware you owned',
      'Highlight domain specialisation such as automotive or medical, where standards expertise commands a premium',
      'Compare tool access and hardware lab facilities, as they affect how fast you can grow',
      'Use hands-on debugging and bring-up experience as evidence for moving to a higher band',
    ],
    faqs: [
      { q: 'What is the average embedded systems engineer salary in India?', a: 'Embedded systems engineers in India typically earn about ₹4L – ₹30L a year. Freshers are usually at ₹4L – ₹8L, mid-level engineers at ₹9L – ₹18L, and senior engineers in automotive, semiconductor and defence domains at ₹18L and above.' },
      { q: 'Which domain pays embedded engineers the most?', a: 'Automotive, semiconductor and defence electronics tend to offer higher pay, particularly for engineers with functional-safety, AUTOSAR or Linux BSP experience, while consumer and generic IoT roles are often at lower bands.' },
    ],
  },
};

const eastWestCities: Record<string, { kolkata: string; ahmedabad: string }> = {
  'sales-executive': { kolkata: '₹2.2L – ₹7L (FMCG, BFSI and distribution sales)', ahmedabad: '₹2.3L – ₹7.5L (pharma, industrial and D2C sales)' },
  'ios-developer': { kolkata: '₹4L – ₹24L (IT services and product startups)', ahmedabad: '₹4L – ₹24L (SaaS and consumer apps)' },
  'full-stack-developer': { kolkata: '₹4L – ₹26L (IT services and product startups)', ahmedabad: '₹4L – ₹26L (IT, fintech and SaaS)' },
  'machine-learning-engineer': { kolkata: '₹6L – ₹32L (analytics and IT services)', ahmedabad: '₹6L – ₹32L (analytics, fintech and IT)' },
  'chartered-accountant': { kolkata: '₹6L – ₹24L (audit firms, corporates and banks)', ahmedabad: '₹6L – ₹26L (industrial, pharma and trading groups)' },
  'sap-consultant': { kolkata: '₹4L – ₹24L (IT services and manufacturing clients)', ahmedabad: '₹4L – ₹24L (pharma, industrial and IT services)' },
  'react-developer': { kolkata: '₹3.5L – ₹22L (IT services and startups)', ahmedabad: '₹3.5L – ₹22L (SaaS and product teams)' },
  'investment-banker': { kolkata: '₹9L – ₹28L (limited front-office roles; banking and advisory)', ahmedabad: '₹9L – ₹30L (GIFT City banking and advisory)' },
  'scrum-master': { kolkata: '₹6L – ₹20L (IT services)', ahmedabad: '₹6L – ₹20L (IT services and SaaS)' },
  'business-development-manager': { kolkata: '₹5L – ₹26L (IT services, BFSI and manufacturing)', ahmedabad: '₹5L – ₹28L (pharma, industrial and SaaS)' },
  'network-engineer': { kolkata: '₹3.5L – ₹18L (IT services and telecom)', ahmedabad: '₹3.5L – ₹18L (IT services and data centres)' },
  'logistics-manager': { kolkata: '₹4L – ₹18L (port, freight and distribution)', ahmedabad: '₹4.5L – ₹22L (port, pharma and industrial logistics)' },
  'interior-designer': { kolkata: '₹2.5L – ₹11L (residential and commercial studios)', ahmedabad: '₹2.8L – ₹12L (residential, commercial and design studios)' },
  'pharmacist': { kolkata: '₹2.3L – ₹9L (hospitals and pharma distribution)', ahmedabad: '₹2.6L – ₹12L (major pharma manufacturing hub)' },
  'embedded-systems-engineer': { kolkata: '₹3.5L – ₹18L (electronics and IT services)', ahmedabad: '₹3.5L – ₹20L (industrial electronics and automation)' },
};

for (const [slug, extra] of Object.entries(eastWestCities)) {
  const entry = salaryDataMore[slug];
  if (entry) {
    entry.byLocation.kolkata = extra.kolkata;
    entry.byLocation.ahmedabad = extra.ahmedabad;
  }
}
